#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart1[] = {
{"report.title", "DataLab 质量分析报告", "DataLab Quality Analysis Report"},
{"report.template", "模板", "Template"},
{"report.language", "语言", "Language"},
{"report.evidence_level", "证据级别", "Evidence level"},
{"report.evidence.customer", "客户风险摘要", "Customer risk summary"},
{"report.evidence.engineer", "工程师规则/诊断", "Engineer rules/diagnostics"},
{"report.evidence.audit", "审计完整证据", "Full audit evidence"},
{"report.generated_at", "生成时间", "Generated at"},
{"report.source", "数据源", "Data source"},
{"report.source_kind", "来源类型", "Source kind"},
{"report.filter", "过滤", "Filter"},
{"report.filter.none", "（无）", "(none)"},
{"report.software_version", "软件版本", "Software version"},
{"report.algorithm_version", "算法版本", "Algorithm version"},
{"report.unrecorded", "（未记录）", "(not recorded)"},
{"report.import_plan", "ImportPlan/快照", "ImportPlan/snapshot"},
{"report.import_plan.worksheet_fallback",
 "worksheet_snapshot（无原始数据库连接时仍可解释快照来源）",
 "worksheet_snapshot (source interpretable without live DB connection)"},
{"report.input_hash", "输入快照 hash", "Input snapshot hash"},
{"report.facts_hash", "Facts hash", "Facts hash"},
{"report.pdfa_banner",
 "PDF/A：not_validated    PDF/UA：unsupported（QPainter 路径；未接入验证器，不得宣称合规）",
 "PDF/A: not_validated    PDF/UA: unsupported (QPainter path; no validator; do not claim compliance)"},
{"report.no_results", "暂无分析结果。", "No analysis results."},
{"report.method_metadata", "方法元数据", "Method metadata"},
{"report.table_truncated", "（表格预览已截断 %1 行）", "(table preview truncated by %1 rows)"},
{"report.evidence_appendix", "证据附录", "Evidence appendix"},
{"report.formula_references", "公式引用", "Formula references"},
{"report.evidence_truncated", "（证据预览已截断 %1 条）", "(evidence preview truncated by %1 items)"},
{"evidence.formula_reference", "公式引用（非 vendor_oracle）",
 "Formula reference (not vendor_oracle)"},
{"report.rule_line", "规则", "Rule"},
{"report.threshold", "阈值", "Threshold"},
{"report.anomaly_rows", "异常行", "Anomaly rows"},
{"report.no_row_id", "（无 RowId）", "(no RowId)"},
{"report.next_page", "— 下一页 —", "— Next page —"},
{"report.footer", "DataLab 质量分析报告", "DataLab Quality Analysis Report"},
{"report.page", "第 %1 页", "Page %1"},
{"template.customer", "客户版", "Customer"},
{"template.engineer", "工程师版", "Engineer"},
{"template.audit", "审计版", "Audit"},
{"evidence.dataset_snapshot", "数据集快照", "Dataset snapshot"},
{"evidence.import_plan", "导入计划", "Import plan"},
{"evidence.filter", "过滤条件", "Filter"},
{"evidence.filter_excluded_hidden",
 "排除行与隐藏行分别计数（不得合并）",
 "Excluded and hidden rows counted separately (must not merge)"},
{"evidence.row_selection", "行选择（排除/隐藏）", "Row selection (excluded/hidden)"},
{"evidence.parameters", "算法参数", "Parameters"},
{"evidence.parameter", "算法参数", "Parameters"},
{"evidence.reference_implementation", "参考实现", "Reference implementation"},
{"evidence.vendor_oracle", "厂商 oracle", "Vendor oracle"},
{"evidence.golden", "Golden 基准", "Golden baseline"},
{"evidence.table_cell", "表格单元格", "Table cell"},
{"evidence.other", "其他证据", "Other evidence"},
{"evidence.algorithm_version", "算法版本", "Algorithm version"},
{"evidence.plot", "图表嵌入（含排除/隐藏计数）",
 "Chart embed (with excluded/hidden counts)"},
{"evidence.rule", "规则证据", "Rule evidence"},
{"evidence.diagnostic", "诊断", "Diagnostic"},
{"evidence.empty", "空证据", "Empty evidence"},
{"evidence.missing_row_ids", "缺少 RowId", "Missing RowId"},
{"interp.excluded_rows",
 "配置排除了 %1 行；结论只适用于纳入分析的数据。",
 "Configuration excluded %1 rows; conclusions apply only to analysis-eligible data."},
{"interp.hidden_rows",
 "配置隐藏了 %1 行；隐藏行仍计入分析口径，仅影响显示。不得将 hidden 与 excluded 合并叙述。",
 "Configuration hid %1 rows; hidden rows remain analysis-eligible and affect display only. Do not merge hidden with excluded."},
{"interp.section.conclusion", "统计结论", "Statistical conclusion"},
{"interp.section.advice", "工程建议", "Engineering advice"},
{"interp.section.limitations", "限制与数据质量", "Limitations and data quality"},
{"interp.section.key_risks", "关键风险与限制", "Key risks and limits"},
{"interp.section.method", "方法说明", "Method notes"},
{"evidence.rule_without_row_ids", "规则无关联行", "Rule without related rows"},
{"evidence.diagnostic_without_row_ids", "诊断无关联行", "Diagnostic without related rows"},
{"evidence.capability_gate_blocked",
 "能力门禁：禁止过程合格判定",
 "Capability gate: process pass/fail blocked"},
{"evidence.johnson_capability_gated",
 "Johnson 能力门禁（研究预览；禁止合格判定）",
 "Johnson capability gate (research preview; pass/fail blocked)"},
{"evidence.box_cox_not_pass_fail",
 "Box-Cox 变换不是过程合格判定（assumption 未验收）",
 "Box-Cox transformation is not a process pass/fail decision (assumption not verified)"},
{"evidence.box_cox_spec_limit_gate",
 "Box-Cox 规格限门禁：跳过变换后能力表",
 "Box-Cox spec limit gate: post-transform capability table skipped"},
{"evidence.johnson_spec_limit_gate",
 "Johnson 规格限门禁：跳过 overall 能力指数",
 "Johnson spec limit gate: overall capability indices skipped"},
{"evidence.capability_stability_prerequisite",
 "能力稳定性/正态性前置未满足；禁止合格判定",
 "Capability stability/normality prerequisite unmet; pass/fail blocked"},
{"evidence.reliability_zero_failure",
 "可靠性零失效；点估计受限",
 "Reliability zero failures; point estimates limited"},
{"evidence.reliability_all_censored",
 "可靠性全部删失；点估计通常不可得",
 "Reliability all-censored; point estimates usually unavailable"},
{"evidence.km_not_long_term_guarantee",
 "KM/区间删失生存曲线不是长期寿命保证",
 "KM/interval-censored survival is not a long-term life guarantee"},
{"evidence.warranty_not_legal_promise",
 "保修摘要不是法律承诺或放行依据",
 "Warranty summary is not a legal promise or release decision"},
{"evidence.warranty_prediction_not_observation",
 "保修量为模型预测，不是观测索赔计数",
 "Warranty quantity is a model prediction, not observed claim counts"},
{"evidence.gate_status", "门禁状态", "Gate status"},
{"evidence.pass_fail_not_allowed",
 "禁止过程合格判定",
 "Process pass/fail judgment not allowed"},
{"evidence.truncated_supporting_kept_limits",
 "已优先保留限制性证据；支持性图表证据可能被截断",
 "Limiting evidence retained preferentially; supporting chart evidence may be truncated"},
{"evidence.rsm_lof_formula_reference",
 "RSM 失拟 ANOVA（formula_reference；非 vendor_oracle）",
 "RSM lack-of-fit ANOVA (formula_reference; not vendor_oracle)"},
{"evidence.rsm_insufficient_pure_error",
 "RSM 无足够纯误差；不得用残差 MS 冒充纯误差",
 "RSM insufficient pure error; residual MS must not fake pure error"},
{"evidence.rsm_static_surface",
 "RSM 曲面为静态快照；非交互式全域最优保证",
 "RSM surface is a static snapshot; not an interactive global-optimum guarantee"},
{"evidence.design_formula_reference_only",
 "DOE 设计生成仅为 formula_reference；非 vendor_oracle / 商业对齐",
 "DOE design generation is formula_reference only; not vendor_oracle / commercial alignment"},
{"evidence.ccd_beyond_range",
 "CCD 星点超出立方体范围；不是可执行工艺承诺",
 "CCD axial points beyond cube range; not an executable process claim"},
{"evidence.bbd_no_corners",
 "BBD 无角点；不得写成全域预测最优",
 "BBD has no corner points; must not claim domain-wide prediction optimality"},
{"evidence.cif_not_fine_gray",
 "Aalen–Johansen CIF 不是 Fine-Gray；非 cause-specific 可靠度 / vendor_oracle",
 "Aalen–Johansen CIF is not Fine-Gray; not cause-specific reliability / vendor_oracle"},
{"evidence.fine_gray_formula_reference_only",
 "Fine-Gray 仅为 formula_reference IPCW；非 cause-specific Cox / vendor_oracle / pinned R",
 "Fine-Gray is formula_reference IPCW only; not cause-specific Cox / vendor_oracle / pinned R"},
{"evidence.warranty_strata_exposure_honesty",
 "保修分层暴露含比例分摊；不得写成实测分母",
 "Warranty strata exposure includes proportional allocation; must not claim measured denominators"},
{"evidence.warranty_strata_reliability_basis",
 "保修分层可靠度基础（池化 vs 分模式）须如实标注",
 "Warranty strata reliability basis (pooled vs mode-specific) must be labeled honestly"},
{"evidence.warranty_exposure_gate",
 "保修暴露量门禁：跳过保修摘要指标",
 "Warranty exposure gate: warranty summary metrics skipped"},
{"evidence.hexbin_rectangular_bins",
 "Hexbin 使用矩形二维分箱；非正六边形镶嵌",
 "Hexbin uses rectangular 2D bins; not a regular hexagonal tessellation"},
{"evidence.density_curve_not_discrete_marks",
 "密度曲线不是离散行标记（KDE 连续网格）",
 "Density KDE curves are not discrete row marks (continuous grid)"},
{"diag.hexbin_rectangular_bins",
 "使用矩形二维分箱（Binned Scatter）；非正六边形镶嵌。",
 "Using rectangular 2D bins (binned scatter); not a regular hexagonal tessellation."},
{"param.summary.variable_eq",
 "变量 = ",
 "Variable = "},
{"param.summary.variable_colon",
 "变量: ",
 "Variable: "},
{"param.summary.variable_count_eq",
 "变量数 = ",
 "Variable count = "},
{"param.summary.response_eq",
 "响应 = ",
 "Response = "},
{"param.summary.response_column_eq",
 "响应列 = ",
 "Response column = "},
{"param.summary.method_eq",
 "方法 = ",
 "Method = "},
{"param.summary.method_colon",
 "方法: ",
 "Method: "},
{"param.summary.hypothesized_mean_eq",
 "假设均值 = ",
 "Hypothesized mean = "},
{"param.summary.alt_population_mean",
 "备择：总体均值 ",
 "Alternative: population mean "},
{"param.summary.hypothesized_mean_tail",
 " 假设均值",
 " hypothesized mean"},
{"param.summary.alternative_colon",
 "备择: ",
 "Alternative: "},
{"param.summary.missing_nstar_eq",
 "缺失值 N* = ",
 "Missing N* = "},
{"param.summary.pooled_variance",
 "合并方差",
 "Pooled variance"},
{"param.summary.trials_eq",
 "试验 = ",
 "Trials = "},
{"param.summary.target_proportion_eq",
 "目标比例 = ",
 "Target proportion = "},
{"param.summary.hypothesized_proportion_eq",
 "假设比例 = ",
 "Hypothesized proportion = "},
{"param.summary.hypothesized_rate_eq",
 "假设发生率 = ",
 "Hypothesized rate = "},
{"param.summary.comparison_eq",
 "比较 = ",
 "Comparison = "},
{"param.summary.row_colon",
 "行: ",
 "Row: "},
{"param.summary.column_colon",
 "列: ",
 "Column: "},
{"param.summary.transform_eq",
 "变换 = ",
 "Transform = "},
{"param.summary.test_eq",
 "检验 = ",
 "Test = "},
{"param.summary.reference_short_eq",
 "参考 = ",
 "Reference = "},
{"param.summary.crosstab_no_chi2_note",
 "（本命令不做卡方检验；关联检验请用列联表卡方）",
 "(This command does not run a chi-square test; use Chi-Square Association for association tests)"},
{"param.alt.not_equal",
 "不等于",
 "not equal to"},
{"param.alt.less",
 "小于",
 "less than"},
{"param.alt.greater",
 "大于",
 "greater than"},
{"header.row_percent",
 "行百分比",
 "Row percent"},
{"header.column_percent",
 "列百分比",
 "Column percent"},
{"header.total_percent",
 "合计百分比",
 "Total percent"},
{"param.summary.measurement_eq",
 "测量值 = ",
 "Measurement = "},
{"param.summary.measurement_short_eq",
 "测量 = ",
 "Measurement = "},
{"param.summary.factor_count_eq",
 "因子数 = ",
 "Factor count = "},
{"param.summary.factor_count_k_eq",
 "因子数 k = ",
 "Factor count k = "},
{"param.summary.run_count_eq",
 "运行数 = ",
 "Run count = "},
{"param.summary.resolution_eq",
 "分辨度 = ",
 "Resolution = "},
{"param.summary.variant_eq",
 "变体 = ",
 "Variant = "},
{"param.summary.valid_obs_eq",
 "有效观测 = ",
 "Valid observations = "},
{"param.summary.events_eq",
 "事件 = ",
 "Events = "},
{"param.summary.defects_eq",
 "缺陷 = ",
 "Defects = "},
{"param.summary.first_group_eq",
 "第一组 = ",
 "First group = "},
{"param.summary.second_group_eq",
 "第二组 = ",
 "Second group = "},
{"param.summary.first_column_eq",
 "第一列 = ",
 "First column = "},
{"param.summary.second_column_eq",
 "第二列 = ",
 "Second column = "},
{"param.summary.category_column_eq",
 "分类列 = ",
 "Category column = "},
{"param.summary.grouping_column_eq",
 "分组列 = ",
 "Grouping column = "},
{"param.summary.distribution_eq",
 "分布 = ",
 "Distribution = "},
{"param.summary.binomial",
 "二项分布",
 "Binomial"},
{"param.summary.poisson",
 "泊松分布",
 "Poisson"},
{"param.summary.binomial_short",
 "二项",
 "Binomial"},
{"param.summary.poisson_short",
 "泊松",
 "Poisson"},
{"metric.attr.total_defectives",
 "不合格品合计",
 "Total defectives"},
{"metric.attr.total_defects",
 "缺陷合计",
 "Total defects"},
{"metric.attr.total_inspected",
 "检验数合计",
 "Total inspected"},
{"metric.attr.total_units",
 "单位数合计",
 "Total units"},
{"metric.attr.target_proportion_defective",
 "目标不合格品率",
 "Target proportion defective"},
{"metric.attr.target_dpu",
 "目标 DPU",
 "Target DPU"},
{"plot.cumulative_percent_defective",
 "累计 %Defective",
 "Cumulative %Defective"},
{"plot.cumulative_dpu",
 "累计 DPU",
 "Cumulative DPU"},
{"param.summary.npbar_formula",
 "np̄_i = n_i p̄",
 "np̄_i = n_i p̄"},
{"param.summary.rule1_gloss",
 "「单点超出 3σ 控制限」= 超出 3σ 控制限的点（rule_id=beyond_control_limit）",
 "\"Beyond 3σ limits\" = points beyond 3σ limits (rule_id=beyond_control_limit)"},
{"param.summary.c_chart_equal_units",
 "C 图要求每个子组单位数相同",
 "C chart requires equal units per subgroup"},
{"param.summary.total_count_eq",
 "总计数 = ",
 "Total count = "},
{"param.summary.other_threshold_eq",
 "Other 阈值 = ",
 "Other threshold = "},
{"param.summary.cause_count_eq",
 "原因数 = ",
 "Cause count = "},
{"param.summary.category_count_eq",
 "类别数 = ",
 "Category count = "},
{"header.cause",
 "原因",
 "Causes"},
{"plot.suffix.category_cause_counts",
 "— 类别原因计数",
 "— category cause counts"},
};

}  // namespace

void append_report_text_catalog_part1(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart1),
        std::end(kReportTextCatalogPart1));
}

}  // namespace datalab::domain
