#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart12[] = {
{"interp.poisson_warn_small_count",
 "总发生数不大于 10，正态近似可能不准确。",
 "Total event count is not greater than 10; the normal approximation may be inaccurate."},
{"interp.poisson_warn_small_count_two",
 "两组总发生数不大于 10，正态近似可能不准确。",
 "Combined event counts across both groups are not greater than 10; the normal approximation may be inaccurate."},
{"interp.mann_whitney_warn_ci_small_n",
 "样本量过小，无法计算 McKean–Ryan 置信区间。",
 "Sample size too small to compute a McKean–Ryan confidence interval."},
{"interp.mann_whitney_err_need_two_groups",
 "Mann–Whitney 检验要求两组均有有效观测。",
 "Mann–Whitney requires valid observations in both groups."},
{"interp.mann_whitney_err_zero_rank_variance",
 "秩方差为 0，无法计算 Mann–Whitney P 值。",
 "Rank variance is 0; Mann–Whitney P-value cannot be computed."},
{"interp.mann_whitney_warn_small_sample",
 "存在样本量小于 10 的组，Mann–Whitney 正态近似只作提示。",
 "A group has n<10; the Mann–Whitney normal approximation is advisory only."},
{"interp.wilcoxon_err_need_two_nonzero",
 "Wilcoxon signed-rank 检验至少需要两个非零差值。",
 "Wilcoxon signed-rank needs at least two nonzero differences."},
{"interp.wilcoxon_warn_small_sample",
 "非零差值少于 10，Wilcoxon 正态近似只作提示。",
 "Fewer than 10 nonzero differences; Wilcoxon normal approximation is advisory only."},
{"interp.wilcoxon_err_zero_rank_variance",
 "符号秩方差为 0，无法计算 Wilcoxon P 值。",
 "Signed-rank variance is 0; Wilcoxon P-value cannot be computed."},
{"interp.wilcoxon_err_unequal_pairs",
 "Wilcoxon signed-rank 检验要求两列行数相同。",
 "Wilcoxon signed-rank requires equal-length paired columns."},
{"interp.kruskal_err_invalid_groups",
 "Kruskal–Wallis 检验至少需要两个且标签匹配的组。",
 "Kruskal–Wallis needs at least two groups with matching labels."},
{"interp.kruskal_err_insufficient_obs",
 "Kruskal–Wallis 检验需要每个组至少一个有效观测。",
 "Kruskal–Wallis needs at least one valid observation per group."},
{"interp.kruskal_warn_small_group",
 "存在少于 5 个观测的组，卡方近似可能不可靠。",
 "A group has fewer than 5 observations; the chi-square approximation may be unreliable."},
{"interp.friedman_err_input_mismatch",
 "Friedman 检验要求响应、处理与区组等长且非空。",
 "Friedman requires non-empty response, treatment, and block columns of equal length."},
{"interp.friedman_err_invalid_row",
 "Friedman 检验要求数值响应与非空处理/区组标签。",
 "Friedman requires numeric responses and non-empty treatment/block labels."},
{"interp.friedman_err_insufficient_levels",
 "Friedman 检验至少需要 2 个处理与 2 个区组。",
 "Friedman needs at least 2 treatments and 2 blocks."},
{"interp.friedman_err_duplicate_cell",
 "同一区组与处理出现重复观测，Friedman 要求每格恰 1 个观测。",
 "Duplicate observation in a block×treatment cell; Friedman requires exactly one per cell."},
{"interp.friedman_err_unbalanced",
 "存在缺失的区组×处理组合，Friedman 要求平衡设计。",
 "Missing block×treatment combination; Friedman requires a balanced design."},
{"interp.sign_err_no_nonzero",
 "符号检验在丢弃等于假设中位数的观测后无有效符号。",
 "Sign test has no valid signs after discarding ties at the hypothesized median."},
{"interp.sign_warn_large_n_note",
 "有效符号数 ≥ 25；主 P 仍为二项精确，正态近似仅作参考。",
 "Valid signs ≥ 25; the primary P remains exact binomial—normal approximation is reference only."},
{"interp.sign_ci_err_no_data",
 "中位数置信区间需要至少一个有限观测。",
 "Median confidence interval needs at least one finite observation."},
{"interp.sign_ci_warn_insufficient_n",
 "n<2 时无法计算符号检验中位数置信区间。",
 "Sign-test median CI cannot be computed when n<2."},
{"interp.sign_ci_warn_unavailable",
 "无法构造合法的符号检验中位数置信区间。",
 "A valid sign-test median confidence interval could not be constructed."},
{"interp.sign_err_pair_mismatch",
 "配对符号检验要求两列等长。",
 "Paired sign test requires equal-length columns."},
{"interp.mood_err_invalid_groups",
 "Mood 中位数检验至少需要两个且标签匹配的组。",
 "Mood median test needs at least two groups with matching labels."},
{"interp.mood_warn_group_dropped",
 "观测数少于 2 的组已从 Mood 检验中排除。",
 "Groups with fewer than 2 observations were excluded from the Mood test."},
{"interp.mood_err_insufficient_groups",
 "排除小组后不足两个组，无法计算 Mood 中位数检验。",
 "Fewer than two groups remain after dropping small groups; Mood median test cannot be computed."},
{"interp.mood_err_insufficient_observations",
 "Mood 中位数检验有效观测不足。",
 "Mood median test has insufficient valid observations."},
{"interp.mood_err_median_undefined",
 "无法计算总体中位数。",
 "Overall median cannot be computed."},
{"interp.mood_err_degenerate_table",
 "N≤ 或 N> 一侧为 0，Mood χ² 不可计算。",
 "One side of N≤ or N> is 0; Mood χ² cannot be computed."},
{"interp.mood_warn_expected_count",
 "存在期望频数 < 5 的单元格，χ² 近似需谨慎解读。",
 "Some cells have expected count < 5; interpret the χ² approximation cautiously."},
{"interp.mood_warn_small_sample",
 "存在样本量较小的组，Mood χ² 近似只作提示。",
 "A group has a small sample size; the Mood χ² approximation is advisory only."},
{"interp.runs_err_insufficient_n",
 "游程检验至少需要 2 个有限观测。",
 "Runs test needs at least 2 finite observations."},
{"interp.runs_err_missing_criterion",
 "指定比较准则时必须提供有限的 K。",
 "A finite K must be provided when a comparison criterion is specified."},
{"interp.runs_err_one_sided_empty",
 "所有观测都在比较准则的同一侧，无法进行游程检验。",
 "All observations lie on the same side of the criterion; runs test cannot be performed."},
{"interp.runs_warn_normal_thin",
 "两侧观测少于 10，正态近似可能不稳定。",
 "Fewer than 10 observations on a side; the normal approximation may be unstable."},
{"interp.runs_err_variance_invalid",
 "游程方差不可计算。",
 "Runs variance cannot be computed."},
{"interp.run_chart_err_empty",
 "Run Chart 需要至少一个有限观测。",
 "Run Chart needs at least one finite observation."},
{"interp.run_chart_warn_small_n",
 "N < 3，仅输出图形与描述，不出随机性近似 P。",
 "N < 3: chart and description only—no approximate randomness P."},
{"interp.run_chart_warn_median_degenerate",
 "全部点落在中位数同一侧，关于中位数的随机性 P 不可用。",
 "All points lie on one side of the median; median-based randomness P is unavailable."},
{"interp.run_chart_warn_flat_as_down",
 "存在相邻相等点：按产品锁定计入下行游程（平坦差分归下行）。",
 "Adjacent equal points present: product lock counts them as down runs (flat diffs as down)."},
{"interp.gage_warn_neg_var_truncated",
 "方差分量原始估计为负，已截断为 0。",
 "Negative variance-component estimate(s) were truncated to 0."},
{"interp.gage_err_invalid_tolerance",
 "公差必须为有限非负数；NaN、无穷或负数不可用。",
 "Tolerance must be a finite non-negative number; NaN, infinity, or negative values are not allowed."},
{"interp.gage_err_shape",
 "Gage R&R 要求测量值、零件和操作员列长度一致且至少有四条记录。",
 "Gage R&R requires measurement, part, and operator columns of equal length with at least four records."},
{"interp.gage_err_invalid_row",
 "测量值、零件和操作员标签必须有效。",
 "Measurements and part/operator labels must be valid."},
{"interp.gage_err_insufficient_levels",
 "Crossed Gage R&R 至少需要两个零件和两个操作员。",
 "Crossed Gage R&R requires at least two parts and two operators."},
{"interp.gage_err_insufficient_replicates",
 "每个零件与操作员组合至少需要两次重复测量。",
 "Each part×operator cell needs at least two replicate measurements."},
{"interp.gage_err_unbalanced_replicates",
 "每个零件×操作员组合必须具有相同的重复次数。",
 "Every part×operator cell must have the same number of replicates."},
{"interp.gage_warn_interaction_pooling",
 "Part×Operator 交互 p>0.25，传统 AIAG 流程可考虑将交互并入重复性；当前结果保留完整交互模型，不自动缩减。",
 "Part×Operator interaction p>0.25; traditional AIAG practice may pool interaction into repeatability. This result keeps the full interaction model and does not auto-reduce."},
{"interp.gage_warn_ndc_lt5",
 "ndc<5 只作为调查提示，不是量具不合格的绝对结论。",
 "ndc<5 is an investigation hint only, not an absolute gage-fail conclusion."},
{"interp.gage_err_ndc_not_estimable",
 "Gage 标准差为 0，ndc 不可估计。",
 "Gage standard deviation is 0; ndc is not estimable."},
{"interp.gage_err_zero_total_variation",
 "所有测量值相同，无法估计 Gage R&R 方差分量。",
 "All measurements are identical; Gage R&R variance components cannot be estimated."},
{"interp.nested_gage_err_invalid_tolerance",
 "公差必须为有限非负数。",
 "Tolerance must be a finite non-negative number."},
{"interp.nested_gage_err_shape",
 "Nested Gage R&R 要求长度一致、至少四条记录。",
 "Nested Gage R&R requires equal-length columns and at least four records."},
{"interp.nested_gage_err_part_multi_operator",
 "Nested Gage R&R 中每个零件必须只属于一个操作员。",
 "In Nested Gage R&R, each part must belong to only one operator."},
{"interp.nested_gage_err_insufficient_levels",
 "Nested Gage R&R 至少需要两个操作员和两个零件。",
 "Nested Gage R&R requires at least two operators and two parts."},
{"interp.nested_gage_err_insufficient_replicates",
 "每个零件至少需要两次重复测量。",
 "Each part needs at least two replicate measurements."},
{"interp.nested_gage_err_unbalanced_replicates",
 "每个零件必须具有相同的重复次数。",
 "Every part must have the same number of replicates."},
{"interp.nested_gage_err_empty_operator",
 "每个操作员必须至少有一个零件。",
 "Each operator must have at least one part."},
{"interp.nested_gage_err_unbalanced_operator",
 "每个操作员必须分配相同数量的零件。",
 "Each operator must be assigned the same number of parts."},
{"interp.nested_gage_warn_ndc_lt5",
 "ndc<5 只作为调查提示。",
 "ndc<5 is an investigation hint only."},
{"interp.nested_gage_err_zero_total_variation",
 "所有测量值相同，无法估计 Nested Gage R&R 方差分量。",
 "All measurements are identical; Nested Gage R&R variance components cannot be estimated."},
{"interp.expanded_gage_err_length_mismatch",
 "测量值与因子列长度必须一致。",
 "Measurement and factor columns must have equal length."},
{"interp.expanded_gage_err_insufficient_data",
 "三因子 Expanded Gage 需要足够观测。",
 "Three-factor Expanded Gage needs enough observations."},
{"interp.expanded_gage_err_non_finite",
 "测量值必须有限。",
 "Measurements must be finite."},
{"interp.expanded_gage_err_insufficient_levels",
 "Part、Operator 与附加因子各自至少需要 2 个水平。",
 "Part, Operator, and the additional factor each need at least 2 levels."},
{"interp.expanded_gage_err_incomplete_design",
 "本轮 Expanded 仅支持完整平衡交叉；缺失格子请用交叉 Gage 或后续 GLM。",
 "This Expanded path supports only complete balanced crossed designs; for missing cells use crossed Gage or a later GLM."},
{"interp.expanded_gage_err_unbalanced_replicates",
 "各格子重复次数必须相同。",
 "Every cell must have the same number of replicates."},
{"interp.expanded_gage_err_no_replicates",
 "缺少重复。",
 "Replicates are missing."},
{"interp.expanded_gage_warn_three_way_as_error",
 "重复次数=1：三阶交互用作重复性误差估计。",
 "Replicates=1: the three-way interaction is used as the repeatability error estimate."},
{"interp.expanded_gage_info_scoped",
 "本命令为平衡三因子随机 Expanded；不平衡/固定效应/嵌套 GLM 仍延后。",
 "This command is balanced three-factor random Expanded; unbalanced / fixed-effect / nested GLM remains deferred."},
{"interp.msa_type1_err_input",
 "Type 1 Gage 至少需要两条有限测量值，参考值和公差必须有效。",
 "Type 1 Gage requires at least two finite measurements, and the reference and tolerance must be valid."},
{"interp.msa_type1_err_non_finite",
 "测量值必须为有限数。",
 "Measurements must be finite."},
{"interp.msa_type1_err_zero_repeatability",
 "重复性为零时 t、p 和置信区间不可用，不输出 p=0。",
 "When repeatability is zero, t, p, and confidence intervals are unavailable; p=0 is not reported."},
{"interp.bias_lin_err_shape",
 "Bias/Linearity 要求至少三组且参考值与测量值长度一致。",
 "Bias/Linearity requires at least three pairs and matching reference and measurement lengths."},
{"interp.bias_lin_err_non_finite",
 "参考值和测量值必须为有限数。",
 "Reference and measurement values must be finite."},
{"interp.bias_lin_err_zero_ref_range",
 "参考值必须包含至少两个不同水平。",
 "References must include at least two distinct levels."},
{"interp.bias_lin_err_process_variation",
 "过程变差必须为有限正数（6×过程标准差）。",
 "Process variation must be a finite positive number (6× process standard deviation)."},
{"interp.gage_stab_err_input",
 "Stability 至少需要三条测量值。",
 "Stability requires at least three measurements."},
{"interp.msa_type1_err_need_measurement_col",
 "请选择测量值列，并在配置中提供参考值。",
 "Select a measurement column and provide a reference value in the configuration."},
{"interp.bias_lin_err_need_reference_col",
 "请选择参考值列。",
 "Select a reference-value column."},
{"interp.bias_lin_err_no_complete_rows",
 "没有可用于 Bias/Linearity 的 complete-case 行。",
 "No complete-case rows are available for Bias/Linearity."},
{"interp.bias_lin_info_no_process_variation",
 "未提供过程变差（6×过程标准差），Linearity / %Linearity / %Bias 未计算。",
 "Process variation (6× process SD) was not provided; Linearity / %Linearity / %Bias were not computed."},
{"interp.msa_type1_err_need_reference_value",
 "请输入参考值。",
 "Enter a reference value."},
{"interp.msa_err_need_measurement_col",
 "请选择测量值列。",
 "Select a measurement column."},
{"interp.attr_agree_err_need_columns",
 "请选择评级、部件和评估者列。",
 "Select rating, part, and appraiser columns."},
{"interp.attr_agree_warn_weighted_unranked",
 "加权 Kappa 需要可排序的数值评级；已回退未加权 Cohen。",
 "Weighted Kappa needs sortable numeric ratings; fell back to unweighted Cohen."},
{"interp.attr_agree_warn_kendall_need_numeric",
 "有序评级必须全部为数值，才能计算 Kendall；未使用字典序。",
 "Ordinal ratings must all be numeric to compute Kendall; lexicographic order is not used."},
{"interp.attr_agree_warn_kendall_need_levels",
 "Kendall 系数需要至少三个有序等级；当前只输出 Kappa。",
 "Kendall coefficients need at least three ordinal levels; only Kappa is reported."},
{"interp.attr_agree_warn_kendall_w_unidentifiable",
 "评估者间 Kendall W 不可识别；不伪造 W=1。",
 "Inter-appraiser Kendall W is not identifiable; W=1 is not fabricated."},
{"interp.attr_agree_warn_mode_tie",
 "部分零件评级众数平票，对应评估者×零件一致率未计算。",
 "Some part rating modes are tied; the corresponding appraiser×part agreement rates were not computed."},
{"interp.attr_agree_warn_unknown_weight_scheme",
 "未知的 kappa_weight_scheme，已回退为 none。",
 "Unknown kappa_weight_scheme; fell back to none."},
{"interp.attr_agree_err_shape",
 "属性一致性要求列长度一致，标准列为空或与记录数一致，置信度必须在 0 与 1 之间。",
 "Attribute agreement requires equal column lengths, an empty or matching-length standard column, and confidence in (0, 1)."},
{"interp.attr_agree_err_empty_labels",
 "项目和评估者标签不能为空。",
 "Item and appraiser labels cannot be empty."},
{"interp.attr_agree_err_insufficient_levels",
 "属性一致性至少需要两个项目和两个评估者。",
 "Attribute agreement requires at least two items and two appraisers."},
{"interp.attr_agree_warn_missing_ratings",
 "存在缺失评级；相关配对只使用双方均有评级的项目。",
 "Missing ratings present; paired comparisons use only items rated by both sides."},
{"interp.attr_agree_warn_incomplete_items",
 "部分项目未被某些评估者评级，评估者间比较将排除这些项目。",
 "Some items were not rated by every appraiser; inter-appraiser comparisons exclude those items."},
{"interp.attr_agree_warn_missing_standards",
 "部分项目缺少标准评级，相关评估者-标准比较将排除这些项目。",
 "Some items lack a standard rating; appraiser-vs-standard comparisons exclude those items."},
{"interp.attr_agree_warn_unequal_replicates",
 "评估者重复次数不一致；不等长配对已排除，不会静默截断。",
 "Appraiser replicate counts differ; unequal-length pairs were excluded without silent truncation."},
{"interp.attr_agree_info_fleiss_unweighted",
 "Fleiss overall Kappa 保持未加权；linear/quadratic 仅用于两两 Cohen。",
 "Fleiss overall Kappa stays unweighted; linear/quadratic apply only to pairwise Cohen."},
{"interp.attr_agree_warn_kappa_unidentifiable",
 "期望一致率 P_expected=1，Kappa 不可识别，不计算无限标准误。",
 "Expected agreement P_expected=1; Kappa is not identifiable and infinite SE is not computed."},
{"interp.reg_err_shape",
 "回归至少需要两个观测、一个响应列和一个预测列。",
 "Linear regression requires at least two observations, one response column, and one predictor column."},
{"interp.reg_err_confidence",
 "置信水平必须为 (0,1) 内的有限数。",
 "Confidence level must be a finite number in (0, 1)."},
{"interp.reg_err_predictor_labels",
 "预测变量数量和标签数量必须有效且一致。",
 "Predictor count and label count must be valid and match."},
{"interp.reg_err_ragged_predictors",
 "每行预测变量必须具有相同列数。",
 "Each predictor row must have the same number of columns."},
{"interp.reg_err_insufficient_n",
 "回归观测数必须不少于参数个数。",
 "The number of observations must be at least the number of parameters."},
{"interp.reg_warn_no_error_df",
 "误差自由度 N-p-1 ≤ 0，不输出 t、F 与 P。",
 "Error degrees of freedom N-p-1 ≤ 0; t, F, and P are not reported."},
{"interp.reg_err_invalid_response",
 "响应变量必须全部为有限数值。",
 "All response values must be finite."},
{"interp.reg_err_invalid_predictor",
 "预测变量必须全部为有限数值。",
 "All predictor values must be finite."},
{"interp.reg_err_collinear_design",
 "设计矩阵存在完全共线或常量预测变量。",
 "The design matrix has perfect collinearity or a constant predictor."},
{"interp.reg_err_rank_deficient",
 "设计矩阵秩亏，已拒绝拟合。",
 "The design matrix is rank-deficient; the fit was rejected."},
{"interp.reg_rec_rank_deficient",
 "秩亏时不要解释系数；先检查常量列或完全共线预测变量。",
 "Do not interpret coefficients when rank-deficient; first check constant columns or perfectly collinear predictors."},
{"interp.reg_err_singular_cov",
 "无法计算回归系数协方差矩阵。",
 "The regression coefficient covariance matrix could not be computed."},
{"interp.reg_warn_vif_gt5",
 "VIF>5 提示共线性调查，不会自动删除预测变量。",
 "VIF>5 flags a collinearity investigation; predictors are not removed automatically."},
{"interp.reg_warn_seq_adj_ss",
 "多预测变量回归应同时查看 Seq SS 与 Adj SS；两者不一致常见于不平衡或共线设计。",
 "For multi-predictor regression, review both Seq SS and Adj SS; differences are common in unbalanced or collinear designs."},
{"interp.reg_warn_dw_bounds",
 "Durbin-Watson 临界界不可用（需要 15≤n≤100 且 1≤k'≤5）。",
 "Durbin–Watson critical bounds are unavailable (requires 15≤n≤100 and 1≤k'≤5)."},
{"interp.reg_assume_dw_out_of_table",
 "Durbin-Watson 按输入顺序计算；n 或回归元数超出 α=0.05 界表范围，未给 dL/dU。",
 "Durbin–Watson is computed in input order; n or number of regressors is outside the α=0.05 bound table, so dL/dU are not provided."},
{"interp.reg_assume_dw_approx",
 "Durbin-Watson 按输入顺序；判定区对照 α=0.05 近似 dL/dU，不能写成已证明无自相关。",
 "Durbin–Watson uses input order; decision regions use approximate α=0.05 dL/dU and must not be written as proven no autocorrelation."},
{"interp.reg_assume_ad_residual",
 "Anderson-Darling 只能在 alpha 下拒绝或未拒绝残差正态假设。",
 "Anderson–Darling can only reject or fail to reject residual normality at alpha; it does not prove normality."},
{"interp.reg_assume_normality_missing",
 "残差正态性未计算。",
 "Residual normality was not computed."},
{"interp.reg_assume_homoscedasticity",
 "方差齐性主要依据残差对拟合值图，当前不单独给出数值判定。",
 "Homoscedasticity is assessed mainly from the residual-vs-fitted plot; no separate numeric decision is given."},
{"interp.reg_rec_need_error_df",
 "增加独立观测或减少模型项后再解释系数显著性。",
 "Add independent observations or reduce model terms before interpreting coefficient significance."},
{"interp.reg_rule_error_df_ok",
 "误差自由度为正，系数推断可用。",
 "Error degrees of freedom are positive; coefficient inference is available."},
{"interp.reg_rec_use_residual_plots",
 "仍需结合残差图和影响点解释模型。",
 "Still interpret the model with residual plots and influential points."},
{"interp.reg_rule_design_estimable",
 "当前设计矩阵可估计。",
 "The current design matrix is estimable."},
{"interp.reg_rule_outlier_triggered",
 "存在删除学生化残差绝对值大于 3 的观测。",
 "Observations with absolute deleted studentized residual greater than 3 are present."},
{"interp.reg_rule_outlier_clear",
 "没有 |删除学生化残差| > 3 的观测。",
 "No observations with |deleted studentized residual| > 3."},
{"interp.reg_rule_leverage_triggered",
 "存在杠杆值超过 2p/n 的高杠杆点。",
 "High-leverage points with leverage exceeding 2p/n are present."},
{"interp.reg_rule_influence_triggered",
 "Cook's D 或 DFITS 超过常用调查阈值。",
 "Cook's D or DFITS exceeds a common investigation threshold."},
{"interp.reg_rec_review_outliers",
 "回查原始行；解释层不会自动删除这些观测。",
 "Review source rows; the interpretation layer does not delete these observations automatically."},
{"interp.reg_rec_check_residuals",
 "仍应检查残差图，不能据此宣称没有异常。",
 "Still check residual plots; do not claim there are no anomalies from this alone."},
{"interp.reg_rec_investigate_leverage",
 "高杠杆点需要调查，不自动删除。",
 "High-leverage points need investigation and are not deleted automatically."},
{"interp.reg_rec_investigate_influence",
 "影响点提示需要调查，解释层不会自动删除这些观测。",
 "Influential points flag investigation; the interpretation layer does not delete these observations automatically."},
{"interp.reg_rule_vif_triggered",
 "至少一个预测变量 VIF>5。",
 "At least one predictor has VIF>5."},
{"interp.reg_rule_vif_clear",
 "未发现 VIF>5 的预测变量。",
 "No predictor with VIF>5 was found."},
{"interp.reg_rec_vif_investigate",
 "VIF>5 只提示共线性调查，不会自动删除变量。",
 "VIF>5 only flags a collinearity investigation; variables are not removed automatically."},
{"interp.anova_err_need_two_groups",
 "单因素 ANOVA 至少需要两个有效组。",
 "One-way ANOVA requires at least two valid groups."},
{"interp.anova_err_label_count",
 "组标签数量必须与有效组数量一致。",
 "The number of group labels must match the number of valid groups."},
{"interp.anova_err_empty_group",
 "ANOVA 不允许存在没有有效观测的组。",
 "ANOVA does not allow a group with no valid observations."},
{"interp.anova_err_zero_error_ss",
 "组内误差平方和为 0，无法计算有限 F 统计量。",
 "Within-group error sum of squares is 0; a finite F statistic cannot be computed."},
{"interp.anova_rule_estimability_zero_error",
 "误差自由度或组内平方和为 0，不输出伪造 F/P。",
 "Error degrees of freedom or within-group sum of squares is 0; forged F/P values are not reported."},
{"interp.anova_rec_add_replicates",
 "增加组内重复或检查是否所有观测完全相同。",
 "Add within-group replicates or check whether all observations are identical."},
{"interp.anova_assume_residual_normality",
 "ANOVA 残差正态性只能拒绝或未拒绝假设，不能证明组内误差正态。",
 "ANOVA residual normality can only reject or fail to reject the assumption; it does not prove within-group errors are normal."},
{"interp.anova_assume_levene_homogeneity",
 "Levene 检验只作为方差齐性调查证据，不能单独决定模型是否可用。",
 "Levene’s test is only investigative evidence for equal variances and alone cannot decide whether the model is usable."},
{"interp.anova_rule_error_df_ok",
 "误差自由度大于 0，F/P 可计算。",
 "Error degrees of freedom are greater than 0; F/P can be computed."},
{"interp.anova_rec_need_posthoc",
 "总体 F 显著只说明至少一组均值不同，需要多重比较。",
 "A significant overall F only indicates that at least one group mean differs; multiple comparisons are needed."},
{"interp.anova_rule_levene_against",
 "Levene 检验提供了组方差不同的证据。",
 "Levene’s test provides evidence that group variances differ."},
{"interp.anova_rule_levene_clear",
 "当前 Levene 检验未提供组方差不同的证据。",
 "The current Levene’s test does not provide evidence that group variances differ."},
{"interp.anova_rec_heteroscedasticity",
 "方差不齐时应结合图形和非参数替代方法，而不是直接宣称 ANOVA 无效。",
 "When variances are unequal, combine plots and nonparametric alternatives rather than declaring ANOVA invalid outright."},
{"interp.twoway_anova_err_shape",
 "两个因子和响应变量必须具有相同且非零的行数。",
 "Both factors and the response must have the same nonzero number of rows."},
{"interp.twoway_anova_warn_omitted",
 "含缺失因子或响应值的观测已从分析中排除。",
 "Observations with missing factor or response values were excluded from the analysis."},
{"interp.twoway_anova_err_levels",
 "双因素 ANOVA 需要两个因子各至少两个水平及至少三个观测。",
 "Two-factor ANOVA requires at least two levels for each factor and at least three observations."},
{"interp.twoway_anova_warn_small_n",
 "观测数较少；部分效应可能不可估计或误差自由度不足。",
 "Few observations; some effects may be non-estimable or error degrees of freedom may be insufficient."},
{"interp.twoway_anova_warn_empty_cells",
 "因子组合存在空单元，交互项可能秩亏。",
 "Some factor combinations have empty cells; the interaction may be rank-deficient."},
{"interp.twoway_anova_warn_unbalanced",
 "因子组合的重复数不平衡；Seq SS 与 Adj SS 可能不同。",
 "Factor-combination replicates are unbalanced; Seq SS and Adj SS may differ."},
{"interp.twoway_anova_warn_rank_deficient",
 "设计矩阵秩亏；不可估计的项不输出伪造 F/P。",
 "The design matrix is rank-deficient; non-estimable terms do not report forged F/P values."},
{"interp.twoway_anova_warn_no_error_df",
 "误差自由度为 0，无法计算 F 与 P。",
 "Error degrees of freedom are 0; F and P cannot be computed."},
{"interp.twoway_anova_assume_residual_normality",
 "双因素 ANOVA 残差来自单元均值；拒绝正态假设只是调查证据。",
 "Two-factor ANOVA residuals come from cell means; rejecting normality is investigative evidence only."},
{"interp.twoway_anova_assume_levene",
 "单元重复数足够时用 Levene 检验作为方差齐性证据。",
 "When cell replicates are sufficient, Levene’s test is used as evidence of variance homogeneity."},
{"interp.twoway_anova_assume_homogeneity_missing",
 "单元重复不足，无法计算方差齐性检验。",
 "Cell replicates are insufficient; a variance-homogeneity test cannot be computed."},
};

}  // namespace

void append_report_text_catalog_part12(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart12),
        std::end(kReportTextCatalogPart12));
}

}  // namespace datalab::domain
