#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart8[] = {
{"header.variable_2",
 "变量 2",
 "Variable 2"},
{"header.correlation",
 "相关系数",
 "Correlation"},
{"header.confidence_interval",
 "置信区间",
 "Confidence interval"},
{"header.confidence_level",
 "置信水平",
 "Confidence level"},
{"header.hypothesized_mean",
 "假设均值",
 "Hypothesized mean"},
{"header.mean_difference",
 "均值差",
 "Mean difference"},
{"header.se_difference",
 "SE 差值",
 "SE difference"},
{"header.event_count",
 "事件数",
 "Events"},
{"header.trial_count",
 "试验数",
 "Trials"},
{"header.proportion",
 "比例",
 "Proportion"},
{"header.rate",
 "率",
 "Rate"},
{"header.exposure_length",
 "观测长度",
 "Exposure length"},
{"header.part_count",
 "零件数",
 "Parts"},
{"header.operator_count",
 "操作员数",
 "Operators"},
{"header.replicate_count",
 "重复次数",
 "Replicates"},
{"page.capability_normal",
 "正态过程能力分析",
 "Normal process capability analysis"},
{"page.capability_johnson",
 "Johnson 变换过程能力",
 "Johnson-transform process capability"},
{"page.capability_nonnormal",
 "非正态过程能力",
 "Nonnormal process capability"},
{"page.capability_between_within",
 "组间/组内过程能力",
 "Between/within process capability"},
{"page.doe_response_analysis",
 "DOE 响应分析",
 "DOE response analysis"},
{"page.doe_response_optimization",
 "DOE 响应优化",
 "DOE response optimization"},
{"page.plackett_burman_design",
 "Plackett–Burman 设计",
 "Plackett–Burman design"},
{"page.oneway_anova",
 "单因素 ANOVA",
 "One-way ANOVA"},
{"page.linear_regression",
 "线性回归",
 "Linear regression"},
{"page.display_descriptive_stats",
 "显示描述性统计",
 "Display descriptive statistics"},
{"page.normality_test",
 "正态性检验",
 "Normality test"},
{"page.outlier_test",
 "异常值检验",
 "Outlier test"},
{"page.one_sample_t",
 "单样本 t 检验",
 "One-sample t-test"},
{"page.one_sample_z",
 "单样本 Z 检验",
 "One-sample Z-test"},
{"page.two_sample_t",
 "双样本 t 检验",
 "Two-sample t-test"},
{"page.paired_t",
 "配对 t 检验",
 "Paired t-test"},
{"page.equivalence_test",
 "等价性检验",
 "Equivalence test"},
{"page.equivalence_one_sample",
 "单样本等价性检验",
 "1-Sample Equivalence Test"},
{"page.equivalence_two_sample",
 "双样本等价性检验",
 "2-Sample Equivalence Test"},
{"page.equivalence_two_sample_ratio",
 "双样本均值比等价性检验",
 "2-Sample Equivalence Ratio Test"},
{"page.equivalence_paired",
 "配对等价性检验",
 "Paired Equivalence Test"},
{"page.equivalence_one_proportion",
 "单比例等价性检验",
 "1-Proportion Equivalence Test"},
{"page.equivalence_two_proportion",
 "两比例等价性检验",
 "2-Proportion Equivalence Test"},
{"table.fit_forecast_detail",
 "拟合与预测明细",
 "Fit and forecast detail"},
{"table.forecast_accuracy",
 "预测准确度",
 "Forecast accuracy"},
{"table.candidate_model_comparison",
 "候选模型比较",
 "Candidate model comparison"},
{"table.model_summary_forecast",
 "模型摘要与预测",
 "Model summary and forecast"},
{"table.seasonal_indices",
 "季节指数",
 "Seasonal indices"},
{"table.sarima_candidate_comparison",
 "SARIMA 候选模型比较",
 "SARIMA candidate model comparison"},
{"table.rolling_origin_eval",
 "Rolling-origin 评估",
 "Rolling-origin evaluation"},
{"table.rolling_origin_detail",
 "Rolling-origin 明细",
 "Rolling-origin detail"},
{"table.pca_eigen",
 "特征值与解释率",
 "Eigenvalues and explained variance"},
{"table.pca_coefficients",
 "主成分系数",
 "Principal component coefficients"},
{"table.pca_loadings",
 "相关载荷",
 "Correlation loadings"},
{"table.pca_scores",
 "主成分得分",
 "Principal component scores"},
{"table.pca_tq_limits",
 "T² 与 Q 阈值",
 "T² and Q limits"},
{"table.pca_tq_residuals",
 "T² 与 Q 残差",
 "T² and Q residuals"},
{"table.cluster_summary",
 "簇摘要",
 "Cluster summary"},
{"table.centroids_analysis_scale",
 "质心（分析尺度）",
 "Centroids (analysis scale)"},
{"table.cluster_assignment",
 "簇分配",
 "Cluster assignment"},
{"table.cart_nodes",
 "树结点",
 "Tree nodes"},
{"table.variable_importance",
 "变量重要性",
 "Variable importance"},
{"table.train_confusion",
 "训练集混淆矩阵",
 "Training confusion matrix"},
{"table.stepwise_steps",
 "逐步步骤",
 "Stepwise steps"},
{"table.selected_terms",
 "选入项",
 "Selected terms"},
{"table.final_model_coefficients",
 "终模型系数",
 "Final model coefficients"},
{"table.power_sample_size",
 "功效与样本量",
 "Power and sample size"},
{"table.sampling_plan",
 "抽样计划",
 "Sampling plan"},
{"table.oc_curve",
 "OC 曲线",
 "OC curve"},
{"table.decision_limits",
 "决策限",
 "Decision limits"},
{"plot.actual_fitted_forecast_interval",
 "实际值、拟合值与预测区间",
 "Actual, fitted, and prediction interval"},
{"plot.arima_fit_forecast",
 "ARIMA 拟合与预测",
 "ARIMA fit and forecast"},
{"plot.decompose_fit",
 "时间序列分解拟合",
 "Time series decomposition fit"},
{"plot.seasonal_fit_forecast",
 "季节性拟合与预测",
 "Seasonal fit and forecast"},
{"plot.pca_scores",
 "PCA 得分图",
 "PCA score plot"},
{"plot.kmeans_scatter",
 "K-Means 散点（前两列）",
 "K-Means scatter (first two columns)"},
{"plot.power_curve",
 "功效曲线",
 "Power curve"},
{"plot.oc_curve_binomial",
 "OC 曲线（二项）",
 "Binomial OC curve"},
{"plot.suffix.anom_chart",
 "ANOM 图",
 "ANOM chart"},
{"plot.series.forecast",
 "预测值",
 "Forecast"},
{"plot.series.prediction_interval",
 "预测区间",
 "Prediction interval"},
{"plot.series.trend",
 "趋势",
 "Trend"},
{"plot.series.power",
 "功效",
 "Power"},
{"header.model",
 "模型",
 "Model"},
{"header.best_model",
 "最优模型",
 "Best model"},
{"header.intercept",
 "截距",
 "Intercept"},
{"header.coeff_drift",
 "系数/漂移",
 "Coefficient/drift"},
{"header.forecast_horizon",
 "预测期",
 "Forecast horizon"},
{"header.quantile",
 "分位数",
 "Quantile"},
{"header.t2_limit",
 "T² 限",
 "T² limit"},
{"header.q_limit",
 "Q 限",
 "Q limit"},
{"header.basis",
 "口径",
 "Basis"},
{"header.t2_anomaly",
 "T² 异常",
 "T² anomaly"},
{"header.q_residual",
 "Q 残差",
 "Q residual"},
{"header.q_anomaly",
 "Q 异常",
 "Q anomaly"},
{"header.combined_anomaly",
 "综合异常",
 "Combined anomaly"},
{"header.outside_decision_limit",
 "超出决策限",
 "Beyond decision limit"},
{"header.overall_mean",
 "总体均值",
 "Overall mean"},
{"header.within_sd",
 "组内 SD",
 "Within SD"},
{"header.target_proportion",
 "目标比例",
 "Target proportion"},
{"status.pca_empirical_quantile_not_minitab",
 "经验分位（非 Minitab T² 控制图 UCL）",
 "Empirical quantile (not a Minitab T² chart UCL)"},
{"status.intercept_only",
 "(仅截距)",
 "(Intercept only)"},
{"plot.axis.accept_probability_pa",
 "接收概率 Pa(p)",
 "Acceptance probability Pa(p)"},
{"page.imr_chart",
 "I-MR 控制图",
 "I-MR control chart"},
{"page.p_chart",
 "P 图",
 "P chart"},
{"page.np_chart",
 "NP 图",
 "NP chart"},
{"page.c_chart",
 "C 图",
 "C chart"},
{"page.u_chart",
 "U 图",
 "U chart"},
{"page.g_chart",
 "G 图",
 "G chart"},
{"page.g_chart_geometric",
 "G 图（几何间隔）",
 "G chart (geometric interval)"},
{"page.t_chart",
 "T 图",
 "T chart"},
{"page.t_chart_time",
 "T 图（时间间隔）",
 "T chart (time interval)"},
{"page.xbar_r_chart",
 "Xbar-R 控制图",
 "Xbar-R control chart"},
{"page.xbar_s_chart",
 "Xbar-S 控制图",
 "Xbar-S control chart"},
{"page.ewma_chart",
 "EWMA 控制图",
 "EWMA control chart"},
{"page.cusum_chart",
 "CUSUM 控制图",
 "CUSUM control chart"},
{"page.z_mr_chart",
 "Z-MR 控制图",
 "Z-MR control chart"},
{"page.ma_chart",
 "移动平均控制图",
 "Moving-average control chart"},
{"page.zone_chart",
 "区域图",
 "Zone chart"},
{"page.area_faceted",
 "区域图（分面）",
 "Faceted Area Plot"},
{"page.area_plot",
 "面积区域图",
 "Area Plot"},
{"page.capability_sixpack",
 "过程能力 Sixpack",
 "Process capability Sixpack"},
{"page.warranty_summary",
 "保修摘要",
 "Warranty summary"},
{"page.histogram",
 "直方图",
 "Histogram"},
{"page.run_chart",
 "运行图",
 "Run chart"},
{"page.boxplot",
 "箱线图",
 "Boxplot"},
{"page.pareto",
 "柏拉图",
 "Pareto chart"},
{"page.rsm_analysis",
 "响应曲面分析",
 "Response surface analysis"},
{"page.attribute_capability_binomial",
 "二项过程能力",
 "Binomial process capability"},
{"page.attribute_capability_poisson",
 "泊松过程能力",
 "Poisson process capability"},
{"page.factorial_full_2level",
 "2 水平全因子设计",
 "2-level full factorial design"},
{"page.factorial_fractional_2level",
 "2 水平部分析因设计",
 "2-level fractional factorial design"},
{"page.bbd_design",
 "Box–Behnken 设计",
 "Box–Behnken design"},
{"page.ccd_design",
 "中心复合设计 (CCD)",
 "Central composite design (CCD)"},
{"page.reliability_analysis",
 "可靠性分析",
 "Reliability analysis"},
{"page.km_interval_turnbull",
 "区间删失 Kaplan–Meier（Turnbull）",
 "Interval-censored Kaplan–Meier (Turnbull)"},
{"page.scatter",
 "散点图",
 "Scatterplot"},
{"page.interval_scatter",
 "区间散点图",
 "Interval scatterplot"},
{"page.correlogram",
 "相关图",
 "Correlogram"},
{"page.bubble",
 "气泡图",
 "Bubble chart"},
{"page.ecdf",
 "经验累积分布图",
 "Empirical CDF"},
{"page.matrix_plot",
 "矩阵图",
 "Matrix plot"},
{"page.marginal_plot",
 "边际图",
 "Marginal plot"},
{"page.parallel_coordinates",
 "平行坐标图",
 "Parallel coordinates"},
{"page.heatmap",
 "热图",
 "Heatmap"},
{"page.time_series",
 "时间序列图",
 "Time series plot"},
{"page.contour",
 "等值线图",
 "Contour plot"},
{"page.pie",
 "饼图",
 "Pie chart"},
{"page.density",
 "密度图",
 "Density plot"},
{"page.hexbin",
 "Hexbin / 二维分箱",
 "Hexbin / 2D binning"},
{"page.hexbin_short",
 "Hexbin",
 "Hexbin"},
{"page.hexbin_2d",
 "二维分箱",
 "2D binning"},
{"page.hexbin_2d_scatter",
 "二维分箱散点",
 "2D binning scatter"},
{"page.violin",
 "小提琴图",
 "Violin plot"},
{"page.bar",
 "条形图",
 "Bar chart"},
{"page.multi_vari",
 "Multi-Vari 图",
 "Multi-Vari chart"},
{"page.variability",
 "变异性图",
 "Variability chart"},
{"page.cause_effect",
 "因果图",
 "Cause-and-effect diagram"},
{"page.pearson_correlation",
 "Pearson 相关",
 "Pearson correlation"},
{"page.spearman_correlation",
 "Spearman 秩相关",
 "Spearman rank correlation"},
{"page.one_proportion",
 "单比例检验",
 "One-proportion test"},
{"page.two_proportions",
 "两比例检验",
 "Two-proportions test"},
{"page.one_poisson_rate",
 "单样本泊松率",
 "One-sample Poisson rate"},
{"page.two_poisson_rates",
 "双样本泊松率",
 "Two-sample Poisson rates"},
{"page.chi_square_contingency",
 "列联表卡方",
 "Chi-square contingency"},
};

}  // namespace

void append_report_text_catalog_part8(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart8),
        std::end(kReportTextCatalogPart8));
}

}  // namespace datalab::domain
