#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart11[] = {
{"interp.type1_gage_skip_n_obs",
 "Type 1 Gage 跳过 %1 个缺失或非法观测。",
 "Type 1 Gage skipped %1 missing or invalid observation(s)."},
{"interp.bias_linearity_skip_n_obs",
 "Bias/Linearity 跳过 %1 个缺失或不完整观测。",
 "Bias/Linearity skipped %1 missing or incomplete observation(s)."},
{"interp.mann_whitney_skip_n_star",
 "Mann–Whitney 跳过 %1 个缺失或非法单元格（含 *）。",
 "Mann–Whitney skipped %1 missing or invalid cell(s) (including *)."},
{"interp.wilcoxon_skip_n_star",
 "Wilcoxon 跳过 %1 个缺失或非法单元格（含 *）。",
 "Wilcoxon skipped %1 missing or invalid cell(s) (including *)."},
{"interp.sign_skip_n_star",
 "符号检验跳过 %1 个缺失或非法单元格（含 *）。",
 "Sign test skipped %1 missing or invalid cell(s) (including *)."},
{"interp.mcnemar_skip_n_star",
 "McNemar 按 complete-case 跳过 %1 个缺失或非法单元格（含 *）。",
 "McNemar complete-case skipped %1 missing or invalid cell(s) (including *)."},
{"interp.mood_skip_n_star",
 "Mood 跳过 %1 个缺失或非法单元格（含 *）。",
 "Mood skipped %1 missing or invalid cell(s) (including *)."},
{"interp.kruskal_skip_n_star",
 "Kruskal–Wallis 跳过 %1 个缺失或非法单元格（含 *）。",
 "Kruskal–Wallis skipped %1 missing or invalid cell(s) (including *)."},
{"interp.friedman_skip_n_star",
 "Friedman 按 complete-case 跳过 %1 个缺失或非法单元格（含 *）。",
 "Friedman complete-case skipped %1 missing or invalid cell(s) (including *)."},
{"interp.fisher_skip_n_missing_cells",
 "Fisher 精确检验按 complete-case 跳过 %1 个缺失单元格。",
 "Fisher exact complete-case skipped %1 missing cell(s)."},
{"interp.cochran_skip_n_rows_star",
 "Cochran Q 按 complete-case 跳过 %1 行缺失（含 *）。",
 "Cochran Q complete-case skipped %1 missing row(s) (including *)."},
{"interp.multivari_skip_n_rows",
 "测量或因子缺失、* 或非法单元格已跳过 %1 行。",
 "Skipped %1 row(s) with missing, *, or invalid measurement/factor cells."},
{"interp.cause_effect_skip_n_empty",
 "因果图跳过 %1 个空类别或空原因单元格。",
 "Cause-and-effect skipped %1 empty category or cause cell(s)."},
{"interp.runs_skip_nstar_ends",
 "游程检验跳过两端缺失或非法单元格 N* = %1。",
 "Runs test skipped end missing or invalid cells N* = %1."},
{"interp.run_chart_skip_nstar_ends",
 "运行图跳过两端缺失或非法单元格 N* = %1。",
 "Run chart skipped end missing or invalid cells N* = %1."},
{"interp.named_skip_n_missing_cells",
 "%1 跳过 %2 个缺失或非法单元格。",
 "%1 skipped %2 missing or invalid cell(s)."},
{"param.summary.partial_corr_yes",
 "偏相关 = 是",
 "Partial correlation = yes"},
{"param.summary.part_eq",
 "零件 = ",
 "Part = "},
{"param.summary.operator_eq",
 "操作员 = ",
 "Operator = "},
{"param.summary.operator_count_eq",
 "操作者数 = ",
 "Operator count = "},
{"param.summary.z_ooc_eq",
 "Z 超限 = ",
 "Z out-of-control = "},
{"param.summary.window_w_eq",
 "窗宽 w = ",
 "Window w = "},
{"param.summary.limit_multiplier_eq",
 "控制限倍数 = ",
 "Control-limit multiplier = "},
{"param.summary.selection_criterion_eq",
 "选择准则 = ",
 "Selection criterion = "},
{"param.summary.period_eq",
 "周期 = ",
 "Period = "},
{"param.summary.score_threshold_eq",
 "得分阈值 = ",
 "Score threshold = "},
{"param.summary.max_depth_eq",
 "深度上限 = ",
 "Max depth = "},
{"param.summary.leaf_count_eq",
 "叶数 = ",
 "Leaf count = "},
{"param.summary.selected_in_eq",
 "选入 = ",
 "Selected = "},
{"param.summary.bandwidth_pm_eq",
 "带宽 = ±",
 "Bandwidth = ±"},
{"param.summary.binning_rule_eq",
 "分箱规则 = ",
 "Binning rule = "},
{"param.summary.whisker_tukey",
 "须线 = Tukey 1.5×IQR",
 "Whiskers = Tukey 1.5×IQR"},
{"param.summary.design_source_id_eq",
 "设计来源 ID = ",
 "Design source ID = "},
{"param.summary.design_family_eq",
 "；设计族 = ",
 "; design family = "},
{"interp.eq_two_sample_skip_missing",
 "双样本等价性检验跳过缺失或非法单元格。",
 "Two-sample equivalence skipped missing or invalid cells."},
{"interp.eq_ratio_skip_missing",
 "均值比等价性检验跳过缺失或非法单元格。",
 "Mean-ratio equivalence skipped missing or invalid cells."},
{"interp.eq_paired_cc_skip_unpaired",
 "配对等价性检验按 complete-case 对齐，已跳过不成对的缺失或非法单元格。",
 "Paired equivalence used complete-case alignment and skipped unpaired missing or invalid cells."},
{"interp.eq_two_prop_skip_missing",
 "两比例等价性检验跳过了缺失或非法单元格。",
 "Two-proportion equivalence skipped missing or invalid cells."},
{"interp.reg_cc_skip_incomplete_rows",
 "回归使用 complete-case，跳过响应缺失、预测变量缺失或无效的行。",
 "Regression used complete-case and skipped rows with missing response, missing predictors, or invalid values."},
{"interp.two_prop_skip_missing",
 "两比例检验跳过了缺失或非法单元格。",
 "Two-proportion test skipped missing or invalid cells."},
{"interp.runs_err_interior_missing",
 "序列中间存在缺失或非法值，游程检验要求完整连续观测，未计算检验。",
 "Interior missing or invalid values found; runs test requires contiguous observations and was not computed."},
{"interp.smooth_skip_missing_cells",
 "平滑跳过缺失或无效的数值单元格。",
 "Smoothing skipped missing or invalid numeric cells."},
{"interp.logistic_cc_excluded_rows",
 "Logistic 回归使用 complete-case，缺失或非法行已排除。",
 "Logistic regression used complete-case; missing or invalid rows were excluded."},
{"interp.tol_skip_missing_star_invalid",
 "缺失、* 或非法数值未进入容差区间计算。",
 "Missing, *, or invalid values were not included in the tolerance-interval calculation."},
{"interp.decomp_skip_unpaired_time_value",
 "时间列与值列未配对的行已跳过，分解仅使用可对齐的完整观测。",
 "Rows with unpaired time/value columns were skipped; decomposition uses only alignable complete observations."},
{"interp.decomp_skip_missing_time_value",
 "分解跳过缺失或无效的时间/数值单元格。",
 "Decomposition skipped missing or invalid time/value cells."},
{"interp.nested_gage_skip_missing_cells",
 "Nested Gage R&R 跳过缺失或非法的测量/零件/操作者单元格。",
 "Nested Gage R&R skipped missing or invalid measurement/part/operator cells."},
{"interp.run_chart_err_interior_missing",
 "序列中间存在缺失或非法值，运行图随机性检验要求完整连续观测，未计算四模式 P。",
 "Interior missing or invalid values found; run-chart randomness tests require contiguous observations; four-pattern P values were not computed."},
{"interp.skip_missing_invalid_cells",
 "跳过了缺失或非法单元格。",
 "Missing or invalid cells were skipped."},
{"interp.pca_warn_missing_row_excluded",
 "包含缺失或非有限值的观测行已被排除。",
 "Observation rows with missing or non-finite values were excluded."},
{"interp.doe_warn_missing_response_effects",
 "缺失或非有限响应未参与 DOE 效应摘要。",
 "Missing or non-finite responses were not included in the DOE effects summary."},
{"interp.doe_warn_missing_response_fit",
 "缺失响应运行未参与拟合。",
 "Runs with missing responses were not included in the fit."},
{"interp.violin_skip_small_group_density",
 "某分组观测少于 2，已跳过密度形状。",
 "A group had fewer than 2 observations; density shape was skipped."},
{"interp.multi_vari_err_no_cc",
 "没有可用于 Multi-Vari 图的 complete-case 观测。",
 "No complete-case observations are available for the Multi-Vari chart."},
{"interp.cap_err_target_finite_no_silent_skip",
 "Target 必须为有限数，不能静默跳过。",
 "Target must be finite; it cannot be silently skipped."},
{"interp.distribution_id_summary",
 "个体分布识别按 Anderson-Darling 升序比较四族二参数分布；当前表内最优为 %1%2。排序结果不证明数据服从该分布，也不自动改写过程能力默认方法。",
 "Individual distribution identification ranks four two-parameter families by Anderson-Darling ascending; current table best is %1%2. Ranking does not prove the data follow that distribution and does not auto-rewrite the default capability method."},
{"interp.equal_variance_summary",
 "等方差检验方法为 %1%2。未拒绝原假设不能证明方差相等。%3",
 "Equal-variance test method is %1%2. Failure to reject the null does not prove equal variances. %3"},
{"interp.equal_variance_bonett",
 "Bonett 为连续分布下的标准差比路径，与中位数 Levene 不同；极偏/重尾小样本时宜对照 Levene。",
 "Bonett is a continuous-distribution SD-ratio path, distinct from median Levene; for highly skewed/heavy-tailed small samples, compare with Levene."},
{"interp.equal_variance_bartlett",
 "Bartlett 对正态偏离敏感；稳健场景宜对照中位数 Levene。正态假设状态未在本页验证。",
 "Bartlett is sensitive to nonnormality; for robust settings compare with median Levene. Normality was not verified on this page."},
{"interp.equal_variance_f",
 "F 检验依赖正态假设。",
 "The F-test depends on a normality assumption."},
{"interp.equal_variance_levene",
 "Levene（中位数）为稳健默认路径。",
 "Levene (median) is the robust default path."},
{"interp.cpk_below_1_33",
 "Cpk = %1，低于项目提示基准 1.33，需要调查过程能力。",
 "Cpk = %1, below the project hint baseline 1.33; investigate process capability."},
{"interp.cpk_meets_1_33",
 "Cpk = %1，达到项目提示基准 1.33；这不是已验证的过程合格结论。",
 "Cpk = %1, meets the project hint baseline 1.33; this is not a verified process pass conclusion."},
{"interp.ppk_below_1_33",
 "Ppk = %1，整体过程表现低于 1.33 提示基准。",
 "Ppk = %1; overall process performance is below the 1.33 hint baseline."},
{"interp.ppk_meets_1_33",
 "Ppk = %1，整体过程表现达到 1.33 提示基准。",
 "Ppk = %1; overall process performance meets the 1.33 hint baseline."},
{"interp.cpk_ci_bissell",
 "Cpk 置信区间 [%1, %2]（Bissell 近似，公式参考）。区间描述抽样不确定性，不是合格判定。",
 "Cpk confidence interval [%1, %2] (Bissell approximation, formula reference). The interval describes sampling uncertainty, not a pass/fail decision."},
{"interp.capability_assumption_not_verified",
 "过程能力未验证稳定性与正态性（assumption_status=%1），不能把 Cpk/Ppk 直接写成合格判定。",
 "Process capability has not verified stability and normality (assumption_status=%1); do not write Cpk/Ppk directly as a pass/fail decision."},
{"interp.anderson_darling_p_not_proof",
 "Anderson-Darling P = %1；未拒绝正态假设不等于已证明正态分布。",
 "Anderson-Darling P = %1; failure to reject normality is not proof of a normal distribution."},
{"interp.johnson_pp_honesty",
 "Johnson 变换后的 Pp/Ppk 是变换尺度上的 overall 指数；未拒绝变换后正态假设不等于原始数据服从正态分布，也不能写成过程合格。",
 "Johnson-transformed Pp/Ppk are overall indices on the transform scale; failure to reject post-transform normality does not mean the original data are normal and must not be written as process pass."},
{"interp.nonnormal_zscore_pp_honesty",
 "非正态 Z-score Pp/Ppk 依赖所选分布的 CDF；拟合未拒绝假设不等于已证明过程服从该分布，也不能写成过程合格。",
 "Nonnormal Z-score Pp/Ppk depend on the selected distribution CDF; failure to reject the fit does not prove the process follows that distribution and must not be written as process pass."},
{"interp.johnson_transform_ad_p",
 "Johnson 变换 AD P = %1；这是变换尺度上的拟合证据，不是原始数据正态性证明。",
 "Johnson transform AD P = %1; this is fit evidence on the transform scale, not proof of original-data normality."},
{"interp.between_within_capability_honesty",
 "组间/组内能力使用 σ_BW 计算 Cp/Cpk、样本标准差计算 Pp/Ppk；未验证稳定性不等于过程合格。",
 "Between/within capability uses σ_BW for Cp/Cpk and sample SD for Pp/Ppk; unverified stability is not process pass."},
{"interp.capability_research_preview_gate",
 "gate_status=%1：当前为研究/预览，证据类型 %2；未满足 golden/尾部验收前不得开放合格判定。",
 "gate_status=%1: research/preview now; evidence type %2; do not open pass/fail until golden and tail acceptance are satisfied."},
{"interp.capability_multi_screen_gate",
 "gate_status=%1；stability_screen=%2（OOC=%3）；bimodality_screen=%4（peaks=%5）；hartigan_dip=%6（D=%7）；mixture=%8（k=%9，ΔBIC=%10）：I-MR Rule-1 / 直方图双峰 / Hartigan dip / 高斯混合门禁筛查不等于完整稳定性或单峰验收。",
 "gate_status=%1; stability_screen=%2 (OOC=%3); bimodality_screen=%4 (peaks=%5); hartigan_dip=%6 (D=%7); mixture=%8 (k=%9, ΔBIC=%10): I-MR Rule-1 / histogram bimodality / Hartigan dip / Gaussian-mixture gate screens are not full stability or unimodality acceptance."},
{"interp.pareto_largest_category",
 "最大类别为“%1”，计数 %2，单项占比 %3%。",
 "Largest category is “%1”, count %2, item share %3%."},
{"interp.pareto_top_cumulative",
 "前 %1 个类别累计占比 %2%；应优先结合现场原因验证，而不是直接假设存在 80/20 规律。",
 "Top %1 categor(ies) cumulative share %2%; prioritize field cause verification rather than assuming an 80/20 rule."},
{"interp.pareto_use_with_field",
 "若要比较原因频次优先级，请改用柏拉图并结合现场验证。",
 "To prioritize cause frequencies, use a Pareto chart and validate in the field."},
{"interp.forecast_pi_not_spec",
 "预测区间反映模型不确定性，不是规格上下限；应通过滚动验证检查不同预测期的稳定性。",
 "Prediction intervals reflect model uncertainty, not specification limits; check stability across horizons with rolling validation."},
{"interp.decomp_multiplicative_advice",
 "乘法分解要求观测值为正；季节指数与趋势外推对结构变化敏感，应核对残差与移动平均边界。",
 "Multiplicative decomposition requires positive observations; seasonal indices and trend extrapolation are sensitive to structural change—check residuals and moving-average boundaries."},
{"interp.decomp_additive_advice",
 "加法分解的季节指数与线性趋势外推对结构变化敏感；应核对残差与非等间隔时间诊断。",
 "Additive decomposition seasonal indices and linear-trend extrapolation are sensitive to structural change; check residuals and irregular-spacing diagnostics."},
{"interp.forecast_smoothing_arima_advice",
 "未来预测依赖平滑/ARIMA 模型假设；应检查残差、自相关和结构变化，避免外推超出历史范围。",
 "Future forecasts depend on smoothing/ARIMA assumptions; check residuals, autocorrelation, and structural change—avoid extrapolating beyond the historical range."},
{"interp.anova_interval_plot_not_tukey",
 "区间图是各组均值的个体置信区间（pooled MSE），不是 Tukey 同时比较。",
 "The interval plot shows individual mean CIs (pooled MSE), not Tukey simultaneous comparisons."},
{"interp.anova_grouping_letters",
 "Grouping Information 使用 %1 个字母；字母来自成对显著矩阵，不改 Studentized Range 近似。",
 "Grouping Information uses %1 letter(s); letters come from the pairwise-significance matrix and do not change the Studentized Range approximation."},
{"interp.anova_residual_assumption_evidence",
 "残差正态或方差齐性检查提供了需要调查的证据，不能把 p 值直接写成工程差异。",
 "Residual normality or variance-homogeneity checks provide evidence to investigate; do not write p-values directly as engineering differences."},
{"interp.attr_agree_kappa_summary",
 "属性一致性报告观察一致率与 Kappa；≥3 名评估者使用 Fleiss，两两比较仍用 Cohen。",
 "Attribute agreement reports observed agreement and Kappa; ≥3 appraisers use Fleiss, pairwise comparisons still use Cohen."},
{"interp.attr_agree_kappa_honesty",
 "拒绝 Kappa=0 不等于已证明评估者一致；Kappa 只描述超出偶然的绝对一致率。",
 "Rejecting Kappa=0 does not prove appraiser agreement; Kappa only describes absolute agreement beyond chance."},
{"interp.attr_agree_kendall_computed",
 "有序评级已计算 Kendall 系数；拒绝 W=0 或 τ=0 不等于已证明有序一致。",
 "Ordinal ratings have Kendall coefficients; rejecting W=0 or τ=0 does not prove ordinal agreement."},
{"interp.attr_agree_kendall_unavailable",
 "已请求有序评级，但 Kendall 不可识别或等级不足；未伪造 W=1。",
 "Ordinal ratings were requested, but Kendall is non-identifiable or levels are insufficient; W=1 was not fabricated."},
{"interp.attr_agree_ordinal_hint",
 "名义评级看 Kappa；有序评级请设置 ordinal=true 以计算 Kendall W/τ。",
 "For nominal ratings use Kappa; for ordinal ratings set ordinal=true to compute Kendall W/τ."},
{"interp.attr_agree_missing_facts",
 "属性一致性缺少 Facts，不能从表头反解析 Kappa 或 Kendall。",
 "Attribute agreement lacks Facts; Kappa or Kendall must not be reverse-parsed from table headers."},
{"interp.durbin_watson_summary",
 "Durbin-Watson = %1，判定区 = %2（按输入顺序与 α=0.05 近似 dL/dU）。不能写成已证明无自相关或存在自相关。",
 "Durbin-Watson = %1, decision zone = %2 (approximate dL/dU at α=0.05 for the input order). Do not write proven absence or presence of autocorrelation."},
{"interp.imr_sigma_method",
 "I-MR σ 估计方法 = %1%2。σ 估计变化只影响控制限宽度，不能单独写成稳定结论。",
 "I-MR σ estimation method = %1%2. σ-method changes affect control-limit width only and must not alone be written as a stability conclusion."},
{"interp.imr_historical_limits",
 "控制限使用了历史 μ/σ；分阶段估计表仅供对照，不会自动改写全局限。",
 "Control limits use historical μ/σ; the stage-estimate table is for comparison only and does not auto-rewrite global limits."},
{"interp.imr_stage_estimates",
 "已按阶段列汇总估计（阶段数 = %1）；当前输出仍使用全样本估计限，不是逐阶段独立控制图。",
 "Stage-column estimates summarized (stage count = %1); current output still uses full-sample limits, not independent per-stage charts."},
{"interp.multivariate_spc_summary",
 "%1：m = %2，p = %3%4，超限 = %5。超限是统计信号提示，需要结合工艺调查，不能单独写成失控或稳定结论。%6",
 "%1: m = %2, p = %3%4, out-of-control = %5. Exceedances are statistical signal hints—investigate with process knowledge; do not alone write out-of-control or stability conclusions.%6"},
{"interp.multivariate_spc_hotelling_note",
 " 本图不是 PCA 经验分位 T²。",
 " This chart is not PCA empirical-quantile T²."},
{"interp.multivariate_spc_mewma_note",
 " 默认 UCL 可能是渐近近似，不是 ARL 仿真校准。",
 " Default UCL may be an asymptotic approximation, not ARL simulation calibration."},
{"interp.multivariate_spc_gs_note",
 " Montgomery |S| 子组图；个体路径与 NIST 争议说明见诊断。",
 " Montgomery |S| subgroup chart; see diagnostics for individual-path and NIST controversy notes."},
{"interp.laney_sigma_z_overdisp",
 "%1 Sigma Z = %2，存在过度离散，传统控制限可能过窄。",
 "%1 Sigma Z = %2; overdispersion present—traditional control limits may be too narrow."},
{"interp.laney_sigma_z_adjusted",
 "%1 Sigma Z = %2，控制限已按离散程度进行调整。",
 "%1 Sigma Z = %2; control limits were adjusted for dispersion."},
{"interp.chi2_small_expected_cats",
 "存在期望频数过小的类别，卡方近似可能不可靠。",
 "Some categories have small expected counts; the chi-square approximation may be unreliable."},
{"interp.chi2_small_expected_cells",
 "存在期望频数过小的单元格，卡方近似可能不可靠。",
 "Some cells have small expected counts; the chi-square approximation may be unreliable."},
{"interp.gof_rec_merge_adjacent",
 "建议合并相邻类别后复算；当前 P 值可作为探索性证据。",
 "Consider merging adjacent categories and recomputing; the current P-value is exploratory evidence only."},
{"interp.gof_rec_regroup_low_expected",
 "期望频数过低，建议先调整分组（合并类别）再进行拟合优度检验。",
 "Expected counts are too low; adjust grouping (merge categories) before goodness-of-fit testing."},
{"interp.gof_diag_expected_lt5_cats",
 "存在期望频数小于 5 的类别，卡方近似可能不可靠。",
 "Some categories have expected count < 5; the chi-square approximation may be unreliable."},
{"interp.gof_diag_high_low_expected_share",
 "低期望频数比例偏高，建议合并类别并谨慎解释 P 值。",
 "A high share of low expected counts; consider merging categories and interpret P-values cautiously."},
{"interp.gof_diag_expected_too_low",
 "期望频数过低，卡方近似可靠性较差。",
 "Expected counts are too low; the chi-square approximation is poorly supported."},
{"interp.chi2_diag_expected_lt1_cells",
 "存在期望频数小于 1 的单元格，卡方近似 P 值不显示。",
 "Some cells have expected count < 1; chi-square approximate P-values are not shown."},
{"interp.gof_err_need_two_categories",
 "拟合优度至少需要两个类别，且类别与计数长度相同。",
 "Goodness-of-fit needs at least two categories, with matching category and count lengths."},
{"interp.gof_err_nonneg_counts_names",
 "各类观察计数必须为非负有限数，类别名不能为空。",
 "Observed counts must be finite and non-negative; category names cannot be empty."},
{"interp.gof_err_proportion_length",
 "期望比例个数必须与类别个数相同。",
 "The number of expected proportions must match the number of categories."},
{"interp.gof_err_total_count_positive",
 "观察总计数必须大于 0。",
 "Total observed count must be greater than 0."},
{"interp.gof_err_proportion_positive",
 "期望比例必须为正有限数。",
 "Expected proportions must be positive and finite."},
{"interp.gof_err_proportions_sum_one",
 "期望比例之和必须为 1。",
 "Expected proportions must sum to 1."},
{"interp.chi2_err_table_shape",
 "列联表至少需要两行两列，且标签数量必须匹配。",
 "The contingency table needs at least two rows and two columns, with matching label counts."},
{"interp.chi2_err_ragged_rows",
 "列联表每一行必须具有相同列数。",
 "Each contingency-table row must have the same number of columns."},
{"interp.chi2_err_nonneg_cells",
 "列联表单元格必须是非负有限计数。",
 "Contingency-table cells must be finite, non-negative counts."},
{"interp.chi2_err_total_positive",
 "列联表总计数必须大于 0。",
 "Contingency-table total count must be greater than 0."},
{"interp.percent_table_descriptive",
 "百分比表是描述性结果，不能写成已证明存在或不存在关联。",
 "Percentage tables are descriptive; do not write them as proof that association exists or does not."},
{"interp.row_col_pct_descriptive",
 "行%/列%/合计% 是描述性汇总，不替代独立性检验结论。",
 "Row%/column%/total% are descriptive summaries and do not replace an independence-test conclusion."},
{"interp.heatmap_counts_not_causal",
 "观察频数热图只展示列联表中的计数分布，不能证明因果关系。",
 "Observed-count heatmaps only show contingency counts; they do not prove causation."},
{"interp.chi2_residual_heatmap",
 "调整残差热图只描述单元格相对独立假设的偏离方向与相对大小，不是因果证据。",
 "Adjusted-residual heatmaps only describe cell deviation direction/size versus independence; they are not causal evidence."},
{"interp.fisher_exact_summary",
 "Fisher 精确检验%1%2。P 值只描述当前 2×2 表与独立性假设的一致程度，不能写成已证明存在或不存在关联。",
 "Fisher exact test%1%2. The P-value only describes how well the current 2×2 table matches independence and must not be written as proof that association exists or does not."},
{"interp.pearson_chi2_assoc",
 "Pearson χ²%1%2。P 值只描述当前列联表与独立性假设的一致程度，不能证明因果关系。",
 "Pearson χ²%1%2. The P-value only describes consistency of the contingency table with independence and does not prove causation."},
{"interp.chi2_max_adj_residual",
 "最大 |调整残差| = %1%2。这些量只帮助定位偏离，不能写成已证明关联或无关联。",
 "Largest |adjusted residual| = %1%2. These quantities only help locate deviations and do not prove association or its absence."},
{"interp.cross_tab_summary",
 "交叉表汇总 %1 × %2 分类，N = %3。本输出只提供频数与百分比，不做独立性检验；检验请使用列联表卡方。",
 "Cross-tabulation summarizes %1 × %2 categories, N = %3. This output provides counts and percentages only—no independence test; use chi-square association for testing."},
{"interp.gof_poisson",
 "泊松拟合优度 Pearson χ²%1%2，DF = %3%4。P 值只描述观察计数与泊松模型的偏离程度，不能证明总体服从泊松分布。",
 "Poisson goodness-of-fit Pearson χ²%1%2, DF = %3%4. The P-value only describes deviation of observed counts from a Poisson model and does not prove the population is Poisson."},
{"interp.gof_pearson",
 "拟合优度 Pearson χ²%1%2，DF = %3。P 值只描述观察频数与指定比例的一致程度，不能证明总体比例等于假设。",
 "Goodness-of-fit Pearson χ²%1%2, DF = %3. The P-value only describes consistency of observed frequencies with specified proportions and does not prove population proportions equal the hypothesis."},
{"interp.gof_validity_status",
 "GOF 有效性状态为 %1%2。",
 "GOF validity status is %1%2."},
{"interp.gof_missing_n",
 "缺失 N* = %1，未进入类别计数。",
 "Missing N* = %1; these rows are excluded from category counts."},
{"interp.mcnemar_summary",
 "McNemar（Edwards 连续性校正）χ² = %1，配对有效 N = %2，不一致对数 b+c = %3%4。结果只陈述边际比例差异证据，不能写成已证明相同或不同。",
 "McNemar (Edwards continuity correction) χ² = %1, paired valid N = %2, discordant pairs b+c = %3%4. Results only state evidence of marginal proportion difference and must not be written as proof of sameness or difference."},
{"interp.mcnemar_not_computable",
 "McNemar 未计算出统计量（非二元、无不一致对或输入不足）。这只说明当前配对表不支持该检验，不能写成前后比例已证明相同或不同。",
 "McNemar did not compute a statistic (not binary, no discordant pairs, or insufficient input). This only means the paired table does not support the test and must not be written as proof that before/after proportions are the same or different."},
{"interp.mcnemar_err_input_mismatch",
 "McNemar 要求两列配对标签等长且非空。",
 "McNemar requires two paired label columns of equal, non-empty length."},
{"interp.mcnemar_err_not_binary",
 "存在无法识别为二元水平的标签。",
 "Some labels could not be recognized as binary levels."},
{"interp.mcnemar_err_no_discordant",
 "无不一致对（b+c=0），McNemar 统计量不可计算。",
 "No discordant pairs (b+c=0); the McNemar statistic cannot be computed."},
{"interp.binary_encode_err_need_columns",
 "二元编码至少需要两列配对标签。",
 "Binary encoding needs at least two paired label columns."},
{"interp.binary_encode_err_length_mismatch",
 "配对二元列必须等长。",
 "Paired binary columns must have equal length."},
{"interp.binary_encode_err_empty",
 "配对二元输入为空。",
 "Paired binary input is empty."},
{"interp.binary_encode_err_empty_label",
 "配对二元要求标签非空。",
 "Paired binary labels must be non-empty."},
{"interp.binary_encode_err_not_binary",
 "要求合计恰为两个水平，或可识别的二元编码（0/1、pass/fail 等）。",
 "Labels must total exactly two levels, or use a recognized binary encoding (0/1, pass/fail, etc.)."},
{"interp.cochran_err_empty",
 "Cochran Q 输入为空。",
 "Cochran Q input is empty."},
{"interp.cochran_err_use_mcnemar",
 "Cochran Q 要求至少 3 个处理列；两列配对请用 McNemar。",
 "Cochran Q needs at least three treatment columns; for two paired columns use McNemar."},
{"interp.cochran_err_label_mismatch",
 "处理标签个数必须与列数一致。",
 "The number of treatment labels must match the number of columns."},
{"interp.cochran_err_ragged",
 "Cochran Q 宽表每行处理数必须一致。",
 "Each Cochran Q wide-format row must have the same number of treatments."},
{"interp.cochran_err_not_binary",
 "Cochran Q 仅接受已编码的 0/1 值。",
 "Cochran Q accepts only pre-coded 0/1 values."},
{"interp.cochran_warn_sparse_column",
 "存在全失败或全成功的处理列，解读需谨慎。",
 "Some treatment columns are all failures or all successes; interpret with caution."},
{"interp.cochran_warn_small_n",
 "受试者数 < 4，χ² 近似只作提示。",
 "Subject count < 4; the χ² approximation is only a hint."},
{"interp.cochran_err_degenerate",
 "Cochran Q 分母为 0（行和无变异），统计量不可计算。",
 "Cochran Q denominator is 0 (no row-sum variation); the statistic cannot be computed."},
{"interp.fisher_err_empty_table",
 "2×2 表总计数必须大于 0。",
 "The 2×2 table total count must be greater than 0."},
{"interp.fisher_warn_or_undefined",
 "存在零单元格，优势比未定义（输出 *）。",
 "Zero cells present; the odds ratio is undefined (reported as *)."},
{"interp.two_prop_warn_small_count",
 "事件数或非事件数小于 5，正态近似可能不准确；请参考 Fisher 精确检验。",
 "Events or non-events are fewer than 5; the normal approximation may be inaccurate—consult Fisher’s exact test."},
{"interp.two_prop_err_counts",
 "两比例检验要求非零分母，事件数不能超过试验数，且置信水平有效。",
 "Two-proportion tests require non-zero denominators, events ≤ trials, and a valid confidence level."},
{"interp.two_prop_err_zero_se",
 "比例标准误为 0，无法计算正态近似检验。",
 "Proportion standard error is 0; the normal-approximation test cannot be computed."},
{"interp.one_prop_err_zero_se",
 "假设比例标准误为 0，无法计算正态近似检验。",
 "Hypothesized-proportion standard error is 0; the normal-approximation test cannot be computed."},
{"interp.one_prop_err_counts",
 "单比例检验要求试验数大于 0，且事件数不能超过试验数。",
 "One-proportion tests require trials > 0 and events ≤ trials."},
{"interp.one_prop_err_hypothesized",
 "假设比例必须位于 (0, 1) 内。",
 "The hypothesized proportion must lie in (0, 1)."},
{"interp.one_prop_err_hypothesized_alt",
 "假设比例必须在 0 与 1 之间。",
 "The hypothesized proportion must be between 0 and 1."},
{"interp.one_prop_warn_summarized_rows",
 "已将多行事件数/试验数求和后再做单比例检验。",
 "Events/trials from multiple rows were summed before the one-proportion test."},
{"interp.one_prop_warn_small_np0",
 "n p0 或 n(1-p0) 小于 5，正态近似可能不准确。",
 "n·p0 or n·(1−p0) is less than 5; the normal approximation may be inaccurate."},
{"interp.poisson_warn_summarized_rows",
 "已将多行缺陷数/观测长度求和后再做单样本泊松率检验。",
 "Defect counts/exposure lengths from multiple rows were summed before the one-sample Poisson rate test."},
};

}  // namespace

void append_report_text_catalog_part11(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart11),
        std::end(kReportTextCatalogPart11));
}

}  // namespace datalab::domain
