#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart16[] = {
{"interp.spc_policy_plain",
 "特殊原因策略 = %1",
 "Special-cause policy = %1"},
{"interp.doe_pareto_largest",
 "效应 Pareto 最大项为 %1；参考线方法为 %2。条越过参考线只提供统计证据，不表示过程合格。",
 "Largest Pareto effect term is %1; reference-line method is %2. Crossing the reference line is statistical evidence only and does not mean process pass/fail."},
{"interp.doe_contour_axes",
 "等值线/曲面轴为 %1 与 %2。",
 "Contour/surface axes are %1 and %2."},
{"interp.doe_contour_axes_coded_hold",
 "等值线/曲面轴为 %1 与 %2；其余因子编码 hold=0：%3。",
 "Contour/surface axes are %1 and %2; other factors held at coded 0: %3."},
{"interp.doe_contour_axes_actual_hold",
 "等值线/曲面轴为 %1 与 %2；其余因子实际单位 hold：%3。",
 "Contour/surface axes are %1 and %2; other factors held at actual units: %3."},
{"interp.doe_contour_rsm_hold0",
 "等值线/曲面按前两因子绘制，其余因子编码 hold=0；用于探索响应形状。",
 "Contour/surface uses the first two factors; other factors held at coded 0; for exploring response shape."},
{"interp.doe_design_type_runs",
 "设计类型 = %1；运行数 = %2%3。可将设计矩阵写入工作表后用 DOE 响应分析衔接。",
 "Design type = %1; run count = %2%3. After writing the design matrix to a worksheet, continue with DOE response analysis."},
{"interp.doe_generator_alias",
 "生成器：%1。别名结构仅说明混淆模式，不是显著性结论。",
 "Generators: %1. Alias structure describes confounding patterns only and is not a significance conclusion."},
{"interp.doe_desirability_multi",
 "多响应 Desirability 优化覆盖 %1 个响应（%2）；总体 D 为几何平均。",
 "Multi-response desirability optimization covers %1 response(s) (%2); overall D is the geometric mean."},
{"interp.doe_desirability_best",
 "最佳候选总体 Desirability = %1；这是在编码 ±1 设计空间内枚举得到的结果。",
 "Best candidate overall desirability = %1; obtained by enumeration inside the coded ±1 design space."},
{"interp.doe_desirability_enum_only",
 "响应优化在编码 ±1 空间枚举候选组合；结果不能外推到设计空间之外。",
 "Response optimization enumerates candidates in coded ±1 space; results must not be extrapolated outside the design space."},
{"interp.doe_desirability_conflict_advice",
 "多响应冲突时优先核对各响应 Desirability 与权重；确认性试验应覆盖总体 D 靠前且工程上可实施的组合。",
 "When responses conflict, reconcile each desirability and weights first; confirmation trials should cover high overall-D combinations that are engineering-feasible."},
{"interp.rsm_quadratic_summary",
 "RSM 二次模型（编码单位）：因子数 = %1；项数 = %2%3。",
 "RSM quadratic model (coded units): factor count = %1; term count = %2%3."},
{"interp.rsm_largest_abs_t",
 "当前 |t| 最大项 = %1（仅描述相对大小，不是工程最优）。",
 "Largest |t| term currently = %1 (relative magnitude only; not an engineering optimum)."},
{"interp.rsm_design_source",
 "设计来源 ID = %1%2；编码模式 = %3。",
 "Design source ID = %1%2; coding mode = %3."},
{"interp.rsm_lof_available",
 "失拟检验可用（纯误差 DF = %1；失拟 DF = %2%3）；证据类型 formula_reference，不是 vendor_oracle。",
 "Lack-of-fit test available (pure-error DF = %1; lack-of-fit DF = %2%3); evidence type formula_reference, not vendor_oracle."},
{"interp.spc_ewma_limits_only",
 "EWMA 仅启用「单点超出 3σ 控制限」；其余特殊原因规则不适用，超限点需结合原始观测调查。",
 "EWMA enables only '1 point beyond 3σ limits'; other special-cause rules do not apply—investigate out-of-control points with raw observations."},
{"interp.spc_cusum_not_shewhart",
 "CUSUM 使用累计和决策间隔信号，不套用 Shewhart 特殊原因规则（beyond_control_limit 等）；信号点需结合原始行调查，不是删点指令。",
 "CUSUM uses cumulative-sum decision-interval signals and does not apply Shewhart special-cause rules (e.g. beyond_control_limit); investigate signal points in source rows—this is not a delete-points instruction."},
{"interp.spc_no_auto_anomaly",
 "未发现当前规则能够自动判定的异常；请结合现场工艺、规格要求和图表进行确认。",
 "No anomaly was auto-flagged by the current rules; confirm with process knowledge, specifications, and charts."},
{"interp.spc_combine_field_action",
 "将统计结果与规格、风险等级、历史基线和现场特殊原因结合后再采取措施。",
 "Combine statistical results with specifications, risk level, historical baselines, and field special causes before taking action."},
{"interp.spc_sigma_within",
 "组内 σ = %1。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1. These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.spc_sigma_within_method",
 "组内 σ = %1（%2）。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1 (%2). These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.spc_sigma_within_between",
 "组内 σ = %1，组间 σ = %2。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1, between σ = %2. These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.spc_sigma_within_between_method",
 "组内 σ = %1，组间 σ = %2（%3）。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1, between σ = %2 (%3). These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.spc_sigma_within_bw",
 "组内 σ = %1，σ_BW = %2。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1, σ_BW = %2. These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.spc_sigma_within_bw_method",
 "组内 σ = %1，σ_BW = %2（%3）。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1, σ_BW = %2 (%3). These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.spc_sigma_full",
 "组内 σ = %1，组间 σ = %2，σ_BW = %3。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1, between σ = %2, σ_BW = %3. These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.spc_sigma_full_method",
 "组内 σ = %1，组间 σ = %2，σ_BW = %3（%4）。这些标准差只描述当前子组分解，不是规格判定。",
 "Within σ = %1, between σ = %2, σ_BW = %3 (%4). These SDs describe the current subgroup decomposition only and are not a specification decision."},
{"interp.ttest_one_z",
 "单样本 Z 检验（已知 σ%1）%2%3%4。P 值与置信区间只描述当前样本证据，统计显著不等于工程差异具有实际重要性，也不是过程合格判定。",
 "One-sample Z test (known σ%1)%2%3%4. P-values and CIs describe sample evidence only; statistical significance is not engineering importance and not a process pass/fail decision."},
{"interp.ttest_two_sample",
 "双样本 t 检验（%1）%2%3。P 值与置信区间只描述当前样本证据，统计显著不等于工程差异具有实际重要性，也不是过程合格判定。",
 "Two-sample t test (%1)%2%3. P-values and CIs describe sample evidence only; statistical significance is not engineering importance and not a process pass/fail decision."},
{"interp.ttest_paired",
 "配对 t 检验%1%2。P 值与置信区间只描述当前样本证据，统计显著不等于工程差异具有实际重要性，也不是过程合格判定。",
 "Paired t test%1%2. P-values and CIs describe sample evidence only; statistical significance is not engineering importance and not a process pass/fail decision."},
{"interp.ttest_one_sample",
 "单样本 t 检验%1%2。P 值与置信区间只描述当前样本证据，统计显著不等于工程差异具有实际重要性，也不是过程合格判定。",
 "One-sample t test%1%2. P-values and CIs describe sample evidence only; statistical significance is not engineering importance and not a process pass/fail decision."},
{"interp.ttest_z_assumption",
 "Z 检验要求已知总体标准差且正态/大样本近似成立（assumption_status=%1）；样本 StDev 仅展示，不参与 Z/CI。",
 "Z test requires known population SD and normality/large-sample approximation (assumption_status=%1); sample StDev is display-only and does not enter Z/CI."},
{"interp.ttest_assumption",
 "t 检验正态与独立假设未验证（assumption_status=%1）。",
 "t-test normality and independence assumptions are unverified (assumption_status=%1)."},
{"interp.normality_fail_to_reject",
 "%1 正态性检验判定为 %2%3%4。在 alpha 下未拒绝正态假设，不能写成数据已正态。",
 "%1 normality test decision is %2%3%4. Failure to reject normality at alpha does not prove the data are normal."},
{"interp.normality_reject",
 "%1 正态性检验判定为 %2%3%4。证据反对正态假设，这不是规格判定。",
 "%1 normality test decision is %2%3%4. Evidence against normality is not a specification decision."},
{"interp.normality_other",
 "%1 正态性检验判定为 %2%3%4。统计量未计算，不能写成数据已正态。",
 "%1 normality test decision is %2%3%4. Statistics were not computed; do not claim the data are normal."},
{"interp.normality_assumption_status",
 "正态假设状态为 %1。",
 "Normality assumption status is %1."},
{"interp.attr_percent_defective",
 "%Defective = %1（Average P = %2）。这是当前样本的不合格品率估计，不是过程合格判定。",
 "%Defective = %1 (Average P = %2). This estimates the current sample defective rate and is not a process pass/fail decision."},
{"interp.attr_process_z",
 "Process Z = %1，由 Average P 的标准正态右尾得到。",
 "Process Z = %1, obtained from the standard-normal right tail of Average P."},
{"interp.attr_mean_dpu",
 "Mean DPU = %1。这是当前样本的单位缺陷率估计，不是过程合格判定。",
 "Mean DPU = %1. This estimates the current sample defects-per-unit rate and is not a process pass/fail decision."},
{"interp.attr_binomial_assumption",
 "二项过程能力未验证独立性、恒定 p 与稳定性（assumption_status=%1），不能写成过程合格。",
 "Binomial capability did not verify independence, constant p, or stability (assumption_status=%1); do not claim process pass."},
{"interp.attr_poisson_assumption",
 "泊松过程能力未验证独立性、恒定 DPU 与稳定性（assumption_status=%1），不能写成过程合格。",
 "Poisson capability did not verify independence, constant DPU, or stability (assumption_status=%1); do not claim process pass."},
{"interp.outlier_reject",
 "%1%2%3。在 α 下拒绝“无异常值”假设，嫌疑观测需工程调查，P 值只描述与正态假设下的一致性，勿当作删点依据，也勿当成异常已核实。",
 "%1%2%3. At α, reject the no-outlier hypothesis; investigate suspect observations—P only describes consistency under normality and is not a delete-points warrant or confirmed anomaly."},
{"interp.outlier_not_reject",
 "%1%2%3。未拒绝“无异常值”假设，不能证明数据中没有异常值。",
 "%1%2%3. Failure to reject the no-outlier hypothesis does not prove the data contain no outliers."},
{"interp.outlier_dixon_assumption",
 "Dixon r10 要求近似正态、至多一个异常值，且 P 可能为临界值插值近似（assumption_status=%1）。",
 "Dixon r10 assumes approximate normality and at most one outlier; P may be a critical-value interpolation (assumption_status=%1)."},
{"interp.outlier_grubbs_assumption",
 "Grubbs 要求近似正态且至多一个异常值（assumption_status=%1）。",
 "Grubbs requires approximate normality and at most one outlier (assumption_status=%1)."},
{"interp.corr_pearson",
 "Pearson 相关系数表示变量关联方向与强度；P-Value 反映在零相关假设下的证据强度，不能单独证明因果关系。未拒绝零相关不能写成已证明无关。",
 "Pearson correlation describes association direction and strength; the P-value reflects evidence under zero correlation and alone cannot prove causation. Failure to reject zero correlation does not prove independence."},
{"interp.corr_spearman",
 "Spearman 相关系数表示变量关联方向与强度；P-Value 反映在零相关假设下的证据强度，不能单独证明因果关系。未拒绝零相关不能写成已证明无关。",
 "Spearman correlation describes association direction and strength; the P-value reflects evidence under zero correlation and alone cannot prove causation. Failure to reject zero correlation does not prove independence."},
{"interp.corr_complete_case",
 "相关分析使用 complete-case 对齐（N = %1），assumption_status=%2。",
 "Correlation uses complete-case alignment (N = %1), assumption_status=%2."},
{"interp.corr_covariance",
 "协方差矩阵基于 complete-case 样本协方差；对角线为各变量方差。",
 "The covariance matrix is complete-case sample covariance; the diagonal is each variable's variance."},
{"interp.corr_partial",
 "偏相关在控制其余变量后给出 Pearson 偏系数；不能写成已排除混杂或已证明因果。",
 "Partial correlation gives Pearson partial coefficients after controlling other variables; do not claim confounders are removed or causation is proven."},
{"interp.corr_generic",
 "相关系数表示变量关联方向与强度；P-Value 反映在零相关假设下观察到当前系数的证据强度，不能单独证明因果关系。",
 "Correlation describes association direction and strength; the P-value reflects evidence for the observed coefficient under zero correlation and alone cannot prove causation."},
{"interp.oc_binomial",
 "二项 OC 曲线描述在 n=%1、c=%2 计划下，不同不合格品率 p 的接收概率 Pa(p)；OC 用于评估抽样方案风险，不能替代对具体批次的接收判定。",
 "The binomial OC curve gives acceptance probability Pa(p) for plan n=%1, c=%2 across defective rates p; OC assesses sampling-plan risk and does not replace lot disposition decisions."},
{"interp.oc_pa_aql",
 "Pa(AQL) = %1 只反映 AQL 风险点，不是生产判定结论。",
 "Pa(AQL) = %1 reflects the AQL risk point only and is not a production disposition conclusion."},
{"interp.oc_pa_rql",
 "Pa(RQL) = %1 只反映 RQL 风险点，不是拒收证明。",
 "Pa(RQL) = %1 reflects the RQL risk point only and is not proof of rejection."},
{"interp.oc_lot_size",
 "批大小 N = %1 仅作摘要；本轮 OC 仍用二项（无限批）近似。",
 "Lot size N = %1 is summary only; this OC still uses a binomial (infinite-lot) approximation."},
{"interp.equiv_within",
 "等价性检验比较%1与界限 [%2, %3]%4，区间落在等价界限内。%5这只陈述界限关系，不能写成已证明等价。",
 "Equivalence testing compares %1 to limits [%2, %3]%4; the interval falls inside the equivalence limits. %5This states a limit relationship only and does not prove equivalence."},
{"interp.equiv_outside",
 "等价性检验比较%1与界限 [%2, %3]%4，区间未落入等价界限内。%5这只陈述界限关系，不能写成已证明等价。",
 "Equivalence testing compares %1 to limits [%2, %3]%4; the interval does not fall inside the equivalence limits. %5This states a limit relationship only and does not prove equivalence."},
{"interp.equiv_quantity_diff", "差值", "a difference"},
{"interp.equiv_quantity_prop", "比例差", "a proportion difference"},
{"interp.equiv_quantity_ratio", "均值比", "a mean ratio"},
{"interp.tost_assumption",
 "TOST 依赖%1假设（assumption_status=%2）。",
 "TOST depends on %1 assumptions (assumption_status=%2)."},
{"interp.anom_summary",
 "ANOM 在 α=%1 下比较各组均值与总体均值；超出 UDL/LDL 的组数 = %2。这标记值得进一步调查的组，不能写成组间无差异或应剔除该组。",
 "ANOM at α=%1 compares group means to the overall mean; groups beyond UDL/LDL = %2. This flags groups for investigation and does not prove no differences or that a group should be removed."},
{"interp.anom_decision_limits",
 "决策限方法 = %1（正态近似）；二项/泊松计数不适用本命令。",
 "Decision-limit method = %1 (normal approximation); binomial/Poisson counts are not for this command."},
{"interp.anova_f_followup",
 "ANOVA 的总体 F 检验显著时，只能说明至少存在一组均值差异；需要后续多重比较确定具体组对。",
 "A significant overall ANOVA F only indicates at least one mean difference; follow-up multiple comparisons are needed to identify pairs."},
{"interp.ttest_generic_advice",
 "请结合 P-Value 与均值差置信区间判断差异；统计显著不等于工程差异具有实际重要性。",
 "Interpret differences using the P-value and the mean-difference CI; statistical significance is not engineering importance."},
{"interp.response_opt_coded",
 "响应优化在编码 ±1 空间枚举候选组合；缺协方差时置信/预测区间不可用，最佳组合不能外推到设计空间之外。",
 "Response optimization enumerates candidates in coded ±1 space; without covariance, confidence/prediction intervals are unavailable and the best combination must not be extrapolated outside the design space."},
{"interp.prop_two",
 "两比例检验方法为 %1，p̂1 = %2，p̂2 = %3%4%5%6。P 值只描述两组比例差异的证据强度，不是规格判定。",
 "Two-proportion test method is %1, p̂1 = %2, p̂2 = %3%4%5%6. P-values describe evidence for a proportion difference only and are not a specification decision."},
{"interp.prop_one",
 "单比例检验方法为 %1%2，p̂ = %3%4%5。P 值只描述与假设比例的证据强度，不是规格判定。",
 "One-proportion test method is %1%2, p̂ = %3%4%5. The P-value describes evidence versus the hypothesized proportion only and is not a specification decision."},
{"interp.prop_assumption",
 "比例假设未验证独立性与恒定 p（assumption_status=%1）。",
 "Proportion assumptions did not verify independence or constant p (assumption_status=%1)."},
{"interp.poisson_two",
 "双样本泊松率方法为 %1%2%3。P 值只描述与假设发生率的证据强度，不是规格判定。",
 "Two-sample Poisson-rate method is %1%2%3. The P-value describes evidence versus hypothesized rates only and is not a specification decision."},
{"interp.poisson_one",
 "单样本泊松率方法为 %1，λ̂ = %2%3%4。P 值只描述与假设发生率的证据强度，不是规格判定。",
 "One-sample Poisson-rate method is %1, λ̂ = %2%3%4. The P-value describes evidence versus the hypothesized rate only and is not a specification decision."},
{"interp.poisson_rate_assumption",
 "泊松率假设未验证独立同质发生率（assumption_status=%1）。",
 "Poisson-rate assumptions did not verify independent homogeneous incidence (assumption_status=%1)."},
{"interp.boxcox_summary",
 "Box-Cox 选定 λ = %1，有效观测 N = %2%3。概率图只是诊断，不能写成数据已正态。",
 "Box-Cox selected λ = %1 with effective N = %2%3. The probability plot is diagnostic only; do not claim the data are normal."},
{"interp.boxcox_assumption",
 "变换后能力指数（若出现）不是过程合格判定（assumption_status=%1）。",
 "Any capability index after transformation is not a process pass/fail decision (assumption_status=%1)."},
{"interp.box_cox_spec_limit_gate",
 "规格限无法变换或顺序无效，已跳过变换后过程能力表（非合格判定）。",
 "Spec limits could not be transformed or are out of order; the post-transform capability table was skipped (not a pass/fail decision)."},
{"interp.johnson_spec_limit_gate",
 "规格限落在 Johnson 变换定义域外，已跳过 overall 能力指数表（非合格判定）。",
 "Specification limits fall outside Johnson transform support; the overall capability indices table was skipped (not a pass/fail decision)."},
{"interp.warranty_exposure_gate",
 "暴露量列无效或求和为零，已跳过保修摘要指标（非法律/质量承诺）。",
 "Exposure column is invalid or sums to zero; warranty summary metrics were skipped (not a legal/quality promise)."},
{"interp.power_missing_metrics",
 "缺少 Actual Power 或 Effect Size；结果不能用于样本量决策。",
 "Actual Power or Effect Size is missing; results must not be used for sample-size decisions."},
{"interp.power_ttest",
 "在效应量 = %1、α = %2 下，估计实际功效 = %3。",
 "At effect size = %1 and α = %2, estimated actual power = %3."},
{"interp.power_generic",
 "在效应量 = %1%2 下，估计实际功效 = %3%4。数值是假设条件下的计算值。",
 "At effect size = %1%2, estimated actual power = %3%4. Values are computed under stated assumptions."},
{"interp.power_ttest_advice",
 "将效应量预先定义为具有工程意义的最小差异，并同时考虑实际脱落、分组和方差不确定性。",
 "Pre-define the effect size as the smallest difference of engineering importance, and account for attrition, grouping, and variance uncertainty."},
{"interp.power_sample_advice",
 "样本量结果是模型和效应量假设的条件结果；试验前应进行敏感性分析并向上取整到可执行的分组方案。",
 "Sample-size results are conditional on model and effect-size assumptions; run sensitivity analysis before the trial and round up to an executable grouping plan."},
{"interp.forecast_mase_advice",
 "MASE > 1，当前模型不优于朴素基准；上线前应比较替代模型或扩大验证窗口。",
 "MASE > 1: the current model is no better than a naïve baseline; compare alternatives or widen the validation window before deployment."},
{"interp.forecast_mape",
 "预测误差指标已计算；%1",
 "Forecast error metrics were computed; %1"},
{"interp.regression_r2",
 "R² = %1 只描述当前样本拟合程度，不能单独判定模型合格。",
 "R² = %1 describes current-sample fit only and alone cannot declare the model acceptable."},
{"interp.regression_flagged_obs",
 "存在打标观测，请结合异常观测表调查；解释层不会自动删除这些观测。",
 "Flagged observations are present; investigate via the outlier table—the interpretation layer does not auto-delete them."},
{"interp.regression_vif_advice",
 "最大 VIF = %1，提示共线性调查，不会自动删除预测变量。",
 "Max VIF = %1 suggests collinearity investigation; predictors are not auto-removed."},
{"interp.regression_assumption_against",
 "残差假设检查提供了需要调查的证据；不能把系数显著性直接写成因果关系。",
 "Residual assumption checks provide evidence needing investigation; coefficient significance alone must not be written as causation."},
{"interp.regression_residual_advice",
 "结合残差对拟合值图、残差顺序图、拟合线图置信/预测带、杠杆值和 Cook's D 后再解释模型。",
 "Interpret the model only after residual-vs-fitted, residual-order, fit-line CI/PI bands, leverage, and Cook's D."},
{"interp.anova_no_significant",
 "在当前显著性水平下，没有可报告为显著的 ANOVA 项；这不等于各组完全相同。",
 "At the current significance level, no ANOVA terms are reportable as significant; this does not mean all groups are identical."},
{"interp.anova_significant_terms",
 "当前有统计证据的项：%1。",
 "Terms with statistical evidence: %1."},
{"interp.anova_tukey",
 "Tukey 同时置信水平 = %1，显著比较对数 = %2；区间含 0 不显著。同字母仅表示在本产品 Tukey 近似规则下未显著不同，不能写成已证明相同。",
 "Tukey family confidence level = %1, significant pair count = %2; intervals containing 0 are not significant. Same-letter grouping only means not significantly different under this product's Tukey approximation and does not prove equality."},
{"interp.method_unspecified",
 "未指定",
 "unspecified"},
{"diag.severity.error", "错误", "Error"},
{"diag.severity.warning", "警告", "Warning"},
{"diag.severity.info", "信息", "Info"},
{"body.analysis_incomplete", "分析未完成", "Analysis incomplete"},
{"body.honesty.gap",
 "本页部分分析正文仍可能保留源语言；已覆盖报告壳层、关键表题、可见性限制句、可靠性/DOE/能力门禁固定解释句与部分诊断；catalog↔Linguist .ts/.qm 镜像已同步；主菜单、分析命令 menu/title/group、分析设置对话框角色/输入/chrome 已走 DataLabUi tr()；动态拼接解释句已加深 DOE/MSA/可靠性/CIF/Fine-Gray/RSM/控制图/σ/t·Z/正态性/属性能力/异常值/相关/OC/等价性/ANOM/比例/泊松率/Box-Cox/功效与样本量/预测 MAPE·MASE/回归 R²·VIF/ANOVA·Tukey 与常用表分析；其余动态句与部分占位/帮助文案仍未全量双语。",
 "Parts of this analysis body may still be in the source language; report shell, key table titles, visibility limitation bullets, fixed reliability/DOE/capability-gate interpretation sentences, and selected diagnostics are covered; catalog↔Linguist .ts/.qm mirrors are synced; main menus, analysis command menu/title/group labels, and analysis-setup dialog roles/inputs/chrome use DataLabUi tr(); dynamic interpretation deepen covers DOE/MSA/reliability/CIF/Fine-Gray/RSM/control charts/σ/t·Z/normality/attribute capability/outliers/correlation/OC/equivalence/ANOM/proportion/Poisson-rate/Box-Cox/power-sample-size/forecast MAPE·MASE/regression R²·VIF/ANOVA·Tukey plus common tabular fixed bullets; remaining dynamic sentences and some placeholders/help text are not fully bilingual yet."},
{"status.triggered", "已触发", "Triggered"},
{"status.not_triggered", "未触发", "Not triggered"},
{"status.not_applicable", "不适用", "Not applicable"},
{"status.not_verified", "未验证", "Not verified"},
{"status.calculation_failed", "计算失败", "Calculation failed"},
{"status.present", "存在", "Present"},
{"header.rule_id", "规则ID", "Rule ID"},
{"header.rule_name", "规则名称", "Rule name"},
{"header.decision_window", "判定窗口", "Decision window"},
{"header.threshold", "阈值", "Threshold"},
{"header.comparison_direction", "比较方向", "Comparison direction"},
{"header.explanation", "解释", "Explanation"},
{"header.triggered_plot_points", "触发图点", "Triggered plot points"},
{"header.suggested_action", "建议动作", "Suggested action"},
{"header.not_applicable_reason", "不适用原因", "Not-applicable reason"},
{"header.not_verified_reason", "未验证原因", "Not-verified reason"},
{"header.calculation_failed_reason", "计算失败原因", "Calculation-failed reason"},
{"header.triggered_rules", "触发规则", "Triggered rules"},
{"header.primary_rule", "主要规则", "Primary rule"},
{"header.subgroup", "子组", "Subgroup"},
{"header.stage", "阶段", "Stage"},
{"header.signal", "信号", "Signal"},
{"header.direction", "方向", "Direction"},
{"header.rule", "规则", "Rule"},
{"header.center_line", "中心线", "Center line"},
{"header.plotted_value", "绘制值", "Plotted value"},
{"header.observation_value", "观测值", "Observed value"},
{"header.observation_index", "观测序号", "Observation index"},
{"header.cumulative_value", "累计值", "Cumulative value"},
{"header.zone_band", "区域带", "Zone band"},
{"header.cumulative_score", "累计得分", "Cumulative score"},
{"header.jaehn_signal", "Jaehn 信号", "Jaehn signal"},
{"status.missing", "缺失", "Missing"},
{"status.truncated", "已截断", "Truncated"},
{"diag.missing_translation",
 "缺少翻译，已回退到源语言文本",
 "Missing translation; fell back to source-language text"},
{"ui.template_dialog.title", "选择报告模板", "Select report template"},
{"ui.template_dialog.intro",
 "模板只改变展示密度与证据级别，不会重新计算统计 Facts。客户版保留关键风险与限制；工程师版显示参数/规则/诊断；审计版额外显示快照、ImportPlan、版本与 hash。",
 "Templates change presentation density and evidence level only; they never recompute Facts. Customer keeps key risks/limits; Engineer shows parameters/rules/diagnostics; Audit adds snapshot, ImportPlan, versions, and hashes."},
{"ui.template_dialog.group", "报告模板", "Report template"},
{"ui.template_dialog.customer", "客户版 — 结论摘要、关键风险、主图",
 "Customer — summary, key risks, primary charts"},
{"ui.template_dialog.engineer", "工程师版 — 参数、统计表、规则证据、异常行",
 "Engineer — parameters, tables, rule evidence, anomaly rows"},
{"ui.template_dialog.audit", "审计版 — 输入快照、过滤、算法版本、来源与 hash",
 "Audit — input snapshot, filters, algorithm version, provenance, hashes"},
{"ui.template_dialog.language_group", "报告语言（独立于界面语言）",
 "Report language (independent of UI language)"},
{"ui.template_dialog.lang_zh", "中文（zh-CN）", "Chinese (zh-CN)"},
{"ui.template_dialog.lang_en", "English (en-US)", "English (en-US)"},
{"ui.template_dialog.note",
 "报告语言写入 ReportProfile.locale，不受系统 locale 覆盖。PDF/A 为 not_validated；PDF/UA 在 QPainter 路径为 unsupported；不得宣称合规。",
 "Report language is stored on ReportProfile.locale and is not overridden by system locale. PDF/A remains not_validated; PDF/UA is unsupported on the QPainter path; do not claim compliance."},
{"ui.template_dialog.continue", "继续预览", "Continue to preview"},
{"ui.template_dialog.cancel", "取消", "Cancel"},
{"ui.preview.title", "报告预览", "Report preview"},
{"ui.preview.confirm", "确认导出", "Confirm export"},
{"ui.preview.evidence_summary", "证据摘要", "Evidence summary"},
{"ui.preview.rule_evidence", "规则证据", "Rule evidence"},
};

}  // namespace

void append_report_text_catalog_part16(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart16),
        std::end(kReportTextCatalogPart16));
}

}  // namespace datalab::domain
