#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart14[] = {
{"interp.spc_rule5_two_of_three_2sigma",
 "检测到 3 点中有 2 点同侧超过 2σ，提示可能存在较小的过程偏移。",
 "Detected 2 of 3 points on the same side beyond 2σ, suggesting a possible small process shift."},
{"interp.spc_rule6_four_of_five_1sigma",
 "检测到 5 点中有 4 点同侧超过 1σ，提示可能存在较小的过程偏移。",
 "Detected 4 of 5 points on the same side beyond 1σ, suggesting a possible small process shift."},
{"interp.spc_rule7_fifteen_within_1sigma",
 "检测到连续 15 点落在 1σ 以内，控制限可能过宽或数据存在分层。",
 "Detected 15 consecutive points within 1σ; control limits may be too wide or the data may be stratified."},
{"interp.spc_rule8_eight_beyond_1sigma",
 "检测到连续 8 点落在 1σ 以外，提示可能存在混合总体或双群模式。",
 "Detected 8 consecutive points outside 1σ, suggesting a possible mixed population or bimodal pattern."},
{"interp.imr_err_non_finite",
 "I-MR 不允许 NaN 或无穷观测。",
 "I-MR does not allow NaN or infinite observations."},
{"interp.imr_err_mssd_need_pair",
 "MSSD 需要至少一对相继差分。",
 "MSSD requires at least one successive difference pair."},
{"interp.imr_warn_mssd_c4_approx",
 "MSSD 无偏常数 c4' 使用近似式，不是完整 Minitab 表查表。",
 "The MSSD unbiased constant c4' uses an approximation, not a full Minitab table lookup."},
{"interp.imr_warn_nelson_ignored_mssd",
 "Nelson estimate 仅适用于平均移动极差法；当前 MSSD 方法已忽略该选项。",
 "Nelson estimate applies only to average moving range; the current MSSD method ignored that option."},
{"interp.imr_warn_nelson_fallback",
 "Nelson estimate 剔除后无剩余移动极差，回退到未剔除估计。",
 "After Nelson estimate exclusions, no moving ranges remained; fell back to the untrimmed estimate."},
{"interp.imr_warn_nelson_ignored_method",
 "Nelson estimate 仅适用于平均移动极差法；当前方法已忽略该选项。",
 "Nelson estimate applies only to average moving range; the current method ignored that option."},
{"interp.xbar_r_err_unequal_n",
 "Xbar-R 要求各组样本量相等，不能用最后一组的 d2/A2 代替。",
 "Xbar-R requires equal subgroup sizes; d2/A2 from the last subgroup cannot be substituted."},
{"interp.xbar_r_err_non_finite",
 "Xbar-R 子组不允许 NaN 或无穷观测。",
 "Xbar-R subgroups do not allow NaN or infinite observations."},
{"interp.imr_rs_err_need_two_subgroups",
 "I-MR-R/S 至少需要两个子组。",
 "I-MR-R/S requires at least two subgroups."},
{"interp.spc_err_subgroup_min_two",
 "各子组必须至少包含两个观测。",
 "Each subgroup must contain at least two observations."},
{"interp.imr_rs_err_non_finite",
 "I-MR-R/S 子组不允许 NaN 或无穷观测。",
 "I-MR-R/S subgroups do not allow NaN or infinite observations."},
{"diag.imr_rs.cannot_compute_chart",
 "无法计算 I-MR-R/S 控制图。",
 "Cannot compute I-MR-R/S control chart."},
{"interp.spc_warn_neg_between_var",
 "估计的组间方差为负，已截断为 0；σ_B 可能低估。",
 "Estimated between-subgroup variance was negative and truncated to 0; σ_B may be understated."},
{"interp.ewma_err_options",
 "EWMA 要求非空数据、lambda 位于 (0,1] 且控制限倍数大于 0。",
 "EWMA requires non-empty data, lambda in (0,1], and a control-limit multiplier greater than 0."},
{"interp.ewma_err_sigma",
 "EWMA 的过程标准差必须大于 0。",
 "EWMA process standard deviation must be greater than 0."},
{"interp.cusum_err_options",
 "CUSUM 要求非空数据、sigma/h 大于 0 且 k 不小于 0。",
 "CUSUM requires non-empty data, sigma/h greater than 0, and k not less than 0."},
{"interp.zone_err_need_two",
 "区域图至少需要 2 个观测。",
 "The zone chart requires at least 2 observations."},
{"interp.zone_err_non_finite",
 "区域图不允许非有限观测。",
 "The zone chart does not allow non-finite observations."},
{"interp.zone_err_sigma_mr",
 "无法估计过程 σ（移动极差）。",
 "Unable to estimate process σ (moving range)."},
{"interp.zone_err_sigma_positive",
 "过程 σ 必须大于 0。",
 "Process σ must be greater than 0."},
{"interp.zmr_err_sigma",
 "无法估计 σ。",
 "Unable to estimate σ."},
{"interp.zmr_err_insufficient_n",
 "Z-MR 至少需要 2 个观测。",
 "Z-MR requires at least 2 observations."},
{"interp.zmr_err_non_finite",
 "Z-MR 不允许非有限观测。",
 "Z-MR does not allow non-finite observations."},
{"interp.zmr_err_group_sigma",
 "存在组 σ ≤ 0。",
 "A group σ ≤ 0 was found."},
{"interp.ma_err_non_finite",
 "移动平均图不允许非有限观测。",
 "Moving-average chart does not allow non-finite observations."},
{"interp.ma_err_insufficient_n",
 "移动平均图需要至少 w 个观测。",
 "Moving-average chart requires at least w observations."},
{"interp.ma_err_sigma",
 "无法估计过程 σ。",
 "Unable to estimate process σ."},
{"interp.ma_err_sigma_limit",
 "σ 与控制限倍数必须大于 0。",
 "σ and the control-limit multiple must be greater than 0."},
{"interp.spc_err_within_need_two_subgroups",
 "组内 σ 至少需要两个子组。",
 "Within-subgroup σ requires at least two subgroups."},
{"interp.spc_err_equal_subgroup_size",
 "各子组必须具有相同观测数。",
 "All subgroups must have the same number of observations."},
{"interp.spc_err_subgroup_non_finite",
 "子组不允许 NaN 或无穷观测。",
 "Subgroups must not contain NaN or infinite observations."},
{"interp.spc_err_subgroup_size_table",
 "子组大小超出无偏常数表范围。",
 "Subgroup size is outside the unbiased-constant table range."},
{"interp.spc_err_c4",
 "无法计算该子组大小的 c4。",
 "Unable to compute c4 for this subgroup size."},
{"interp.g_err_insufficient_points",
 "G 图至少需要两个有限间隔。",
 "G chart requires at least two finite intervals."},
{"interp.g_err_invalid_interval",
 "G 图间隔必须为非负有限数。",
 "G-chart intervals must be non-negative and finite."},
{"interp.g_err_invalid_probability",
 "无法从间隔均值估计几何分布参数 p。",
 "Unable to estimate geometric parameter p from interval mean."},
{"interp.t_err_invalid_interval",
 "T 图间隔必须为非负有限数。",
 "T-chart intervals must be non-negative and finite."},
{"interp.t_err_insufficient_points",
 "T 图至少需要两个正间隔。",
 "T chart requires at least two positive intervals."},
{"interp.t_err_weibull_failed",
 "Weibull 参数无法识别，T 图控制限未计算。",
 "Weibull parameters not identifiable; T-chart control limits not computed."},
{"interp.t_warn_zero_interval_regression",
 "存在 0 间隔，已排除后用 log-log 回归估计 Weibull 参数。",
 "Zero intervals present; excluded and Weibull parameters estimated via log-log regression."},
{"interp.t_err_regression_failed",
 "0 间隔回归无法估计 Weibull 参数。",
 "Zero-interval regression could not estimate Weibull parameters."},
{"interp.t_err_regression_nonpositive_shape",
 "0 间隔回归得到非正形状参数。",
 "Zero-interval regression yielded a non-positive shape parameter."},
{"interp.nelson_estimate_applied",
 "Nelson estimate 剔除了 %1 个过大移动极差后重估 σ。",
 "Nelson estimate excluded %1 oversized moving range(s) and re-estimated σ."},
{"interp.capability_err_lsl_finite",
 "LSL 必须为有限数。",
 "LSL must be a finite number."},
{"interp.capability_err_usl_finite",
 "USL 必须为有限数。",
 "USL must be a finite number."},
{"interp.capability_err_mean_finite",
 "过程均值必须为有限数。",
 "Process mean must be a finite number."},
{"interp.capability_err_bw_need_valid",
 "组间/组内能力需要有效数值观测。",
 "Between/within capability requires valid numeric observations."},
{"interp.anom_err_need_two_groups",
 "ANOM 至少需要两个组。",
 "ANOM requires at least two groups."},
{"interp.anom_err_group_min_two",
 "每组至少需要 2 个观测。",
 "Each group requires at least 2 observations."},
{"interp.anom_err_within_var",
 "无法估计组内方差。",
 "Unable to estimate within-group variance."},
{"interp.anom_err_zero_within_sd",
 "组内标准差为 0。",
 "Within-group standard deviation is 0."},
{"interp.zone_warn_jaehn_scoring",
 "区域得分采用 Jaehn 1/2/4 权重、累计阈值 8（formula_reference），不是 Minitab 自定义权重 golden。",
 "Zone scores use Jaehn 1/2/4 weights with cumulative threshold 8 (formula_reference), not Minitab custom-weight golden."},
{"interp.zmr_warn_estimated_limits",
 "未提供完整历史 μ/σ；本轮用各组样本均值与全序列 MR/d2 估计 σ。",
 "Complete historical μ/σ were not provided; this run estimates σ from each group's sample mean and the full-series MR/d2."},
{"interp.cusum_info_not_shewhart_rules",
 "CUSUM 不使用 Shewhart 特殊原因规则（beyond_control_limit 等），改用上/下侧累计和首次信号。",
 "CUSUM does not use Shewhart special-cause rules (beyond_control_limit, etc.); it uses first signals from the upper/lower cumulative sums instead."},
{"interp.censoring_worksheet_empty",
 "删失工作表为空。",
 "Censoring worksheet is empty."},
{"interp.censoring_worksheet_missing_columns",
 "删失工作表需要 censoring_type 与 time 列。",
 "Censoring worksheet requires censoring_type and time columns."},
{"interp.censoring_worksheet_missing_interval_bounds",
 "interval 行需要 interval_left / interval_right 列。",
 "Interval rows require interval_left / interval_right columns."},
{"interp.censoring_empty",
 "删失契约至少需要一条观测。",
 "Censoring contract requires at least one observation."},
{"interp.censoring_negative_or_nonfinite_time",
 "时间必须为有限非负数；负时间阻止分析。",
 "Time must be finite and non-negative; negative time blocks analysis."},
{"interp.censoring_zero_failure_time",
 "出现时间为 0 的失效；请确认单位与记录口径。",
 "A failure at time 0 was found; confirm units and recording convention."},
{"interp.censoring_interval_nonfinite",
 "区间删失边界必须为有限非负数。",
 "Interval-censoring bounds must be finite and non-negative."},
{"interp.censoring_interval_reversed",
 "区间删失要求左端严格小于右端；反向区间阻止。",
 "Interval censoring requires left bound strictly less than right; reversed intervals are blocked."},
{"interp.censoring_invalid_exposure",
 "暴露量必须为有限非负数。",
 "Exposure must be finite and non-negative."},
{"interp.censoring_time_unit_conflict",
 "观测时间单位不一致，阻止合并分析。",
 "Observation time units disagree; pooled analysis is blocked."},
{"interp.censoring_zero_failures",
 "零失效（全删失或无 exact 事件）；生存/参数估计可能不可识别。",
 "Zero failures (all censored or no exact events); survival/parameter estimates may be unidentifiable."},
{"interp.censoring_all_failures",
 "全部为失效事件，无删失。",
 "All events are failures; no censoring."},
{"interp.censoring_all_censored",
 "全部删失；中位寿命等点估计通常不可得。",
 "All observations are censored; point estimates such as median life are usually unavailable."},
{"interp.censoring_formula_reference",
 "删失契约证据类型 formula_reference；右删失不得当作失效。",
 "Censoring-contract evidence type is formula_reference; right-censored times must not be treated as failures."},
{"interp.warranty_invalid_window",
 "保修窗口 T_w 必须为正有限数。",
 "Warranty window T_w must be a positive finite number."},
{"interp.warranty_missing_time_unit",
 "保修摘要需要明确时间单位。",
 "Warranty summary requires an explicit time unit."},
{"interp.warranty_invalid_reliability",
 "R(T_w) 必须落在 [0,1]。",
 "R(T_w) must lie in [0,1]."},
{"interp.warranty_all_censored_input",
 "输入为全删失；预测摘要仍可计算，但不得宣称为观察失效率。",
 "Input is fully censored; a prediction summary can still be computed but must not be labeled as an observed failure rate."},
{"interp.warranty_formula_reference",
 "claims/1000 = 1000*(1-R(T_w))；证据类型 formula_reference，非 vendor_oracle。",
 "claims/1000 = 1000*(1-R(T_w)); evidence type formula_reference, not vendor_oracle."},
{"interp.warranty_prediction_label",
 "当前摘要标记为 prediction，不得与观察失效计数混读为同一口径。",
 "This summary is labeled prediction and must not be read as the same quantity as observed failure counts."},
{"interp.warranty_strata_mixed_reliability",
 "部分 failure_mode 层使用 cause-specific R(T_w)，其余仍用池化 R；证据类型 formula_reference，不是 vendor_oracle。",
 "Some failure_mode strata use cause-specific R(T_w); others still use pooled R; evidence type formula_reference, not vendor_oracle."},
{"interp.warranty_strata_mode_specific_reliability",
 "分层 expected_failures = 层暴露量 * F_mode(T_w)，F_mode 来自 cause-specific 分模式拟合（竞争失效作右删失）；formula_reference，不是 vendor_oracle。",
 "Stratum expected_failures = stratum exposure * F_mode(T_w), where F_mode comes from cause-specific per-mode fits (competing failures as right-censored); formula_reference, not vendor_oracle."},
{"interp.mode_fit_threshold_model_unsupported",
 "分模式拟合当前仅支持二参数 Weibull / Lognormal / Exponential / KM；阈值模型请用总体拟合。",
 "Per-mode fitting currently supports two-parameter Weibull / Lognormal / Exponential / KM only; use overall fitting for threshold models."},
{"interp.mode_fit_no_labeled_failures",
 "无带 failure_mode 标签的 exact 失效，跳过分模式拟合。",
 "No exact failures labeled with failure_mode; per-mode fitting skipped."},
{"interp.mode_fit_cause_specific_scope",
 "分模式可靠度 = cause-specific：目标模式 exact 为失效，其他已标注模式的 exact 作为右删失，原始 right 仍为右删失；evidence_type=formula_reference，algorithm_id=cause_specific_right_censored_competing；不是 vendor_oracle。",
 "Per-mode reliability is cause-specific: target-mode exact events are failures; other labeled-mode exact events are right-censored; original right remains right-censored; evidence_type=formula_reference, algorithm_id=cause_specific_right_censored_competing; not vendor_oracle."},
{"interp.rel_invalid_event_value",
 "事件列只接受明确的失效/删失编码；未知值不会被静默当作删失。",
 "The event column accepts only explicit failure/censoring codes; unknown values are not silently treated as censored."},
{"interp.rel_invalid_censoring_type_value",
 "删失类型列无法解析，或与事件列冲突；未知值不会被静默改写。left/interval 若出现在数据中，将由删失契约拒绝经典 KM 路径。",
 "Censoring-type column could not be parsed or conflicts with the event column; unknown values are not silently rewritten. If left/interval appear, the censoring contract rejects the classic KM path."},
{"interp.censoring_contract_failed",
 "删失契约校验失败。",
 "Censoring-contract validation failed."},
{"interp.hotelling_err_empty_matrix",
 "需要至少一行多元观测。",
 "At least one multivariate observation row is required."},
{"interp.hotelling_err_need_multivariate",
 "Hotelling T² 至少需要两个变量列。",
 "Hotelling T² requires at least two variable columns."},
{"interp.hotelling_err_phase1_m_gt_p_plus_1",
 "个体 T² Phase I 需要 m > p+1。",
 "Individuals T² Phase I requires m > p+1."},
{"interp.hotelling_err_source_row_mismatch",
 "source_rows 长度必须匹配观测数。",
 "source_rows length must match the number of observations."},
{"interp.hotelling_err_invalid_matrix",
 "无法估计均值/协方差（非有限或不矩形）。",
 "Unable to estimate mean/covariance (non-finite or non-rectangular)."},
{"interp.hotelling_err_singular_covariance",
 "样本协方差奇异，无法计算 T²。",
 "Sample covariance is singular; T² cannot be computed."},
{"interp.hotelling_info_not_pca_empirical_t2",
 "本命令是正式多元 Hotelling T² 控制图，不是 PCA 经验分位 T²。",
 "This command is a formal multivariate Hotelling T² control chart, not PCA empirical-quantile T²."},
{"interp.mewma_err_need_multivariate",
 "MEWMA 至少需要两个变量列。",
 "MEWMA requires at least two variable columns."},
{"interp.mewma_err_need_three_obs",
 "MEWMA 至少需要 3 个观测。",
 "MEWMA requires at least 3 observations."},
{"interp.mewma_err_invalid_matrix",
 "无法估计均值/协方差。",
 "Unable to estimate mean/covariance."},
{"interp.mewma_err_ragged_matrix",
 "观测矩阵必须矩形。",
 "The observation matrix must be rectangular."},
{"interp.mewma_err_singular_step_cov",
 "MEWMA 协方差在当前步奇异。",
 "MEWMA covariance is singular at the current step."},
{"interp.mewma_warn_ucl_not_arl_calibrated",
 "默认 UCL 使用渐近 χ² 近似，不是仿真 ARL 校准常数；可手工指定 ucl。",
 "Default UCL uses an asymptotic χ² approximation, not a simulation ARL-calibrated constant; you may specify ucl manually."},
{"interp.mewma_info_not_univariate_ewma",
 "MEWMA 是多元向量平滑；不要与单变量 EWMA 图混淆。",
 "MEWMA is multivariate vector smoothing; do not confuse it with a univariate EWMA chart."},
{"interp.gv_err_empty_subgroups",
 "需要至少一个子组。",
 "At least one subgroup is required."},
{"interp.gv_err_empty_subgroup",
 "子组不能为空。",
 "Subgroups cannot be empty."},
{"interp.gv_err_need_multivariate",
 "GV 图至少需要两个变量。",
 "The GV chart requires at least two variables."},
{"interp.gv_err_subgroup_too_small",
 "广义方差图要求每个子组大小 n > 变量数 p。",
 "Generalized variance requires each subgroup size n > number of variables p."},
{"interp.gv_err_unequal_subgroups",
 "广义方差图要求等量子组。",
 "Generalized variance requires equal-sized subgroups."},
{"interp.gv_err_ragged_subgroup",
 "子组观测必须具有相同变量数。",
 "Subgroup observations must have the same number of variables."},
{"interp.gv_err_invalid_b_constants",
 "b1/b2 常数无效。",
 "b1/b2 constants are invalid."},
{"interp.gv_err_non_finite",
 "子组含非有限值。",
 "Subgroup contains non-finite values."},
{"interp.gv_info_montgomery_subgroup",
 "广义方差图按 Montgomery |S| 子组公式；个体观测路径不做假 |S|。",
 "Generalized variance follows Montgomery |S| subgroup formulas; the individuals path does not fabricate |S|."},
{"interp.gv_warn_variability_chart_caveat",
 "NIST 指出多元变差图存在争议；本输出仅作 |S| 探索信号，不是唯一变差判定。",
 "NIST notes multivariate variability charts are controversial; this output is an exploratory |S| signal only, not a sole variability decision."},
{"interp.emp_warn_zero_repeatability",
 "重复性方差为 0，Probable Error 为 0；请检查设计。",
 "Repeatability variance is 0, so Probable Error is 0; check the design."},
{"interp.emp_info_not_aiag_pass_fail",
 "EMP 分级基于 Wheeler ICC，不是 AIAG %Study Var 合格判定。",
 "EMP classification is based on Wheeler ICC, not an AIAG %Study Var pass/fail decision."},
{"interp.cif_info_no_labeled_failures",
 "无带 failure_mode 标签的 exact 失效，跳过 Aalen–Johansen CIF。",
 "No exact failures with a failure_mode label; skipping Aalen–Johansen CIF."},
{"interp.cif_info_aalen_johansen_scope",
 "累计发生函数 CIF = Aalen–Johansen（formula_reference / aalen_johansen_cif）：总体生存把任一标注失效当作事件；CIF_k 为原因 k 的累计发生概率。不是 Fine-Gray 多协变量回归，不是 cause-specific（竞争删失）可靠度，不是 vendor_oracle。二分类 group 的 Fine-Gray 另有门禁路径。",
 "CIF = Aalen–Johansen (formula_reference / aalen_johansen_cif): overall survival treats any labeled failure as an event; CIF_k is the cumulative incidence for cause k. Not Fine-Gray multivariable regression, not cause-specific (competing-censor) reliability, and not vendor_oracle. Binary-group Fine-Gray has a separate gated path."},
{"interp.cif_warn_not_fine_gray",
 "Aalen–Johansen CIF 本身不是 Fine-Gray 回归；不得把 CIF 表写成 Fine-Gray 或商业软件对齐。",
 "Aalen–Johansen CIF is not Fine-Gray regression; do not present the CIF table as Fine-Gray or commercial-software alignment."},
{"interp.fine_gray_warn_not_commercial_alignment",
 "不得把本 Fine-Gray 结果写成商业软件对齐或 pinned R survival::finegray 黄金标准。",
 "Do not present these Fine-Gray results as commercial-software alignment or a pinned R survival::finegray golden standard."},
{"interp.fine_gray_err_singular_information_beta",
 "Fine-Gray 信息量退化，未能估计 β。",
 "Fine-Gray information matrix is singular; β could not be estimated."},
{"interp.fine_gray_err_beta_diverged",
 "Fine-Gray β 迭代发散。",
 "Fine-Gray β iteration diverged."},
{"interp.fine_gray_err_not_converged",
 "Fine-Gray 未在迭代上限内收敛。",
 "Fine-Gray did not converge within the iteration limit."},
{"interp.fine_gray_err_singular_information_se",
 "Fine-Gray 信息量不可逆，未能估计 SE。",
 "Fine-Gray information matrix is not invertible; SE could not be estimated."},
{"interp.fine_gray_err_covariate_row_mismatch",
 "Fine-Gray 协变量矩阵行数与观测不一致。",
 "Fine-Gray covariate matrix row count does not match the observation count."},
{"interp.fine_gray_err_need_labeled_failures",
 "Fine-Gray 需要带 failure_mode 的 exact 失效。",
 "Fine-Gray requires exact failures that carry a failure_mode."},
{"interp.fine_gray_err_ragged_covariate_matrix",
 "Fine-Gray 协变量矩阵行长度不一致。",
 "Fine-Gray covariate matrix rows have inconsistent lengths."},
{"interp.fine_gray_err_need_two_covariates",
 "fine_gray_multi 需要至少两个协变量；单列请用 fine_gray_continuous。",
 "fine_gray_multi needs at least two covariates; for a single column use fine_gray_continuous."},
{"interp.fine_gray_err_continuous_length_mismatch",
 "Fine-Gray 连续协变量长度与观测不一致。",
 "Fine-Gray continuous covariate length does not match the observation count."},
{"interp.fine_gray_warn_target_one_group_only",
 "目标原因失效只出现在一个分组中；估计仍可运行但对比识别较弱。",
 "Target-cause failures appear in only one group; estimation can still run, but contrast identification is weak."},
{"interp.fine_gray_info_multi_priority",
 "已指定多协变量列：Fine-Gray 使用 multi IPCW，不与二分类 group Fine-Gray 同时运行。",
 "Multiple covariate columns were specified: Fine-Gray uses multi IPCW and does not also run binary-group Fine-Gray."},
{"interp.fine_gray_info_continuous_priority",
 "已指定连续协变量列：Fine-Gray 使用 continuous IPCW，不与二分类 group Fine-Gray 同时运行。",
 "A continuous covariate column was specified: Fine-Gray uses continuous IPCW and does not also run binary-group Fine-Gray."},
{"interp.iforest_err_empty",
 "Isolation Forest 需要非空矩阵与 tree_count ≥ 1。",
 "Isolation Forest requires a non-empty matrix and tree_count ≥ 1."},
{"interp.iforest_err_need_2x2",
 "至少需要 2 个观测与 2 个变量。",
 "At least 2 observations and 2 variables are required."},
{"interp.iforest_scope",
 "自研 Isolation Forest；多元异常辅助；非单变量 Grubbs/Dixon；非 TreeNet。",
 "In-house Isolation Forest; multivariate anomaly aid; not univariate Grubbs/Dixon; not TreeNet."},
{"interp.kmeans_err_k_lt2",
 "K-Means 需要 k ≥ 2。",
 "K-Means requires k ≥ 2."},
{"interp.kmeans_err_empty",
 "K-Means 需要至少一行有效数值观测。",
 "K-Means requires at least one valid numeric observation row."},
{"interp.cluster_err_n_lt_k",
 "有效观测数必须 ≥ k。",
 "The number of valid observations must be ≥ k."},
{"interp.kmeans_init_lloyd",
 "初始质心取前 k 个有效观测（分析尺度）；Lloyd 迭代（分配→更新质心）。",
 "Initial centroids use the first k valid observations (analysis scale); Lloyd iteration (assign → update centroids)."},
{"interp.kmeans_warn_max_iter",
 "已达最大迭代次数，分配可能尚未完全稳定。",
 "Maximum iterations reached; assignments may not be fully stable."},
{"interp.cart_err_empty",
 "CART 需要预测矩阵与响应对齐且非空。",
 "CART requires a non-empty predictor matrix aligned with the response."},
{"interp.cart_err_no_predictors",
 "至少需要一个数值预测变量。",
 "At least one numeric predictor is required."},
{"interp.cart_err_insufficient_for_min_leaf",
 "有效观测过少，无法按 min_leaf 分裂。",
 "Too few valid observations to split under min_leaf."},
{"interp.cart_scope_producer",
 "自研 CART 单树；非 Minitab TreeNet/Random Forests 数值对齐；本轮无成本复杂度剪枝。",
 "In-house single CART tree; not numerically aligned to Minitab TreeNet/Random Forests; no cost-complexity pruning in this run."},
{"interp.lda_err_invalid",
 "线性判别需要 ≥2 类、≥1 预测变量与足够观测。",
 "Linear discriminant needs ≥2 classes, ≥1 predictor, and enough observations."},
{"interp.lda_err_bad_row",
 "类别编码或预测行列不一致。",
 "Class codes or predictor row/column layout are inconsistent."},
{"interp.lda_err_small_class",
 "每个类至少需要 2 个观测。",
 "Each class needs at least 2 observations."},
{"interp.lda_err_pooled_df",
 "合并协方差自由度不足。",
 "Insufficient degrees of freedom for the pooled covariance."},
{"interp.lda_err_singular_pooled",
 "合并协方差奇异。",
 "Pooled covariance is singular."},
{"interp.lda_scope_producer",
 "线性判别（等协方差）；非 Minitab golden；不做 QDA。",
 "Linear discriminant (equal covariance); not Minitab golden; no QDA."},
{"interp.hclust_err_invalid",
 "层次聚类需要非空矩阵且 k≥2。",
 "Hierarchical clustering requires a non-empty matrix and k≥2."},
{"interp.hclust_linkage_scope",
 "Complete linkage + 欧氏距离；非 Minitab golden。",
 "Complete linkage + Euclidean distance; not Minitab golden."},
{"interp.mixture2_err_insufficient_n",
 "观测不足（n<30），无法做二维高斯混合 EM；不得把不足样本写成已排除混合。",
 "Insufficient observations (n<30) for two-component Gaussian-mixture EM; do not write undersized samples as having ruled out a mixture."},
{"interp.mixture2_err_density_degenerate",
 "二维高斯混合 EM 密度退化，未能收敛；不得伪造混合拟合。",
 "Two-component Gaussian-mixture EM density degenerated and did not converge; do not fabricate a mixture fit."},
{"interp.mixture2_err_not_converged",
 "二维高斯混合 EM 未在迭代上限内收敛；不得把未收敛结果写成已确认混合。",
 "Two-component Gaussian-mixture EM did not converge within the iteration limit; do not write a non-converged result as a confirmed mixture."},
{"interp.mixture_k_err_insufficient_n",
 "观测不足（n<30），无法做多 k 高斯混合 BIC 搜索；不得把不足样本写成已排除混合。",
 "Insufficient observations (n<30) for multi-k Gaussian-mixture BIC search; do not write undersized samples as having ruled out a mixture."},
{"interp.mixture_k_err_search_failed",
 "多 k 高斯混合 BIC 搜索未得到可用拟合；不得伪造混合结论。",
 "Multi-k Gaussian-mixture BIC search produced no usable fit; do not fabricate mixture conclusions."},
{"interp.cap_assumption_stability_normality",
 "能力指标未验证过程稳定性和正态性；数值仅供调查，不能单独作为过程合格结论。",
 "Capability indices have not verified process stability and normality; values are for investigation only and must not stand alone as process pass/fail."},
{"interp.cap_assumption_stability_only",
 "能力指标未验证过程稳定性；数值仅供调查，不能单独作为过程合格结论。",
 "Capability indices have not verified process stability; values are for investigation only and must not stand alone as process pass/fail."},
{"interp.cap_stability_insufficient_n",
 "观测不足，无法做能力分析前的 I-MR 稳定性初筛。",
 "Too few observations for the pre-capability I-MR stability screen."},
{"interp.cap_bimodality_insufficient_n",
 "观测不足（n<30），无法做能力分析前的双峰直方图初筛；不得把不足样本写成已排除双峰。",
 "Fewer than 30 observations; bimodality histogram screen cannot run—do not describe an insufficient sample as having ruled out bimodality."},
{"interp.cap_bimodality_clear_not_proof",
 "直方图双峰初筛未检出可分离峰；这不是单峰证明，不得据此开放过程合格判定。",
 "Histogram bimodality screen found no separable peaks; this does not prove unimodality and must not open process pass/fail."},
{"interp.cap_bimodality_screen_note",
 "能力分析双峰前置：当前为公式参考级直方图峰谷初筛；Hartigan dip 与二维高斯混合另有门禁筛查；合格判定保持关闭。",
 "Capability bimodality prerequisite: formula-reference histogram peak/valley screen; Hartigan dip and Gaussian mixture are separate gated screens; pass/fail stays closed."},
{"interp.cap_hartigan_insufficient_n",
 "观测不足（n<8），无法做 Hartigan dip 单峰门禁筛查；不得把不足样本写成已证明单峰。",
 "Fewer than 8 observations; Hartigan dip unimodality screen cannot run—do not describe an insufficient sample as proving unimodality."},
};

}  // namespace

void append_report_text_catalog_part14(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart14),
        std::end(kReportTextCatalogPart14));
}

}  // namespace datalab::domain
