#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart4[] = {
{"diag.normality.ryan_joiner_not_computed",
 "Ryan–Joiner 统计量无法计算（方差或正态得分为零）。",
 "Ryan–Joiner statistic cannot be computed (zero variance or normal scores)."},
{"diag.normality.ryan_joiner_p_gt_010",
 "Ryan–Joiner：R 高于 α=0.10 临界，报告 p>0.10（存储 0.10）。",
 "Ryan–Joiner: R exceeds the α=0.10 critical value; reporting p>0.10 (stored as 0.10)."},
{"diag.normality.ryan_joiner_p_lt_001",
 "Ryan–Joiner：R 不高于 α=0.01 临界，报告 p<0.01（存储 0.01）。",
 "Ryan–Joiner: R does not exceed the α=0.01 critical value; reporting p<0.01 (stored as 0.01)."},
{"diag.distribution_id.insufficient_data",
 "个体分布识别至少需要 3 个有效数值观测。",
 "Individual distribution identification requires at least 3 valid numeric observations."},
{"diag.distribution_id.non_positive_values",
 "存在非正值；Weibull、Lognormal 与 Exponential 仅对全部正值计算 AD。",
 "Non-positive values present; Anderson–Darling for Weibull, Lognormal, and Exponential is computed only when all values are positive."},
{"diag.doe.factor_count_overflow",
 "因子数量过大，无法验证全因子运行数。",
 "Too many factors to verify full-factorial run count."},
{"diag.doe.invalid_run_shape",
 "每个 DOE 运行必须包含一个对应每个因子的编码。",
 "Each DOE run must include one coded level per factor."},
{"diag.doe.invalid_center_point",
 "中心点的所有编码必须为零。",
 "All coded levels at center points must be zero."},
{"diag.doe.invalid_factor_level",
 "全因子运行的编码只能为 -1 或 +1。",
 "Full-factorial run coded levels must be -1 or +1 only."},
{"diag.doe.incomplete_factorial_coverage",
 "设计未完整覆盖每个 2 水平因子组合，或存在重复运行。",
 "Design does not fully cover every two-level factor combination, or duplicate runs exist."},
{"diag.doe.hold_out_of_range",
 "hold 实际值超出高低水平，已 clamp 到编码 [-1,1]。",
 "Hold actual value exceeds low/high levels; clamped to coded [-1, 1]."},
{"diag.doe.invalid_hold_levels",
 "因子高低水平相等，hold 回退编码 0。",
 "Factor low and high levels are equal; hold falls back to coded 0."},
{"diag.doe.invalid_hold_value",
 "hold 实际值无法匹配高低水平，该因子回退编码 0。",
 "Hold actual value does not match low/high levels; factor falls back to coded 0."},
{"diag.doe.contour_factors_held_at_actual",
 "未作图的因子按指定实际单位 hold（已转换为编码）求值。",
 "Factors not plotted are held at specified actual units (converted to coded values) for evaluation."},
{"diag.doe.contour_factors_held_at_zero",
 "未作图的因子在编码 0 处保持不变。",
 "Factors not plotted are held at coded 0."},
{"diag.doe.base_design_factor_overflow",
 "基设计因子过多，无法生成运行数。",
 "Too many base-design factors to generate run count."},
{"diag.doe.generate_run_count_overflow",
 "因子数量过大，无法生成运行数。",
 "Too many factors to generate run count."},
{"diag.doe.center_point_count_overflow",
 "中心点数量过大，无法生成 DOE 运行列表。",
 "Center-point count too large to generate DOE run list."},
{"diag.doe.invalid_run_count",
 "DOE 运行数与设计内容不一致。",
 "DOE run count does not match design contents."},
{"diag.doe.invalid_block",
 "DOE 区组编号必须从 1 开始。",
 "DOE block numbers must start at 1."},
{"diag.doe.invalid_response_shape",
 "响应值数量必须与 DOE 运行数一致。",
 "Response count must match DOE run count."},
{"diag.doe.insufficient_effect_data",
 "计算 DOE 效应时正负对比组必须都有有效响应。",
 "Both positive and negative contrast groups must have valid responses to compute DOE effects."},
{"diag.doe.diagnose_factor_count_overflow",
 "因子数量过大，无法诊断完整 2 水平组合。",
 "Too many factors to diagnose complete two-level combinations."},
{"diag.doe.missing_runs",
 "设计缺少一个或多个 2 水平因子组合。",
 "Design is missing one or more two-level factor combinations."},
{"diag.doe.duplicate_runs",
 "设计包含重复的因子组合。",
 "Design contains duplicate factor combinations."},
{"diag.doe.block_terms_included",
 "区组项已作为模型中的分类项纳入拟合。",
 "Block terms included as categorical model terms in the fit."},
{"diag.doe.replicated_runs",
 "检测到重复因子组合，已用于纯误差估计。",
 "Duplicate factor combinations detected and used for pure-error estimation."},
{"diag.doe.lenth_pse_unreplicated",
 "误差自由度为 0，标准化效应 Pareto 使用 Lenth PSE 参考线。",
 "Error degrees of freedom are 0; standardized-effects Pareto uses Lenth PSE reference line."},
{"diag.doe.invalid_contour_factor_index",
 "等值线因子索引无效。",
 "Contour factor index is invalid."},
{"diag.doe.missing_factorial_coefficients",
 "没有可用于求值的析因系数。",
 "No factorial coefficients available for evaluation."},
{"diag.doe.factorial_contour_no_quadratic",
 "二水平模型无平方项，等值线为双线性面，不能表示曲率。",
 "Two-level model has no squared terms; contour is a bilinear surface and cannot represent curvature."},
{"diag.doe.hold_ignored_axis_factor",
 "轴因子的 hold 条目已忽略。",
 "Hold entry for axis factor ignored."},
{"diag.doe.unknown_hold_factor",
 "hold 中出现未知因子名，已忽略。",
 "Unknown factor name in hold; ignored."},
{"diag.cif.unlabeled_exact_excluded",
 "有 %1 条 exact 失效缺少 failure_mode，已从 CIF 排除。",
 "%1 exact failure(s) lack failure_mode and were excluded from CIF."},
{"diag.cif.left_interval_omitted",
 "CIF 省略 left/interval 行 %1 条；请用 km_interval 路径处理。",
 "CIF omitted %1 left/interval row(s); use the km_interval path."},
{"diag.km_interval.need_three_obs",
 "区间删失 KM 至少需要约 3 条观测。",
 "Interval-censored KM requires about 3 or more observations."},
{"diag.km_interval.invalid_interval_order",
 "存在 R < L 的无效区间。",
 "Invalid interval with R < L."},
{"diag.km_interval.too_few_valid",
 "有效区间过少。",
 "Too few valid intervals."},
{"diag.km_interval.grid_failed",
 "无法构造 Turnbull 时间网格。",
 "Cannot construct Turnbull time grid."},
{"diag.km_interval.no_mass_points",
 "无候选质量点。",
 "No candidate mass points."},
{"diag.km_interval.mass_collapsed",
 "Turnbull 质量塌缩。",
 "Turnbull mass collapsed."},
{"diag.km_interval.max_iter",
 "Turnbull 已达最大迭代。",
 "Turnbull reached maximum iterations."},
{"diag.km_interval.scope",
 "Turnbull NPMLE（简化网格）；非右删失 product-limit；非 Minitab golden。",
 "Turnbull NPMLE (simplified grid); not right-censored product-limit; not Minitab golden."},
{"diag.gaussian_mixture_k.skipped_sparse",
 "跳过 k=%1（n < 15k）；不得把跳过写成已排除该 k。",
 "Skipped k=%1 (n < 15k); must not treat skip as exclusion of that k."},
{"diag.gaussian_mixture_k.em_failed",
 "k=%1 高斯混合 EM 失败（%2）；该 k 不参与 BIC 优选。",
 "k=%1 Gaussian mixture EM failed (%2); that k is excluded from BIC selection."},
{"diag.gaussian_mixture_k.not_converged",
 "k=%1 高斯混合 EM 未收敛；该 k 不参与 BIC 优选。",
 "k=%1 Gaussian mixture EM did not converge; that k is excluded from BIC selection."},
{"diag.cap.between_variance_truncated",
 "估计的组间方差为负，已截断为 0；σ_B 可能低估。",
 "Estimated between-subgroup variance was negative and truncated to 0; σ_B may be underestimated."},
{"diag.cap.ci_df_used_sample_n",
 "组间/组内能力区间自由度使用 N−1，不是 Minitab Rbar/Sbar 调整 ν。",
 "Between/within capability interval df uses N−1, not Minitab Rbar/Sbar adjusted ν."},
{"diag.cap.ci_not_computed",
 "样本量不足或置信水平非法，未计算能力指数区间。",
 "Sample size insufficient or confidence level invalid; capability index intervals were not computed."},
{"diag.cap.hartigan_mc_clause",
 "，Uniform 零假设 MC p≈%1（reps=%2）",
 ", Uniform-null MC p≈%1 (reps=%2)"},
{"diag.censoring.worksheet_row_type_unparsed",
 "第 %1 行 censoring_type 无法解析。",
 "Row %1 censoring_type could not be parsed."},
{"diag.censoring.worksheet_row_time_invalid",
 "第 %1 行 time 不是有限数。",
 "Row %1 time is not a finite number."},
{"diag.censoring.worksheet_row_interval_invalid",
 "第 %1 行区间界缺失或非法（不静默补齐）。",
 "Row %1 interval bounds missing or invalid (not silently imputed)."},
{"diag.censoring.worksheet_row_exposure_invalid",
 "第 %1 行 exposure 非法。",
 "Row %1 exposure is invalid."},
{"diag.warranty.no_strata_input",
 "未提供分层输入；仅输出总体保修摘要。",
 "No stratum input provided; overall warranty summary only."},
{"diag.warranty.stratum_invalid_mode_r",
 "分层 %1 提供的分模式 R(T_w) 非法，已回退到池化 R。",
 "Stratum %1 supplied invalid mode-specific R(T_w); fell back to pooled R."},
{"diag.warranty.stratum_no_denominator",
 "分层无测量暴露量且 valid_count 全为 0，无法追溯分母。",
 "Strata have no measured exposure and all valid_count are 0; denominators cannot be traced."},
{"diag.warranty.stratum_kind_missing",
 "分层 kind 必须为 failure_mode 或 group。",
 "Each stratum kind must be failure_mode or group."},
{"diag.warranty.stratum_kind_mixed",
 "同一次分层摘要不得混用 failure_mode 与 group。",
 "A single stratum summary must not mix failure_mode and group."},
{"diag.warranty.stratum_invalid_exposure",
 "分层暴露量必须为有限非负数。",
 "Stratum exposure must be finite and non-negative."},
{"diag.mode_fit.left_interval_omitted",
 "分模式拟合省略 left/interval 行 %1 条；请用 km_interval / 总体路径处理。",
 "Per-mode fitting omitted %1 left/interval row(s); use km_interval / overall path."},
{"diag.mode_fit.model_unsupported",
 "分模式拟合不支持模型 '%1'。",
 "Per-mode fitting does not support model '%1'."},
{"diag.mode_fit.no_failures",
 "模式 %1 无 exact 失效，无法拟合。",
 "Mode %1 has no exact failures; cannot fit."},
{"diag.mode_fit.reliability_at_tw_failed",
 "模式 %1 已拟合但未能在 T_w 计算 R。",
 "Mode %1 was fitted but R could not be computed at T_w."},
{"diag.censoring_worksheet_export_ready",
 "已生成逐观测删失状态工作表（%1 行；censoring_type=exact|right|left|interval）。可写回活动表以便审计或再导入；不是 vendor_oracle。",
 "Per-observation censoring-status worksheet generated (%1 rows; censoring_type=exact|right|left|interval). Can be written back to the active sheet for audit or re-import; not vendor_oracle."},
{"status.unknown_special_cause_rule",
 "未知特殊原因规则",
 "Unknown special-cause rule"},
{"plot.cusum_upper",
 "上侧 CUSUM",
 "Upper CUSUM"},
{"plot.cusum_lower",
 "下侧 CUSUM",
 "Lower CUSUM"},
{"plot.series.part_mean",
 "零件均值",
 "Part mean"},
{"plot.axis.suffix.grouped_by_open",
 "（按 ",
 "(grouped by "},
{"plot.axis.suffix.grouped_by_close",
 " 分组）",
 ")"},
{"plot.msa_by_part_xbar",
 "按零件 Xbar",
 "Xbar by part"},
{"plot.msa_by_part_r",
 "按零件 R",
 "R by part"},
{"plot.msa_by_operator_xbar",
 "按操作者 Xbar",
 "Xbar by operator"},
{"plot.msa_by_operator_r",
 "按操作者 R",
 "R by operator"},
{"interp.section.residual_normality",
 "残差正态性",
 "Residual normality"},
{"interp.regression_residual_ad_fail_to_reject",
 "Anderson-Darling = %1，在 alpha 下未拒绝残差正态假设，不能据此宣称模型合格。",
 "Anderson-Darling = %1; failure to reject residual normality at alpha does not qualify the model."},
{"interp.regression_residual_ad_use_plot_p",
 "Anderson-Darling = %1，请结合正态概率图和 P 值判断残差正态性，不能只看 R²。",
 "Anderson-Darling = %1; use the normal probability plot and P value to judge residual normality; do not rely on R² alone."},
{"metric.spc.rule_policy",
 "规则策略",
 "Rule policy"},
{"metric.spc.enabled_rules",
 "启用规则",
 "Enabled rules"},
{"metric.spc.enabled_tests",
 "启用测试",
 "Enabled tests"},
{"metric.spc.decision_basis",
 "判定口径",
 "Decision basis"},
{"metric.spc.valid_subgroup_count",
 "有效子组数",
 "Valid subgroups"},
{"metric.spc.subgroup_count",
 "子组数",
 "Subgroup count"},
{"metric.spc.subgroup_size",
 "子组大小",
 "Subgroup size"},
{"metric.spc.ooc_points_rule1",
 "「单点超出 3σ 控制限」触发点数",
 "Points beyond 3σ limits"},
{"metric.spc.xbar_ooc_points_rule1",
 "Xbar「单点超出 3σ 控制限」触发点数",
 "Xbar points beyond 3σ limits"},
{"metric.spc.r_ooc_points_rule1",
 "R「单点超出 3σ 控制限」触发点数",
 "R points beyond 3σ limits"},
{"metric.spc.s_ooc_points_rule1",
 "S「单点超出 3σ 控制限」触发点数",
 "S points beyond 3σ limits"},
{"metric.spc.r_applicable_rules",
 "R 适用规则",
 "R applicable rules"},
{"metric.spc.s_applicable_rules",
 "S 适用规则",
 "S applicable rules"},
{"metric.spc.xbar_enabled_tests",
 "Xbar 启用测试",
 "Xbar enabled tests"},
{"metric.spc.i_chart_enabled_tests",
 "I 图启用测试",
 "I-chart enabled tests"},
{"metric.spc.applicability",
 "适用性",
 "Applicability"},
{"metric.spc.parameter_source",
 "参数来源",
 "Parameter source"},
{"metric.spc.limit_sigma_multiple",
 "控制限倍数",
 "Control-limit multiple"},
{"metric.spc.sigma_estimation_method",
 "σ 估计方法",
 "σ estimation method"},
{"metric.spc.mr_applicable_rules",
 "MR 图适用规则",
 "MR chart applicable rules"},
{"metric.spc.mr_rs_applicable_rules",
 "MR/R/S 适用规则",
 "MR/R/S applicable rules"},
{"status.spc.policy_user_specified",
 "用户指定",
 "User-specified"},
{"status.spc.policy_minitab_like",
 "minitab_like（仅「单点超出 3σ 控制限」）",
 "minitab_like (Rule 1 only)"},
{"status.spc.policy_all_applicable",
 "all_applicable（全部适用）",
 "all_applicable (all applicable)"},
{"status.spc.cusum_dedicated_signal",
 "CUSUM 专用信号",
 "CUSUM-dedicated signals"},
{"status.spc.no_shewhart_tests",
 "无（不套用 Tests 1–8）",
 "None (Tests 1–8 not applied)"},
{"status.spc.historical_params",
 "历史参数",
 "Historical parameters"},
{"metric.capability.spec_mode",
 "规格模式",
 "Specification mode"},
{"metric.capability.within_sigma_source",
 "Within σ 来源",
 "Within σ source"},
{"metric.capability.between_sigma_source",
 "Between σ 来源",
 "Between σ source"},
{"metric.capability.bw_sigma_source",
 "Between/Within σ 来源",
 "Between/Within σ source"},
{"metric.capability.overall_sigma_method",
 "Overall σ 方法",
 "Overall σ method"},
{"metric.capability.ad_decision",
 "AD 判定",
 "AD decision"},
{"status.unable_to_compute",
 "无法计算",
 "Unable to compute"},
{"status.ad_reject_normality",
 "在 alpha 下拒绝正态假设",
 "Reject normality at alpha"},
{"status.ad_fail_reject_normality",
 "在 alpha 下未拒绝正态假设",
 "Fail to reject normality at alpha"},
{"metric.capability.assumption_status",
 "假设状态",
 "Assumption status"},
{"metric.capability.ppm_below_lsl",
 "低于 LSL",
 "Below LSL"},
{"metric.capability.ppm_above_usl",
 "高于 USL",
 "Above USL"},
{"metric.spc.limit_method",
 "限方法",
 "Limit method"},
{"metric.spc.points_above_ucl",
 "超 UCL 点数",
 "Points above UCL"},
{"status.out_of_control",
 "超限",
 "Out of control"},
{"metric.cusum.target_t",
 "目标 T",
 "Target T"},
{"metric.cusum.first_upper_signal",
 "上侧首次信号点",
 "First upper signal point"},
{"metric.cusum.first_lower_signal",
 "下侧首次信号点",
 "First lower signal point"},
{"metric.cusum.signal_count",
 "信号总数",
 "Total signals"},
{"status.cusum.decision_basis",
 "上侧/下侧累计和超过决策间隔 hσ 记为信号，原因待调查。",
 "Upper/lower cumulative sums beyond decision interval hσ are signals pending investigation."},
{"metric.spc.moving_range_length",
 "移动极差长度",
 "Moving-range length"},
{"metric.zone.jaehn_threshold",
 "Jaehn 累计阈值",
 "Jaehn cumulative threshold"},
{"metric.zone.jaehn_signal_count",
 "Jaehn 信号点数",
 "Jaehn signal points"},
{"metric.zone.scoring_rule",
 "计分规则",
 "Scoring rule"},
{"status.zone.jaehn_scoring_value",
 "Jaehn 1/2/4 权重；不是完整 Western Electric Tests 1–8。",
 "Jaehn 1/2/4 weights; not full Western Electric Tests 1–8."},
{"metric.zmr.z_rule1_triggers",
 "Z 图「单点超出 3σ 控制限」触发",
 "Z chart “1 point beyond 3σ” triggers"},
{"metric.spc.applicable_tests",
 "适用测试",
 "Applicable tests"},
{"status.zmr.sample_params",
 "样本估计（未提供完整历史 μ/σ）",
 "Sample estimates (complete historical μ/σ not provided)"},
{"status.zmr.historical_mu_sigma",
 "历史 μ/σ",
 "Historical μ/σ"},
{"status.zmr.applicable_tests_value",
 "Z 图 Tests 1–4；MR 图无 Shewhart 测试。",
 "Z chart Tests 1–4; MR chart has no Shewhart tests."},
{"metric.imr.nelson_excluded_mr",
 "Nelson 剔除 MR 数",
 "Nelson excluded MR count"},
{"metric.spc.historical_mu",
 "历史 μ",
 "Historical μ"},
{"metric.spc.historical_sigma",
 "历史 σ",
 "Historical σ"},
{"status.not_specified_paren",
 "（未指定）",
 "(not specified)"},
{"metric.spc.limit_parameter_source",
 "控制限参数来源",
 "Control-limit parameter source"},
{"status.spc.historical_params_preferred",
 "历史参数优先",
 "Historical parameters preferred"},
{"status.spc.estimated_from_current",
 "当前数据估计",
 "Estimated from current data"},
{"metric.spc.stage_count",
 "阶段数",
 "Stage count"},
{"metric.spc.stage_column",
 "阶段列",
 "Stage column"},
{"status.not_specified",
 "未指定",
 "Not specified"},
{"metric.spc.stage_row_n_mean_sigma",
 "阶段 %1（N / 均值 / σ̂_MR）",
 "Stage %1 (N / mean / σ̂_MR)"},
{"status.spc.stage_estimate_note",
 "分阶段估计仅作对照；全局控制限仍由历史参数或全样本估计决定，不自动按阶段切换限。",
 "Stage estimates are for comparison only; global control limits still come from historical parameters or the full-sample estimate and do not auto-switch by stage."},
{"status.spc.attr_decision_basis",
 "特殊原因规则 beyond_control_limit…eight_beyond_1sigma；超过 kσ 使用严格大于，窗口不跨阶段或缺失断点",
 "Special-cause rules beyond_control_limit…eight_beyond_1sigma; kσ uses strict greater-than; windows do not cross stages or missing breaks"},
{"status.spc.ewma_applicability",
 "EWMA 只开放「单点超出 3σ 控制限」；其余特殊原因规则不附加到 EWMA。",
 "EWMA enables only points beyond 3σ limits; other special-cause rules are not attached to EWMA."},
{"status.spc.mr_rule_list",
 "单点超出 3σ 控制限、连续 9 点同侧、连续 6 点趋势、连续 14 点交替",
 "Points beyond 3σ limits, 9 consecutive on one side, 6 consecutive trending, 14 alternating"},
{"status.spc.mr_rule_list_minitab_note",
 "单点超出 3σ 控制限 / 连续 9 点同侧 / 连续 6 点趋势 / 连续 14 点交替（Minitab 不在 MR 图上启用后四条规则）",
 "Points beyond 3σ limits / 9 consecutive on one side / 6 consecutive trending / 14 alternating (Minitab does not enable the last four on the MR chart)"},
{"param.summary.subgroup_count_eq",
 "子组数 = ",
 "Subgroups = "},
{"param.summary.subgroup_size_eq",
 "子组大小 = ",
 "Subgroup size = "},
{"param.summary.historical_paren",
 "（历史参数）",
 " (historical)"},
{"param.summary.estimated_paren",
 "（估计）",
 " (estimated)"},
{"table.imr_chart",
 "I-MR 控制图",
 "I-MR control chart"},
{"table.imr_point_stats",
 "I-MR 逐点统计",
 "I-MR point statistics"},
{"table.xbar_r_params",
 "Xbar-R 参数",
 "Xbar-R parameters"},
{"table.xbar_r_chart",
 "Xbar-R 控制图",
 "Xbar-R control chart"},
{"table.xbar_r_subgroup_stats",
 "Xbar-R 逐子组统计",
 "Xbar-R subgroup statistics"},
};

}  // namespace

void append_report_text_catalog_part4(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart4),
        std::end(kReportTextCatalogPart4));
}

}  // namespace datalab::domain
