#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart2[] = {
{"diag.attr.need_defect_column",
 "请选择不合格品/缺陷数列。",
 "Select a defectives/defects column."},
{"diag.attr.need_inspected_or_constant",
 "请指定检验数/单位数列或常数。",
 "Specify an inspected/units column or constant."},
{"diag.attr.defectives_nonneg_int",
 "不合格品数必须是非负整数。",
 "Number of defectives must be a non-negative integer."},
{"diag.attr.defectives_inspected_nonneg_int",
 "不合格品数和检验数必须是非负整数。",
 "Defectives and inspected counts must be non-negative integers."},
{"diag.attr.need_defectives_and_inspected",
 "请指定不合格品数列和检验数（常数或列）。",
 "Specify a defectives column and inspected count (constant or column)."},
{"diag.attr.np_need_inspected",
 "NP 图需要固定检验数或检验数列。",
 "NP chart requires a fixed inspected count or inspected column."},
{"diag.attr.defects_nonneg_int",
 "缺陷数必须是非负整数。",
 "Number of defects must be a non-negative integer."},
{"diag.attr.u_need_units",
 "U 图需要单位数列。",
 "U chart requires a units column."},
{"diag.attr.defects_units_nonneg_int",
 "缺陷数和单位数必须是非负整数。",
 "Defects and units must be non-negative integers."},
{"diag.attr.defects_units_valid_cols",
 "缺陷数和单位数必须是有效的非负整数列。",
 "Defects and units must be valid non-negative integer columns."},
{"diag.pareto.no_category_data",
 "没有可用于柏拉图的类别数据。",
 "No category data is available for the Pareto chart."},
{"diag.pareto.ignored_bad_counts",
 "已忽略负数或非整数缺陷计数。",
 "Negative or non-integer defect counts were ignored."},
{"diag.attr.need_inspected_col_or_constant",
 "请指定检验数列或检验数常数。",
 "Specify an inspected column or inspected constant."},
{"diag.attr.inspected_nonneg_int",
 "检验数必须是非负整数。",
 "Inspected count must be a non-negative integer."},
{"diag.cause_effect.need_category_and_cause",
 "请选择类别列与原因列。",
 "Select a category column and a cause column."},
{"diag.cause_effect.empty",
 "未找到有效的类别-原因行。请提供非空类别列与原因列。",
 "No valid category-cause rows found; provide non-empty category and cause columns."},
{"diag.cause_effect.skipped_empty_cells",
 "已跳过 %1 个空类别或空原因单元格。",
 "Skipped %1 empty category or cause cell(s)."},
{"label.cause_effect.unnamed",
 "效果（未命名）",
 "Unnamed effect"},
{"diag.variability.length_mismatch_a",
 "测量列与因子 A 长度不一致。",
 "Measurement column length does not match factor A."},
{"diag.variability.length_mismatch_b",
 "测量列与因子 B 长度不一致。",
 "Measurement column length does not match factor B."},
{"diag.variability.empty",
 "没有有效的测量值可用于变异性图。",
 "No valid measurements are available for a variability chart."},
{"diag.variability.singleton_cell",
 "单元「%1」仅 1 个点，SD 记为 0。",
 "Cell \"%1\" has only 1 point; SD is recorded as 0."},
{"diag.import.contract.column_types_mismatch",
 "导入结果的列类型数量与列名不一致。",
 "Imported column-type count does not match column names."},
{"diag.import.contract.row_ids_mismatch",
 "导入结果的 RowId 数量与数据行不一致。",
 "Imported RowId count does not match data rows."},
{"diag.import.contract.cell_states_rows_mismatch",
 "导入结果的单元格状态行数与数据行不一致。",
 "Imported cell-state row count does not match data rows."},
{"diag.import.contract.metadata_row_count_mismatch",
 "导入元数据中的原始行数与数据行不一致。",
 "Import metadata original row count does not match data rows."},
{"diag.import.contract.metadata_column_count_mismatch",
 "导入元数据中的列数与列名不一致。",
 "Import metadata column count does not match column names."},
{"diag.import.contract.row_field_count_mismatch",
 "第 %1 行的字段数与列数不一致。",
 "Row %1 field count does not match column count."},
{"diag.import.contract.row_cell_states_mismatch",
 "第 %1 行的单元格状态数与列数不一致。",
 "Row %1 cell-state count does not match column count."},
{"diag.import.contract.duplicate_row_id",
 "导入结果包含重复的 RowId。",
 "Imported result contains duplicate RowId values."},
{"diag.graph.facet_levels_truncated",
 "分面水平数 = %1，受控 Graph Builder 最多显示 %2 个面板；已截断 %3 个水平（非自由拼版）。",
 "Facet levels = %1; controlled Graph Builder shows at most %2 panels; truncated %3 level(s) (not free-form layout)."},
{"diag.graph.facet_controlled_panels",
 "使用受控分面面板（facet），不是自由像素拼版；by/分组仍是图内着色，与分面列不同。",
 "Using controlled facet panels (facet), not free-form pixel layout; by/grouping is in-plot coloring and differs from facet columns."},
{"diag.adf.default_lags",
 "默认滞后 p = floor((T-1)^(1/3)) = %1。",
 "Default lag p = floor((T-1)^(1/3)) = %1."},
{"diag.adf.lags_too_large",
 "滞后过大，有效回归行不足。",
 "Lag order is too large; insufficient rows for regression."},
{"diag.adf.critical_source",
 "临界值为大样本 MacKinnon 风格常数表；非 Minitab 导出 golden。",
 "Critical values use large-sample MacKinnon-style constants; not Minitab-export golden."},
{"diag.eda.kde_silverman_bandwidth",
 "默认带宽为 Silverman：h=0.9·min(s,IQR/1.34)·n^(-1/5)；高斯核。",
 "Default bandwidth is Silverman: h=0.9·min(s,IQR/1.34)·n^(-1/5); Gaussian kernel."},
{"diag.import.plan.missing_provider_id",
 "ImportPlan 缺少 provider_id。",
 "ImportPlan is missing provider_id."},
{"diag.import.plan.missing_object_name",
 "ImportPlan 缺少对象名称。",
 "ImportPlan is missing object name."},
{"diag.import.plan.need_selected_columns",
 "请至少选择一列导入。",
 "Select at least one column to import."},
{"diag.import.plan.column_not_found",
 "所选列不存在：%1",
 "Selected column does not exist: %1"},
{"diag.import.plan.duplicate_column",
 "所选列重复：%1",
 "Duplicate selected column: %1"},
{"diag.import.plan.column_order_length",
 "column_order 长度必须与 selected_columns 一致。",
 "column_order length must match selected_columns."},
{"diag.import.plan.column_order_mismatch",
 "column_order 必须与 selected_columns 是同一集合。",
 "column_order must be the same set as selected_columns."},
{"diag.import.plan.aliases_length",
 "aliases 长度必须与 selected_columns 一致。",
 "aliases length must match selected_columns."},
{"diag.import.plan.order_key_not_found",
 "排序键不存在：%1",
 "Order key does not exist: %1"},
{"diag.import.plan.keyset_columns_empty",
 "keyset_after.columns 不能为空。",
 "keyset_after.columns must not be empty."},
{"diag.import.plan.keyset_columns_values_length",
 "keyset_after.columns 与 after_values 长度必须一致。",
 "keyset_after.columns and after_values lengths must match."},
{"diag.import.plan.keyset_column_not_found",
 "keyset 列不存在：%1",
 "Keyset column does not exist: %1"},
{"diag.import.plan.keyset_single_order_key",
 "单列 keyset 必须与 order_key 一致。",
 "Single-column keyset must match order_key."},
{"diag.import.plan.keyset_must_include_order_key",
 "复合 keyset 必须包含 order_key。",
 "Composite keyset must include order_key."},
{"diag.import.plan.keyset_row_offset_conflict",
 "不能同时使用 keyset_after 与 row_offset；优先 keyset。",
 "Do not use keyset_after and row_offset together; keyset takes priority."},
{"diag.import.plan.keyset_needs_row_limit",
 "keyset 分页需要设置 row_limit/page_size。",
 "Keyset paging requires row_limit/page_size."},
{"diag.import.plan.filter_column_not_found",
 "过滤列不存在：%1",
 "Filter column does not exist: %1"},
{"diag.import.plan.filter_op_unsupported",
 "不支持的过滤运算符：%1",
 "Unsupported filter operator: %1"},
{"diag.import.plan.filter_null_no_value",
 "%1 不得带绑定值。",
 "%1 must not include a bound value."},
{"diag.import.plan.filter_needs_value",
 "过滤运算符 %1 需要绑定值。",
 "Filter operator %1 requires a bound value."},
{"rule.msa.type1.stability_clear.message",
 "当前观测未发现稳定性图超限点。",
 "No out-of-control stability-chart points in current observations."},
{"rule.msa.type1.stability_triggered.message",
 "量具稳定性图存在超限点，需要调查特殊原因。",
 "Gage stability chart has out-of-control points; investigate special causes."},
{"rule.msa.type1.stability.action",
 "超限只是调查提示，不能直接判定量具合格或不合格。",
 "Out-of-control is an investigation hint only; do not treat it as gage pass/fail."},
{"header.target_value",
 "目标值",
 "Target value"},
{"header.weight",
 "权重",
 "Weight"},
{"header.goal",
 "目标",
 "Goal"},
{"header.best_prediction",
 "最佳预测",
 "Best prediction"},
{"header.single_response_d",
 "单响应 D",
 "Single-response D"},
{"header.rank",
 "排序",
 "Rank"},
{"header.prediction",
 "预测",
 "Prediction"},
{"header.predicted_value",
 "预测值",
 "Predicted value"},
{"header.confidence_lower",
 "置信下限",
 "Confidence lower"},
{"header.confidence_upper",
 "置信上限",
 "Confidence upper"},
{"header.prediction_lower",
 "预测下限",
 "Prediction lower"},
{"header.prediction_upper",
 "预测上限",
 "Prediction upper"},
{"header.suffix.prediction",
 " 预测",
 " prediction"},
{"header.suffix.desirability_d",
 " D",
 " D"},
{"param.summary.rsm_model_linear_interact_pq",
 "线性+交互+纯二次（编码单位）",
 "linear + interaction + pure quadratic (coded units)"},
{"param.summary.effective_runs_eq",
 "有效运行数 = ",
 "Effective runs = "},
{"diag.rsm.no_center_points_coded",
 "未检测到中心点（编码全 0）；纯误差/失拟诊断受限。",
 "No center points detected (all coded 0); pure-error / lack-of-fit diagnostics are limited."},
{"diag.doe.opt_missing_cov_ci_star",
 "缺少回归系数协方差矩阵，响应优化表中的置信区间与预测区间显示为 *。",
 "Regression coefficient covariance is unavailable; confidence and prediction intervals in the response-optimization tables show *."},
{"diag.ccd.nist_formula_reference",
 "CCD 点集按 NIST Response Surface / CCD 定义生成；证据类型 formula_reference，非 vendor_oracle，未冻结为商业软件对齐 golden。",
 "CCD points follow the NIST Response Surface / CCD definition; evidence type formula_reference, not vendor_oracle; not frozen as commercial-software golden alignment."},
{"diag.bbd.nist_formula_reference",
 "BBD 点集按 NIST Box–Behnken 定义生成；证据类型 formula_reference，非 vendor_oracle。",
 "BBD points follow the NIST Box–Behnken definition; evidence type formula_reference, not vendor_oracle."},
{"diag.rsm.insufficient_complete_case",
 "complete-case 有效行不足，无法拟合二次模型。",
 "Too few complete-case rows to fit a quadratic model."},
{"diag.rsm.factor_coding_failed",
 "因子编码失败。",
 "Factor coding failed."},
{"plot.axis.abs_effect",
 "|效应|",
 "|Effect|"},
{"page.km_interval_short",
 "区间删失 KM",
 "Interval-censored KM"},
{"diag.km_interval.need_left_right_columns",
 "请选择区间左端与右端列（右删失可用空/Inf）。",
 "Select interval left and right columns (right-censoring may use empty/Inf)."},
{"param.summary.exposure_total_eq",
 "暴露量合计 = ",
 "Total exposure = "},
{"param.summary.exposure_eq",
 "暴露量 = ",
 "Exposure = "},
{"param.summary.column_sum_open",
 "（列求和，",
 "(column sum, "},
{"param.summary.rows_close",
 " 行）",
 " rows)"},
{"param.summary.exact_eq",
 "精确 = ",
 "Exact = "},
{"param.summary.left_eq",
 "左 = ",
 "Left = "},
{"param.summary.interval_eq",
 "区间 = ",
 "Interval = "},
{"param.summary.right_eq",
 "右 = ",
 "Right = "},
{"plot.axis.standardized_value",
 "标准化值",
 "Standardized value"},
{"plot.axis.composition_proportion",
 "组成比例",
 "Composition proportion"},
{"plot.axis.density",
 "密度",
 "Density"},
{"header.chart",
 "图",
 "Plot"},
{"header.check_hypothesis",
 "检查假设",
 "Hypothesis to check"},
{"status.eda.run_sequence_hypothesis",
 "位置是否漂移；散布是否大致恒定",
 "Whether location drifts; whether spread is roughly constant"},
{"status.eda.lag1_hypothesis",
 "相邻观测是否呈结构（随机性）",
 "Whether adjacent observations show structure (randomness)"},
{"status.eda.histogram_hypothesis",
 "分布形态（是否近似钟形）",
 "Distribution shape (whether approximately bell-shaped)"},
{"status.eda.npp_hypothesis",
 "正态分位是否近似直线",
 "Whether normal quantiles are approximately linear"},
{"header.minimum",
 "最小值",
 "Minimum"},
{"header.maximum",
 "最大值",
 "Maximum"},
{"header.lower_whisker",
 "下须",
 "Lower whisker"},
{"header.upper_whisker",
 "上须",
 "Upper whisker"},
{"header.outlier_count",
 "异常点数",
 "Outlier count"},
{"plot.series.outliers",
 "异常点",
 "Outliers"},
{"diag.eda.four_plot_exploratory",
 "EDA 四图用于探索位置/散布/随机性/分布形态假设，不能写成过程受控或分布已正态。",
 "The EDA four-plot explores location / spread / randomness / shape hypotheses; it must not be written as process-in-control or as proven normality."},
{"diag.column_no_numeric_observations",
 "所选列没有数值观测。",
 "The selected column has no numeric observations."},
{"header.iteration_count",
 "迭代次数",
 "Iterations"},
{"header.chi_square",
 "卡方",
 "Chi-square"},
{"header.distribution",
 "分布",
 "Distribution"},
{"header.decision",
 "判定",
 "Decision"},
{"header.location_shape",
 "位置/形状",
 "Location / shape"},
{"header.scale",
 "尺度",
 "Scale"},
{"header.method_family",
 "方法族",
 "Method family"},
{"header.coverage",
 "覆盖率",
 "Coverage"},
{"header.target_confidence",
 "目标置信水平",
 "Target confidence"},
{"status.ad_reject_at_alpha",
 "在 alpha 下拒绝",
 "Reject at alpha"},
{"status.ad_fail_reject_at_alpha",
 "在 alpha 下未拒绝",
 "Fail to reject at alpha"},
{"param.summary.event_level_eq",
 "事件水平 = ",
 "Event level = "},
{"param.summary.predictor_variable_count_eq",
 "预测变量数 = ",
 "Predictor count = "},
{"param.summary.coverage_eq",
 "覆盖率 = ",
 "Coverage = "},
{"param.summary.direction_eq",
 "方向 = ",
 "Direction = "},
{"plot.series.fitted_line",
 "拟合线",
 "Fitted line"},
{"plot.series.selected_lambda",
 "选定 λ",
 "Selected λ"},
{"plot.series.suspect_observation",
 "嫌疑观测",
 "Suspect observation"},
{"plot.series.difference_zero",
 "差 = 0",
 "Difference = 0"},
{"diag.graph.need_xy",
 "请选择 X 变量和 Y 变量。",
 "Select an X variable and a Y variable."},
{"diag.graph.need_response_and_category",
 "请选择响应变量和分类变量。",
 "Select a response variable and a categorical variable."},
{"diag.graph.need_two_continuous",
 "请至少选择两个连续变量。",
 "Select at least two continuous variables."},
{"diag.graph.need_xy_size",
 "请选择 X、Y 和气泡大小变量。",
 "Select X, Y, and bubble-size variables."},
{"diag.graph.need_continuous",
 "请选择连续变量。",
 "Select a continuous variable."},
{"diag.graph.need_multi_or_heatmap_layout",
 "请选择多个连续变量，或行类别、列类别和数值。",
 "Select multiple continuous variables, or row category, column category, and values."},
{"diag.graph.need_numeric",
 "请选择数值变量。",
 "Select a numeric variable."},
{"diag.graph.need_xyz",
 "请选择 X、Y 和 Z 变量。",
 "Select X, Y, and Z variables."},
{"diag.graph.need_category",
 "请选择分类变量。",
 "Select a categorical variable."},
{"diag.graph.interval_no_valid_groups",
 "区间图没有可用于计算的有效分组。",
 "Interval plot has no valid groups for computation."},
{"diag.graph.negative_bubble_size",
 "气泡大小不能为负数。",
 "Bubble size cannot be negative."},
{"diag.graph.no_valid_bubbles",
 "气泡图没有可用于绘制的完整观测行。",
 "Bubble plot has no complete observation rows to plot."},
{"diag.graph.ecdf_need_one",
 "经验累积分布图至少需要一个有效观测。",
 "ECDF requires at least one valid observation."},
{"diag.graph.heatmap_no_valid_cells",
 "热图没有可用于聚合的完整观测。",
 "Heatmap has no complete observations to aggregate."},
{"diag.graph.duplicate_time",
 "存在重复时间点；图形按时间排序后保留全部观测。",
 "Duplicate time points; plot keeps all observations after sorting by time."},
{"diag.graph.irregular_interval",
 "时间间隔不规则；图形按时间排序，但不把间隔当作等距。",
 "Irregular time spacing; plot is time-sorted but intervals are not treated as uniform."},
{"diag.graph.time_series_need_two",
 "时间序列图至少需要两个有效观测。",
 "Time series plot requires at least two valid observations."},
{"diag.graph.contour_irregular_grid",
 "等值线图需要完整的规则 X/Y/Z 网格。",
 "Contour plot requires a complete regular X/Y/Z grid."},
{"diag.graph.negative_pie_weight",
 "饼图权重不能为负数。",
 "Pie weights cannot be negative."},
{"diag.graph.pie_zero_total",
 "饼图各类别合计必须大于 0。",
 "Pie category totals must be greater than 0."},
{"diag.graph.need_response",
 "请选择响应变量。",
 "Select a response variable."},
{"diag.graph.bar_hidden_excluded_distinct",
 "条形图显示计数省略 hidden；分析口径计数保留 hidden、仅省略 excluded。两者不得合并为一个 bool。",
 "Bar display counts omit hidden; analysis counts keep hidden and only omit excluded. Do not merge these into one bool."},
{"diag.row_visibility.contract",
 "hidden 只影响显示；excluded 影响分析输入。两者必须可区分。",
 "hidden affects display only; excluded affects analysis input. The two must remain distinguishable."},
{"diag.row_visibility.overlap",
 "存在同时标记为 hidden 与 excluded 的行；分析以 excluded 为准，显示同时不展示。禁止合并为一个 bool。",
 "Some rows are marked both hidden and excluded; analysis follows excluded and display hides both. Do not merge into one bool."},
{"param.summary.corr_heatmap_not_obs_layer",
 "相关矩阵热图单元格不是观测层；不伪造 per-cell member_source_rows",
 "Correlation-matrix heatmap cells are not an observation layer; do not invent per-cell member_source_rows"},
{"param.summary.corr_cell_not_obs_layer",
 "相关矩阵单元格不是观测层",
 "Correlation-matrix cells are not an observation layer"},
{"diag.corr.need_two_numeric",
 "请选择至少两列数值变量。",
 "Select at least two numeric columns."},
{"diag.ttest.need_hypothesized_mean",
 "请指定假设均值。",
 "Specify a hypothesized mean."},
{"diag.ztest.need_known_sigma",
 "请指定已知总体标准差 σ（必须为正）。",
 "Specify a known population standard deviation σ (must be positive)."},
{"diag.two_sample_t.need_two_columns",
 "请选择两列独立样本变量。",
 "Select two independent sample columns."},
{"diag.tost.need_two_independent",
 "请选择两列独立样本。",
 "Select two independent samples."},
{"diag.equiv.need_test_and_reference",
 "请选择检验列与参考列。",
 "Select a test column and a reference column."},
};

}  // namespace

void append_report_text_catalog_part2(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart2),
        std::end(kReportTextCatalogPart2));
}

}  // namespace datalab::domain
