#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart3[] = {
{"diag.paired.need_two_columns",
 "请选择两列配对测量值。",
 "Select two paired measurement columns."},
{"diag.one_prop.need_events_trials",
 "请选择事件数列和试验数列。",
 "Select an events column and a trials column."},
{"diag.two_prop.need_two_event_trial_pairs",
 "请选择两组事件数和试验数列。",
 "Select two pairs of events and trials columns."},
{"diag.regression.need_response_and_predictor",
 "请选择一个响应变量和至少一个预测变量。",
 "Select one response variable and at least one predictor."},
{"diag.one_prop.need_hypothesized_proportion",
 "请指定假设比例。",
 "Specify a hypothesized proportion."},
{"diag.poisson.need_count_column",
 "请选择缺陷计数列。",
 "Select a defect-count column."},
{"diag.poisson.need_length_or_const",
 "请选择观测长度列或输入观测长度常数。",
 "Select an observation-length column or enter a length constant."},
{"diag.poisson.need_hypothesized_rate",
 "请指定假设发生率。",
 "Specify a hypothesized rate."},
{"diag.two_poisson.need_count_length_pairs",
 "请选择两组缺陷计数和观测长度列。",
 "Select two pairs of defect-count and observation-length columns."},
{"diag.chi2.need_row_and_column",
 "请选择行分类列和列分类列。",
 "Select a row-category column and a column-category column."},
{"diag.gof.need_category_column",
 "请选择分类列。",
 "Select a category column."},
{"diag.variance.need_first_or_measure",
 "请选择第一样本列或测量列。",
 "Select the first-sample column or a measurement column."},
{"diag.column_insufficient_numeric",
 "所选列没有足够的数值观测。",
 "The selected column does not have enough numeric observations."},
{"diag.prop.no_complete_case_rows",
 "没有可用于比例检验的 complete-case 行。",
 "No complete-case rows are available for the proportion test."},
{"diag.prop.events_trials_nonneg_bounded",
 "事件数和试验数必须为非负整数，且事件数不能超过试验数。",
 "Events and trials must be non-negative integers, and events cannot exceed trials."},
{"diag.mann_whitney.need_exactly_two",
 "请选择正好两列独立样本。",
 "Select exactly two independent sample columns."},
{"diag.wilcoxon.need_one_or_paired",
 "请选择一列（相对 η0）或两列配对样本。",
 "Select one column (relative to η0) or two paired samples."},
{"diag.sign.need_one_or_paired",
 "请选择一列（单样本）或两列（配对）。",
 "Select one column (one-sample) or two columns (paired)."},
{"diag.runs.need_numeric_sequence",
 "请选择一列数值序列（按行序）。",
 "Select one numeric sequence column (in row order)."},
{"diag.fisher.need_exactly_two_categorical",
 "请选择正好两列分类变量以构建 2×2 表。",
 "Select exactly two categorical columns to build a 2×2 table."},
{"diag.mcnemar.need_exactly_two_paired_binary",
 "请选择正好两列配对二元结果。",
 "Select exactly two paired binary outcome columns."},
{"diag.cochran.need_at_least_two_paired_binary",
 "请选择至少两列配对二元结果（k≥3 才计算；k=2 请用 McNemar）。",
 "Select at least two paired binary outcome columns (computed only for k≥3; use McNemar when k=2)."},
{"diag.grouped.need_measure_and_group",
 "请选择测量列和分组列。",
 "Select a measurement column and a grouping column."},
{"diag.msa.need_measure_part_operator",
 "请选择测量值、零件和操作员列。",
 "Select measurement, part, and operator columns."},
{"diag.msa.need_expanded_factors",
 "请选择测量值、零件、操作员与附加因子列；无附加因子时请用交叉 Gage R&R。",
 "Select measurement, part, operator, and additional-factor columns; with no additional factors use crossed Gage R&R."},
{"diag.friedman.need_response_treatment_block",
 "请选择响应、处理与区组列。",
 "Select response, treatment, and block columns."},
{"diag.multivariate.need_two_numeric",
 "请至少选择两个数值变量列。",
 "Select at least two numeric variable columns."},
{"diag.ts.need_numeric_series",
 "请选择时间序列数值列。",
 "Select a time-series numeric column."},
{"diag.logistic.need_binary_response_and_predictor",
 "请选择二元响应列和至少一个预测变量。",
 "Select a binary response column and at least one predictor."},
{"diag.seasonal.need_series_and_period",
 "请选择时间序列值列并输入正整数季节周期。",
 "Select a time-series value column and enter a positive integer seasonal period."},
{"diag.rsm.need_response_and_two_factors",
 "请选择响应列与至少两个连续因子列。",
 "Select a response column and at least two continuous factor columns."},
{"diag.doe_opt.need_response_and_imported_factors",
 "请选择至少一个响应列和已导入因子列。",
 "Select at least one response column and imported factor columns."},
{"diag.reliability.need_lifetime_column",
 "请选择寿命列。",
 "Select a lifetime column."},
{"diag.reliability.need_event_or_censor_type",
 "请选择失效/删失指示列，或逐行删失类型列（exact/right/left/interval）。",
 "Select a failure/censoring indicator column, or a per-row censoring-type column (exact/right/left/interval)."},
{"diag.ts.need_one_numeric_series",
 "请选择一个数值序列列。",
 "Select one numeric series column."},
{"diag.msa.need_measure_part_operator_alt",
 "请选择测量值、部件和操作者列。",
 "Select measurement, part, and operator columns."},
{"diag.poisson_reg.need_count_response_and_predictor",
 "请选择计数响应列与至少一个数值预测列。",
 "Select a count-response column and at least one numeric predictor column."},
{"diag.cart.need_response_and_numeric_predictor",
 "请选择响应列与至少一个数值预测列。",
 "Select a response column and at least one numeric predictor column."},
{"diag.univariate.need_one_numeric",
 "请选择一个数值列。",
 "Select one numeric column."},
{"diag.ordinal.need_ordered_response_and_predictor",
 "请选择有序响应列与至少一个数值预测列。",
 "Select an ordinal response column and at least one numeric predictor column."},
{"diag.discriminant.need_class_response_and_predictor",
 "请选择类别响应与至少一个数值预测列。",
 "Select a class-response column and at least one numeric predictor column."},
{"diag.ts.need_two_numeric_series",
 "请选择两个数值序列列。",
 "Select two numeric series columns."},
{"diag.stepwise.need_response_and_two_candidates",
 "请选择响应列与至少两个候选预测列。",
 "Select a response column and at least two candidate predictor columns."},
{"diag.pb.need_factor_name",
 "请提供至少一个因子名称。",
 "Provide at least one factor name."},
{"diag.capability.need_lsl_or_usl",
 "请输入 LSL 或 USL。",
 "Enter an LSL or USL."},
{"diag.run_chart.need_individuals",
 "请选择一列数值观测（子组大小=1）。",
 "Select one numeric observation column (subgroup size = 1)."},
{"diag.oc.need_sample_size_n",
 "请指定样本量 n ≥ 1。",
 "Specify sample size n ≥ 1."},
{"diag.gof.need_nonneg_integer_counts",
 "请选择一列非负整数计数。",
 "Select one non-negative integer count column."},
{"param.summary.time_eq",
 "时间 = ",
 "Time = "},
{"param.summary.category_eq",
 "类别 = ",
 "Category = "},
{"param.summary.reference_eq",
 "参考值 = ",
 "Reference = "},
{"param.summary.process_variation_eq",
 "过程变差(6σ) = ",
 "Process variation (6σ) = "},
{"param.summary.lifetime_column_eq",
 "寿命列 = ",
 "Lifetime column = "},
{"param.summary.mode_eq",
 "模式 = ",
 "Mode = "},
{"param.summary.part_count_eq",
 "部件数 = ",
 "Part count = "},
{"param.summary.observation_count_eq",
 "观测数 = ",
 "Observation count = "},
{"param.summary.treatment_columns_eq",
 "处理列数 = ",
 "Treatment columns = "},
{"param.summary.value_column_eq",
 "值列 = ",
 "Value column = "},
{"param.summary.first_sample_eq",
 "第一样本 = ",
 "First sample = "},
{"param.summary.task_eq",
 "任务 = ",
 "Task = "},
{"param.summary.factors_eq",
 "因子 = ",
 "Factors = "},
{"param.summary.corr_color_range",
 "颜色范围固定为相关系数 [-1, 1]    方法 = ",
 "Color scale fixed to correlation [-1, 1]    Method = "},
{"param.summary.cell_group_mean",
 "单元格为组内均值",
 "Cells are within-group means"},
{"param.summary.area_not_ci",
 "面积表示相邻观测之间的数值区间，不是置信区间",
 "Area shows the numeric interval between adjacent observations, not a confidence interval"},
{"param.summary.target_eq",
 "目标 = ",
 "Target = "},
{"param.summary.category_column_colon",
 "类别列: ",
 "Category column: "},
{"param.summary.effect_colon",
 "效应: ",
 "Effect: "},
{"param.summary.model_eq",
 "模型 = ",
 "Model = "},
{"param.summary.binomial_oc",
 "二项 OC",
 "Binomial OC"},
{"param.summary.binomial_pbar_formula",
 "p̄ = Σ不合格品数 / Σ检验数",
 "p̄ = Σdefectives / Σinspections"},
{"param.summary.poisson_cbar_formula",
 "c̄ = 缺陷数均值",
 "c̄ = mean defect count"},
{"param.summary.poisson_ubar_formula",
 "ū = Σ缺陷数 / Σ单位数",
 "ū = Σdefects / Σunits"},
{"table.property", "属性", "Property"},
{"table.value", "值", "Value"},
{"table.warranty_summary", "保修摘要", "Warranty summary"},
{"table.weibull_params", "Weibull 参数", "Weibull parameters"},
{"table.weibull3_params", "三参数 Weibull 参数", "3-parameter Weibull parameters"},
{"table.lognormal_params", "Lognormal 参数", "Lognormal parameters"},
{"table.percentiles", "百分位寿命", "Percentile life"},
{"table.failure_modes", "失效模式（观测到的 exact 失效）",
 "Failure modes (observed exact failures)"},
{"table.km_summary", "Kaplan-Meier 摘要", "Kaplan-Meier summary"},
{"table.km_survival", "Kaplan-Meier 生存表", "Kaplan-Meier survival table"},
{"table.survival_estimates", "生存估计", "Survival estimates"},
{"table.mode_specific_reliability", "分模式可靠度（cause-specific）",
 "Mode-specific reliability (cause-specific)"},
{"table.cif_aalen_johansen", "累计发生函数 CIF（Aalen-Johansen）",
 "Cumulative incidence CIF (Aalen–Johansen)"},
{"table.fine_gray_multi", "Fine-Gray 子分布风险（多协变量）",
 "Fine-Gray subdistribution hazard (multi-covariate)"},
{"table.fine_gray_continuous", "Fine-Gray 子分布风险（连续协变量）",
 "Fine-Gray subdistribution hazard (continuous covariate)"},
{"table.fine_gray_binary", "Fine-Gray 子分布风险（二分类 group）",
 "Fine-Gray subdistribution hazard (binary group)"},
{"table.exponential_params", "Exponential 参数", "Exponential parameters"},
{"table.exponential2_params", "两参数指数参数", "2-parameter exponential parameters"},
{"table.lognormal3_params", "三参数对数正态参数", "3-parameter lognormal parameters"},
{"table.rsm_coefficients_coded", "系数（编码单位）", "Coefficients (coded units)"},
{"table.binomial_capability", "二项能力", "Binomial capability"},
{"table.poisson_capability", "泊松能力", "Poisson capability"},
{"table.laney_subgroup_stats", "Laney 图逐子组统计", "Laney chart subgroup statistics"},
{"table.zone_point_stats", "区域图逐点统计", "Zone chart point statistics"},
{"table.param_dist_compare", "参数分布比较", "Parametric distribution comparison"},
{"table.log_rank", "Log-rank 分组比较", "Log-rank group comparison"},
{"table.warranty_failure_mode_denominators", "失效模式分母追溯",
 "Failure-mode denominator trace"},
{"table.warranty_group_denominators", "分组分母追溯",
 "Group denominator trace"},
{"table.pure_error_lof", "纯误差与失拟", "Pure error and lack of fit"},
{"table.box_cox_capability", "变换后过程能力", "Capability after transform"},
{"table.box_cox_lambda", "Box-Cox λ 选择诊断", "Box-Cox λ selection diagnostic"},
{"plot.box_cox_lambda", "Box-Cox λ 选择诊断", "Box-Cox λ selection diagnostic"},
{"table.johnson_transform", "Johnson 变换", "Johnson transform"},
{"plot.johnson_transform", "Johnson 变换", "Johnson transform"},
{"plot.capability_histogram", "过程能力直方图", "Process capability histogram"},
{"table.doe_coefficients_effects",
 "系数与效应",
 "Coefficients and effects"},
{"table.doe_model_terms_blocks",
 "模型项与区组",
 "Model terms and blocks"},
{"table.doe_center_curvature",
 "中心点与曲率",
 "Center points and curvature"},
{"table.residual_diagnostics",
 "残差诊断",
 "Residual diagnostics"},
{"table.design_info",
 "设计信息",
 "Design information"},
{"table.design_generators",
 "设计生成器",
 "Design generators"},
{"table.defining_relation",
 "定义关系",
 "Defining relation"},
{"table.alias_structure",
 "别名结构",
 "Alias structure"},
{"table.design_matrix",
 "设计矩阵",
 "Design matrix"},
{"table.factor_definitions",
 "因素定义",
 "Factor definitions"},
{"table.plackett_burman_design",
 "Plackett–Burman 设计",
 "Plackett–Burman design"},
{"table.doe_response_analysis",
 "DOE 响应分析",
 "DOE response analysis"},
{"table.doe_response_optimization",
 "DOE 响应优化",
 "DOE response optimization"},
{"table.rsm_analysis",
 "响应曲面分析",
 "Response surface analysis"},
{"table.capability_normal",
 "正态过程能力分析",
 "Normal process capability"},
{"table.capability_johnson",
 "Johnson 变换过程能力",
 "Johnson-transform process capability"},
{"table.capability_nonnormal",
 "非正态过程能力",
 "Nonnormal process capability"},
{"table.capability_between_within",
 "组间/组内过程能力",
 "Between/within process capability"},
{"table.process_data",
 "过程数据",
 "Process Data"},
{"table.overall_capability",
 "总体能力",
 "Overall Capability"},
{"table.distribution_params",
 "分布参数",
 "Distribution parameters"},
{"table.capability_indices",
 "能力指数",
 "Capability indices"},
{"table.capability_sixpack",
 "过程能力 Sixpack",
 "Process capability Sixpack"},
{"table.imr_params",
 "I-MR 参数",
 "I-MR parameters"},
{"table.imrrs_params",
 "I-MR-R/S 参数",
 "I-MR-R/S parameters"},
{"table.suffix.method_and_params",
 " 方法与参数",
 " method and parameters"},
{"table.suffix.parameters",
 " 参数",
 " parameters"},
{"table.suffix.subgroup_statistics",
 "逐子组统计",
 " subgroup statistics"},
{"table.suffix.point_statistics",
 " 逐点统计",
 " point statistics"},
{"header.interval",
 "间隔",
 "Interval"},
{"status.direction.upper",
 "上侧",
 "Upper"},
{"status.direction.lower",
 "下侧",
 "Lower"},
{"status.none",
 "无",
 "None"},
{"diag.spc.stage_column_missing_labels",
 "阶段列存在缺失标签，请补齐原始数据。",
 "Stage column has missing labels; complete the source data."},
{"diag.spc.policy_minitab_like",
 "特殊原因策略=minitab_like：默认仅启用「%1」（与 Minitab 常见默认接近）。",
 "Special-cause policy=minitab_like: only enables '%1' by default (close to common Minitab default)."},
{"diag.spc.policy_all_applicable",
 "特殊原因策略=all_applicable：启用该图种全部适用特殊原因规则；多规则提高灵敏度也提高误报风险，与 Minitab 默认仅「%1」不同。",
 "Special-cause policy=all_applicable: enables all rules applicable to this chart type; more rules raise sensitivity and false-alarm risk, unlike Minitab default '%1' only."},
{"diag.spc.test_not_applicable",
 "已忽略不适用于此控制图的特殊原因规则：%1。",
 "Ignored special-cause rules not applicable to this chart type: %1."},
{"diag.msa.insufficient_replicates_part_r",
 "重复次数小于 2，无法绘制按零件 R 图。",
 "Replicate count < 2; cannot plot R chart by part."},
{"diag.msa.insufficient_replicates_operator_r",
 "重复次数小于 2，无法绘制按操作者 R 图。",
 "Replicate count < 2; cannot plot R chart by operator."},
{"diag.reliability.two_param_weibull_hint",
 "当前为二参数 Weibull。含阈值的三参数模型请选择 model=weibull3。",
 "Using 2-parameter Weibull; for a threshold model select model=weibull3."},
{"diag.reliability.one_param_exponential_hint",
 "当前为一参数指数。含阈值的两参数模型请选择 model=exponential2。",
 "Using 1-parameter exponential; for a threshold model select model=exponential2."},
{"diag.reliability.two_param_lognormal_hint",
 "当前为二参数对数正态。含阈值的三参数模型请选择 model=lognormal3。",
 "Using 2-parameter lognormal; for a threshold model select model=lognormal3."},
{"diag.power.target_not_in_01",
 "目标功效必须位于 0 和 1 之间。",
 "Target power must be between 0 and 1."},
{"diag.power.max_sample_cannot_reach_target",
 "在允许的最大样本量内无法达到目标功效。",
 "Target power cannot be reached within the allowed maximum sample size."},
{"diag.power.max_replicate_cannot_reach_target",
 "在允许的最大重复数内无法达到目标功效。",
 "Target power cannot be reached within the allowed maximum replicates."},
{"diag.power.howe_k_exceeds_limit_at_max_n",
 "在允许的最大 n 内 Howe k 仍大于目标上限。",
 "Howe k still exceeds the target upper limit within the allowed maximum n."},
{"diag.time_series.no_valid_observations",
 "时间序列没有有效数值观测。",
 "Time series has no valid numeric observations."},
{"diag.time_series.single_exp_invalid",
 "单指数平滑要求至少两个观测、alpha 位于 (0,1] 且预测期数大于 0。",
 "Single exponential smoothing requires at least two observations, alpha in (0, 1], and forecast periods > 0."},
{"diag.time_series.double_exp_invalid",
 "双指数平滑要求至少三个观测，alpha/gamma 位于 (0,1] 且预测期数大于 0。",
 "Double exponential smoothing requires at least three observations, alpha/gamma in (0, 1], and forecast periods > 0."},
{"diag.normality.need_one_valid",
 "正态性检验需要至少一个有效数值观测。",
 "Normality test requires at least one valid numeric observation."},
{"diag.normality.need_two_obs_prob_only",
 "正态性检验至少需要 2 个观测；当前仅返回概率图点。",
 "Normality test requires at least 2 observations; only probability-plot points are returned."},
{"diag.normality.zero_variance",
 "常量样本无法计算正态性检验统计量。",
 "Constant sample; normality test statistic cannot be computed."},
{"diag.normality.need_three_valid",
 "正态性检验至少需要 3 个有效观测；n<3 时不计算统计量与 p 值。",
 "Normality test requires at least 3 valid observations; statistics and p-value are not computed when n<3."},
};

}  // namespace

void append_report_text_catalog_part3(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart3),
        std::end(kReportTextCatalogPart3));
}

}  // namespace datalab::domain
