#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart6[] = {
{"table.correlation_matrix",
 "相关系数矩阵",
 "Correlation matrix"},
{"table.covariance_matrix",
 "协方差矩阵",
 "Covariance matrix"},
{"table.partial_correlation_matrix",
 "偏相关系数矩阵",
 "Partial correlation matrix"},
{"table.correlation_details",
 "相关分析详细结果",
 "Correlation analysis details"},
{"table.doe_response_objectives",
 "响应目标",
 "Response objectives"},
{"table.doe_best_combination",
 "最佳组合",
 "Best combination"},
{"table.doe_candidate_combinations",
 "候选组合",
 "Candidate combinations"},
{"table.doe_response_predictions",
 "响应预测",
 "Response predictions"},
{"plot.doe_overall_desirability",
 "候选组合总体 Desirability",
 "Overall desirability of candidates"},
{"table.factor_means",
 "因子均值",
 "Factor means"},
{"table.cell_means",
 "单元均值",
 "Cell means"},
{"table.variability_cell_stats",
 "单元统计",
 "Cell statistics"},
{"plot.mean_and_range",
 "均值与极差",
 "Mean and range"},
{"plot.stdev_chart",
 "标准差图",
 "Standard deviation chart"},
{"plot.capability_chart",
 "能力图",
 "Capability chart"},
{"table.eda_four_plot_notes",
 "四图说明",
 "Four-plot notes"},
{"table.box_plot_stats",
 "箱线统计",
 "Boxplot statistics"},
{"table.cause_effect_structure",
 "结构摘要",
 "Structure summary"},
{"table.runs_about_median",
 "关于中位数的游程",
 "Runs about the median"},
{"table.runs_up_down",
 "上升/下降游程",
 "Runs up/down"},
{"table.zone_params",
 "区域图参数",
 "Zone chart parameters"},
{"plot.zone_cumulative_score",
 "区域累计得分",
 "Zone cumulative score"},
{"table.gv_summary",
 "广义方差摘要",
 "Generalized variance summary"},
{"table.gv_subgroup_s",
 "逐子组 |S|",
 "Subgroup |S|"},
{"plot.gv_s_chart",
 "广义方差 |S| 图",
 "Generalized variance |S| chart"},
{"table.t2_summary",
 "T² 摘要",
 "T² summary"},
{"table.t2_pointwise",
 "逐点 T²",
 "Pointwise T²"},
{"table.mewma_t2_pointwise",
 "逐点 MEWMA T²",
 "Pointwise MEWMA T²"},
{"table.mann_whitney_rank_sum",
 "秩和检验",
 "Rank-sum test"},
{"table.wilcoxon_signed_rank",
 "符号秩检验",
 "Signed-rank test"},
{"table.walsh_location",
 "位置估计（Walsh）",
 "Location estimate (Walsh)"},
{"table.sign_summary",
 "符号摘要",
 "Sign summary"},
{"table.median_ci",
 "中位数置信区间",
 "Median confidence interval"},
{"table.comparison_criterion",
 "比较准则",
 "Comparison criterion"},
{"table.runs_test",
 "Runs检验",
 "Runs test"},
{"table.fisher_exact",
 "Fisher精确检验",
 "Fisher exact test"},
{"table.crosstab_2x2",
 "2×2 交叉表",
 "2×2 crosstab"},
{"table.treatment_success_counts",
 "处理成功计数",
 "Treatment success counts"},
{"table.treatment_positive_rates",
 "各处理阳性率",
 "Positive rate by treatment"},
{"table.groups_above_below",
 "各组 Above/Below",
 "Groups above/below"},
{"table.kruskal_wallis_results",
 "Kruskal-Wallis 结果",
 "Kruskal–Wallis results"},
{"table.test_statistic",
 "检验统计量",
 "Test statistic"},
{"table.treatment_summary",
 "处理摘要",
 "Treatment summary"},
{"table.nemenyi_pairwise",
 "Nemenyi 成对比较",
 "Nemenyi pairwise comparisons"},
{"table.steel_dwass_pairwise",
 "Steel-Dwass 成对比较",
 "Steel-Dwass pairwise comparisons"},
{"table.dunn_pairwise",
 "Dunn 成对比较",
 "Dunn pairwise comparisons"},
{"header.nonzero_diff_n",
 "非零差值 N",
 "Nonzero differences N"},
{"header.positive_rank_sum",
 "正秩和",
 "Positive rank sum"},
{"header.negative_rank_sum",
 "负秩和",
 "Negative rank sum"},
{"header.estimated_median",
 "估计中位数",
 "Estimated median"},
{"header.valid_signs_n",
 "有效符号 N",
 "Valid signs N"},
{"header.tie_count",
 "结数",
 "Ties"},
{"header.sample_median",
 "样本中位数",
 "Sample median"},
{"header.hypothesized_median_eta0",
 "假设中位数 η0",
 "Hypothesized median η0"},
{"header.nominal_confidence",
 "名义置信水平",
 "Nominal confidence level"},
{"header.attained_level",
 "达到水平",
 "Attained level"},
{"header.criterion",
 "准则",
 "Criterion"},
{"header.approximation",
 "近似",
 "Approximation"},
{"header.success_count",
 "成功数",
 "Successes"},
{"header.success_rate",
 "成功率",
 "Success rate"},
{"header.overall_median_m",
 "总体中位数 M",
 "Overall median M"},
{"header.median",
 "中位数",
 "Median"},
{"header.adjusted_h",
 "调整后 H",
 "Adjusted H"},
{"header.adjusted_s",
 "调整后 S",
 "Adjusted S"},
{"header.block_count",
 "区组数",
 "Blocks"},
{"header.treatment_count",
 "处理数",
 "Treatments"},
{"plot.suffix.runs_series",
 " 游程序列图",
 "Runs series plot"},
{"table.aa_within_evaluator",
 "评估者内一致性",
 "Within-evaluator agreement"},
{"table.aa_between_evaluator",
 "评估者间一致性",
 "Between-evaluator agreement"},
{"table.aa_overall_fleiss_kappa",
 "评估者间总体 Kappa（Fleiss）",
 "Overall between-evaluator Kappa (Fleiss)"},
{"table.aa_between_kendall_w",
 "评估者间 Kendall W",
 "Between-evaluator Kendall W"},
{"table.aa_within_kendall_w",
 "评估者内 Kendall W",
 "Within-evaluator Kendall W"},
{"table.aa_evaluator_vs_standard_kendall_tau",
 "评估者 vs 标准 Kendall τ",
 "Evaluator vs standard Kendall τ"},
{"table.aa_all_vs_standard_kendall_tau",
 "全体 vs 标准 Kendall τ",
 "All vs standard Kendall τ"},
{"table.aa_evaluator_part_agreement",
 "评估者×零件一致率",
 "Evaluator × part agreement rate"},
{"table.aa_evaluator_agreement_rate",
 "评估者一致率",
 "Evaluator agreement rate"},
{"header.first_group_n",
 "第一组 N",
 "First group N"},
{"header.second_group_n",
 "第二组 N",
 "Second group N"},
{"header.rank_sum",
 "秩和",
 "Rank sum"},
{"header.location_difference",
 "位置差异",
 "Location difference"},
{"header.continuity_correction",
 "连续性修正",
 "Continuity correction"},
{"header.approximation_method",
 "近似方法",
 "Approximation method"},
{"header.small_sample_warning",
 "小样本警告",
 "Small-sample warning"},
{"header.effect_size",
 "效应量",
 "Effect size"},
{"status.yes",
 "是",
 "Yes"},
{"status.no",
 "否",
 "No"},
{"plot.axis.positive_rate",
 "阳性率",
 "Positive rate"},
{"plot.axis.evaluator",
 "评估者",
 "Evaluator"},
{"param.summary.evaluator_count_eq",
 "评估者数 = ",
 "Evaluators = "},
{"param.summary.kappa_weight_eq",
 "Kappa权重 = ",
 "Kappa weight = "},
{"plot.residual_vs_fitted",
 "残差与拟合值",
 "Residuals vs fits"},
{"plot.residual_vs_order",
 "残差与观测顺序",
 "Residuals vs observation order"},
{"plot.residual_normal_probability",
 "残差正态概率图",
 "Residual normal probability plot"},
{"plot.residual_histogram",
 "残差直方图",
 "Residual histogram"},
{"plot.normal_probability",
 "正态概率图",
 "Normal probability plot"},
{"plot.transformed_normal_probability",
 "变换后正态概率图",
 "Transformed normal probability plot"},
{"plot.boxplot",
 "箱线图",
 "Boxplot"},
{"plot.individual_value",
 "个体值图",
 "Individual value plot"},
{"plot.interval_plot",
 "区间图",
 "Interval plot"},
{"plot.imr_chart",
 "I-MR 控制图",
 "I-MR control chart"},
{"plot.xbar_r_chart",
 "Xbar-R 控制图",
 "Xbar-R control chart"},
{"plot.xbar_s_chart",
 "Xbar-S 控制图",
 "Xbar-S control chart"},
{"plot.ewma_chart",
 "EWMA 控制图",
 "EWMA control chart"},
{"plot.cusum_chart",
 "CUSUM 控制图",
 "CUSUM control chart"},
{"plot.z_mr_chart",
 "Z-MR 控制图",
 "Z-MR control chart"},
{"plot.p_chart",
 "P 图",
 "P chart"},
{"plot.np_chart",
 "NP 图",
 "NP chart"},
{"plot.c_chart",
 "C 图",
 "C chart"},
{"plot.u_chart",
 "U 图",
 "U chart"},
{"plot.individuals_i",
 "单值图 (I)",
 "Individuals chart (I)"},
{"plot.moving_range_mr",
 "移动极差图 (MR)",
 "Moving range chart (MR)"},
{"plot.i_chart",
 "I 图",
 "I chart"},
{"plot.mr_chart",
 "MR 图",
 "MR chart"},
{"plot.r_chart",
 "R 图",
 "R chart"},
{"plot.s_chart",
 "S 图",
 "S chart"},
{"plot.xbar_chart",
 "Xbar 图",
 "Xbar chart"},
{"plot.i_chart_subgroup_mean",
 "I 图（子组均值）",
 "I chart (subgroup mean)"},
{"plot.g_chart",
 "G 图",
 "G chart"},
{"plot.g_chart_geometric",
 "G 图（几何间隔）",
 "G chart (geometric interval)"},
{"plot.t_chart",
 "T 图",
 "T chart"},
{"plot.t_chart_time",
 "T 图（时间间隔）",
 "T chart (time interval)"},
{"plot.fitted_line",
 "拟合线图",
 "Fitted line plot"},
{"plot.matrix_scatter",
 "矩阵散点图",
 "Matrix scatterplot"},
{"plot.histogram",
 "直方图",
 "Histogram"},
{"plot.run_chart",
 "运行图",
 "Run chart"},
{"plot.zone_chart",
 "区域图",
 "Zone chart"},
{"plot.pareto",
 "柏拉图",
 "Pareto chart"},
{"plot.paired_measurement_scatter",
 "配对测量散点图",
 "Paired-measurement scatterplot"},
{"plot.residual_vs_predictor",
 "残差与预测变量",
 "Residuals vs predictor"},
{"plot.observed_count_heatmap",
 "观察频数热图",
 "Observed-count heatmap"},
{"plot.adjusted_residual_heatmap",
 "调整残差热图",
 "Adjusted-residual heatmap"},
{"plot.gage_run_chart",
 "Gage Run Chart",
 "Gage Run Chart"},
{"plot.equivalence_interval",
 "等价性区间",
 "Equivalence interval"},
{"plot.observed_expected",
 "观察与期望",
 "Observed and expected"},
{"plot.hotelling_t2",
 "Hotelling T² 图",
 "Hotelling T² chart"},
{"plot.mewma_t2",
 "MEWMA T² 图",
 "MEWMA T² chart"},
{"plot.isolation_score",
 "Isolation 分数",
 "Isolation scores"},
{"plot.gage_stability_run",
 "Gage Stability Run Chart",
 "Gage Stability Run Chart"},
{"plot.bias_versus_reference",
 "Bias versus Reference",
 "Bias versus Reference"},
{"plot.doe_main_effects",
 "主效应图",
 "Main effects plot"},
{"plot.doe_interaction",
 "交互作用图",
 "Interaction plot"},
{"plot.doe_cube",
 "立方图",
 "Cube plot"},
{"plot.doe_cube_square",
 "立方图（方形）",
 "Cube plot (square)"},
{"plot.effects_pareto",
 "效应 Pareto",
 "Effects Pareto"},
{"plot.standardized_effects_pareto",
 "标准化效应 Pareto",
 "Standardized effects Pareto"},
{"plot.contour",
 "等值线图",
 "Contour plot"},
{"plot.response_surface",
 "响应曲面图",
 "Response surface plot"},
{"plot.rsm_static_surface",
 "静态响应曲面图（非可旋转 3D）",
 "Static response surface (non-rotatable 3D)"},
{"plot.msa_components_contribution",
 "方差分量 %Contribution",
 "Variance components %Contribution"},
{"plot.msa_components_study_var",
 "方差分量 %Study Var",
 "Variance components %Study Var"},
{"plot.msa_components_tolerance",
 "方差分量 %Tolerance",
 "Variance components %Tolerance"},
{"plot.msa_by_part",
 "按零件",
 "By part"},
{"plot.msa_operator_part_interaction",
 "操作者×零件交互",
 "Operator × part interaction"},
{"plot.type1_gage_histogram",
 "Type 1 Gage 直方图",
 "Type 1 Gage histogram"},
{"plot.laney_p_chart",
 "Laney P' 图",
 "Laney P' chart"},
{"plot.laney_u_chart",
 "Laney U' 图",
 "Laney U' chart"},
{"plot.sixpack_last_25_subgroups",
 "最后 25 个子组",
 "Last 25 subgroups"},
{"plot.sixpack_last_25_observations",
 "最近 25 个观测",
 "Last 25 observations"},
{"plot.normal_probability_before_transform",
 "变换前正态概率图",
 "Normal probability plot before transform"},
{"plot.km_survival_curve",
 "Kaplan-Meier 生存曲线",
 "Kaplan-Meier survival curve"},
};

}  // namespace

void append_report_text_catalog_part6(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart6),
        std::end(kReportTextCatalogPart6));
}

}  // namespace datalab::domain
