#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart5[] = {
{"table.xbar_s_params",
 "Xbar-S 参数",
 "Xbar-S parameters"},
{"table.xbar_s_chart",
 "Xbar-S 控制图",
 "Xbar-S control chart"},
{"table.xbar_s_subgroup_stats",
 "Xbar-S 逐子组统计",
 "Xbar-S subgroup statistics"},
{"table.ewma_params",
 "EWMA 参数",
 "EWMA parameters"},
{"table.ewma_chart",
 "EWMA 控制图",
 "EWMA control chart"},
{"table.ewma_point_stats",
 "EWMA 逐点统计",
 "EWMA point statistics"},
{"table.cusum_params",
 "CUSUM 参数",
 "CUSUM parameters"},
{"table.cusum_chart",
 "CUSUM 控制图",
 "CUSUM control chart"},
{"table.cusum_point_stats",
 "CUSUM 逐点统计",
 "CUSUM point statistics"},
{"table.cusum_signals",
 "CUSUM 信号",
 "CUSUM signals"},
{"table.z_mr_params",
 "Z-MR 参数",
 "Z-MR parameters"},
{"table.z_mr_chart",
 "Z-MR 控制图",
 "Z-MR control chart"},
{"table.z_mr_point_stats",
 "Z-MR 逐点统计",
 "Z-MR point statistics"},
{"table.ma_params",
 "移动平均参数",
 "Moving-average parameters"},
{"table.ma_chart",
 "移动平均控制图",
 "Moving-average control chart"},
{"table.ma_point_stats",
 "移动平均逐点统计",
 "Moving-average point statistics"},
{"table.spc_historical_stage",
 "历史参数与分阶段估计",
 "Historical parameters and stage estimates"},
{"table.rule_evidence",
 "规则证据",
 "Rule evidence"},
{"table.special_cause_rule_evidence",
 "特殊原因规则证据",
 "Special-cause rule evidence"},
{"table.doe_anova",
 "DOE ANOVA",
 "DOE ANOVA"},
{"table.two_sample_descriptive",
 "双样本描述统计",
 "Two-sample descriptive statistics"},
{"table.test_results",
 "检验结果",
 "Test results"},
{"table.observed_counts",
 "观察频数",
 "Observed counts"},
{"table.chi_square_test",
 "卡方检验",
 "Chi-square test"},
{"table.cell_statistics",
 "单元格统计",
 "Cell statistics"},
{"table.grouping_information",
 "Grouping Information",
 "Grouping Information"},
{"table.grouping_information_nemenyi",
 "Grouping Information (Nemenyi)",
 "Grouping Information (Nemenyi)"},
{"table.durbin_watson",
 "Durbin-Watson",
 "Durbin-Watson"},
{"table.assumption_checks",
 "假设检查",
 "Assumption checks"},
{"table.fit_diagnostics",
 "拟合与诊断",
 "Fits and diagnostics"},
{"table.paired_difference_stats",
 "配对差值统计",
 "Paired-difference statistics"},
{"table.equivalence_interval",
 "等价性区间",
 "Equivalence interval"},
{"table.transform_parameters",
 "变换参数",
 "Transform parameters"},
{"table.observed_expected",
 "观察与期望",
 "Observed and expected"},
{"table.one_proportion_descriptive",
 "单比例描述",
 "One-proportion descriptive"},
{"table.poisson_rate_descriptive",
 "泊松率描述",
 "Poisson-rate descriptive"},
{"table.two_poisson_rate_descriptive",
 "双样本泊松率描述",
 "Two-sample Poisson-rate descriptive"},
{"table.mewma_summary",
 "MEWMA 摘要",
 "MEWMA summary"},
{"table.nested_gage_rr_anova",
 "Nested Gage R&R ANOVA",
 "Nested Gage R&R ANOVA"},
{"table.gage_rr_summary",
 "Gage R&R 摘要",
 "Gage R&R summary"},
{"table.gage_rr_anova",
 "Gage R&R 方差分析",
 "Gage R&R ANOVA"},
{"table.emp_stats",
 "EMP 统计",
 "EMP statistics"},
{"table.type1_gage_results",
 "Type 1 Gage 结果",
 "Type 1 Gage results"},
{"table.stability_stats",
 "Stability 统计",
 "Stability statistics"},
{"table.variance_components",
 "方差分量",
 "Variance components"},
{"table.oneway_anova",
 "单因素 ANOVA",
 "One-way ANOVA"},
{"table.group_means",
 "组均值",
 "Group means"},
{"table.adf_test",
 "ADF 检验",
 "ADF test"},
{"table.adf_coefficients",
 "ADF 回归系数",
 "ADF regression coefficients"},
{"table.fitted_pearson_residuals",
 "拟合与 Pearson 残差",
 "Fitted and Pearson residuals"},
{"table.anomaly_scores",
 "异常分数",
 "Anomaly scores"},
{"table.bootstrap_summary",
 "Bootstrap 摘要",
 "Bootstrap summary"},
{"table.hclust_merge_history",
 "合并历程",
 "Merge history"},
{"table.hclust_cut_assignment",
 "簇分配（切 k）",
 "Cluster assignment (cut k)"},
{"table.ordinal_thresholds_slopes",
 "系数（阈值与斜率）",
 "Coefficients (thresholds and slopes)"},
{"table.lda_class_means",
 "类均值",
 "Class means"},
{"plot.observed_vs_fitted",
 "观测 vs 拟合",
 "Observed vs fitted"},
{"plot.series_index",
 "序列",
 "Series"},
{"plot.fitted_vs_pearson",
 "拟合 vs Pearson 残差",
 "Fitted vs Pearson residual"},
{"plot.bootstrap_mean_dist",
 "Bootstrap 均值分布",
 "Bootstrap mean distribution"},
{"plot.hclust_scatter_first_two",
 "层次聚类散点（前两列）",
 "Hierarchical cluster scatter (first two columns)"},
{"plot.lda_projection",
 "LD 投影（示意）",
 "LD projection (schematic)"},
{"plot.correlation_heatmap",
 "相关热图",
 "Correlation heatmap"},
{"plot.axis.fitted_short",
 "拟合",
 "Fitted"},
{"plot.series.upper_confidence_limit",
 "上置信限",
 "Upper confidence limit"},
{"plot.series.lower_confidence_limit",
 "下置信限",
 "Lower confidence limit"},
{"header.iterations",
 "迭代",
 "Iterations"},
{"header.converged",
 "收敛",
 "Converged"},
{"param.summary.regression_eq",
 "回归 = ",
 "Regression = "},
{"param.summary.predictor_count_eq",
 "预测变量 = ",
 "Predictors = "},
{"param.summary.link_eq",
 "链 = ",
 "Link = "},
{"param.summary.anomaly_count_eq",
 "异常数 = ",
 "Anomalies = "},
{"param.summary.class_count_eq",
 "类数 = ",
 "Classes = "},
{"param.summary.accuracy_approx_eq",
 "准确率 ≈ ",
 "Accuracy ≈ "},
{"param.summary.level_count_eq",
 "水平 = ",
 "Levels = "},
{"table.anova_table",
 "方差分析",
 "Analysis of variance"},
{"table.anova_effects_table",
 "ANOVA 表",
 "ANOVA table"},
{"table.variance_components_crossed_anova",
 "方差分量（交叉 ANOVA）",
 "Variance components (crossed ANOVA)"},
{"table.factor_a_means",
 "因子 A 均值",
 "Factor A means"},
{"table.factor_b_means",
 "因子 B 均值",
 "Factor B means"},
{"table.goodness_of_fit",
 "拟合优度",
 "Goodness of fit"},
{"table.coefficients_and_odds_ratio",
 "系数与 Odds Ratio",
 "Coefficients and odds ratios"},
{"table.fitted_and_residuals",
 "拟合与残差",
 "Fitted values and residuals"},
{"table.parameter_estimates",
 "参数估计",
 "Parameter estimates"},
{"table.variance_test_results",
 "方差检验结果",
 "Variance test results"},
{"table.km_interval_summary",
 "摘要",
 "Summary"},
{"table.imr_rs_subgroup_stats",
 "I-MR-R/S 逐子组统计",
 "I-MR-R/S subgroup statistics"},
{"table.defect_counts",
 "缺陷计数",
 "Defect counts"},
{"table.poisson_parameters",
 "泊松参数",
 "Poisson parameters"},
{"plot.diff_confidence_interval",
 "差值置信区间",
 "Difference confidence interval"},
{"plot.rate_ratio_confidence_interval",
 "率比置信区间",
 "Rate-ratio confidence interval"},
{"plot.predicted_probability",
 "预测概率",
 "Predicted probability"},
{"plot.tolerance_interval_histogram",
 "容差区间直方图",
 "Tolerance-interval histogram"},
{"plot.suffix.pareto_of",
 " 的 Pareto 图",
 "Pareto chart"},
{"plot.suffix.normal_probability_of",
 " 的正态概率图",
 "Normal probability plot"},
{"plot.suffix.histogram_of",
 " 的直方图",
 "Histogram"},
{"plot.suffix.individual_value_of",
 " 的个体值图",
 "Individual value plot"},
{"plot.suffix.scatter_of",
 " 的散点图",
 "Scatterplot"},
{"plot.suffix.run_chart",
 " 运行图",
 "Run chart"},
{"plot.infix.and",
 " 与 ",
 " and "},
{"plot.series.suspect_point",
 "嫌疑点",
 "Suspect point"},
{"header.truncated_flag",
 "截断",
 "Truncated"},
{"header.n_optional",
 "N（可选）",
 "N (optional)"},
{"plot.axis.factor_1",
 "因子 1",
 "Factor 1"},
{"param.summary.treatment_eq",
 "处理 = ",
 "Treatment = "},
{"param.summary.block_eq",
 "区组 = ",
 "Block = "},
{"param.summary.missing_eq",
 "缺失 = ",
 "Missing = "},
{"param.summary.forecast_periods_eq",
 "预测期数 = ",
 "Forecast periods = "},
{"param.summary.factor_a_eq",
 "因子 A = ",
 "Factor A = "},
{"param.summary.factor_b_eq",
 "因子 B = ",
 "Factor B = "},
{"param.summary.moving_range_length_eq",
 "移动极差长度 = ",
 "Moving-range length = "},
{"param.summary.normal_prob_corr_eq",
 "正态概率图相关系数 = ",
 "Normal probability plot correlation = "},
{"param.summary.proportion_eq",
 "比例 = ",
 "Proportion = "},
{"param.summary.group_count_eq",
 "组数 = ",
 "Group count = "},
{"param.summary.iterations_eq",
 "迭代 = ",
 "Iterations = "},
{"param.summary.standardized_flag",
 "标准化",
 "standardized"},
{"param.summary.median_eq",
 "中位数 = ",
 "Median = "},
{"param.summary.overall_median_m_eq",
 "；总体中位数 M = ",
 "; overall median M = "},
{"param.summary.emp_wheeler_note",
 "（Wheeler EMP；非全量 Expanded Gage）",
 "(Wheeler EMP; not full Expanded Gage)"},
{"param.summary.part_operator_slash",
 "零件 / 操作员 / ",
 "Part / Operator / "},
{"param.summary.expanded_gage_balanced_note",
 "（平衡三因子随机；非全量 GLM）",
 "(balanced 3-factor random; not full GLM)"},
{"param.summary.error_model_eq",
 "误差模型 = ",
 "Error model = "},
{"param.summary.trend_model_eq",
 "趋势模型 = ",
 "Trend model = "},
{"param.summary.info_paren",
 "（信息）",
 " (info)"},
{"param.summary.manual_bins_prefix",
 "手工 ",
 "Manual "},
{"diag.attr.need_units_column_suffix",
 "需要单位数列。",
 " requires a units column."},
{"diag.attr.laney_u_need_units",
 "Laney U' 图需要单位数列。",
 "Laney U' chart requires a units column."},
{"interp.doe_fractional_resolution",
 "部分析因分辨度 %1（字长最短非 I 词）。",
 "Fractional factorial resolution %1 (shortest non-I word length)."},
{"interp.fisher_need_2x2_levels",
 "Fisher 精确检验要求恰好 2×2 水平；当前行水平数 = %1，列水平数 = %2。",
 "Fisher exact test requires exactly 2×2 levels; current row levels = %1, column levels = %2."},
{"plot.axis.rate_ratio",
 "率比",
 "Rate ratio"},
{"plot.axis.event_probability",
 "事件概率",
 "Event probability"},
{"plot.axis.category",
 "类别",
 "Category"},
{"plot.axis.category_index",
 "类别序号",
 "Category index"},
{"plot.axis.standardized_transform_sd",
 "标准化变换 SD",
 "Standardized transformed SD"},
{"plot.axis.transformed_value",
 "变换值",
 "Transformed value"},
{"plot.axis.candidate_rank",
 "候选排序",
 "Candidate rank"},
{"plot.axis.measurement_index",
 "测量序号",
 "Measurement index"},
{"plot.axis.cause_count",
 "原因数",
 "Number of causes"},
{"header.overall_desirability_d",
 "总体 D",
 "Overall D"},
{"header.group_count",
 "组数",
 "Number of groups"},
{"header.test_name",
 "检验",
 "Test"},
{"table.tukey_comparisons",
 "Tukey 同时比较",
 "Tukey simultaneous comparisons"},
{"table.tukey_diff_intervals",
 "Tukey 差值同时区间",
 "Tukey difference simultaneous intervals"},
{"table.interval_plot_table",
 "区间图",
 "Interval plot"},
{"table.linear_regression",
 "线性回归",
 "Linear regression"},
{"table.model_summary",
 "模型摘要",
 "Model summary"},
{"table.coefficients",
 "系数",
 "Coefficients"},
{"table.regression_anova",
 "回归方差分析",
 "Regression ANOVA"},
{"table.unusual_observations",
 "异常观测",
 "Unusual observations"},
{"table.normality_test",
 "正态性检验",
 "Normality test"},
{"table.outlier_test",
 "异常值检验",
 "Outlier test"},
{"table.descriptive_stats",
 "描述统计",
 "Descriptive statistics"},
{"table.display_descriptive_stats",
 "显示描述性统计",
 "Display descriptive statistics"},
{"table.method",
 "方法",
 "Method"},
{"table.confidence_interval",
 "置信区间",
 "Confidence interval"},
{"table.equivalence_test",
 "等价性检验",
 "Equivalence test"},
{"table.one_sample_t",
 "单样本 t 检验",
 "One-sample t-test"},
{"table.one_sample_z",
 "单样本 Z 检验",
 "One-sample Z-test"},
{"table.two_sample_t",
 "双样本 t 检验",
 "Two-sample t-test"},
{"table.paired_t",
 "配对 t 检验",
 "Paired t-test"},
};

}  // namespace

void append_report_text_catalog_part5(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart5),
        std::end(kReportTextCatalogPart5));
}

}  // namespace datalab::domain
