#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart9[] = {
{"page.crosstab",
 "交叉表",
 "Crosstabulation"},
{"page.chi_square_gof",
 "卡方拟合优度",
 "Chi-square goodness of fit"},
{"page.poisson_gof",
 "泊松拟合优度",
 "Poisson goodness of fit"},
{"page.box_cox",
 "Box-Cox 变换",
 "Box-Cox transformation"},
{"page.twoway_anova",
 "双因素 ANOVA",
 "Two-way ANOVA"},
{"page.variance_test",
 "方差检验",
 "Test for equal variances"},
{"page.tolerance_normal",
 "正态容差区间",
 "Normal tolerance interval"},
{"page.tolerance_nonparametric",
 "非参数容差区间",
 "Nonparametric tolerance interval"},
{"page.t_power_sample_size",
 "T 功效与样本量",
 "t power and sample size"},
{"page.distribution_id",
 "个体分布识别",
 "Individual distribution identification"},
{"page.anom",
 "均值分析 (ANOM)",
 "Analysis of means (ANOM)"},
{"page.attribute_sampling",
 "属性一次抽样",
 "Attribute single sampling"},
{"page.attribute_agreement",
 "属性一致性分析",
 "Attribute agreement analysis"},
{"page.mann_whitney",
 "Mann-Whitney 检验",
 "Mann-Whitney test"},
{"page.wilcoxon_signed_rank",
 "Wilcoxon 符号秩检验",
 "Wilcoxon signed-rank test"},
{"page.sign_test",
 "符号检验",
 "Sign test"},
{"page.runs_test",
 "游程检验",
 "Runs test"},
{"page.fisher_exact",
 "Fisher 精确检验",
 "Fisher exact test"},
{"page.mcnemar",
 "McNemar 检验",
 "McNemar test"},
{"page.cochran_q",
 "Cochran Q 检验",
 "Cochran Q test"},
{"page.mood_median",
 "Mood 中位数检验",
 "Mood median test"},
{"page.kruskal_wallis",
 "Kruskal-Wallis 检验",
 "Kruskal-Wallis test"},
{"page.friedman",
 "Friedman 检验",
 "Friedman test"},
{"page.binary_logistic",
 "二元 Logistic 回归",
 "Binary logistic regression"},
{"page.ordinal_logistic",
 "有序 Logistic 回归",
 "Ordinal logistic regression"},
{"page.pca",
 "主成分分析",
 "Principal component analysis"},
{"page.kmeans",
 "K-Means 聚类",
 "K-Means clustering"},
{"page.cart",
 "CART 单树",
 "CART single tree"},
{"page.adf",
 "ADF 单位根检验",
 "ADF unit-root test"},
{"page.poisson_regression",
 "Poisson 回归",
 "Poisson regression"},
{"page.hierarchical_clustering",
 "层次聚类（观测）",
 "Hierarchical clustering (observations)"},
{"page.lda",
 "线性判别分析",
 "Linear discriminant analysis"},
{"page.stepwise_regression",
 "逐步回归",
 "Stepwise regression"},
{"page.best_subsets_regression",
 "Best Subsets 回归",
 "Best subsets regression"},
{"page.batch_capability",
 "批次过程能力",
 "Batch capability analysis"},
{"page.acf_pacf",
 "自相关 / 偏自相关",
 "ACF / PACF"},
{"page.ccf",
 "互相关（CCF）",
 "Cross-correlation (CCF)"},
{"page.correlogram_heatmap",
 "Correlogram（相关热图）",
 "Correlogram (correlation heatmap)"},
{"page.time_series_smooth",
 "时间序列平滑",
 "Time series smoothing"},
{"page.arima_forecast",
 "ARIMA 基础预测",
 "ARIMA basic forecast"},
{"page.seasonal_forecast",
 "季节性预测",
 "Seasonal forecast"},
{"page.time_series_decompose",
 "时间序列分解",
 "Time series decomposition"},
{"page.bootstrap_mean_ci",
 "Bootstrap 均值置信区间",
 "Bootstrap mean confidence interval"},
{"page.eda_four_plot",
 "EDA 四图",
 "EDA four-plot"},
{"page.imr_rs_chart",
 "I-MR-R/S 控制图",
 "I-MR-R/S control chart"},
{"page.generalized_variance",
 "广义方差图",
 "Generalized variance chart"},
{"page.hotelling_t2",
 "Hotelling T²",
 "Hotelling T²"},
{"page.mewma",
 "MEWMA",
 "MEWMA"},
{"page.isolation_forest",
 "Isolation Forest",
 "Isolation Forest"},
{"page.crossed_gage_rr",
 "Crossed Gage R&R",
 "Crossed Gage R&R"},
{"page.nested_gage_rr",
 "Nested Gage R&R",
 "Nested Gage R&R"},
{"page.expanded_gage_rr",
 "Expanded Gage R&R",
 "Expanded Gage R&R"},
{"page.emp_crossed",
 "EMP Crossed",
 "EMP Crossed"},
{"page.gage_stability",
 "Gage Stability",
 "Gage Stability"},
{"page.bias_linearity",
 "Bias/Linearity",
 "Bias/Linearity"},
{"page.msa_type1_gage",
 "MSA Type 1 Gage",
 "MSA Type 1 Gage"},
{"page.suffix.faceted",
 "（分面）",
 " (faceted)"},
{"graph.caption.display_n",
 "显示 N = ",
 "Display N = "},
{"graph.caption.analysis_n_level",
 "分析 N(水平) = ",
 "Analysis N (level) = "},
{"graph.caption.analysis_n",
 "分析 N = ",
 "Analysis N = "},
{"graph.caption.facet",
 "分面 = ",
 "Facet = "},
{"param.summary.panel_eq",
 "面板 = ",
 "Panels = "},
{"param.summary.group_eq",
 "分组 = ",
 "Group = "},
{"param.summary.size_eq",
 "大小 = ",
 "Size = "},
{"param.summary.numeric_value_eq",
 "数值 = ",
 "Value = "},
{"param.summary.confidence_level_eq",
 "置信水平 = ",
 "Confidence level = "},
{"param.summary.valid_variable_count_eq",
 "有效变量数 = ",
 "Valid variables = "},
{"param.summary.display_group_count_eq",
 "显示组数 = ",
 "Displayed groups = "},
{"param.summary.display_category_count_eq",
 "显示类别数 = ",
 "Displayed categories = "},
{"param.summary.analysis_category_count_eq",
 "分析类别数 = ",
 "Analysis categories = "},
{"param.summary.small_category_merge_threshold_eq",
 "小类别合并阈值 = ",
 "Small-category merge threshold = "},
{"param.summary.coords_minmax_standardized",
 "坐标已按各变量最小-最大范围标准化",
 "Coordinates scaled to each variable's min–max range"},
{"param.summary.linearity_not_normality_proof",
 "直线性不能单独作为正态性证明",
 "Linearity alone is not proof of normality"},
{"param.summary.linearity_hidden_fit_note",
 "直线性不能单独作为正态性证明；显示拟合省略 hidden，分析拟合保留 hidden",
 "Linearity alone is not proof of normality; display fit omits hidden, analysis fit keeps hidden"},
{"plot.axis.cumulative_proportion",
 "累计比例",
 "Cumulative proportion"},
{"interp.capability_stability_blocked",
 "（稳定性前置未验收；禁止写成过程合格判定）。",
 " (stability prerequisite not accepted; do not write process pass/fail)."},
{"interp.capability_stability_screen_signals",
 "I-MR Rule-1 初筛检出 %1 个超限点；能力指数仅供调查，不得写成过程合格。",
 "I-MR Rule-1 screen found %1 out-of-control point(s); capability indices are for investigation only and must not be written as process pass/fail."},
{"interp.capability_stability_clear_not_verified",
 "I-MR Rule-1 初筛未检出超限点；这不是完整控制图验收，也不等于已验证稳定性/正态性，不得自动开放合格判定。",
 "I-MR Rule-1 screen found no out-of-control points; this is not a full control-chart acceptance and does not verify stability/normality—do not auto-open pass/fail."},
{"interp.capability_stability_prerequisite",
 "能力分析稳定性前置：当前仅做公式参考级 I-MR Rule-1 初筛；合格判定保持关闭，直至独立稳定性与正态性验收工作流落地。",
 "Capability stability prerequisite: only formula-reference I-MR Rule-1 screening is applied; pass/fail stays closed until an independent stability and normality acceptance workflow lands."},
{"interp.rsm_no_replicates_lof",
 "无重复编码点：未报告纯误差/失拟；不得用残差 MS 冒充纯误差。",
 "No replicated coded points: pure error / lack of fit not reported; residual MS must not be presented as pure error."},
{"interp.doe_no_significant_terms",
 "在当前显著性水平下，没有发现可报告为显著的 DOE 项。",
 "At the current significance level, no DOE terms are reportable as significant."},
{"interp.doe_no_center_points",
 "未配置中心点，无法用中心点直接检验曲率；二水平线性模型的适用范围有限。",
 "No center points were configured, so curvature cannot be tested directly via center points; a two-level linear model has limited scope."},
{"interp.km_empty",
 "Kaplan-Meier 生存表为空，不能估计生存曲线或中位寿命。",
 "Kaplan-Meier survival table is empty; the survival curve or median life cannot be estimated."},
{"interp.km_right_censoring",
 "存在右删失；尾部生存率由较少的风险集支持，不能把删失时间当作失效时间。",
 "Right censoring is present; tail survival is supported by a thinner risk set—do not treat censoring times as failures."},
{"interp.km_advice",
 "按目标任务时间读取生存概率，并报告置信区间；需要比较产品/方案时使用分层或组间检验。",
 "Read survival probability at the target mission time and report confidence intervals; use stratified or between-group tests when comparing products/plans."},
{"interp.weibull_params_missing",
 "Weibull 参数缺失，不能解释失效率随时间的变化。",
 "Weibull parameters are missing; the time pattern of the failure rate cannot be interpreted."},
{"interp.weibull_not_converged",
 "Weibull 参数未收敛，分位寿命不能作为决策依据。",
 "Weibull parameters did not converge; percentile life must not be used for decisions."},
{"interp.exponential_constant_hazard",
 "指数模型估计的是恒定失效率假设下的寿命分布。",
 "The exponential model estimates a lifetime distribution under a constant hazard assumption."},
{"interp.exponential_limitation",
 "指数模型不能描述随时间上升或下降的失效率；应与 Weibull 等模型比较适配性。",
 "The exponential model cannot describe rising or falling hazard over time; compare fit with Weibull and other models."},
{"interp.reliability_advice_no_guarantee",
 "报告模型参数和删失处理，并用现场失效机理验证模型假设；不要把分位寿命当成单件保证寿命。",
 "Report model parameters and censoring handling, and validate assumptions with field failure mechanisms; do not treat percentile life as a unit warranty life."},
{"interp.warranty_not_legal_promise",
 "不得把统计预测写成法律/质量承诺；分母与时间窗口必须一并阅读。",
 "Do not write statistical forecasts as legal/quality commitments; denominators and time windows must be read together."},
{"interp.not_vendor_oracle",
 "不是 vendor_oracle；不得写成商业软件对齐。",
 "Not vendor_oracle; do not claim commercial-software alignment."},
{"interp.johnson_gate_clause",
 "（研究/预览指数；门禁禁止写成过程合格判定）。",
 " (research/preview indices; gate forbids writing process pass/fail)."},
{"interp.nonnormal_gate_clause",
 "（非正态/变换路径；禁止写成过程合格判定）。",
 " (nonnormal/transform path; do not write process pass/fail)."},
{"interp.bimodality_not_hartigan",
 "不得写成过程合格（非混合模型 / 非 Hartigan dip）。",
 "Do not write process pass/fail (not a mixture fit / not Hartigan dip)."},
{"interp.bimodality_not_mixture",
 "不得写成过程合格（直方图初筛 ≠ 混合模型证明）。",
 "Do not write process pass/fail (histogram screen ≠ mixture-model proof)."},
{"interp.bimodality_suspected_full",
 "双峰初筛为 suspected：单一分布能力指数仅供调查，不得写成过程合格（直方图初筛 ≠ 混合模型证明）。",
 "Bimodality screen is suspected: single-distribution capability indices are for investigation only; do not write process pass/fail (histogram screen ≠ mixture-model proof)."},
{"interp.hartigan_dip_evidence_against",
 "Hartigan dip 为 evidence_against：单一分布能力指数仅供调查，不得写成过程合格（formula_reference；非 vendor_oracle）。",
 "Hartigan dip is evidence_against: single-distribution capability indices are for investigation only; do not write process pass/fail (formula_reference; not vendor_oracle)."},
{"interp.mixture_preferred_2comp",
 "二维高斯混合为 preferred_2comp：单一分布能力指数仅供调查，不得写成过程合格（formula_reference / gaussian_mixture_k_bic；非 vendor_oracle）。",
 "Two-component Gaussian mixture is preferred_2comp: single-distribution capability indices are for investigation only; do not write process pass/fail (formula_reference / gaussian_mixture_k_bic; not vendor_oracle)."},
{"interp.mixture_preferred_kcomp",
 "高斯混合为 preferred_kcomp（k=%1）：单一分布能力指数仅供调查，不得写成过程合格（formula_reference / gaussian_mixture_k_bic；非 vendor_oracle）。",
 "Gaussian mixture is preferred_kcomp (k=%1): single-distribution capability indices are for investigation only; do not write process pass/fail (formula_reference / gaussian_mixture_k_bic; not vendor_oracle)."},
{"interp.johnson_no_pass_fail_until_golden",
 "未满足 golden/尾部验收前不得开放合格判定。",
 "Do not open pass/fail until golden and tail acceptance are satisfied."},
{"interp.stability_not_capability_pass",
 "未验证稳定性不等于过程合格。",
 "Unverified stability is not process pass/fail."},
{"interp.ndc_unavailable",
 "ndc 不可估计，不能据此评价测量系统分辨力。",
 "ndc is not estimable; measurement-system discrimination cannot be judged from it."},
{"rule.msa.ndc_not_computed.message",
 "ndc 不可估计；不能据此评价测量系统分辨力。",
 "ndc cannot be estimated; do not judge measurement-system discrimination from it."},
{"rule.msa.ndc_not_computed.action",
 "先检查零总变异、零 Gage 标准差或无效容差后再解释 ndc。",
 "Check zero total variation, zero Gage SD, or invalid tolerance before interpreting ndc."},
{"rule.msa.ndc_lt5.message",
 "ndc < 5，提示测量系统对零件间差异的分辨力需要调查。",
 "ndc < 5 suggests investigating discrimination versus part-to-part variation."},
{"rule.msa.ndc_lt5.action",
 "ndc 小于 5 只是调查提示，不是量具不合格的绝对结论。",
 "ndc below 5 is an investigation hint only, not an absolute gage-fail conclusion."},
{"rule.msa.ndc_ge5.message",
 "ndc ≥ 5；这只说明当前研究中零件间变异相对 Gage 变异较大。",
 "ndc ≥ 5 only means part variation is large relative to Gage variation in this study."},
{"rule.msa.ndc_ge5.action",
 "仍需结合 %Study Var、%Tolerance 和现场公差风险解释。",
 "Still interpret with %Study Var, %Tolerance, and field tolerance risk."},
{"rule.msa.design_balance.message",
 "交叉设计单元重复次数平衡。",
 "Crossed-design cell replicate counts are balanced."},
{"rule.msa.design_balance.action",
 "平衡设计是 ANOVA 方差分量解释的前提。",
 "Balance is a prerequisite for interpreting ANOVA variance components."},
{"rule.msa.design_balance_unbalanced.message",
 "零件×操作员单元重复次数不一致。",
 "Part×operator cell replicate counts are inconsistent."},
{"rule.msa.design_balance_unbalanced.action",
 "交叉设计需要平衡重复后才能解释方差分量。",
 "Balance replicates in the crossed design before interpreting variance components."},
{"rule.msa.nested_design_balance_unbalanced.message",
 "嵌套设计零件重复次数不一致。",
 "Nested-design part replicate counts are inconsistent."},
{"rule.msa.nested_design_balance_unbalanced.action",
 "先补齐平衡重复后再解释方差分量。",
 "Balance replicates before interpreting variance components."},
{"rule.msa.nested_design_balance_ok.message",
 "嵌套设计在操作员和零件重复上平衡。",
 "Nested design is balanced across operators and part replicates."},
{"rule.msa.nested_design_balance_triggered.message",
 "嵌套设计不平衡。",
 "Nested design is unbalanced."},
{"rule.msa.nested_design_balance.action",
 "每个零件只属于一个操作员，且重复次数应一致。",
 "Each part belongs to one operator, and replicate counts should match."},
{"rule.msa.nested_negative_variance_triggered.message",
 "存在负方差分量，已截断为 0。",
 "Negative variance components were truncated to 0."},
{"rule.msa.nested_negative_variance.action",
 "解释 %Contribution 时同时查看截断前的原始方差分量。",
 "When interpreting %Contribution, also review pre-truncation variance components."},
{"rule.msa.interaction_triggered.message",
 "交互项 p>0.25，可考虑缩减，但当前保留完整模型。",
 "Interaction p>0.25; reduction may be considered, but the full model is retained."},
{"rule.msa.interaction_ok.message",
 "当前保留 Part×Operator 交互模型。",
 "The Part×Operator interaction model is retained."},
{"rule.msa.interaction.action",
 "交互是否缩减必须回显；本实现不自动并入重复性。",
 "Whether interaction is reduced must be reported; this implementation does not fold it into repeatability."},
{"rule.msa.negative_variance_triggered.message",
 "存在负方差分量，已截断为 0，并保留原始估计。",
 "Negative variance components were truncated to 0; original estimates are retained."},
{"rule.msa.negative_variance_ok.message",
 "方差分量原始估计均非负。",
 "All raw variance-component estimates are non-negative."},
{"rule.msa.negative_variance.action",
 "截断后的分量用于 %Contribution；解释时同时查看原始值。",
 "Truncated components feed %Contribution; also review the original estimates."},
{"rule.msa.percent_metrics.message",
 "%Contribution 基于方差，%Study Var 基于标准差，口径不同。",
 "%Contribution is variance-based; %Study Var is SD-based—different bases."},
{"rule.msa.percent_metrics.action",
 "不要把 %Contribution 与 %Study Var 当成同一个百分比。",
 "Do not treat %Contribution and %Study Var as the same percentage."},
{"rule.msa.invalid_tolerance.message",
 "未提供有效公差，%Tolerance 不可用。",
 "No valid tolerance was provided; %Tolerance is unavailable."},
{"rule.msa.invalid_tolerance.action",
 "只有有限正公差才能计算 %Tolerance。",
 "Only a finite positive tolerance allows %Tolerance."},
{"rule.aa.kappa_interpretation.message",
 "拒绝 Kappa=0 不等于已证明评估者一致。",
 "Rejecting Kappa=0 does not prove rater agreement."},
{"rule.aa.kappa_interpretation.action",
 "Kappa 只描述超出偶然的绝对一致率，不能写成测量系统合格。",
 "Kappa describes chance-corrected absolute agreement only—not MSA pass/fail."},
{"rule.aa.weighted_kappa.message",
 "Weighted Kappa 是 DataLab 可选 Cohen 加权，不是 Minitab AAA 默认输出。",
 "Weighted Kappa is DataLab's optional Cohen weighting, not Minitab AAA default output."},
{"rule.aa.weighted_kappa.action",
 "Minitab 有序评级路径使用 Kendall；不要把加权 κ 写成 Minitab AAA 结果。",
 "Minitab ordinal paths use Kendall; do not report weighted κ as Minitab AAA."},
{"rule.aa.kendall_ok.message",
 "有序评级已计算 Kendall W/τ；拒绝系数为 0 不等于已证明有序一致。",
 "Ordinal ratings computed Kendall W/τ; rejecting zero coefficient does not prove ordinal agreement."},
{"rule.aa.kendall_unavailable.message",
 "已请求有序评级，但 Kendall 不可识别或等级不足。",
 "Ordinal ratings were requested, but Kendall is not identifiable or levels are insufficient."},
{"rule.aa.kendall.action",
 "不要把 Kendall 写成加权 Kappa，也不要把未拒绝原假设写成已证明一致。",
 "Do not call Kendall weighted Kappa, and do not treat failure to reject as proven agreement."},
{"rule.msa.catalog.design_balance.name",
 "设计平衡",
 "Design balance"},
{"rule.msa.catalog.ndc_investigation.name",
 "ndc 调查",
 "ndc investigation"},
{"rule.msa.catalog.ndc_investigation.message",
 "ndc = truncate(1.41×PartStDev/GageStDev)，<5 只作调查提示。",
 "ndc = truncate(1.41×PartStDev/GageStDev); <5 is investigation-only."},
{"rule.regression.catalog.error_df.name",
 "误差自由度",
 "Error degrees of freedom"},
{"rule.regression.catalog.error_df.message",
 "N-p-1 必须为正才能输出 t、F 与 P。",
 "N-p-1 must be positive to output t, F, and P."},
{"rule.regression.catalog.rank_deficiency.name",
 "秩亏/共线",
 "Rank deficiency / collinearity"},
{"rule.regression.catalog.rank_deficiency.message",
 "设计矩阵秩亏时拒绝拟合，不输出伪造推断。",
 "Reject fit when the design matrix is rank-deficient; do not emit fabricated inference."},
{"rule.regression.catalog.residual_normality.name",
 "残差正态性",
 "Residual normality"},
{"rule.regression.catalog.residual_normality.message",
 "Anderson-Darling 只能拒绝或未拒绝正态假设。",
 "Anderson-Darling can only reject or fail to reject normality."},
{"rule.regression.catalog.residual_independence.name",
 "残差独立性",
 "Residual independence"},
{"rule.regression.catalog.residual_independence.message",
 "Durbin-Watson 对照 α=0.05 近似 dL/dU 判定区；不能写成已证明无自相关。",
 "Durbin-Watson uses α=0.05 approximate dL/dU zones; cannot be written as proof of no autocorrelation."},
{"rule.regression.catalog.homoscedasticity.name",
 "方差齐性",
 "Homoscedasticity"},
{"rule.regression.catalog.homoscedasticity.message",
 "残差对拟合值图是主要证据，不单独宣称已验证。",
 "Residuals vs fitted plot is primary evidence; do not claim verified homoscedasticity alone."},
{"rule.regression.catalog.leverage.name",
 "高杠杆",
 "High leverage"},
{"rule.regression.catalog.leverage.message",
 "杠杆值 > 2p/n 时标记为需要调查的高杠杆点。",
 "Flag points with leverage > 2p/n for investigation."},
{"rule.regression.catalog.outlier.name",
 "异常残差",
 "Outlier residuals"},
{"rule.regression.catalog.outlier.message",
 "|删除学生化残差| > 3 时标记为异常点调查。",
 "Flag |deleted studentized residual| > 3 for outlier investigation."},
{"rule.regression.catalog.influence.name",
 "影响点",
 "Influential points"},
{"rule.regression.catalog.influence.message",
 "Cook's D > 4/n 或 |DFITS| 超过阈值时标记影响点。",
 "Flag influence when Cook's D > 4/n or |DFITS| exceeds threshold."},
{"rule.regression.catalog.collinearity.name",
 "共线性",
 "Collinearity"},
{"rule.regression.catalog.collinearity.message",
 "VIF > 5 提示共线性调查，不自动删除变量。",
 "VIF > 5 suggests collinearity investigation; do not auto-drop predictors."},
{"rule.anova.catalog.estimability.name",
 "可估计性",
 "Estimability"},
{"rule.anova.catalog.estimability.message",
 "秩亏或无误差自由度时不输出伪造 F/P。",
 "Do not emit fabricated F/P when rank-deficient or no error df."},
{"rule.anova.catalog.residual_normality.name",
 "残差正态性",
 "Residual normality"},
{"rule.anova.catalog.residual_normality.message",
 "用残差 Anderson-Darling 作为假设证据。",
 "Use residual Anderson-Darling as assumption evidence."},
};

}  // namespace

void append_report_text_catalog_part9(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart9),
        std::end(kReportTextCatalogPart9));
}

}  // namespace datalab::domain
