#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart7[] = {
{"plot.turnbull_survival_curve",
 "Turnbull 生存曲线",
 "Turnbull survival curve"},
{"plot.suffix.survival_curve",
 "生存曲线",
 "Survival curve"},
{"plot.suffix.probability_plot",
 "概率图",
 "Probability plot"},
{"model.weibull3",
 "三参数 Weibull",
 "3-parameter Weibull"},
{"model.exponential2",
 "两参数指数",
 "2-parameter exponential"},
{"model.lognormal3",
 "三参数对数正态",
 "3-parameter lognormal"},
{"plot.axis.time",
 "时间",
 "Time"},
{"plot.axis.measurement",
 "测量值",
 "Measurement"},
{"plot.axis.subgroup_mean",
 "子组均值",
 "Subgroup mean"},
{"plot.axis.moving_range",
 "移动极差",
 "Moving range"},
{"plot.axis.subgroup_range",
 "子组极差",
 "Subgroup range"},
{"plot.axis.subgroup_stdev",
 "子组标准差",
 "Subgroup StDev"},
{"plot.axis.proportion_defective",
 "不合格品率",
 "Proportion defective"},
{"plot.axis.number_defective",
 "不合格品数",
 "Number defective"},
{"plot.axis.defect_count",
 "缺陷数",
 "Defect count"},
{"plot.axis.defects_per_unit",
 "单位缺陷数",
 "Defects per unit"},
{"plot.axis.proportion_defective_p",
 "不合格品率 p",
 "Proportion defective p"},
{"header.inspected_count",
 "检验数",
 "Inspected count"},
{"header.unit_count",
 "单位数",
 "Unit count"},
{"header.proportion_defective",
 "不合格品率",
 "Proportion defective"},
{"header.number_defective",
 "不合格品数",
 "Number defective"},
{"header.defect_count",
 "缺陷数",
 "Defect count"},
{"header.defects_per_unit",
 "单位缺陷数",
 "Defects per unit"},
{"plot.series.fitted_st",
 "拟合 S(t)",
 "Fitted S(t)"},
{"header.item",
 "项目",
 "Item"},
{"header.metric",
 "指标",
 "Metric"},
{"header.numeric_value",
 "数值",
 "Value"},
{"header.parameter",
 "参数",
 "Parameter"},
{"header.source",
 "来源",
 "Source"},
{"header.term",
 "项",
 "Term"},
{"header.observation",
 "观测",
 "Observation"},
{"header.expected_overall",
 "期望 Overall",
 "Expected overall"},
{"header.expected_within",
 "期望 Within",
 "Expected within"},
{"header.estimate",
 "估计",
 "Estimate"},
{"header.lower",
 "下限",
 "Lower"},
{"header.upper",
 "上限",
 "Upper"},
{"header.group",
 "组",
 "Group"},
{"header.mean",
 "均值",
 "Mean"},
{"header.stdev",
 "标准差",
 "StDev"},
{"header.level",
 "水平",
 "Level"},
{"header.difference",
 "差值",
 "Difference"},
{"header.sample_1",
 "样本 1",
 "Sample 1"},
{"header.sample_2",
 "样本 2",
 "Sample 2"},
{"header.paired_difference",
 "配对差值",
 "Paired difference"},
{"header.reference_sample",
 "参考样本",
 "Reference sample"},
{"header.test_sample",
 "检验样本",
 "Test sample"},
{"header.ratio",
 "比值",
 "Ratio"},
{"header.lower_z",
 "下限 z",
 "Lower z"},
{"header.lower_p",
 "下限 P",
 "Lower P"},
{"header.upper_z",
 "上限 z",
 "Upper z"},
{"header.upper_p",
 "上限 P",
 "Upper P"},
{"header.lower_t",
 "下限 t",
 "Lower t"},
{"header.upper_t",
 "上限 t",
 "Upper t"},
{"header.ci_method",
 "CI 方法",
 "CI method"},
{"header.equivalence_limits",
 "界限",
 "Limits"},
{"header.conclusion",
 "结论",
 "Conclusion"},
{"plot.series.equivalence_lower",
 "等价下限",
 "Equivalence lower"},
{"plot.series.equivalence_upper",
 "等价上限",
 "Equivalence upper"},
{"plot.axis.proportion_difference",
 "比例差",
 "Proportion difference"},
{"param.summary.limits_bracket_eq",
 "界限 = [",
 "Limits = ["},
{"diag.equiv_need_bounds",
 "请指定等价下限和上限。",
 "Specify the equivalence lower and upper limits."},
{"diag.equiv_need_ratio_bounds",
 "请指定比值等价下限和上限。",
 "Specify the ratio equivalence lower and upper limits."},
{"diag.equiv_need_target_proportion",
 "请指定目标比例。",
 "Specify the target proportion."},
{"header.method",
 "方法",
 "Method"},
{"header.statistic",
 "统计量",
 "Statistic"},
{"header.status",
 "状态",
 "Status"},
{"header.notes",
 "说明",
 "Notes"},
{"header.check_item",
 "检查项",
 "Check"},
{"header.decision_zone",
 "判定区",
 "Decision zone"},
{"header.order",
 "顺序",
 "Order"},
{"header.source_row",
 "原始行",
 "Source row"},
{"header.response",
 "响应",
 "Response"},
{"header.fitted",
 "拟合值",
 "Fitted"},
{"header.residual",
 "残差",
 "Residual"},
{"header.std_residual",
 "标准化残差",
 "Standardized residual"},
{"header.significant",
 "显著",
 "Significant"},
{"header.family_confidence_level",
 "族置信水平",
 "Family confidence level"},
{"header.error_df",
 "误差 DF",
 "Error DF"},
{"header.min_expected_count",
 "最小期望频数",
 "Minimum expected count"},
{"header.categories_below_five",
 "<5 类别数",
 "Categories with expected <5"},
{"header.expected_below_five_count",
 "期望<5 数",
 "Count with expected <5"},
{"header.category_count",
 "类别数",
 "Category count"},
{"header.validity",
 "有效性",
 "Validity"},
{"header.total",
 "合计",
 "Total"},
{"header.row",
 "行",
 "Row"},
{"header.column",
 "列",
 "Column"},
{"header.row_count",
 "行数",
 "Row count"},
{"header.estimability",
 "可估计性",
 "Estimability"},
{"header.factor_a",
 "因子 A",
 "Factor A"},
{"header.factor_b",
 "因子 B",
 "Factor B"},
{"header.internally_standardized_residual",
 "内部标准化残差",
 "Internally standardized residual"},
{"header.studentized_residual",
 "学生化残差",
 "Studentized residual"},
{"header.deleted_studentized_residual",
 "删除学生化残差",
 "Deleted studentized residual"},
{"header.leverage",
 "杠杆值",
 "Leverage"},
{"header.leverage_abbr",
 "杠杆",
 "Leverage"},
{"header.cooks_distance",
 "Cook 距离",
 "Cook's distance"},
{"header.cook_abbr",
 "Cook",
 "Cook"},
{"header.diagnostic_flags",
 "诊断标记",
 "Diagnostic flags"},
{"header.flag",
 "标记",
 "Flag"},
{"header.cell",
 "单元格",
 "Cell"},
{"header.count",
 "计数",
 "Count"},
{"header.continuity_correction_alt",
 "连续性校正",
 "Continuity correction"},
{"header.odds_ratio",
 "优势比 OR",
 "Odds ratio (OR)"},
{"header.contrast",
 "对比",
 "Contrast"},
{"header.unadjusted_p",
 "未调整 P",
 "Unadjusted P"},
{"header.bonferroni_p",
 "Bonferroni P",
 "Bonferroni P"},
{"header.mean_rank_diff",
 "平均秩差",
 "Mean rank difference"},
{"header.mean_rank",
 "平均秩",
 "Mean rank"},
{"header.group_label",
 "组别",
 "Group label"},
{"header.treatment",
 "处理",
 "Treatment"},
{"header.ties_correction",
 "Ties 修正",
 "Ties correction"},
{"header.predicted_probability",
 "预测概率",
 "Predicted probability"},
{"header.pearson_residual",
 "Pearson 残差",
 "Pearson residual"},
{"header.deviance_residual",
 "Deviance 残差",
 "Deviance residual"},
{"status.anova_between",
 "组间",
 "Between groups"},
{"status.anova_error",
 "误差",
 "Error"},
{"status.anova_regression",
 "回归",
 "Regression"},
{"status.anova_lack_of_fit",
 "失拟",
 "Lack of fit"},
{"status.anova_pure_error",
 "纯误差",
 "Pure error"},
{"header.factor",
 "因子",
 "Factor"},
{"header.actual_value",
 "实际值",
 "Actual"},
{"header.sequence_index",
 "序号",
 "Index"},
{"header.coded_level",
 "编码水平",
 "Coded level"},
{"header.actual_level",
 "实际水平",
 "Actual level"},
{"header.combination",
 "组合",
 "Combination"},
{"header.group_median",
 "组中位数",
 "Group median"},
{"header.ci_lower",
 "CI 下限",
 "CI lower"},
{"header.ci_upper",
 "CI 上限",
 "CI upper"},
{"header.first_group",
 "第一组",
 "First group"},
{"header.second_group",
 "第二组",
 "Second group"},
{"header.n_le",
 "N≤",
 "N≤"},
{"header.n_gt",
 "N>",
 "N>"},
{"header.discordant_pairs",
 "不一致对数 b+c",
 "Discordant pairs b+c"},
{"header.valid_pair_count",
 "有效配对数",
 "Valid pair count"},
{"table.interaction_means",
 "交互均值",
 "Interaction means"},
{"plot.interaction_means",
 "交互均值图",
 "Interaction means plot"},
{"plot.axis.residual",
 "残差",
 "Residual"},
{"plot.axis.observation_order",
 "观测顺序",
 "Observation order"},
{"plot.axis.theoretical_quantile",
 "理论分位数",
 "Theoretical quantile"},
{"plot.axis.frequency",
 "频数",
 "Frequency"},
{"plot.axis.part",
 "零件",
 "Part"},
{"plot.axis.cell_mean",
 "单元格均值",
 "Cell mean"},
{"plot.axis.sample",
 "样本",
 "Sample"},
{"plot.axis.grouping",
 "分组",
 "Group"},
{"plot.axis.theoretical_standard_normal_quantile",
 "理论标准正态分位数",
 "Theoretical standard normal quantile"},
{"plot.axis.standard_normal_quantile",
 "标准正态分位数",
 "Standard normal quantile"},
{"plot.axis.transformed_measurement",
 "变换后测量",
 "Transformed measurement"},
{"plot.axis.obs_order_abbr",
 "观测序",
 "Obs. order"},
{"plot.axis.pairwise_comparison",
 "成对比较",
 "Pairwise comparison"},
{"plot.axis.reference_value",
 "参考值",
 "Reference"},
{"plot.axis.suffix.coded",
 "（编码）",
 " (coded)"},
{"plot.series.observed_bias",
 "观测偏倚",
 "Observed bias"},
{"plot.series.residual_zero",
 "残差 = 0",
 "Residual = 0"},
{"plot.series.cube_edge",
 "棱",
 "Edge"},
{"diag.cube_plot_requires_2_or_3_factors",
 "立方图仅支持 2 或 3 个因子（当前 %1 个）；请用主效应图、交互图、等值线/曲面图查看高维设计。",
 "Cube plots support only 2 or 3 factors (currently %1); use main-effects, interaction, and contour/surface plots for higher dimensions."},
{"diag.invalid_contour_factors",
 "等值线/曲面的 X/Y 因子无效或相同；请指定两个不同的因子名。",
 "Contour/surface X/Y factors are invalid or identical; specify two different factor names."},
{"diag.contour_requires_two_factors",
 "等值线/曲面图需要至少两个连续因子。",
 "Contour/surface plots require at least two continuous factors."},
{"diag.doe_worksheet_export_ready",
 "已生成可写入工作表的设计矩阵（实际水平 + 空 Response 列）；UI 可一键替换活动工作表以录入响应。",
 "Design matrix ready for worksheet write-back (actual levels + empty Response column); UI can replace the active worksheet to enter responses."},
{"header.variable",
 "变量",
 "Variable"},
{"header.variable_1",
 "变量 1",
 "Variable 1"},
};

}  // namespace

void append_report_text_catalog_part7(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart7),
        std::end(kReportTextCatalogPart7));
}

}  // namespace datalab::domain
