#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart13[] = {
{"interp.twoway_anova_rec_report_seq_adj",
 "不平衡设计应同时报告 Seq SS 与 Adj SS，不要只看其中一个。",
 "For unbalanced designs, report both Seq SS and Adj SS; do not rely on only one."},
{"interp.anova_info_interval_unavailable",
 "误差自由度或 MSE 不可用，未输出组均值区间。",
 "Error degrees of freedom or MSE is unavailable; group-mean intervals were not reported."},
{"interp.anova_err_need_factor_col",
 "请选择因子/分组列。",
 "Select a factor / grouping column."},
{"interp.twoway_anova_err_need_columns",
 "请选择响应变量、因子 A 和因子 B。",
 "Select a response, factor A, and factor B."},
{"interp.twoway_anova_rule_balanced",
 "因子组合重复数平衡。",
 "Factor-combination replicates are balanced."},
{"interp.twoway_anova_rule_unbalanced",
 "因子组合不平衡，Sequential SS 与 Adjusted SS 可能不同。",
 "Factor combinations are unbalanced; Sequential SS and Adjusted SS may differ."},
{"interp.twoway_anova_rule_estimability_triggered",
 "存在不可估计项或无误差自由度，不输出伪造 F/P。",
 "Non-estimable terms or no error degrees of freedom are present; forged F/P values are not reported."},
{"interp.twoway_anova_rule_estimability_clear",
 "当前效应可估计且误差自由度为正。",
 "Current effects are estimable and error degrees of freedom are positive."},
{"interp.twoway_anova_rec_show_reason",
 "不可估计项必须显示原因，不能填入默认 F/P。",
 "Non-estimable terms must show a reason; default F/P values must not be filled in."},
{"interp.tukey_err_invalid_groups",
 "Tukey 比较至少需要两个且标签数量必须匹配的有效组。",
 "Tukey comparisons require at least two valid groups with matching label counts."},
{"interp.tukey_err_confidence",
 "置信水平必须大于 0 且小于 1。",
 "Confidence level must be greater than 0 and less than 1."},
{"interp.tukey_err_empty_group",
 "Tukey 比较不允许空组。",
 "Tukey comparisons do not allow empty groups."},
{"interp.tukey_err_non_finite",
 "Tukey 比较不允许无穷或非数值观测。",
 "Tukey comparisons do not allow infinite or non-numeric observations."},
{"interp.tukey_err_error_df",
 "Tukey 比较需要正的组内误差自由度。",
 "Tukey comparisons require positive within-group error degrees of freedom."},
{"interp.tukey_warn_approx",
 "当前 Tukey 调整使用 Studentized range 的保守 t 分布近似。",
 "The current Tukey adjustment uses a conservative t-distribution approximation to the studentized range."},
{"interp.tukey_rec_family_error",
 "不要把逐比较 alpha 当成家族错误率。",
 "Do not treat per-comparison alpha as the family-wise error rate."},
{"interp.doe_err_generator_format",
 "生成器格式应为 D=ABC;E=ABD。",
 "Generator format must be like D=ABC;E=ABD."},
{"interp.doe_err_generator_left",
 "生成器左侧应为单个因子字母。",
 "Generator left-hand side must be a single factor letter."},
{"interp.doe_err_generator_unknown_letter",
 "生成器引用了不存在的因子字母。",
 "Generator references a factor letter that does not exist."},
{"interp.doe_err_generator_product",
 "生成器右侧乘积无法解析。",
 "Generator right-hand product could not be parsed."},
{"interp.doe_err_generator_self_ref",
 "生成器右侧不能包含被生成因子。",
 "Generator right-hand side must not include the generated factor."},
{"interp.doe_err_generator_not_extra",
 "生成器应定义最后 p 个附加因子。",
 "Generators must define the last p added factors."},
{"interp.doe_err_generator_count",
 "生成器数量必须等于部分析因 p。",
 "Number of generators must equal fractional factorial p."},
{"interp.doe_err_generator_incomplete",
 "每个附加因子都需要生成器。",
 "Every added factor requires a generator."},
{"interp.doe_err_empty_factors",
 "DOE 至少需要一个因子。",
 "DOE requires at least one factor."},
{"interp.doe_err_block_count",
 "区组数必须大于零。",
 "Block count must be greater than zero."},
{"interp.doe_err_fraction_p",
 "部分析因 p 必须小于因子数 k。",
 "Fractional factorial p must be less than factor count k."},
{"interp.doe_err_incomplete_factor",
 "每个 DOE 因子必须有名称、低水平和高水平。",
 "Each DOE factor must have a name, low level, and high level."},
{"interp.doe_err_duplicate_factor_name",
 "DOE 因子名称必须唯一。",
 "DOE factor names must be unique."},
{"interp.doe_err_no_default_generators",
 "该 (k,p) 无内置默认生成器，请在 generators 中手写。",
 "No built-in default generators for this (k,p); enter generators manually."},
{"interp.rsd_err_no_factors",
 "至少需要一个连续因素。",
 "At least one continuous factor is required."},
{"interp.rsd_err_duplicate_factor_id",
 "因素 ID 必须唯一。",
 "Factor IDs must be unique."},
{"interp.rsd_err_categorical_blocked",
 "第一阶段只接受连续因素；分类因素不得静默编码。",
 "Phase 1 accepts continuous factors only; categorical factors must not be silently coded."},
{"interp.rsd_err_invalid_bounds",
 "因素低水平必须严格小于高水平。",
 "Factor low level must be strictly less than high level."},
{"interp.rsd_err_empty_factor_id",
 "因素 ID 不能为空。",
 "Factor ID must not be empty."},
{"interp.rsd_err_nonfinite_bounds",
 "因素低/高水平必须有限。",
 "Factor low/high levels must be finite."},
{"interp.rsd_err_invalid_center",
 "中心值必须有限且落在 [low, high] 内。",
 "Center must be finite and within [low, high]."},
{"interp.ccd_err_invalid_alpha",
 "alpha 必须为正有限数。",
 "alpha must be a positive finite number."},
{"diag.prefix.correlation",
 "相关分析：",
 "Correlation: "},
{"diag.prefix.one_sample_t",
 "单样本 t：",
 "One-sample t: "},
{"diag.prefix.one_sample_z",
 "单样本 Z：",
 "One-sample Z: "},
{"diag.prefix.two_sample_t",
 "双样本 t：",
 "Two-sample t: "},
{"diag.prefix.first_group",
 "第一组：",
 "Group 1: "},
{"diag.prefix.second_group",
 "第二组：",
 "Group 2: "},
{"diag.prefix.capability",
 "能力分析: ",
 "Capability: "},
{"diag.prefix.response_opt_prediction",
 "响应优化预测：",
 "Response optimization prediction: "},
{"interp.acceptance_err_n_ge_1",
 "样本量 n 必须 ≥ 1。",
 "Sample size n must be ≥ 1."},
{"interp.acceptance_err_c_gt_n",
 "接收数 c 不能大于样本量 n。",
 "Acceptance number c cannot exceed sample size n."},
{"interp.acceptance_warn_lot_lt_n",
 "批大小 N < n；本轮仍用二项 OC（无限批近似）。",
 "Lot size N < n; this run still uses binomial OC (infinite-lot approximation)."},
{"interp.anom_warn_unequal_n",
 "各组样本量不等；决策限仍用总 N 近似，解读需谨慎。",
 "Group sizes are unequal; decision limits still use total-N approximation—interpret with care."},
{"interp.anom_warn_limits_approx",
 "决策限采用正态/多重比较近似（formula_reference），不是 Minitab exact h 表 golden。",
 "Decision limits use a normal/multiple-comparison approximation (formula_reference), not a Minitab exact h-table golden."},
{"interp.poisson_gof_err_nonneg_int",
 "泊松拟合优度要求非负整数计数。",
 "Poisson GOF requires non-negative integer counts."},
{"interp.poisson_gof_err_need_two",
 "至少需要 2 个有效计数。",
 "At least 2 valid counts are required."},
{"interp.poisson_gof_err_too_few_bins",
 "合并后类别不足，无法计算拟合优度。",
 "Too few categories after merging; GOF cannot be computed."},
{"interp.poisson_gof_err_df_lt_1",
 "自由度 < 1（类别过少）。",
 "Degrees of freedom < 1 (too few categories)."},
{"interp.poisson_gof_warn_expected_lt5",
 "存在期望频数 < 5，卡方近似需谨慎。",
 "Some expected frequencies are < 5; treat the chi-square approximation with caution."},
{"interp.design_gen_failed",
 "设计生成失败。",
 "Design generation failed."},
{"interp.arima_warn_aicc_unavailable",
 "有效样本不足以进行 AICc 小样本修正，已返回未修正的 AIC。",
 "Effective sample size is too small for AICc small-sample correction; uncorrected AIC is returned."},
{"interp.arima_warn_near_zero_sse",
 "残差平方和接近零，信息准则使用数值下限稳定计算。",
 "Residual sum of squares is near zero; information criteria use a numeric floor for stability."},
{"interp.arima_err_ar1_fit_failed",
 "AR(1) 拟合失败。",
 "AR(1) fit failed."},
{"interp.arima_err_ma1_fit_failed",
 "MA(1) 拟合失败。",
 "MA(1) fit failed."},
{"interp.arima_err_insufficient_differenced",
 "差分后样本不足以拟合 ARIMA 阶数。",
 "Differenced sample is insufficient to fit the requested ARIMA order."},
{"interp.arima_err_ar_fit_rank_deficient",
 "AR 拟合失败或设计矩阵秩亏。",
 "AR fit failed or the design matrix is rank-deficient."},
{"interp.arima_err_ma_fit_failed",
 "MA 拟合失败。",
 "MA fit failed."},
{"interp.arima_err_no_mixed_arma_candidates",
 "当前仅支持 AR(p,d,0) 与 MA(0,d,q) 候选，不含混合 ARMA 阶。",
 "Only AR(p,d,0) and MA(0,d,q) candidates are supported; mixed ARMA orders are not included."},
{"interp.arima_err_insufficient_samples",
 "ARIMA 候选要求更多的有限观测值才能拟合。",
 "More finite observations are required to fit this ARIMA candidate."},
{"interp.arima_err_forecast_horizon_gt0",
 "预测期数必须大于零。",
 "Forecast horizon must be greater than zero."},
{"interp.arima_err_nonfinite_observations",
 "观测序列必须全部为有限数值。",
 "All observations in the series must be finite."},
{"interp.arima_err_nonfinite_result",
 "模型计算产生了非有限结果，请检查数据尺度后重试。",
 "Model computation produced non-finite results; check data scale and retry."},
{"interp.arima_err_order_bounds",
 "仅支持 p/q≤3、d≤2 的有限阶 ARIMA。",
 "Only finite ARIMA orders with p/q≤3 and d≤2 are supported."},
{"interp.arima_err_degenerate_000",
 "ARIMA(0,0,0) 不在候选网格内。",
 "ARIMA(0,0,0) is not in the candidate grid."},
{"interp.arima_err_mixed_arma_not_in_grid",
 "混合 ARMA 阶尚未纳入 Best ARIMA 网格。",
 "Mixed ARMA orders are not yet included in the Best ARIMA grid."},
{"interp.arima_warn_css_aicc_not_minitab",
 "Best ARIMA 候选基于条件最小二乘与差分尺度 AICc；与 Minitab 迭代最小二乘（Meeker TSERIES）的最优阶可能不同。",
 "Best ARIMA candidates use conditional least squares and differenced-scale AICc; the selected order may differ from Minitab iterative least squares (Meeker TSERIES)."},
{"interp.chart_no_displayable_data_suffix",
 "没有可显示的数据。",
 " has no displayable data."},
{"chart.no_displayable_data",
 "没有可显示的数据",
 "No displayable data"},
{"interp.ccd_err_min_factors",
 "CCD 至少需要 2 个连续因素。",
 "CCD requires at least 2 continuous factors."},
{"interp.ccd_err_ccc_beyond_range",
 "CCC 星点超出原始因素范围；请允许超范围星点，或改用 CCI/CCF。",
 "CCC axial points exceed original factor ranges; allow beyond-range axials, or use CCI/CCF."},
{"interp.ccd_info_ccc_beyond_allowed",
 "CCC 星点超出原始 low/high；已按允许超范围策略生成，实验可行性需人工确认。",
 "CCC axial points exceed original low/high; generated under allow-beyond-range policy—experimental feasibility needs human confirmation."},
{"interp.bbd_err_factor_count",
 "BBD 第一阶段支持 3–7 个连续因素；2 因素不接受。",
 "Phase-1 BBD supports 3–7 continuous factors; 2 factors are not accepted."},
{"interp.bbd_info_no_corners",
 "BBD 不包含所有因素同时处于极端水平的角点；这是设计空间边界，不是实现缺陷。",
 "BBD omits corners where all factors are at extreme levels; this is a design-space boundary, not an implementation defect."},
{"interp.doe_warn_no_pure_error",
 "没有重复运行，无法估计纯误差和失拟。",
 "No replicate runs; pure error and lack of fit cannot be estimated."},
{"interp.doe_warn_lof_df_zero",
 "纯误差占用了全部残差自由度，无法检验失拟。",
 "Pure error uses all residual degrees of freedom; lack of fit cannot be tested."},
{"interp.doe_warn_curvature_no_pe",
 "中心点与角点均存在，但没有可用纯误差无法检验曲率。",
 "Center and corner points are present, but curvature cannot be tested without usable pure error."},
{"interp.doe_info_no_curvature_test",
 "设计没有中心点，未执行曲率检验。",
 "Design has no center points; curvature test was not performed."},
{"interp.doe_err_need_response_factors",
 "请选择响应列和至少一个设计因子列。",
 "Select a response column and at least one design factor column."},
{"interp.doe_err_no_valid_runs",
 "没有可用于响应分析的有效 DOE 运行。",
 "No valid DOE runs available for response analysis."},
{"interp.rsd_err_need_continuous_factor",
 "请提供至少一个连续因素。",
 "Provide at least one continuous factor."},
{"interp.doe_warn_missing_run",
 "存在缺少有效因子水平的运行，已跳过。",
 "Runs missing valid factor levels were skipped."},
{"interp.doe_info_center_imported",
 "已按 PointType/中心水平导入中心点运行，可用于曲率与纯误差。",
 "Center-point runs were imported via PointType/center levels and can be used for curvature and pure error."},
{"interp.rsm_factors_already_coded",
 "因子值均在 [-1,1]，按已编码单位拟合 RSM。",
 "Factor values are already in [-1,1]; fitting RSM in coded units."},
{"interp.rsm_factor_no_variation",
 "至少一个因子无变异，无法编码。",
 "At least one factor has no variation and cannot be coded."},
{"interp.rsm_factors_minmax_coded",
 "因子已按列内 min/max 线性编码到 [-1,1]。",
 "Factors were linearly coded to [-1,1] using each column’s min/max."},
{"interp.rsm_design_bounds_incomplete",
 "设计编码边界与因子数不匹配。",
 "Design coding bounds do not match the number of factors."},
{"interp.rsm_design_bounds_invalid",
 "设计低/高水平必须有限且 low < high。",
 "Design low/high levels must be finite with low < high."},
{"interp.rsm_design_center_invalid",
 "设计中心必须落在 [low, high] 内。",
 "Design center must lie within [low, high]."},
{"interp.rsm_factors_design_bounds_coded",
 "因子已按设计 low/high/center 编码（与 CCD/BBD 一致）。",
 "Factors were coded with design low/high/center (consistent with CCD/BBD)."},
{"interp.rsm_err_shape",
 "RSM 需要响应与因子行数一致，且至少两个因子。",
 "RSM requires matching response and factor row counts and at least two factors."},
{"interp.rsm_err_ragged_factors",
 "每行因子列数必须一致。",
 "Each row must have the same number of factor columns."},
{"interp.rsm_replicated_coded_points",
 "检测到重复编码点，已用于纯误差 / 失拟估计。",
 "Replicated coded points detected; used for pure-error / lack-of-fit estimation."},
{"interp.rsm_insufficient_pure_error",
 "没有重复编码点，无法估计纯误差和失拟；不得用残差 MS 冒充纯误差。",
 "No replicated coded points; cannot estimate pure error or lack of fit—do not present residual MS as pure error."},
{"interp.rsm_lof_formula_reference_only",
 "失拟 ANOVA 证据类型 formula_reference；不是 vendor_oracle。",
 "Lack-of-fit ANOVA evidence_type is formula_reference; not vendor_oracle."},
{"interp.rsm_pure_error_exceeds_residual_df",
 "纯误差自由度大于残差自由度，跳过失拟分解（可能模型过参或重复点过多）。",
 "Pure-error DF exceeds residual DF; skipping lack-of-fit decomposition (possible over-parameterization or excess replicates)."},
{"interp.rsm_err_invalid_grid",
 "等值线需要两个不同因子且模型已拟合。",
 "Contours require two distinct factors and a fitted model."},
{"interp.rel_err_shape",
 "寿命和删失指示列长度必须一致且至少包含两条记录。",
 "Lifetime and censoring indicator columns must have equal length and at least two records."},
{"interp.rel_err_time_positive",
 "寿命必须为有限正数。",
 "Lifetime values must be finite and positive."},
{"interp.weibull_err_all_censored",
 "全为删失，无法识别 Weibull 参数。",
 "All observations are censored; Weibull parameters are not identifiable."},
{"interp.weibull_err_one_failure",
 "只有一条失效记录时 Weibull 形状参数通常不可稳定识别。",
 "With only one failure, the Weibull shape is usually not stably identifiable."},
{"interp.weibull_err_no_variation",
 "失效时间没有足够变化，无法有限地识别 Weibull 形状。",
 "Failure times lack enough variation to identify a finite Weibull shape."},
{"interp.rel_err_confidence",
 "置信水平必须在 0 和 1 之间。",
 "Confidence level must be between 0 and 1."},
{"interp.km_err_all_censored",
 "全为删失，无法识别失效分布或中位寿命。",
 "All observations are censored; failure distribution and median life are not identifiable."},
{"interp.km_warn_tail_not_to_zero",
 "最大观测为删失，尾部生存函数不可估计到 0。",
 "The largest observation is censored; the survival curve may not reach 0 in the tail."},
{"interp.logrank_err_shape",
 "Log-rank 检验要求寿命、事件和分组列长度一致。",
 "Log-rank requires equal-length lifetime, event, and group columns."},
{"interp.logrank_err_values",
 "Log-rank 时间必须为正数，分组必须编码为 0 或 1。",
 "Log-rank times must be positive and groups must be coded 0 or 1."},
{"interp.logrank_err_two_groups",
 "Log-rank 检验至少需要两个非空分组。",
 "Log-rank requires at least two non-empty groups."},
{"interp.logrank_err_zero_variance",
 "分组失效模式没有可估计的 Log-rank 方差。",
 "Group failure pattern yields no estimable Log-rank variance."},
{"interp.weibull3_err_few_failures",
 "三参数 Weibull 至少需要三次失效才能识别阈值。",
 "Three-parameter Weibull needs at least three failures to identify the threshold."},
{"interp.weibull3_err_no_variation",
 "失效时间没有足够变化，无法识别三参数 Weibull。",
 "Failure times lack enough variation to identify three-parameter Weibull."},
{"interp.weibull3_err_unbounded",
 "三参数 Weibull 似然无界（常见于形状 ≤ 1）；不估计阈值，也不伪造参数。",
 "Three-parameter Weibull likelihood is unbounded (often when shape ≤ 1); threshold is not estimated and parameters are not invented."},
{"interp.weibull3_err_no_interior",
 "未能找到形状大于 1 的有限三参数 Weibull 估计。",
 "No finite three-parameter Weibull estimate with shape > 1 was found."},
{"interp.exp_err_need_failure",
 "指数模型至少需要一条失效记录。",
 "The exponential model requires at least one failure."},
{"interp.exp2_err_need_failure",
 "两参数指数至少需要一条失效记录。",
 "Two-parameter exponential requires at least one failure."},
{"interp.exp2_err_unbounded_variation",
 "失效时间没有足够变化，两参数指数似然无界；不估计阈值，也不伪造参数。",
 "Failure times lack enough variation; two-parameter exponential likelihood is unbounded—threshold is not estimated and parameters are not invented."},
{"interp.exp2_err_no_threshold",
 "两参数指数未能找到有限阈值估计；不伪造参数。",
 "Two-parameter exponential found no finite threshold estimate; parameters are not invented."},
{"interp.lognormal_err_all_censored",
 "全为删失，无法识别对数正态参数。",
 "All observations are censored; lognormal parameters are not identifiable."},
{"interp.lognormal_err_one_failure",
 "只有一条失效记录时对数正态尺度通常不可稳定识别。",
 "With only one failure, the lognormal scale is usually not stably identifiable."},
{"interp.lognormal3_err_few_failures",
 "三参数对数正态至少需要两次失效才能识别阈值。",
 "Three-parameter lognormal needs at least two failures to identify the threshold."},
{"interp.lognormal3_err_unbounded_variation",
 "失效时间没有足够变化，三参数对数正态似然无界；不估计阈值，也不伪造参数。",
 "Failure times lack enough variation; three-parameter lognormal likelihood is unbounded—threshold is not estimated and parameters are not invented."},
{"interp.lognormal3_err_unbounded",
 "三参数对数正态似然无界；不估计阈值，也不伪造参数。",
 "Three-parameter lognormal likelihood is unbounded; threshold is not estimated and parameters are not invented."},
{"interp.lognormal3_err_no_interior",
 "未能找到有限的三参数对数正态估计。",
 "No finite three-parameter lognormal estimate was found."},
{"interp.logistic_hl_not_computed",
 "Hosmer–Lemeshow 在样本量不足、未收敛或完全分离时不计算。",
 "Hosmer–Lemeshow is not computed when the sample is too small, the fit did not converge, or complete separation is present."},
{"interp.logistic_hl_low_group_variance",
 "Hosmer–Lemeshow 分组期望方差过小，检验不可用。",
 "Hosmer–Lemeshow group expected variance is too small; the test is unavailable."},
{"interp.logistic_hl_too_few_groups",
 "Hosmer–Lemeshow 有效组数不足，检验不可用。",
 "Too few usable Hosmer–Lemeshow groups; the test is unavailable."},
{"interp.logistic_err_need_obs_predictor",
 "二元 Logistic 回归至少需要三个观测和一个预测变量。",
 "Binary logistic regression requires at least three observations and one predictor."},
{"interp.logistic_err_invalid_options",
 "置信水平、收敛容差和最大迭代次数必须有效。",
 "Confidence level, convergence tolerance, and maximum iterations must be valid."},
{"interp.logistic_err_label_count",
 "预测变量标签数量必须与预测变量列数一致。",
 "The number of predictor labels must match the number of predictor columns."},
{"interp.logistic_err_binary_response",
 "响应变量必须全部为 0 或 1。",
 "All response values must be 0 or 1."},
{"interp.logistic_err_need_more_obs_than_params",
 "Logistic 回归需要多于参数数量的观测。",
 "Logistic regression requires more observations than parameters."},
{"interp.logistic_err_rank_deficient_info",
 "Logistic 信息矩阵秩亏，无法进行 IRLS 更新。",
 "The logistic information matrix is rank-deficient; IRLS cannot update."},
{"interp.logistic_warn_eta_clipped",
 "线性预测量达到数值稳定性边界，概率已进行安全截断。",
 "The linear predictor reached a numeric stability bound; probabilities were safely clipped."},
{"interp.logistic_warn_irls_not_converged",
 "IRLS 在最大迭代次数内未达到收敛容差。",
 "IRLS did not reach the convergence tolerance within the maximum iterations."},
{"interp.logistic_warn_complete_separation",
 "预测变量完全分离了 0/1 响应，极大似然估计可能不存在。",
 "Predictors completely separate the 0/1 response; the MLE may not exist."},
{"interp.logistic_warn_quasi_separation",
 "预测概率达到边界，模型可能存在准分离。",
 "Predicted probabilities reached the boundary; the model may have quasi-separation."},
{"interp.logistic_err_cov_failed",
 "无法计算 Logistic 系数协方差矩阵。",
 "Unable to compute the logistic coefficient covariance matrix."},
{"interp.poisson_reg_err_need_obs_predictor",
 "Poisson 回归至少需要三个观测和一个预测变量。",
 "Poisson regression requires at least three observations and one predictor."},
{"interp.poisson_reg_err_invalid_response",
 "响应必须为非负有限值，且预测矩阵规整。",
 "Responses must be non-negative and finite, and the predictor matrix must be well-formed."},
{"interp.poisson_reg_err_nonfinite_predictor",
 "预测变量含非有限值。",
 "Predictors contain non-finite values."},
{"interp.poisson_reg_err_singular_info",
 "IRLS 信息矩阵奇异。",
 "The IRLS information matrix is singular."},
{"interp.glm_warn_max_iterations",
 "已达最大迭代次数。",
 "Maximum iterations reached."},
{"interp.poisson_reg_warn_cov_failed",
 "无法计算系数协方差。",
 "Unable to compute coefficient covariances."},
{"interp.stepwise_err_need_obs_candidates",
 "逐步回归需要 ≥4 观测与 ≥2 候选预测变量。",
 "Stepwise regression requires ≥4 observations and ≥2 candidate predictors."},
{"interp.stepwise_err_alpha_range",
 "α_enter / α_remove 必须在 (0,1)。",
 "α_enter / α_remove must be in (0,1)."},
{"interp.stepwise_warn_alpha_order",
 "α_remove < α_enter 可能导致振荡；仍继续。",
 "α_remove < α_enter may cause oscillation; continuing anyway."},
{"interp.stepwise_warn_intercept_only",
 "未选入任何预测变量（仅截距）。",
 "No predictors were selected (intercept only)."},
{"interp.ordinal_err_need_obs_levels",
 "有序 Logistic 需要 ≥10 观测、≥3 有序水平与 ≥1 预测变量。",
 "Ordinal logistic requires ≥10 observations, ≥3 ordered levels, and ≥1 predictor."},
{"interp.ordinal_err_bad_category_code",
 "响应类别编码越界。",
 "Response category code is out of range."},
{"interp.ordinal_err_singular_info",
 "有序 Logistic 信息矩阵奇异。",
 "The ordinal logistic information matrix is singular."},
{"interp.spc_rule1_beyond_3sigma",
 "检测到 1 点超出 3σ 控制限，建议复核该观测、测量和记录过程。",
 "Detected 1 point beyond the 3σ control limits; review that observation, the measurement, and the recording process."},
{"interp.spc_rule2_nine_same_side",
 "检测到连续 9 点位于中心线同侧，建议复核阶段、设备或批次因素。",
 "Detected 9 consecutive points on the same side of the center line; review stage, equipment, or batch factors."},
{"interp.spc_rule3_six_trend",
 "检测到连续 6 点单调上升或下降，建议复核趋势、刀具磨损或过程漂移。",
 "Detected 6 consecutive points rising or falling monotonically; review trend, tool wear, or process drift."},
{"interp.spc_rule4_fourteen_alternating",
 "检测到连续 14 点上下交替，建议复核系统性周期或两台设备交替影响。",
 "Detected 14 consecutive points alternating up and down; review systematic cycles or alternating equipment effects."},
};

}  // namespace

void append_report_text_catalog_part13(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart13),
        std::end(kReportTextCatalogPart13));
}

}  // namespace datalab::domain
