#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart17[] = {
{"interp.rf_summary",
 "随机森林：任务 = %1，N = %2，树数 = %3。训练集指标不能外推为过程合格。",
 "Random forest: task = %1, N = %2, trees = %3. Training metrics must not be extrapolated to process acceptance."},
{"interp.rf_importance",
 "变量重要性以平均不纯度下降汇总；仅描述相对分裂贡献。",
 "Variable importance aggregates mean impurity decrease; it only describes relative split contribution."},
{"interp.rf_disclosure",
 "Bagging CART 集成；非 TreeNet / Minitab Random Forests 数值对齐。",
 "Bagging CART ensemble; not TreeNet / Minitab Random Forests numeric alignment."},
{"interp.rf_honesty",
 "禁止 TreeNet/Minitab RF对齐 / 过程合格。",
 "Forbid TreeNet/Minitab RF alignment / process acceptance claims."},
{"interp.weibayes_summary",
 "Weibayes：N = %1，失效 r = %2，形状先验 β = %3。",
 "Weibayes: N = %1, failures r = %2, shape prior β = %3."},
{"interp.weibayes_shape_prior",
 "形状先验固定；η 由 Σ t_i^β / r 估计（r≥1）。",
 "Shape prior is fixed; η is estimated from Σ t_i^β / r when r≥1."},
{"interp.weibayes_limits",
 "少失效/无失效走诚实边界；禁止「寿命已达标」。",
 "Few/zero-failure paths stay honest; forbid life-target-met claims."},
{"interp.taguchi_design_summary",
 "Taguchi 正交设计：阵列 = %1，因子 = %2，运行 = %3。",
 "Taguchi orthogonal design: array = %1, factors = %2, runs = %3."},
{"interp.taguchi_export_hint",
 "设计矩阵可写入工作表；新表不携带旧 excluded_rows/hidden_rows。",
 "Design matrix can be written to a worksheet; new sheet does not carry old excluded_rows/hidden_rows."},
{"interp.taguchi_scope",
 "仅设计生成，不是完整 Taguchi ANOVA / SN 分析。",
 "Design generation only; not full Taguchi ANOVA / SN analysis."},
{"interp.distcalc_result",
 "分布计算器：%1 / %2 ≈ %3。",
 "Distribution calculator: %1 / %2 ≈ %3."},
{"interp.distcalc_params",
 "参数：p1=%1，p2=%2，输入=%3。",
 "Parameters: p1=%1, p2=%2, input=%3."},
{"interp.distcalc_scope",
 "工具计算 PDF/CDF/分位；不改 GOF 数值核；禁止「分布已正态」。",
 "Tool computes PDF/CDF/quantile; does not change GOF numeric cores; forbid distribution-already-normal claims."},
{"interp.taguchi_analyze_summary",
 "Taguchi 分析：S/N = %1，因子 = %2，运行 = %3。",
 "Taguchi analyze: S/N = %1, factors = %2, runs = %3."},
{"interp.taguchi_analyze_sn",
 "信噪比响应表给出水平均值、Delta 与 Rank；仅描述相对效应。",
 "S/N response table gives level means, Delta, and Rank; relative effects only."},
{"interp.taguchi_analyze_scope",
 "静态 Taguchi；禁止「过程已优化 / 已合格」。",
 "Static Taguchi only; forbid process-optimized / qualified claims."},
{"interp.mixture_design_summary",
 "Mixture 设计：simplex-lattice m=%1，q=%2，N=%3。",
 "Mixture design: simplex-lattice m=%1, q=%2, N=%3."},
{"interp.mixture_design_export_hint",
 "设计矩阵可写入工作表；新表不携带旧 excluded_rows/hidden_rows。",
 "Design matrix can be written to a worksheet; new sheet does not carry old excluded/hidden rows."},
{"interp.mixture_design_scope",
 "仅设计生成；非 Scheffé 分析。",
 "Design generation only; not Scheffé analysis."},
{"interp.nhpp_summary",
 "可修复 NHPP：n=%1，T=%2，β≈%3。",
 "Repairable NHPP: n=%1, T=%2, β≈%3."},
{"interp.nhpp_params",
 "Crow–AMSAA MLE 参数；强度/M(t) 供趋势阅读。",
 "Crow–AMSAA MLE parameters; intensity/M(t) for trend reading."},
{"interp.nhpp_scope",
 "幂律 NHPP 窄化；禁止「ROCOF合格 / 已证明稳定」。",
 "Power-law NHPP only; forbid ROCOF-qualified / proven-stable claims."},
{"interp.rtp_summary",
 "可靠性试验计划：β=%1，R=%2，CL=%3，n=%4。",
 "Reliability test plan: β=%1, R=%2, CL=%3, n=%4."},
{"interp.rtp_assumptions",
 "β 为工程假设；演示型计划，非寿命估计。",
 "β is an engineering assumption; demonstration plan, not life estimation."},
{"interp.rtp_scope",
 "禁止「寿命已达标 / 过程已优化」。",
 "Forbid life-target-met / process-optimized claims."},
};

}  // namespace

void append_report_text_catalog_part17(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart17),
        std::end(kReportTextCatalogPart17));
}

}  // namespace datalab::domain
