#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart10[] = {
{"rule.anova.catalog.homogeneity.name",
 "方差齐性",
 "Homogeneity of variance"},
{"rule.anova.catalog.homogeneity.message",
 "Levene/组内标准差比较只作为调查证据。",
 "Levene/within-group SD comparison is investigation evidence only."},
{"rule.anova.catalog.family_error_rate.name",
 "家族错误率",
 "Family error rate"},
{"rule.anova.catalog.family_error_rate.message",
 "Tukey 必须回显同时置信水平和调整后 p 值。",
 "Tukey must echo simultaneous confidence level and adjusted p-values."},
{"rule.anova.catalog.unbalanced_design.name",
 "不平衡设计",
 "Unbalanced design"},
{"rule.anova.catalog.unbalanced_design.message",
 "不平衡时 Sequential SS 与 Adjusted SS 可能不同。",
 "Sequential SS and Adjusted SS may differ when unbalanced."},
{"rule.msa.catalog.design_balance.message",
 "零件×操作员单元重复次数必须一致。",
 "Replicate counts must be equal for every part×operator cell."},
{"rule.msa.catalog.negative_variance.name",
 "负方差分量",
 "Negative variance components"},
{"rule.msa.catalog.negative_variance.message",
 "保留截断前后方差分量，截断后用于 %Contribution。",
 "Keep pre- and post-truncation components; truncated values feed %Contribution."},
{"rule.msa.catalog.interaction_model.name",
 "交互项模型",
 "Interaction model"},
{"rule.msa.catalog.interaction_model.message",
 "报告 Part×Operator 显著性，不自动缩减模型。",
 "Report Part×Operator significance; do not auto-reduce the model."},
{"rule.msa.catalog.percent_metrics.name",
 "百分比口径",
 "Percent metrics"},
{"rule.msa.catalog.percent_metrics.message",
 "%Contribution 与 %Study Var 不可混用。",
 "%Contribution and %Study Var must not be mixed."},
{"rule.msa.catalog.invalid_tolerance.name",
 "无效容差",
 "Invalid tolerance"},
{"rule.msa.catalog.invalid_tolerance.message",
 "无有效公差时不计算 %Tolerance。",
 "Do not compute %Tolerance without a valid tolerance."},
{"rule.msa.catalog.zero_repeatability.name",
 "零重复性",
 "Zero repeatability"},
{"rule.msa.catalog.zero_repeatability.message",
 "Type 1 零重复性不输出伪造 p=0 推断。",
 "Type 1 zero repeatability must not emit fabricated p=0 inference."},
{"rule.reliability.catalog.event_encoding.name",
 "事件编码",
 "Event encoding"},
{"rule.reliability.catalog.event_encoding.message",
 "只接受明确的失效/删失语义，拒绝未知编码。",
 "Accept only explicit failure/censor semantics; reject unknown codes."},
{"rule.reliability.catalog.time_validity.name",
 "时间合法性",
 "Time validity"},
{"rule.reliability.catalog.time_validity.message",
 "寿命必须为有限正数。",
 "Lifetime must be a finite positive number."},
{"rule.reliability.catalog.risk_set.name",
 "风险集",
 "Risk set"},
{"rule.reliability.catalog.risk_set.message",
 "同一时刻多个失效应合并，并报告 at-risk/failures/censored。",
 "Merge simultaneous failures and report at-risk/failures/censored."},
{"rule.reliability.catalog.identifiability.name",
 "可识别性",
 "Identifiability"},
{"rule.reliability.catalog.identifiability.message",
 "全删失或最大观测删失时尾部指标可能不可估计。",
 "Tail metrics may be inestimable when all censored or max observation is censored."},
{"rule.reliability.catalog.convergence.name",
 "参数收敛",
 "Parameter convergence"},
{"rule.reliability.catalog.convergence.message",
 "Weibull 必须回显收敛、边界命中和估计方法。",
 "Weibull must echo convergence, boundary hits, and estimation method."},
{"header.rule_name_col",
 "名称",
 "Name"},
{"header.evidence",
 "证据",
 "Evidence"},
{"header.related_rows",
 "关联行",
 "Related rows"},
{"header.suggestion",
 "建议",
 "Suggestion"},
{"interp.msa_empty",
 "MSA 结果表为空，不能判定偏倚、线性或 Type 1 能力。",
 "MSA result table is empty; bias, linearity, or Type 1 capability cannot be judged."},
{"interp.gage_stability_no_points",
 "没有可用的超限点统计，不能判定量具稳定性。",
 "No out-of-control point statistics are available; gage stability cannot be judged."},
{"interp.gage_stability_clear_not_capability",
 "当前观测未发现稳定性图超限点；这不等同于量具满足能力要求。",
 "No stability-chart out-of-control points were found in the current observations; this does not mean the gage meets capability requirements."},
{"interp.evidence_type_not_vendor",
 "证据类型 %1；非 vendor_oracle。",
 "Evidence type %1; not vendor_oracle."},
{"interp.km_curve_summary",
 "Kaplan-Meier 曲线基于 %1 个时间点；删失数合计 %2。",
 "Kaplan-Meier curve is based on %1 time point(s); total censored count %2."},
{"interp.warranty_summary_line",
 "保修摘要：T_w = %1 %2，暴露量 = %3，claims/1000 = %4（口径 = %5）。",
 "Warranty summary: T_w = %1 %2, exposure = %3, claims/1000 = %4 (quantity = %5)."},
{"interp.analysis_error_prefix",
 "分析错误，以下结论不可用于决策：%1",
 "Analysis error; the following conclusions must not be used for decisions: %1"},
{"interp.analysis_limitation_prefix",
 "分析限制：%1",
 "Analysis limitation: %1"},
{"interp.weibull_shape_line",
 "Weibull 形状参数 β = %1%2",
 "Weibull shape parameter β = %1%2"},
{"interp.weibull_shape_tip_rising",
 "，提示失效率随时间上升。",
 ", suggesting the failure rate rises over time."},
{"interp.weibull_shape_tip_falling",
 "，提示早期失效型失效率随时间下降。",
 ", suggesting an early-failure failure rate that decreases over time."},
{"interp.weibull_shape_tip_constant",
 "，接近恒定失效率。",
 ", near a constant failure rate."},
{"interp.weibull_threshold_percentile",
 "阈值 λ = %1；百分位寿命按 t_p = λ + α[-ln(1-p)]^(1/β) 计算。",
 "Threshold λ = %1; percentile life uses t_p = λ + α[-ln(1-p)]^(1/β)."},
{"interp.exp_two_param_threshold",
 "两参数指数估计了阈值 λ = %1 后的恒定失效率。",
 "Two-parameter exponential estimates a constant failure rate after threshold λ = %1."},
{"interp.lognormal_three_param_threshold",
 "三参数对数正态估计了阈值 λ = %1；分位寿命按 λ + exp(μ + σ Φ⁻¹(p)) 计算。",
 "Three-parameter lognormal estimates threshold λ = %1; percentile life uses λ + exp(μ + σ Φ⁻¹(p))."},
{"interp.lognormal_two_param_summary",
 "对数正态模型估计了右删失下的位置/尺度参数；分位寿命由 exp(μ + σ Φ⁻¹(p)) 给出。",
 "The lognormal model estimates location/scale under right censoring; percentile life is given by exp(μ + σ Φ⁻¹(p))."},
{"interp.doe_opt_no_prediction_interval",
 "缺协方差或残差自由度不足，置信/预测区间不可用；不要仅凭点预测确定最优设置。",
 "Covariance or residual degrees of freedom are insufficient; confidence/prediction intervals are unavailable—do not set the optimum from the point prediction alone."},
{"interp.doe_no_pvalue",
 "DOE 表中没有可用的 P-Value；不能据此宣称因子或交互作用显著。",
 "The DOE table has no usable P-Value; do not claim factor or interaction significance from it."},
{"interp.doe_confirm_significant",
 "优先在确认性试验中复核显著项，并结合效应方向选择可操作的因子水平；显著性本身不代表工程影响足够大。",
 "Re-check significant terms in confirmatory trials and choose operable factor levels with effect direction; significance alone does not mean engineering impact is large enough."},
{"interp.doe_no_cube_plot",
 "未生成立方图（仅支持 2–3 个因子）；高维设计请结合 Pareto 与主效应/交互图。",
 "Cube plot was not generated (only 2–3 factors supported); for higher-dimensional designs combine Pareto with main-effect/interaction plots."},
{"interp.doe_residual_plots",
 "残差图供调查残差形态；直方图不用于证明正态。",
 "Residual plots are for investigating residual patterns; histograms are not used to prove normality."},
{"interp.doe_contour_coded_space",
 "等值线/曲面在编码 [-1,1] 空间求值；非轴因子默认 hold 编码 0，也可按实际单位 hold；二水平模型无平方项，不能把曲面曲率当成已估计。",
 "Contours/surfaces are evaluated in coded [-1,1] space; non-axis factors default to coded hold 0 (or actual-unit hold); two-level models have no quadratic terms—do not treat surface curvature as estimated."},
{"interp.doe_check_residuals_before_opt",
 "检查残差随机性、异常值和重复/纯误差后再确定最优设置；不要仅凭主效应图下结论。",
 "Check residual randomness, outliers, and replicate/pure error before choosing optimal settings; do not conclude from main-effect plots alone."},
{"interp.doe_rank_deficient",
 "设计矩阵秩亏，回归系数不可解释。",
 "The design matrix is rank-deficient; regression coefficients are not interpretable."},
{"interp.doe_no_center_pure_error",
 "未检测到中心点；纯误差估计可能不可用。",
 "No center points detected; pure-error estimation may be unavailable."},
{"interp.doe_lof_df_insufficient",
 "有纯误差但失拟自由度不足，未给出失拟 F/P。",
 "Pure error exists but lack-of-fit degrees of freedom are insufficient; LOF F/P was not reported."},
{"interp.doe_axial_beyond_range",
 "检测到星点超出原始因素范围；需人工确认实验可行性。",
 "Axial points beyond the original factor ranges were detected; confirm experimental feasibility manually."},
{"interp.doe_unestimable_terms",
 "存在不可估计项或误差自由度不足，这些项不输出伪造 F/P。",
 "Unestimable terms or insufficient error df are present; forged F/P values are not emitted for those terms."},
{"interp.doe_error_df_insufficient",
 "误差自由度不足，不输出 t、F 与 P。",
 "Error degrees of freedom are insufficient; t, F, and P are not emitted."},
{"interp.rsm_coded_coeffs",
 "RSM 系数在编码单位；显著不等于已找到工程最优设定。",
 "RSM coefficients are in coded units; significance does not mean an engineering optimum was found."},
{"interp.rsm_static_surface",
 "曲面图为静态栅格，不是可旋转交互 3D。",
 "The surface plot is a static grid, not an interactive rotatable 3D view."},
{"interp.rsm_check_model_adequacy",
 "请结合残差与拟合值/顺序/正态/直方图判断模型充分性。",
 "Judge model adequacy using residuals with fitted/order/normal/histogram diagnostics together."},
{"interp.msa_negative_variance",
 "存在负方差分量并已截断为 0；解释时应同时查看原始估计。",
 "Negative variance components were truncated to 0; review the raw estimates when interpreting."},
{"interp.msa_by_part_plot",
 "按零件图展示各零件重复测量的离散程度；同一零件上点越集中表示重复性越小。该图不单独判定量具是否合格。",
 "The by-part plot shows within-part repeat scatter; tighter points on a part mean smaller repeatability. The plot alone does not pass/fail the gage."},
{"interp.msa_study_tol_together",
 "将 %Study Var、%Tolerance 和现场公差一起看，不要把单个百分比写成量具合格。",
 "Read %Study Var, %Tolerance, and field tolerance together; do not write a single percentage as gage pass."},
{"interp.msa_bias_linearity_incomplete",
 "偏倚/线性表缺少斜率或端点偏倚，不能作完整判定。",
 "The bias/linearity table lacks slope or endpoint bias; a complete judgment cannot be made."},
{"interp.msa_compare_endpoint_bias",
 "将端点偏倚与产品公差和测量系统可接受界限比较；回归关系不能替代跨操作者、跨部件的完整 Gage R&R。",
 "Compare endpoint bias with product tolerance and MSA acceptance limits; regression does not replace full cross-operator/part Gage R&R."},
{"interp.msa_stability_investigate",
 "按时间顺序回查校准、环境、操作者和量具维护记录；不要在特殊原因未排除前用该量具放行产品。",
 "Review calibration, environment, operators, and gage maintenance in time order; do not release product with this gage until special causes are cleared."},
{"interp.msa_appraiser_part_not_pass",
 "评估者×零件图是观察一致率，不是量具通过或已证明一致。",
 "The appraiser×part plot shows observed agreement rates, not gage pass or proven agreement."},
{"interp.msa_type1_incomplete",
 "Type 1 表缺少 P 或 Cgk，不能完整评价偏倚与重复性。",
 "The Type 1 table lacks P or Cgk; bias and repeatability cannot be fully evaluated."},
{"interp.msa_emp_icc",
 "EMP Crossed：ICC(with interaction) = %1，分级 = %2。这是 Wheeler 监控能力分级，不是 AIAG 合格判定，不能写成量具合格。",
 "EMP Crossed: ICC(with interaction) = %1, classification = %2. This is Wheeler monitoring-capability grading, not an AIAG pass/fail decision, and must not be written as gage pass."},
{"interp.msa_probable_error",
 "Probable Error = %1；用于对照测量增量是否物理合理，不是公差合格证明。",
 "Probable Error = %1; use it to check whether measurement increments are physically plausible—not proof of tolerance pass."},
{"interp.msa_ndc_low",
 "ndc = %1，小于 5，提示测量系统分辨力需要调查。",
 "ndc = %1, below 5, suggesting measurement-system discrimination needs investigation."},
{"interp.msa_ndc_ok",
 "ndc = %1；ndc 只描述当前研究中零件间变异相对 Gage 变异的分辨力。",
 "ndc = %1; ndc only describes part-to-part variation relative to gage variation discrimination in this study."},
{"interp.msa_ndc_lt5_not_fail",
 "ndc<5 不是量具不合格的绝对结论，需要结合 %Study Var 和公差风险。",
 "ndc<5 is not an absolute gage-fail conclusion; combine with %Study Var and tolerance risk."},
{"interp.msa_gage_study_var",
 "Total Gage R&R %Study Var = %1；%Contribution 与 %Study Var 口径不同，不能混用。",
 "Total Gage R&R %Study Var = %1; %Contribution and %Study Var use different bases and must not be mixed."},
{"interp.msa_interaction_reduce_hint",
 "Part×Operator 交互 p>0.25，传统流程可考虑缩减模型；当前结果仍保留完整交互。",
 "Part×Operator interaction p>0.25; traditional workflows may consider model reduction, but the current result still keeps the full interaction."},
{"interp.msa_average_bias",
 "Average Bias = %1。",
 "Average Bias = %1."},
{"interp.msa_average_bias_p",
 "Average Bias p = %1。",
 "Average Bias p = %1."},
{"interp.msa_constant_p",
 "Constant p = %1。",
 "Constant p = %1."},
{"interp.msa_percent_linearity",
 "%Linearity = %1；基于用户提供的过程变差（6σ）。",
 "%Linearity = %1; based on the user-supplied process variation (6σ)."},
{"interp.msa_slope_significant",
 "斜率检验 p≤0.05，提示线性显著；应分别解读各参考水平的偏倚，不宜只用平均偏倚。",
 "Slope test p≤0.05 suggests significant linearity; interpret bias at each reference level separately rather than using average bias alone."},
{"interp.msa_bias_p_evidence",
 "偏倚检验 P = %1，与参考值差异具有统计证据。",
 "Bias test P = %1; there is statistical evidence of a difference from the reference."},
{"interp.msa_bias_p_no_evidence",
 "偏倚检验 P = %1，未发现与参考值差异的统计证据。",
 "Bias test P = %1; no statistical evidence of a difference from the reference was found."},
{"interp.msa_cgk",
 "Cgk = %1；应结合组织规定的能力门槛解释，而非套用单一通用阈值。",
 "Cgk = %1; interpret against organization-defined capability thresholds rather than a single universal cutoff."},
{"interp.msa_tolerance_percent",
 "%Tolerance = %1；请与产品公差及风险等级核对后决定校准、维修或放行策略。",
 "%Tolerance = %1; decide calibration, repair, or release strategy only after checking product tolerance and risk level."},
{"interp.rel_mode_fit_honesty",
 "分模式可靠度为 formula_reference（竞争失效作右删失），不是 vendor_oracle / golden；阈值模型与 pinned R 对齐仍未冻结。",
 "Mode-specific reliability is formula_reference (competing failures treated as right-censored), not vendor_oracle/golden; threshold models and pinned-R alignment are not frozen."},
{"interp.rel_cif_honesty",
 "CIF 为 formula_reference（Aalen–Johansen），不是 Fine-Gray 回归，也不是 cause-specific 可靠度或 vendor_oracle。",
 "CIF is formula_reference (Aalen–Johansen), not Fine-Gray regression, and not cause-specific reliability or vendor_oracle."},
{"interp.rel_fine_gray_honesty_binary",
 "Fine-Gray 为 formula_reference / fine_gray_binary_ipcw（单协变量 IPCW）；不是 cause-specific Cox、不是 vendor_oracle。",
 "Fine-Gray is formula_reference / fine_gray_binary_ipcw (single-covariate IPCW); not cause-specific Cox, and not vendor_oracle."},
{"interp.rel_fine_gray_honesty_continuous",
 "Fine-Gray 为 formula_reference / fine_gray_continuous_ipcw（单协变量 IPCW）；不是 cause-specific Cox、不是 vendor_oracle。",
 "Fine-Gray is formula_reference / fine_gray_continuous_ipcw (single-covariate IPCW); not cause-specific Cox, and not vendor_oracle."},
{"interp.rel_fine_gray_honesty_multi",
 "Fine-Gray 为 formula_reference / fine_gray_multi_ipcw（多协变量 IPCW，均值中心化）；不是 cause-specific Cox、不是 vendor_oracle；未对齐 pinned R survival::finegray。",
 "Fine-Gray is formula_reference / fine_gray_multi_ipcw (multi-covariate IPCW, mean-centered); not cause-specific Cox, not vendor_oracle; not aligned to pinned R survival::finegray."},
{"interp.rel_fine_gray_not_computed",
 "Fine-Gray 未计算（%1）；不得伪造子分布风险比。",
 "Fine-Gray was not computed (%1); do not invent a subdistribution hazard ratio."},
{"interp.rel_fine_gray_summary",
 "Fine-Gray 二分类子分布风险：目标原因=%1，group %2→0 / %3→1，β=%4%5%6。",
 "Fine-Gray binary subdistribution hazard: target cause=%1, group %2→0 / %3→1, β=%4%5%6."},
{"interp.rel_fine_gray_continuous_summary",
 "Fine-Gray 连续协变量子分布风险：目标原因=%1，协变量=%2，β=%3%4%5。",
 "Fine-Gray continuous-covariate subdistribution hazard: target cause=%1, covariate=%2, β=%3%4%5."},
{"interp.rel_fine_gray_multi_summary",
 "Fine-Gray 多协变量子分布风险：目标原因=%1，项数=%2%3。",
 "Fine-Gray multi-covariate subdistribution hazard: target cause=%1, terms=%2%3."},
{"interp.rel_not_identifiable",
 "可靠性结果当前不可识别，不能估计寿命分位数。",
 "Reliability results are currently non-identifiable; life percentiles cannot be estimated."},
{"interp.rel_median_not_reached",
 "生存曲线未下降到 0.5，中位寿命不可估计。",
 "The survival curve did not fall to 0.5; median life is not estimable."},
{"interp.rel_km_advice_logrank",
 "按目标任务时间读取生存概率和置信区间；比较方案时使用分层或 Log-rank。",
 "Read survival probability and confidence intervals at the target mission time; use stratified or Log-rank tests when comparing plans."},
{"interp.rel_exp_not_proven",
 "指数拟合未拒绝假设不等于已证明寿命服从指数分布。",
 "Failing to reject an exponential fit does not prove lifetimes follow an exponential distribution."},
{"interp.rel_lognormal_not_proven",
 "对数正态拟合未拒绝假设并不等于已证明寿命服从对数正态。",
 "Failing to reject a lognormal fit does not prove lifetimes follow a lognormal distribution."},
{"interp.rel_weibull3_not_proven",
 "三参数拟合未拒绝假设不等于已证明寿命服从三参数 Weibull。",
 "Failing to reject a three-parameter fit does not prove lifetimes follow a three-parameter Weibull."},
{"interp.rel_lognormal_not_converged",
 "对数正态参数未收敛，分位寿命不能作为决策依据。",
 "Lognormal parameters did not converge; percentile life must not be used for decisions."},
{"interp.eda_not_hypothesis_test",
 "EDA 图用于探索形态与频数，不是假设检验结论。",
 "EDA plots explore shape and frequency; they are not hypothesis-test conclusions."},
{"interp.eda_density",
 "密度图：N = %1%2。曲线是平滑估计，不能据此写成正态性结论。",
 "Density plot: N = %1%2. The curve is a smooth estimate and must not be written as a normality conclusion."},
{"interp.eda_hexbin",
 "二维分箱：N = %1；格 = %2×%3（矩形格，产品名 Hexbin）。",
 "2D binning: N = %1; grid = %2×%3 (rectangular bins; product name Hexbin)."},
{"interp.eda_violin",
 "小提琴图：组数 = %1；形状来自分组 KDE，箱线为五数摘要。",
 "Violin plot: group count = %1; shape comes from grouped KDE; box shows the five-number summary."},
{"interp.eda_bar",
 "通用条形图：类别数 = %1；未按计数排序，无累积百分比（与柏拉图分流）。",
 "Generic bar chart: category count = %1; not sorted by count and without cumulative percent (separate from Pareto)."},
{"interp.eda_4plot",
 "NIST EDA 四图：N = %1；同页包含 run sequence、lag-1、histogram、normal probability。四图用于检查位置/散布/随机性/分布形态假设，不能写成受控结论或正态已成立。",
 "NIST EDA 4-plot: N = %1; same page includes run sequence, lag-1, histogram, and normal probability. The four plots check location/spread/randomness/distributional-shape assumptions and must not be written as in-control or proven-normal conclusions."},
{"interp.eda_facet",
 "受控分面：面板 = %1/%2（max=%3）%4。分面是多面板编排，不是自由拼版；by/分组仍是图内着色。",
 "Controlled faceting: panels = %1/%2 (max=%3)%4. Facets are multi-panel layout, not free collage; by/group remains in-plot coloring."},
{"interp.cause_effect_summary",
 "因果图效应为“%1”，共 %2 个类别、%3 条原因。这是结构化头脑风暴摘要，不是统计检验，不能写成已证明根因。",
 "Cause-and-effect diagram effect is “%1”, with %2 categor(y/ies) and %3 cause(s). This is a structured brainstorming summary, not a statistical test, and must not be written as a proven root cause."},
{"interp.km_interval_turnbull",
 "区间删失 KM（Turnbull）：N = %1，左/区间/右 = %2/%3/%4%5。",
 "Interval-censored KM (Turnbull): N = %1, left/interval/right = %2/%3/%4%5."},
{"interp.km_interval_honesty",
 "Turnbull NPMLE（简化网格）；evidence_type=%1；algorithm_id=%2；非右删失 product-limit；非参数寿命模型；不得写成 vendor_oracle/golden。",
 "Turnbull NPMLE (simplified grid); evidence_type=%1; algorithm_id=%2; not right-censored product-limit; nonparametric life model; must not be written as vendor_oracle/golden."},
{"interp.km_interval_exact_not_classic",
 "本批观测均为精确失效（无左/区间/右删失）；仍走区间 NPMLE 路径，不自动等价替换为经典右删失 KM 报告。",
 "All observations in this batch are exact failures (no left/interval/right censoring); the interval NPMLE path is still used and is not automatically replaced by a classic right-censored KM report."},
{"interp.acf_pacf_summary",
 "ACF/PACF 基于 N = %1，最大滞后 = %2；默认置信带方法 = %3%4。越过带宽只提示相对白噪声零假设的相关证据，不能写成过程失控判定。",
 "ACF/PACF based on N = %1, max lag = %2; default confidence-band method = %3%4. Crossing the band only suggests correlation evidence versus a white-noise null and must not be written as a process out-of-control decision."},
{"interp.acf_nist_band_honesty",
 "默认带宽是 NIST 白噪声固定 ±z/√n（独立性检验），不是 ARIMA 识别用的 Bartlett 变带宽；亦非 Minitab golden。",
 "Default bands are NIST white-noise fixed ±z/√n (independence test), not Bartlett variable-width bands for ARIMA identification; also not Minitab golden."},
{"interp.ljung_box_p",
 "Ljung–Box P ≈ %1；小 P 提示序列存在总体自相关结构，应结合 ACF/PACF 图与工艺时序解释。",
 "Ljung–Box P ≈ %1; a small P suggests overall serial correlation—interpret with ACF/PACF plots and process timing."},
{"interp.z_mr_summary",
 "Z-MR 图 N = %1，组数 = %2，Z 图超限 = %3；短流程标准化依赖 %4，超限点需要调查，不能直接当作过程失控或稳定结论。",
 "Z-MR chart N = %1, groups = %2, Z out-of-control = %3; short-run standardization depends on %4; investigate exceedances—do not treat them as process out-of-control or stability conclusions."},
{"interp.z_mr_sample_params",
 "未提供完整历史 μ/σ 表；本轮用各组样本均值与全序列 MR/d2 估计 σ。",
 "A complete historical μ/σ table was not provided; this run estimates σ from per-group sample means and overall-series MR/d2."},
{"interp.ma_chart_summary",
 "移动平均图窗宽 w = %1，「单点超出 3σ 控制限」触发 = %2；MA 平滑后的出限是信号提示，需要结合工艺调查，不能将统计信号直接等同于过程失控判定或稳定结论。",
 "Moving-average chart window w = %1; '1 point beyond 3σ limits' triggers = %2; MA-smoothed exceedances are signal hints—investigate with process knowledge; do not equate statistical signals with out-of-control or stability conclusions."},
{"interp.ma_chart_honesty",
 "移动平均图与 EWMA 不同；仅完整窗 MA 点参与判读，不是 Minitab golden。",
 "Moving-average charts differ from EWMA; only complete-window MA points are judged; not Minitab golden."},
{"interp.run_chart_summary",
 "运行图 N = %1%2；关于中位数游程 = %3，上升/下降游程 = %4。四模式 P 只提示相对随机性的偏离方向，不能写成已证明过程受控或失控。",
 "Run chart N = %1%2; runs about median = %3, up/down runs = %4. Four-pattern P-values only hint deviation directions versus randomness and must not be written as proven in-control or out-of-control."},
{"interp.zone_chart_summary",
 "区域图 Jaehn 累计得分达到阈值 %1 的点有 %2 个；这是统计信号提示，需要调查特殊原因，不能将统计信号直接等同于过程失控判定或稳定结论。",
 "Zone chart: %2 point(s) reached Jaehn cumulative score threshold %1; this is a statistical signal hint—investigate special causes; do not equate signals with out-of-control or stability conclusions."},
{"interp.zone_chart_honesty",
 "区域图采用 Jaehn 1/2/4 计分（formula_reference），不是完整 Shewhart 特殊原因规则（beyond_control_limit 等）的替代品。",
 "Zone chart uses Jaehn 1/2/4 scoring (formula_reference) and is not a substitute for full Shewhart special-cause rules (e.g. beyond_control_limit)."},
{"interp.plackett_burman_summary",
 "Plackett–Burman：因子 = %1，运行 = %2，中心点 = %3。设计矩阵仅供筛选实验排布。",
 "Plackett–Burman: factors = %1, runs = %2, center points = %3. The design matrix is for screening layout only."},
{"interp.plackett_burman_honesty",
 "分辨率 III；非 CCD/BBD；非 Minitab golden。",
 "Resolution III; not CCD/BBD; not Minitab golden."},
{"interp.bbd_design_summary",
 "Box–Behnken：因子 = %1，边中点 = %2，中心点 = %3，总运行 = %4。不包含所有因子同时极端的角点。",
 "Box–Behnken: factors = %1, edge midpoints = %2, center points = %3, total runs = %4. Does not include corners where all factors are extreme at once."},
{"interp.bbd_design_honesty",
 "证据类型 formula_reference；未宣称全域预测最优；非 vendor_oracle。",
 "Evidence type formula_reference; does not claim global prediction optimality; not vendor_oracle."},
{"interp.ccd_design_summary",
 "CCD（%1）：因子 = %2，立方点 = %3，星点 = %4，中心点 = %5，α = %6。",
 "CCD (%1): factors = %2, cube points = %3, star points = %4, center points = %5, α = %6."},
{"interp.ccd_design_honesty",
 "证据类型 formula_reference；非 vendor_oracle / 商业软件对齐。",
 "Evidence type formula_reference; not vendor_oracle / commercial-software alignment."},
{"interp.warranty_strata_mode",
 "已按 %1 追溯 %2 个分层分母；部分/全部分层 expected_failures 使用 cause-specific 分模式 R(T_w)。",
 "Traced %2 stratum denominator(s) by %1; some/all strata expected_failures use cause-specific mode R(T_w)."},
{"interp.warranty_strata_pooled",
 "已按 %1 追溯 %2 个分层分母；分层 expected_failures 使用池化 R(T_w)。",
 "Traced %2 stratum denominator(s) by %1; stratum expected_failures use pooled R(T_w)."},
{"interp.warranty_mode_r_honesty",
 "分模式 R 为 cause-specific（竞争失效作右删失）formula_reference，不是 vendor_oracle；不得写成商业软件对齐。",
 "Mode-specific R is cause-specific (competing failures as right-censored) formula_reference, not vendor_oracle; must not be written as commercial-software alignment."},
{"interp.warranty_pooled_honesty",
 "分层未估计分模式可靠度（uses_pooled_reliability=%1）；比例分摊暴露量须标注 proportional_scalar。",
 "Mode-specific reliability was not estimated for strata (uses_pooled_reliability=%1); proportional exposure allocation must be labeled proportional_scalar."},
{"interp.ccf_summary",
 "CCF：N = %1，max|lag| = %2%3。越过带宽只提示相对独立性零假设的相关证据。",
 "CCF: N = %1, max|lag| = %2%3. Crossing the band only suggests correlation evidence versus an independence null."},
{"interp.correlogram_summary",
 "Correlogram（%1）：变量数 = %2，成对数 = %3。热图只展示两两相关结构。",
 "Correlogram (%1): variables = %2, pairs = %3. The heatmap only shows pairwise correlation structure."},
{"interp.correlogram_honesty",
 "与 correlation_plot 分流；非 Graph Builder。",
 "Separate from correlation_plot; not Graph Builder."},
{"interp.stepwise_summary",
 "逐步回归（%1）：N = %2，候选 = %3，选入 = %4%5。选入项只描述相对拟合证据。",
 "Stepwise regression (%1): N = %2, candidates = %3, selected = %4%5. Selected terms only describe relative fit evidence."},
{"interp.multi_vari_summary",
 "Multi-Vari 图用 %1 个因子分层显示 %2 个有效测量的均值%3。",
 "Multi-Vari chart displays means of %2 valid measurement(s) stratified by %1 factor(s)%3."},
{"interp.multi_vari_advice",
 "结合因子均值表回查占主导的因子水平；需要检验显著性时使用 ANOVA 或回归。",
 "Use the factor-means table to review dominant factor levels; use ANOVA or regression when significance tests are needed."},
{"interp.skipped_incomplete_rows",
 "已跳过 %1 个缺失或不完整行。",
 "Skipped %1 missing or incomplete row(s)."},
{"interp.variability_summary",
 "变异性图按 %1 个因子汇总 %2 个单元、%3 个有效测量的均值与标准差%4%5。图只用于探索变异结构，不是显著性检验或过程判定。",
 "Variability chart summarizes means and SDs for %2 cell(s) and %3 valid measurement(s) across %1 factor(s)%4%5. The chart explores variation structure only—not a significance test or process decision."},
{"interp.variability_advice",
 "先看均值面板中极差较大的单元，再对照标准差面板定位离散度来源。",
 "First inspect cells with large mean-panel ranges, then use the SD panel to locate dispersion sources."},
{"interp.variability_honesty",
 "变异性图与 Multi-Vari 语义不同：本命令输出均值+极差与标准差双面板，不替代 ANOVA。",
 "Variability chart semantics differ from Multi-Vari: this command outputs mean+range and SD dual panels and does not replace ANOVA."},
{"interp.run_chart_pattern_advice",
 "对照 P clustering / mixtures / trends / oscillation 与现场时序，小 P 只表示该模式方向上的偏离证据。",
 "Compare P clustering / mixtures / trends / oscillation with process timing; a small P only indicates evidence of deviation in that pattern direction."},
{"interp.tolerance_summary",
 "容差区间方法为 %1%2%3%4%5%6%7。区间只描述当前样本覆盖，不是规格覆盖或过程判定。",
 "Tolerance-interval method is %1%2%3%4%5%6%7. The interval describes current-sample coverage only—not specification coverage or a process decision."},
{"interp.tolerance_advice",
 "结合直方图与方法族诊断调查覆盖区间；需要对照规格时使用过程能力分析。",
 "Investigate the coverage interval with the histogram and method-family diagnostics; use process capability when comparing to specifications."},
{"interp.tolerance_nonparametric_honesty",
 "非参数容差依赖序统计与连续分布假设；achieved confidence 低于目标时，只说明样本量不足，不是计算错误。",
 "Nonparametric tolerance depends on order statistics and a continuous-distribution assumption; achieved confidence below target means insufficient sample size, not a calculation error."},
{"interp.tolerance_normal_honesty",
 "本方法假设测量近似正态且未在本页验证（assumption_status=%1）；单侧使用 Natrella 近似，双侧使用 Howe 近似。",
 "This method assumes approximately normal measurements not verified on this page (assumption_status=%1); one-sided uses Natrella approximation, two-sided uses Howe."},
{"interp.skipped_illegal_values",
 "已跳过 %1 个缺失或非法数值。",
 "Skipped %1 missing or illegal value(s)."},
{"interp.skip_n_missing_invalid_cells",
 "跳过 %1 个缺失或非法单元格。",
 "Skipped %1 missing or invalid cell(s)."},
{"interp.skip_n_missing_invalid_cells_star",
 "跳过 %1 个缺失或非法单元格（含 *）。",
 "Skipped %1 missing or invalid cell(s) (including *)."},
{"interp.skip_n_missing_counted_nstar",
 "跳过 %1 个缺失或非法单元格（计入 N*）。",
 "Skipped %1 missing or invalid cell(s) (counted in N*)."},
{"interp.desc_skip_n_missing_star",
 "描述统计跳过 %1 个缺失或非法单元格（含 *）。",
 "Descriptive statistics skipped %1 missing or invalid cell(s) (including *)."},
{"interp.poisson_gof_skip_n_missing",
 "泊松拟合优度跳过 %1 个缺失或非法单元格。",
 "Poisson goodness-of-fit skipped %1 missing or invalid cell(s)."},
{"interp.corr_skip_complete_case_rows",
 "相关分析 complete-case 跳过 %1 个含缺失或非法单元格的行。",
 "Correlation complete-case skipped %1 row(s) with missing or invalid cells."},
{"interp.two_sample_t_skip_groups",
 "双样本 t 检验跳过缺失或非法单元格；组 1 = %1，组 2 = %2。",
 "Two-sample t skipped missing or invalid cells; group 1 = %1, group 2 = %2."},
{"interp.anova_skip_n_response",
 "ANOVA 跳过 %1 个缺失或非法响应值。",
 "ANOVA skipped %1 missing or invalid response value(s)."},
{"interp.anom_skip_n_response",
 "ANOM 跳过 %1 个缺失或非法响应值。",
 "ANOM skipped %1 missing or invalid response value(s)."},
{"interp.boxcox_skip_n_obs",
 "Box-Cox 跳过 %1 个缺失或非法观测。",
 "Box-Cox skipped %1 missing or invalid observation(s)."},
};

}  // namespace

void append_report_text_catalog_part10(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart10),
        std::end(kReportTextCatalogPart10));
}

}  // namespace datalab::domain
