#include "domain/report_text_catalog_parts.h"

namespace datalab::domain {
namespace {

const ReportTextEntry kReportTextCatalogPart15[] = {
{"interp.cap_hartigan_consistent_not_proof",
 "Hartigan dip 门禁筛查未拒绝 Uniform 零假设下的单峰（formula_reference）；这不是过程单峰证明，也不得开放合格判定。",
 "Hartigan dip gated screen did not reject unimodality under a Uniform null (formula_reference); this is not proof of process unimodality and must not open pass/fail."},
{"interp.cap_hartigan_screen_note",
 "能力分析 Hartigan dip 前置：公式参考级研究筛查（Uniform 零假设 MC）；不是商业软件对齐；二维高斯混合另有门禁；合格判定保持关闭。",
 "Capability Hartigan dip prerequisite: formula-reference research screen (Uniform-null MC); not commercial-software alignment; Gaussian mixture is a separate gate; pass/fail stays closed."},
{"interp.cap_mixture_insufficient_n",
 "观测不足（n<30），无法做多 k 高斯混合门禁；不得把不足样本写成已排除混合。",
 "Fewer than 30 observations; multi-k Gaussian mixture gate cannot run—do not describe an insufficient sample as having ruled out mixture."},
{"interp.cap_mixture_failed",
 "多 k 高斯混合门禁未得到可用拟合；不得伪造混合结论或开放合格判定。",
 "Multi-k Gaussian mixture gate did not obtain a usable fit; do not invent a mixture conclusion or open process pass/fail."},
{"interp.cap_mixture_not_preferred",
 "多 k 高斯混合门禁未优选多成分（formula_reference / gaussian_mixture_k_bic）；这不是单峰/单成分证明，也不得开放合格判定。",
 "Multi-k Gaussian mixture gate did not prefer multiple components (formula_reference / gaussian_mixture_k_bic); this is not proof of unimodality/single-component and must not open pass/fail."},
{"interp.cap_mixture_screen_note",
 "能力分析混合模型前置：高斯 EM + BIC 搜索 k=1..k_max（formula_reference / gaussian_mixture_k_bic）；不是非高斯混合，不是商业软件对齐，合格判定保持关闭。",
 "Capability mixture prerequisite: Gaussian EM + BIC search k=1..k_max (formula_reference / gaussian_mixture_k_bic); not non-Gaussian mixtures, not commercial-software alignment; pass/fail stays closed."},
{"interp.johnson_capability_gated",
 "Johnson 能力为研究/预览结果：可显示拟合与变换尺度指数，但不得输出过程合格判定（门禁：缺 golden/尾部/人工解释验收）。",
 "Johnson capability is research/preview only: fit and transform-scale indices may be shown, but process pass/fail judgment is blocked (gate: missing golden / tail / human review)."},
{"interp.cap_pass_fail_blocked_stability",
 "正态能力未满足稳定性/正态性验收前置：禁止过程合格判定（pass_fail_judgment_allowed=false）。",
 "Normal capability has not met the stability/normality acceptance prerequisite: process pass/fail judgment is blocked (pass_fail_judgment_allowed=false)."},
{"interp.johnson_spec_outside_support",
 "规格限落在 Johnson 变换定义域外，无法计算 Pp/Ppk。",
 "Specification limits fall outside the Johnson transform support; Pp/Ppk cannot be computed."},
{"interp.johnson_spec_partial_outside",
 "至少一个规格限落在变换定义域外；越界侧的百分位回推未实现，仅输出仍可变换规格的 overall 指数。",
 "At least one specification limit is outside transform support; percentile back-transform for the out-of-support side is not implemented—only overall indices for still-transformable specs are reported."},
{"interp.johnson_within_not_applicable",
 "Johnson 变换路径只报告 overall Pp/Ppk，不报告 within Cp/Cpk。",
 "The Johnson transform path reports overall Pp/Ppk only; within Cp/Cpk are not reported."},
{"interp.johnson_err_need_eight",
 "Johnson 变换至少需要 8 个有限观测。",
 "Johnson transform requires at least 8 finite observations."},
{"interp.johnson_warn_tail_quantile",
 "样本量不足以估计 Johnson 分位匹配所需的尾部分位数。",
 "Sample size is insufficient to estimate the tail quantiles required for Johnson percentile matching."},
{"interp.johnson_formula_reference",
 "Johnson 变换按 Chou et al. (1998) 分位匹配与 AD p 值选择；数值是公式参考，不是 Minitab Individual Distribution Identification 导出。",
 "Johnson transform is selected by Chou et al. (1998) percentile matching and AD p-value; values are formula reference, not a Minitab Individual Distribution Identification export."},
{"interp.cap_nonnormal_zscore_scope",
 "非正态能力使用拟合分布 CDF 的 Z-score 法计算 Pp/Ppk；不报告 Cp/Cpk。数值是公式参考，不是 Minitab 导出。",
 "Nonnormal capability computes Pp/Ppk via the fitted-distribution CDF Z-score method; Cp/Cpk are not reported. Values are formula reference, not a Minitab export."},
{"interp.box_cox_err_need_two",
 "Box-Cox 变换至少需要两个有效观测。",
 "Box-Cox requires at least two valid observations."},
{"interp.box_cox_err_positive",
 "Box-Cox 变换要求所有观测严格大于 0。",
 "Box-Cox requires all observations strictly greater than 0."},
{"interp.box_cox_err_lambda_range",
 "Box-Cox lambda 必须位于 [-5, 5]。",
 "Box-Cox lambda must lie in [-5, 5]."},
{"diag.box_cox_invalid_spec_limit_lsl",
 "规格下限无法变换（须为正有限数）。",
 "Lower spec limit cannot be transformed (must be a positive finite value)."},
{"diag.box_cox_invalid_spec_limit_usl",
 "规格上限无法变换（须为正有限数）。",
 "Upper spec limit cannot be transformed (must be a positive finite value)."},
{"diag.box_cox_invalid_spec_limit_target",
 "规格目标无法变换（须为正有限数）。",
 "Target spec cannot be transformed (must be a positive finite value)."},
{"diag.box_cox_spec_limits_order",
 "变换后规格限顺序无效；请检查 LSL/USL 与 λ。",
 "Transformed spec limits are out of order; check LSL/USL and λ."},
{"interp.normality_warn_n_lt8",
 "n<8 时正态性近似较粗糙，未拒绝正态假设不能当作已验证正态。",
 "With n<8 the normality approximation is coarse; failure to reject normality must not be treated as verified normality."},
{"interp.attr_binomial_assumption_static",
 "二项过程能力未验证独立性、恒定 p 与稳定性，不能写成过程合格。",
 "Binomial process capability has not verified independence, constant p, and stability; do not write process pass/fail."},
{"interp.attr_poisson_assumption_static",
 "泊松过程能力未验证独立性、恒定 DPU 与稳定性，不能写成过程合格。",
 "Poisson process capability has not verified independence, constant DPU, and stability; do not write process pass/fail."},
{"interp.cap_between_within_need_two_subgroups",
 "组间/组内能力至少需要两个子组。",
 "Between/within capability requires at least two subgroups."},
{"diag.capability.between_within_cannot_compute",
 "无法计算组间/组内能力指标。",
 "Cannot compute between/within capability indices."},
{"diag.scatter_need_two_complete",
 "散点图至少需要两个有效的完整观测行。",
 "Scatter plot requires at least two valid complete-case rows."},
{"diag.interval_group_lt2_se",
 "区间图存在有效观测数少于 2 的分组，无法估计标准误。",
 "An interval-plot group has fewer than 2 valid observations; SE cannot be estimated."},
{"diag.correlogram_need_two_vars",
 "相关图至少需要选择两个连续变量。",
 "Correlogram requires at least two continuous variables."},
{"diag.normal_prob_need_three",
 "正态概率图至少需要三个有效观测。",
 "Normal probability plot requires at least three valid observations."},
{"diag.matrix_need_two_vars",
 "矩阵图至少需要两个连续变量。",
 "Matrix plot requires at least two continuous variables."},
{"diag.parallel_need_two_vars",
 "平行坐标图至少需要两个连续变量。",
 "Parallel coordinates require at least two continuous variables."},
{"diag.density_need_two_finite",
 "密度估计至少需要两个有限观测。",
 "Density estimation requires at least two finite observations."},
{"diag.hexbin_need_two_complete",
 "二维分箱至少需要两个 complete-case 点。",
 "2D binning requires at least two complete-case points."},
{"interp.cochran_q_summary",
 "Cochran Q = %1，DF = %2%3。结果只陈述配对二元处理间差异证据，不能写成已证明阳性率相同或不同。",
 "Cochran Q = %1, DF = %2%3. Results only state evidence of differences among paired binary treatments and must not be written as proof that positive rates are the same or different."},
{"interp.cochran_q_not_computable",
 "Cochran Q 未计算出统计量（例如列数不足、编码失败或分母退化）。两列配对请用 McNemar；不得写成已证明各处理阳性率相同或不同。",
 "Cochran Q did not compute a statistic (e.g. too few columns, encoding failure, or degenerate denominator). Use McNemar for two paired columns; do not write proof that treatment positive rates are the same or different."},
{"interp.anova_f_needs_posthoc",
 "总体 F 显著只说明至少一组不同，需要多重比较确定具体组对。",
 "A significant overall F only means at least one group differs; use multiple comparisons to identify pairs."},
{"interp.power_table_empty",
 "功效/样本量结果表为空，不能给出设计建议。",
 "The power/sample-size result table is empty; design advice cannot be given."},
{"interp.power_invalid_config",
 "效应量或 α 配置不在有效范围，不能把数值当作正式设计依据。",
 "Effect size or α is outside a valid range; do not treat the numbers as formal design evidence."},
{"interp.forecast_table_empty",
 "预测结果表为空，不能评价预测或未来期。",
 "The forecast result table is empty; forecasts or future periods cannot be evaluated."},
{"interp.season_period_lt2",
 "季节周期小于 2，不能支持有意义的季节性解释。",
 "Seasonal period < 2 cannot support a meaningful seasonality interpretation."},
{"interp.season_index_lt2",
 "季节周期小于 2，不能支持有意义的季节指数解释。",
 "Seasonal period < 2 cannot support a meaningful seasonal-index interpretation."},
{"interp.pca_not_converged",
 "特征分解未收敛时不对主成分或异常点给出稳定解释。",
 "When eigendecomposition does not converge, do not give stable PCA or outlier interpretations."},
{"interp.small_sample_approx_p",
 "存在小样本组，近似 P 值只作提示。",
 "Small-sample groups are present; approximate P-values are hints only."},
{"interp.nonparam_method_approx",
 "%1 使用 %2 近似%3%4。未拒绝原假设不能证明两组或各组分布相同。",
 "%1 uses %2 approximation%3%4. Failure to reject the null does not prove two or more groups share the same distribution."},
{"interp.nonparam_walsh_ci",
 "Walsh 估计中位数为 %1，置信区间 [%2, %3]。区间只描述中位数的可能范围，不能写成已证明等于假设值。",
 "Walsh estimated median is %1 with confidence interval [%2, %3]. The interval describes a plausible median range only and does not prove equality to the hypothesized value."},
{"interp.nonparam_walsh_lower",
 "Walsh 估计中位数为 %1，置信下界 %2。",
 "Walsh estimated median is %1 with lower confidence bound %2."},
{"interp.nonparam_walsh_upper",
 "Walsh 估计中位数为 %1，置信上界 %2。",
 "Walsh estimated median is %1 with upper confidence bound %2."},
{"interp.nonparam_walsh_point",
 "Walsh 估计中位数为 %1。点估计不能写成已证明等于假设值。",
 "Walsh estimated median is %1. A point estimate does not prove equality to the hypothesized value."},
{"interp.nonparam_location_diff_ci",
 "位置差异估计为 %1，置信区间 [%2, %3]。区间只描述位置差的可能范围。",
 "Location-difference estimate is %1 with confidence interval [%2, %3]. The interval describes a plausible location-difference range only."},
{"interp.nonparam_location_diff_lower",
 "位置差异估计为 %1，置信下界 %2。",
 "Location-difference estimate is %1 with lower confidence bound %2."},
{"interp.nonparam_location_diff_upper",
 "位置差异估计为 %1，置信上界 %2。",
 "Location-difference estimate is %1 with upper confidence bound %2."},
{"interp.nonparam_boxplot_n",
 "箱线图与个体值图基于 %1 个有效观测，缺失单元格未进入图形。",
 "Boxplot and individual-value plots are based on %1 valid observation(s); missing cells are not plotted."},
{"interp.nonparam_dunn_pairs",
 "Dunn–Bonferroni 成对比较共 %1 对；Grouping 字母只反映该规则下的显著矩阵，不能写成组间已证明相同或不同。",
 "Dunn–Bonferroni pairwise comparisons: %1 pair(s); Grouping letters reflect only that rule’s significance matrix and do not prove groups are the same or different."},
{"interp.nonparam_steel_dwass_pairs",
 "Steel–Dwass（近似）成对比较共 %1 对；Grouping 字母只反映该规则下的显著矩阵，不能写成组间已证明相同或不同。",
 "Steel–Dwass (approximate) pairwise comparisons: %1 pair(s); Grouping letters reflect only that rule’s significance matrix and do not prove groups are the same or different."},
{"interp.nonparam_nemenyi_pairs",
 "Nemenyi（近似）成对比较共 %1 对；Grouping 字母只反映该规则下的显著矩阵，不能写成处理间已证明相同或不同。",
 "Nemenyi (approximate) pairwise comparisons: %1 pair(s); Grouping letters reflect only that rule’s significance matrix and do not prove treatments are the same or different."},
{"interp.nonparam_friedman_s",
 "Friedman S（调整后）= %1，P = %2。这只陈述区组设计下处理间秩差异证据，不能写成已证明相同或不同。",
 "Friedman S (adjusted) = %1, P = %2. This only states evidence of treatment rank differences in a blocked design and does not prove sameness or difference."},
{"interp.nonparam_sign_p",
 "符号检验（二项精确）P = %1。未拒绝原假设不能证明中位数等于假设值。",
 "Sign test (exact binomial) P = %1. Failure to reject the null does not prove the median equals the hypothesized value."},
{"interp.nonparam_sign_ci",
 "Sign 中位数置信区间为 [%1, %2]，只描述位置不确定性，不能写成已证明等于假设值。",
 "Sign median confidence interval is [%1, %2]; it describes location uncertainty only and does not prove equality to the hypothesized value."},
{"interp.nonparam_runs",
 "游程检验%1。结果只陈述相对比较准则 K 的顺序随机性证据，不能写成已证明过程受控或失控。",
 "Runs test%1. Results only state evidence of sequential randomness relative to criterion K and do not prove the process is in or out of control."},
{"interp.nonparam_runs_k",
 "比较准则 K = %1；等号归入 ≤K 侧。",
 "Comparison criterion K = %1; ties are assigned to the ≤K side."},
{"interp.nonparam_wilcoxon_one_sample_p",
 "单样本 Wilcoxon 符号秩 P = %1。未拒绝原假设不能证明中位数等于假设值；Walsh 估计与区间只描述位置。",
 "One-sample Wilcoxon signed-rank P = %1. Failure to reject the null does not prove the median equals the hypothesized value; Walsh estimates and intervals describe location only."},
{"interp.nonparam_wilcoxon_paired_p",
 "配对 Wilcoxon 符号秩 P = %1。未拒绝原假设不能证明配对差分中位数为 0。",
 "Paired Wilcoxon signed-rank P = %1. Failure to reject the null does not prove the paired-difference median is 0."},
{"interp.nonparam_mood",
 "Mood 中位数检验 χ² = %1，P = %2。未拒绝原假设不能证明各组中位数相同；各组 Sign CI 只描述组内位置。",
 "Mood median test χ² = %1, P = %2. Failure to reject the null does not prove group medians are equal; per-group Sign CIs describe within-group location only."},
{"interp.review_special_causes",
 "建议回查对应原始行并确认特殊原因。",
 "Review the corresponding source rows and confirm special causes."},
{"interp.percentile_not_bca",
 "本轮为百分位法，非 BCa。",
 "This run uses the percentile method, not BCa."},
{"interp.stepwise_not_best_subsets",
 "α 逐步；非 Best subsets；选择不稳定时勿外推。",
 "α-stepwise selection; not Best Subsets; do not extrapolate when selection is unstable."},
{"interp.no_negbin_zi_offset",
 "本轮无负二项/零膨胀/偏移列；非 Minitab golden。",
 "This run has no negative-binomial/zero-inflated/offset column; not Minitab golden."},
{"interp.not_sklearn_treenet",
 "自研实现；非 sklearn 运行时；非 TreeNet/RF。",
 "In-house implementation; not an sklearn runtime; not TreeNet/RF."},
{"interp.layer_means_not_process_call",
 "分层均值图只用于探索变异来源，不能把结果写成过程判定。",
 "Layer-mean plots explore sources of variation; do not write them as process pass/fail."},
{"interp.bw_fixed_not_prewhitened",
 "白噪声固定带宽；非预白化；宜与 ACF/PACF 对照。",
 "White-noise bandwidth is fixed; not prewhitened; cross-check with ACF/PACF."},
{"interp.do_not_treat_pairwise_alpha_as_fwer",
 "不要把逐比较 alpha 当成家族错误率。",
 "Do not treat per-comparison alpha as a family-wise error rate."},
{"interp.logistic_complete_separation",
 "模型出现完全分离，极大似然估计可能不存在，不对系数给出稳定解释。",
 "Complete separation occurred; MLE may not exist—do not give stable coefficient interpretations."},
{"interp.logistic_irls_not_converged",
 "IRLS 未收敛，不对发散系数给出稳定解释。",
 "IRLS did not converge; do not give stable interpretations of divergent coefficients."},
{"interp.logistic_converged",
 "二元 Logistic 已收敛%1。未拒绝拟合不足不能说明模型已充分%2%3。系数解释依赖事件编码和 complete-case 样本。",
 "Binary logistic converged%1. Failure to reject lack of fit does not mean the model is adequate%2%3. Coefficient interpretation depends on event coding and the complete-case sample."},
{"interp.pca_summary",
 "PCA 模式为 %1，保留 %2 个主成分%3，检测到 %4 个 T²/Q 异常观测。异常阈值只作诊断，T²/Q 超限不是过程合格或失控判定。",
 "PCA mode is %1, retaining %2 principal component(s)%3; detected %4 T²/Q anomaly observation(s). Anomaly thresholds are diagnostic only—T²/Q exceedances are not process pass/fail or out-of-control decisions."},
{"interp.kmeans_summary",
 "K-Means：k = %1，N = %2，变量数 = %3，迭代 = %4%5%6。簇标签只描述相对邻近结构，不能写成过程或批次判定。",
 "K-Means: k = %1, N = %2, variables = %3, iterations = %4%5%6. Cluster labels only describe relative neighborhood structure and must not be written as process or lot decisions."},
{"interp.kmeans_init_honesty",
 "初始质心取前 k 个观测；结果依赖尺度%1；非 Minitab golden。",
 "Initial centroids use the first k observations; results depend on scaling%1; not Minitab golden."},
{"interp.cart_summary",
 "CART 单树任务 = %1，N = %2，预测变量 = %3，结点 = %4，叶 = %5%6%7。训练集指标不能外推为过程合格结论。",
 "CART single-tree task = %1, N = %2, predictors = %3, nodes = %4, leaves = %5%6%7. Training metrics must not be extrapolated as process pass conclusions."},
{"interp.cart_honesty",
 "自研二叉 CART；非 Minitab TreeNet/Random Forests 对齐；本轮无成本复杂度剪枝。",
 "In-house binary CART; not aligned to Minitab TreeNet/Random Forests; no cost-complexity pruning in this run."},
{"interp.adf_summary",
 "ADF（%1）：N = %2，滞后 = %3，有效回归行 = %4%5%6%7。单位根结论只描述差分平稳性证据，不能外推为工艺判定。",
 "ADF (%1): N = %2, lags = %3, usable regression rows = %4%5%6%7. Unit-root conclusions only describe evidence of difference-stationarity and must not be extrapolated as process decisions."},
{"interp.adf_mackinnon_honesty",
 "临界值为大样本 MacKinnon 风格常数；非 Minitab 导出；宜与 ACF/PACF 一并阅读。",
 "Critical values are large-sample MacKinnon-style constants; not Minitab exports; read with ACF/PACF."},
{"interp.poisson_reg_summary",
 "Poisson 回归（log 链）：N = %1，预测变量 = %2，迭代 = %3%4%5%6。系数显著性只描述计数均值与预测变量的关联证据。",
 "Poisson regression (log link): N = %1, predictors = %2, iterations = %3%4%5%6. Coefficient significance only describes association evidence between mean counts and predictors."},
{"interp.isolation_forest_summary",
 "Isolation Forest：N = %1，变量 = %2，树数 = %3，标记异常 = %4%5。分数高只提示相对孤立，与单变量 outlier_test 分流，不能写成工艺判定。",
 "Isolation Forest: N = %1, variables = %2, trees = %3, flagged anomalies = %4%5. High scores only suggest relative isolation—separate from univariate outlier_test—and must not be written as process decisions."},
{"interp.bootstrap_mean_summary",
 "Bootstrap 均值（%1）：N = %2，B = %3%4%5。区间只描述重抽样不确定性。",
 "Bootstrap mean (%1): N = %2, B = %3%4%5. Intervals describe resampling uncertainty only."},
{"interp.hier_cluster_summary",
 "层次聚类（%1）：N = %2，k = %3，合并步 = %4%5。簇标签只描述相对邻近结构。",
 "Hierarchical clustering (%1): N = %2, k = %3, merges = %4%5. Cluster labels only describe relative neighborhood structure."},
{"interp.hier_cluster_honesty",
 "本轮仅 complete linkage；非 K-Means；非 Minitab golden。",
 "This run supports complete linkage only; not K-Means; not Minitab golden."},
{"interp.ordinal_logistic_summary",
 "有序 Logistic（比例优势 logit）：N = %1，水平 = %2，预测变量 = %3%4%5。系数描述有序累积对数优势的关联证据。",
 "Ordinal logistic (proportional-odds logit): N = %1, levels = %2, predictors = %3%4%5. Coefficients describe association evidence for cumulative log-odds."},
{"interp.ordinal_logistic_honesty",
 "本轮仅 logit 链；非名义 Logistic；非 Minitab golden。",
 "This run uses the logit link only; not nominal logistic; not Minitab golden."},
{"interp.lda_summary",
 "线性判别：N = %1，类数 = %2，预测变量 = %3%4。训练集准确率不能外推为工艺判定。",
 "Linear discriminant: N = %1, classes = %2, predictors = %3%4. Training accuracy must not be extrapolated as a process decision."},
{"interp.lda_honesty",
 "等协方差 LDA；不做 QDA；非 Minitab golden。",
 "Equal-covariance LDA; no QDA; not Minitab golden."},
{"interp.descriptive_n_summary",
 "有效观测 N = %1，缺失 N* = %2%3。描述统计不检验分布假设，也不能写成过程合格。",
 "Valid observations N = %1, missing N* = %2%3. Descriptive statistics neither test distributional assumptions nor constitute process pass."},
{"interp.doe_significant_terms",
 "在 α = %1 下显著的项：%2。",
 "Significant terms at α = %1: %2."},
{"interp.doe_design_factors_centers",
 "设计包含 %1 个因子、%2 个中心点；实施时保持随机化/区组记录，避免把运行顺序效应误认为因子效应。",
 "Design has %1 factor(s) and %2 center point(s); keep randomization/block records in execution so run-order effects are not mistaken for factor effects."},
{"interp.gage_stability_ooc",
 "量具稳定性图发现 %1 个超限点，统计上存在失控信号。",
 "Gage stability chart found %1 out-of-control point(s); a statistical out-of-control signal is present."},
{"interp.msa_bias_slope_endpoints",
 "偏倚回归斜率 = %1，低/高参考点偏倚 = %2 / %3。",
 "Bias regression slope = %1; low/high reference bias = %2 / %3."},
{"interp.km_counts_summary",
 "Kaplan-Meier 有效观测 %1，失效 %2，删失 %3。",
 "Kaplan-Meier: %1 valid observation(s), %2 failure(s), %3 censored."},
{"interp.rel_mode_fits_count",
 "已对 %1 个失效模式做 cause-specific 分模式拟合（scheme=%2）。",
 "Fitted cause-specific mode models for %1 failure mode(s) (scheme=%2)."},
{"interp.rel_cif_modes_count",
 "已计算 %1 个失效模式的 Aalen–Johansen 累计发生函数 CIF（algorithm=%2）。",
 "Computed Aalen–Johansen cumulative incidence (CIF) for %1 failure mode(s) (algorithm=%2)."},
{"interp.rel_not_identifiable_reason",
 "可靠性结果不可识别（%1），不能估计寿命分位数。",
 "Reliability results are non-identifiable (%1); life percentiles cannot be estimated."},
{"interp.spc_ooc_count",
 "发现 %1 个控制图超限点。",
 "Found %1 control-chart out-of-control point(s)."},
{"interp.spc_rule_evidence_counts",
 "特殊原因规则证据：已触发 %1 / %2 条；详见「特殊原因规则证据」表（含 rule_id、窗口、阈值与状态）。",
 "Special-cause rule evidence: triggered %1 / %2; see the Special-cause rule evidence table (rule_id, window, threshold, status)."},
{"interp.spc_rule_triggered",
 "规则「%1」已触发。",
 "Rule “%1” triggered."},
{"interp.spc_rule_triggered_action",
 "规则「%1」已触发：%2",
 "Rule “%1” triggered: %2"},
{"spc.rule.beyond_control_limit.name",
 "单点超出 3σ 控制限",
 "1 point beyond 3σ control limits"},
{"spc.rule.beyond_control_limit.action",
 "复核测量、批次、设备或取样条件，并关联原始观测行。",
 "Recheck measurement, lot, equipment, or sampling conditions and link source rows."},
{"spc.rule.nine_same_side.name",
 "连续 9 点位于中心线同侧",
 "9 points in a row on the same side of the center line"},
{"spc.rule.nine_same_side.action",
 "调查均值偏移、分层或阶段变化，检查窗口首尾相关行。",
 "Investigate mean shift, stratification, or stage change; check window endpoints."},
{"spc.rule.six_point_trend.name",
 "连续 6 点持续单调趋势",
 "6 points in a row in a sustained monotonic trend"},
{"spc.rule.six_point_trend.action",
 "调查磨损、漂移或时间相关结构，核对趋势窗口点。",
 "Investigate wear, drift, or time structure; verify trend-window points."},
{"spc.rule.fourteen_alternating.name",
 "连续 14 点上下交替",
 "14 points in a row alternating up and down"},
{"spc.rule.fourteen_alternating.action",
 "调查周期、交替作业或过度调整，核对交替窗口。",
 "Investigate cycles, alternating operations, or over-adjustment; verify the alternating window."},
{"spc.rule.two_of_three_beyond_2sigma.name",
 "3 点中至少 2 点同侧超过 2σ",
 "At least 2 of 3 points beyond 2σ on the same side"},
{"spc.rule.two_of_three_beyond_2sigma.action",
 "调查较小系统性偏移，核对命中点标准化距离。",
 "Investigate a smaller systematic shift; verify standardized distances of hits."},
{"spc.rule.four_of_five_beyond_1sigma.name",
 "5 点中至少 4 点同侧超过 1σ",
 "At least 4 of 5 points beyond 1σ on the same side"},
{"spc.rule.four_of_five_beyond_1sigma.action",
 "调查过程均值小幅移动，核对命中点标准化距离。",
 "Investigate a small process-mean move; verify standardized distances of hits."},
{"spc.rule.fifteen_within_1sigma.name",
 "连续 15 点全部落在 1σ 内",
 "15 points in a row all within 1σ"},
{"spc.rule.fifteen_within_1sigma.action",
 "调查控制限是否过宽或数据分层，核对 σ 来源。",
 "Investigate whether limits are too wide or data are stratified; verify the σ source."},
{"spc.rule.eight_beyond_1sigma.name",
 "连续 8 点全部位于 1σ 外且同侧",
 "8 points in a row beyond 1σ on the same side"},
{"spc.rule.eight_beyond_1sigma.action",
 "调查混合总体或双群模式，按分组/批次复核。",
 "Investigate mixed populations or dual clusters; review by group/lot."},
{"spc.rule.beyond_control_limit.window",
 "单点",
 "1 point"},
{"spc.rule.beyond_control_limit.threshold",
 "LCL / UCL（约 3σ）",
 "LCL / UCL (~3σ)"},
{"spc.rule.beyond_control_limit.comparison",
 "y < LCL 或 y > UCL（严格）",
 "y < LCL or y > UCL (strict)"},
{"spc.rule.beyond_control_limit.explanation",
 "任一点低于 LCL 或高于 UCL；有限控制限使用严格越界比较。表示该点与当前控制模型不一致，不等于根因已确认。",
 "Any point below LCL or above UCL; finite limits use a strict beyond-limit comparison. Means the point disagrees with the current control model, not that a root cause is confirmed."},
{"spc.rule.nine_same_side.window",
 "连续 9 点",
 "9 points in a row"},
{"spc.rule.nine_same_side.threshold",
 "同侧 9 点",
 "9 points on the same side"},
{"spc.rule.nine_same_side.comparison",
 "全部位于中心线同一侧（中心线上点打断）",
 "All on the same side of the center line (on-center points break the run)"},
{"spc.rule.nine_same_side.explanation",
 "连续 9 个可用点全部在中心线同一侧；跨缺失或阶段断点不形成窗口。提示均值偏移、分层或阶段变化。",
 "Nine consecutive usable points all on the same side of the center line; missing or stage breaks do not form a window. Suggests mean shift, stratification, or stage change."},
{"spc.rule.six_point_trend.window",
 "连续 6 点",
 "6 points in a row"},
{"spc.rule.six_point_trend.threshold",
 "严格单调 6 点",
 "Strictly monotonic 6 points"},
{"spc.rule.six_point_trend.comparison",
 "严格递增或严格递减（相等打断）",
 "Strictly increasing or decreasing (ties break the run)"},
{"spc.rule.six_point_trend.explanation",
 "连续 6 点严格递增或严格递减；相等值不构成趋势。提示磨损、漂移或时间相关结构。",
 "Six consecutive points strictly increasing or decreasing; equal values do not form a trend. Suggests wear, drift, or time structure."},
{"spc.rule.fourteen_alternating.window",
 "连续 14 点",
 "14 points in a row"},
{"spc.rule.fourteen_alternating.threshold",
 "相邻符号严格交替",
 "Adjacent signs strictly alternating"},
{"spc.rule.fourteen_alternating.comparison",
 "相邻差分符号交替（零差分打断）",
 "Adjacent difference signs alternate (zero differences break the run)"},
{"spc.rule.fourteen_alternating.explanation",
 "连续 14 点相邻差值符号严格交替；零差值打断规则。提示周期、人机/设备交替或过度调整。",
 "Fourteen consecutive points with strictly alternating adjacent-difference signs; zero differences break the rule. Suggests cycles, alternating ops, or over-adjustment."},
{"spc.rule.two_of_three_beyond_2sigma.window",
 "连续 3 点窗口",
 "3-point window"},
{"spc.rule.two_of_three_beyond_2sigma.threshold",
 "同侧且 |y−CL| > 2σ，至少 2 点",
 "Same side and |y−CL| > 2σ, at least 2 points"},
{"spc.rule.two_of_three_beyond_2sigma.comparison",
 "同侧且严格大于 2σ",
 "Same side and strictly beyond 2σ"},
{"spc.rule.two_of_three_beyond_2sigma.explanation",
 "3 点窗口内至少 2 点位于中心线同侧且距离严格大于 2σ；提示较小但系统性的偏移。",
 "In a 3-point window, at least 2 points are on the same side of the center line and strictly beyond 2σ; suggests a smaller systematic shift."},
{"spc.rule.four_of_five_beyond_1sigma.window",
 "连续 5 点窗口",
 "5-point window"},
{"spc.rule.four_of_five_beyond_1sigma.threshold",
 "同侧且 |y−CL| > 1σ，至少 4 点",
 "Same side and |y−CL| > 1σ, at least 4 points"},
{"spc.rule.four_of_five_beyond_1sigma.comparison",
 "同侧且严格大于 1σ",
 "Same side and strictly beyond 1σ"},
{"spc.rule.four_of_five_beyond_1sigma.explanation",
 "5 点窗口内至少 4 点位于同侧且距离严格大于 1σ；提示过程均值发生小幅移动。",
 "In a 5-point window, at least 4 points are on the same side and strictly beyond 1σ; suggests a small process-mean move."},
{"spc.rule.fifteen_within_1sigma.window",
 "连续 15 点",
 "15 points in a row"},
{"spc.rule.fifteen_within_1sigma.threshold",
 "|y−CL| < σ",
 "|y−CL| < σ"},
{"spc.rule.fifteen_within_1sigma.comparison",
 "严格落在 ±1σ 以内",
 "Strictly within ±1σ"},
{"spc.rule.fifteen_within_1sigma.explanation",
 "连续 15 个点的绝对中心线距离严格小于 σ；提示控制限可能过宽或数据存在分层。",
 "Fifteen consecutive points with absolute center-line distance strictly less than σ; suggests limits may be too wide or data are stratified."},
{"spc.rule.eight_beyond_1sigma.window",
 "连续 8 点",
 "8 points in a row"},
{"spc.rule.eight_beyond_1sigma.threshold",
 "同侧且 |y−CL| > σ",
 "Same side and |y−CL| > σ"},
{"spc.rule.eight_beyond_1sigma.comparison",
 "同侧且严格大于 1σ",
 "Same side and strictly beyond 1σ"},
{"spc.rule.eight_beyond_1sigma.explanation",
 "连续 8 点均在中心线同一侧且绝对距离严格大于 σ；提示混合总体或双群模式。",
 "Eight consecutive points on the same side of the center line with absolute distance strictly greater than σ; suggests mixed populations or dual clusters."},
{"spc.rule.message.not_triggered_suffix",
 " 当前未触发。",
 " Currently not triggered."},
{"spc.rule.message.triggered_points_prefix",
 " 触发图点序号（1-based）: ",
 " Triggered plot point indices (1-based): "},
{"spc.rule.reason.not_verified",
 "规则未启用，本次分析未验证该特殊原因模式。",
 "Rule not enabled; this special-cause pattern was not verified in this analysis."},
{"spc.rule.reason.calculation_failed",
 "没有可绘制的控制图点，无法判定规则。",
 "No plottable control-chart points; rule cannot be evaluated."},
{"spc.rule.reason.not_applicable_prefix",
 "此规则不适用于控制图类型 ",
 "This rule does not apply to control chart type "},
{"interp.spc_policy_all_applicable",
 "特殊原因策略 = %1（多规则提高灵敏度也提高误报风险）",
 "Special-cause policy = %1 (more rules raise sensitivity and false-alarm risk)"},
{"interp.spc_policy_minitab_like",
 "特殊原因策略 = %1（默认接近 Minitab 仅「单点超出 3σ 控制限」）",
 "Special-cause policy = %1 (defaults near Minitab: only '1 point beyond 3σ limits')"},
};

}  // namespace

void append_report_text_catalog_part15(std::vector<ReportTextEntry>& out)
{
    out.insert(
        out.end(),
        std::begin(kReportTextCatalogPart15),
        std::end(kReportTextCatalogPart15));
}

}  // namespace datalab::domain
