# -*- coding: utf-8 -*-
"""Generate catalog + exact_ids snippets for interpretation deepen (manual paste aid)."""
from __future__ import annotations

# Fixed zh -> (id_suffix, en)
FIXED = [
    ("doe_no_pvalue",
     "DOE 表中没有可用的 P-Value；不能据此宣称因子或交互作用显著。",
     "The DOE table has no usable P-Value; do not claim factor or interaction significance from it."),
    ("doe_confirm_significant",
     "优先在确认性试验中复核显著项，并结合效应方向选择可操作的因子水平；显著性本身不代表工程影响足够大。",
     "Re-check significant terms in confirmatory trials and choose operable factor levels with effect direction; significance alone does not mean engineering impact is large enough."),
    ("doe_no_cube_plot",
     "未生成立方图（仅支持 2–3 个因子）；高维设计请结合 Pareto 与主效应/交互图。",
     "Cube plot was not generated (only 2–3 factors supported); for higher-dimensional designs combine Pareto with main-effect/interaction plots."),
    ("doe_residual_plots",
     "残差图供调查残差形态；直方图不用于证明正态。",
     "Residual plots are for investigating residual patterns; histograms are not used to prove normality."),
    ("doe_contour_coded_space",
     "等值线/曲面在编码 [-1,1] 空间求值；非轴因子默认 hold 编码 0，也可按实际单位 hold；二水平模型无平方项，不能把曲面曲率当成已估计。",
     "Contours/surfaces are evaluated in coded [-1,1] space; non-axis factors default to coded hold 0 (or actual-unit hold); two-level models have no quadratic terms—do not treat surface curvature as estimated."),
    ("doe_check_residuals_before_opt",
     "检查残差随机性、异常值和重复/纯误差后再确定最优设置；不要仅凭主效应图下结论。",
     "Check residual randomness, outliers, and replicate/pure error before choosing optimal settings; do not conclude from main-effect plots alone."),
    ("doe_rank_deficient",
     "设计矩阵秩亏，回归系数不可解释。",
     "The design matrix is rank-deficient; regression coefficients are not interpretable."),
    ("doe_no_center_pure_error",
     "未检测到中心点；纯误差估计可能不可用。",
     "No center points detected; pure-error estimation may be unavailable."),
    ("doe_lof_df_insufficient",
     "有纯误差但失拟自由度不足，未给出失拟 F/P。",
     "Pure error exists but lack-of-fit degrees of freedom are insufficient; LOF F/P was not reported."),
    ("doe_axial_beyond_range",
     "检测到星点超出原始因素范围；需人工确认实验可行性。",
     "Axial points beyond the original factor ranges were detected; confirm experimental feasibility manually."),
    ("doe_unestimable_terms",
     "存在不可估计项或误差自由度不足，这些项不输出伪造 F/P。",
     "Unestimable terms or insufficient error df are present; forged F/P values are not emitted for those terms."),
    ("doe_error_df_insufficient",
     "误差自由度不足，不输出 t、F 与 P。",
     "Error degrees of freedom are insufficient; t, F, and P are not emitted."),
    ("rsm_coded_coeffs",
     "RSM 系数在编码单位；显著不等于已找到工程最优设定。",
     "RSM coefficients are in coded units; significance does not mean an engineering optimum was found."),
    ("rsm_static_surface",
     "曲面图为静态栅格，不是可旋转交互 3D。",
     "The surface plot is a static grid, not an interactive rotatable 3D view."),
    ("rsm_check_model_adequacy",
     "请结合残差与拟合值/顺序/正态/直方图判断模型充分性。",
     "Judge model adequacy using residuals with fitted/order/normal/histogram diagnostics together."),
    ("msa_negative_variance",
     "存在负方差分量并已截断为 0；解释时应同时查看原始估计。",
     "Negative variance components were truncated to 0; review the raw estimates when interpreting."),
    ("msa_by_part_plot",
     "按零件图展示各零件重复测量的离散程度；同一零件上点越集中表示重复性越小。该图不单独判定量具是否合格。",
     "The by-part plot shows within-part repeat scatter; tighter points on a part mean smaller repeatability. The plot alone does not pass/fail the gage."),
    ("msa_study_tol_together",
     "将 %Study Var、%Tolerance 和现场公差一起看，不要把单个百分比写成量具合格。",
     "Read %Study Var, %Tolerance, and field tolerance together; do not write a single percentage as gage pass."),
    ("msa_bias_linearity_incomplete",
     "偏倚/线性表缺少斜率或端点偏倚，不能作完整判定。",
     "The bias/linearity table lacks slope or endpoint bias; a complete judgment cannot be made."),
    ("msa_compare_endpoint_bias",
     "将端点偏倚与产品公差和测量系统可接受界限比较；回归关系不能替代跨操作者、跨部件的完整 Gage R&R。",
     "Compare endpoint bias with product tolerance and MSA acceptance limits; regression does not replace full cross-operator/part Gage R&R."),
    ("msa_stability_investigate",
     "按时间顺序回查校准、环境、操作者和量具维护记录；不要在特殊原因未排除前用该量具放行产品。",
     "Review calibration, environment, operators, and gage maintenance in time order; do not release product with this gage until special causes are cleared."),
    ("msa_appraiser_part_not_pass",
     "评估者×零件图是观察一致率，不是量具通过或已证明一致。",
     "The appraiser×part plot shows observed agreement rates, not gage pass or proven agreement."),
    ("msa_type1_incomplete",
     "Type 1 表缺少 P 或 Cgk，不能完整评价偏倚与重复性。",
     "The Type 1 table lacks P or Cgk; bias and repeatability cannot be fully evaluated."),
    ("rel_mode_fit_honesty",
     "分模式可靠度为 formula_reference（竞争失效作右删失），不是 vendor_oracle / golden；阈值模型与 pinned R 对齐仍未冻结。",
     "Mode-specific reliability is formula_reference (competing failures treated as right-censored), not vendor_oracle/golden; threshold models and pinned-R alignment are not frozen."),
    ("rel_not_identifiable",
     "可靠性结果当前不可识别，不能估计寿命分位数。",
     "Reliability results are currently non-identifiable; life percentiles cannot be estimated."),
    ("rel_median_not_reached",
     "生存曲线未下降到 0.5，中位寿命不可估计。",
     "The survival curve did not fall to 0.5; median life is not estimable."),
    ("rel_km_advice_logrank",
     "按目标任务时间读取生存概率和置信区间；比较方案时使用分层或 Log-rank。",
     "Read survival probability and confidence intervals at the target mission time; use stratified or Log-rank tests when comparing plans."),
    ("rel_exp_not_proven",
     "指数拟合未拒绝假设不等于已证明寿命服从指数分布。",
     "Failing to reject an exponential fit does not prove lifetimes follow an exponential distribution."),
    ("rel_lognormal_not_proven",
     "对数正态拟合未拒绝假设并不等于已证明寿命服从对数正态。",
     "Failing to reject a lognormal fit does not prove lifetimes follow a lognormal distribution."),
    ("rel_weibull3_not_proven",
     "三参数拟合未拒绝假设不等于已证明寿命服从三参数 Weibull。",
     "Failing to reject a three-parameter fit does not prove lifetimes follow a three-parameter Weibull."),
    ("rel_lognormal_not_converged",
     "对数正态参数未收敛，分位寿命不能作为决策依据。",
     "Lognormal parameters did not converge; percentile life must not be used for decisions."),
    ("eda_not_hypothesis_test",
     "EDA 图用于探索形态与频数，不是假设检验结论。",
     "EDA plots explore shape and frequency; they are not hypothesis-test conclusions."),
    ("pareto_use_with_field",
     "若要比较原因频次优先级，请改用柏拉图并结合现场验证。",
     "To prioritize cause frequencies, use a Pareto chart and validate in the field."),
    ("chi2_small_expected_cats",
     "存在期望频数过小的类别，卡方近似可能不可靠。",
     "Some categories have small expected counts; the chi-square approximation may be unreliable."),
    ("chi2_small_expected_cells",
     "存在期望频数过小的单元格，卡方近似可能不可靠。",
     "Some cells have small expected counts; the chi-square approximation may be unreliable."),
    ("percent_table_descriptive",
     "百分比表是描述性结果，不能写成已证明存在或不存在关联。",
     "Percentage tables are descriptive; do not write them as proof that association exists or does not."),
    ("row_col_pct_descriptive",
     "行%/列%/合计% 是描述性汇总，不替代独立性检验结论。",
     "Row%/column%/total% are descriptive summaries and do not replace an independence-test conclusion."),
    ("heatmap_counts_not_causal",
     "观察频数热图只展示列联表中的计数分布，不能证明因果关系。",
     "Observed-count heatmaps only show contingency counts; they do not prove causation."),
    ("anova_f_needs_posthoc",
     "总体 F 显著只说明至少一组不同，需要多重比较确定具体组对。",
     "A significant overall F only means at least one group differs; use multiple comparisons to identify pairs."),
    ("power_table_empty",
     "功效/样本量结果表为空，不能给出设计建议。",
     "The power/sample-size result table is empty; design advice cannot be given."),
    ("power_invalid_config",
     "效应量或 α 配置不在有效范围，不能把数值当作正式设计依据。",
     "Effect size or α is outside a valid range; do not treat the numbers as formal design evidence."),
    ("forecast_table_empty",
     "预测结果表为空，不能评价预测或未来期。",
     "The forecast result table is empty; forecasts or future periods cannot be evaluated."),
    ("season_period_lt2",
     "季节周期小于 2，不能支持有意义的季节性解释。",
     "Seasonal period < 2 cannot support a meaningful seasonality interpretation."),
    ("season_index_lt2",
     "季节周期小于 2，不能支持有意义的季节指数解释。",
     "Seasonal period < 2 cannot support a meaningful seasonal-index interpretation."),
    ("pca_not_converged",
     "特征分解未收敛时不对主成分或异常点给出稳定解释。",
     "When eigendecomposition does not converge, do not give stable PCA or outlier interpretations."),
    ("small_sample_approx_p",
     "存在小样本组，近似 P 值只作提示。",
     "Small-sample groups are present; approximate P-values are hints only."),
    ("review_special_causes",
     "建议回查对应原始行并确认特殊原因。",
     "Review the corresponding source rows and confirm special causes."),
    ("percentile_not_bca",
     "本轮为百分位法，非 BCa。",
     "This run uses the percentile method, not BCa."),
    ("stepwise_not_best_subsets",
     "α 逐步；非 Best subsets；选择不稳定时勿外推。",
     "α-stepwise selection; not Best Subsets; do not extrapolate when selection is unstable."),
    ("no_negbin_zi_offset",
     "本轮无负二项/零膨胀/偏移列；非 Minitab golden。",
     "This run has no negative-binomial/zero-inflated/offset column; not Minitab golden."),
    ("not_sklearn_treenet",
     "自研实现；非 sklearn 运行时；非 TreeNet/RF。",
     "In-house implementation; not an sklearn runtime; not TreeNet/RF."),
    ("layer_means_not_process_call",
     "分层均值图只用于探索变异来源，不能把结果写成过程判定。",
     "Layer-mean plots explore sources of variation; do not write them as process pass/fail."),
    ("bw_fixed_not_prewhitened",
     "白噪声固定带宽；非预白化；宜与 ACF/PACF 对照。",
     "White-noise bandwidth is fixed; not prewhitened; cross-check with ACF/PACF."),
    ("do_not_treat_pairwise_alpha_as_fwer",
     "不要把逐比较 alpha 当成家族错误率。",
     "Do not treat per-comparison alpha as a family-wise error rate."),
]

TEMPLATES = [
    ("doe_significant_terms",
     "在 α = %1 下显著的项：%2。",
     "Significant terms at α = %1: %2."),
    ("doe_design_factors_centers",
     "设计包含 %1 个因子、%2 个中心点；实施时保持随机化/区组记录，避免把运行顺序效应误认为因子效应。",
     "Design has %1 factor(s) and %2 center point(s); keep randomization/block records in execution so run-order effects are not mistaken for factor effects."),
    ("gage_stability_ooc",
     "量具稳定性图发现 %1 个超限点，统计上存在失控信号。",
     "Gage stability chart found %1 out-of-control point(s); a statistical out-of-control signal is present."),
    ("msa_bias_slope_endpoints",
     "偏倚回归斜率 = %1，低/高参考点偏倚 = %2 / %3。",
     "Bias regression slope = %1; low/high reference bias = %2 / %3."),
    ("km_counts_summary",
     "Kaplan-Meier 有效观测 %1，失效 %2，删失 %3。",
     "Kaplan-Meier: %1 valid observation(s), %2 failure(s), %3 censored."),
    ("rel_mode_fits_count",
     "已对 %1 个失效模式做 cause-specific 分模式拟合（scheme=%2）。",
     "Fitted cause-specific mode models for %1 failure mode(s) (scheme=%2)."),
    ("rel_not_identifiable_reason",
     "可靠性结果不可识别（%1），不能估计寿命分位数。",
     "Reliability results are non-identifiable (%1); life percentiles cannot be estimated."),
]

print(f"FIXED={len(FIXED)} TEMPLATES={len(TEMPLATES)}")
for sid, zh, en in FIXED + TEMPLATES:
    print(f'        {{"interp.{sid}",')
    print(f'         "{zh}",')
    print(f'         "{en}"}},')
