"""Remaining help catalog families: ANOVA through graphs."""

SPC_TESTS = [
    "Test 1：一点超出该点子组的控制限（y < LCL 或 y > UCL）。",
    "Test 2：连续 9 点严格在中心线同一侧。",
    "Test 3：连续 6 点持续上升或持续下降。",
    "Test 4：连续 14 点上下交替。",
    "Test 5：连续 3 点中至少 2 点位于同侧 2σ 外。",
    "Test 6：连续 5 点中至少 4 点位于同侧 1σ 外。",
    "Test 7：连续 15 点都严格落在中心线两侧 1σ 以内；恰在 1σ 上的点不触发。",
    "Test 8：连续 8 点都在 1σ 外（两侧都算，不要求交替）。",
    "同一点触发多个测试时，图上标签用最小测试编号；表格列出全部失败测试。",
    "R/S/MR 图只适用 Test 1–4；EWMA 只适用 Test 1。",
]


def spc_invalid() -> str:
    return (
        "测量值必须为有限数。子组图：缺失/非法值、固定子组尾部不完整、标签子组大小不一致时只诊断不计算。"
        "属性图：计数与分母必须是非负整数，分母不能为 0；P/NP 还要求不合格品数 ≤ 检验数。"
        "未提供历史参数且无法估计 σ 或 Sigma Z 时中止。"
    )


def add_remaining(entry, fb, t, frac, sqrt, ENTRIES, bar, dbar, heading, line, cases, stack, sub, sup) -> None:
    ENTRIES.append(entry(
        "one_way_anova", "单因素 ANOVA", "ANOVA", "统计 > ANOVA",
        "one_way_anova", "anova", "quality_statistics_test",
        "检验多个组的均值是否全部相等。",
        "分解组间/组内平方和得到 F。组均值个体区间用 pooled MSE。Tukey 同时区间是 conservative Šidák–t / studentized-range 近似，不是精确 Studentized Range。表形拆成下限/上限两列，并输出差值同时区间图与 Grouping Information 字母。",
        "一个数值测量列和一个分组列。",
        ["按组 complete-case。", "算 SS_Between、SS_Error、MS 与 F。", "组均值区间用 MSE。",
         "输出 Tukey 同时区间（下限/上限列）、差值区间图与 CLD 字母表。"],
        [("k", "组数"), ("N", "总有效样本量"), ("MSE", "误差均方"), ("F", "MS_Between/MS_Error")],
        [fb("ANOVA 分解",
            "SS_Between=Σ n_j(ȳ_j−ȳ)²，SS_Error=ΣΣ(y_ij−ȳ_j)²，F=MS_Between/MS_Error，DF_Between=k−1，DF_Error=N−k。",
            [t("F = "), frac("MS_Between", "MS_Error")]),
         fb("Tukey 同时区间", "复用总体 MSE 与误差 DF。输出下限与上限两列；区间含 0 不得标为显著差异。不改近似算法。"),
         fb("Grouping Information", "按现有成对 significant（区间是否含 0）做 Compact Letter Display；"
            "同字母表示在本产品规则下未显著不同。不做精确 Studentized Range。")],
        ["总体 H0：所有组均值相等。", "F 显著不等于已经指出哪两组不同。", "同字母不能写成已证明相同。"],
        "组数<2、某组无有效观测或误差 DF≤0 时诊断。",
        "组均值表、ANOVA 表、Tukey 下限/上限表、Grouping Information、组均值区间图、Tukey 差值区间图、残差四图。",
        "先看总体 F，再用 Tukey 下限/上限与字母看哪对不同。",
        "残差图用于检查，不自动证明正态或等方差。",
        ["anova"],
    ))

    ENTRIES.append(entry(
        "two_factor_anova", "双因素 ANOVA", "ANOVA", "统计 > ANOVA",
        "two_factor_anova", "anova", "two_factor_anova_output_test",
        "把响应变异分解为因子 A、因子 B 和交互作用。",
        "用 RSS 差值构造各项平方和。不平衡或缺失格子导致不可估计时，F/P 显示为 *，不伪造数值。",
        "一个响应列和两个因子列。",
        ["complete-case 三列对齐。", "拟合含交互模型，用 RSS 差得到各项 SS。", "不可估计项标记 *。", "残差四图；交互均值按因子 B 连线。"],
        [("A,B", "两个因子"), ("RSS", "残差平方和"), ("*", "该项不可估计")],
        [fb("RSS 差值", "某效应的 SS = RSS(去掉该项的模型) − RSS(完整模型)。DF 不足或别名时不输出 F/P。")],
        ["不可估计 ≠ 效应为 0。", "交互图只展示格子均值，不代替检验。"],
        "因子水平过少、完全空格子导致设计不可识别、或响应非有限时诊断。",
        "ANOVA 表（可能含 *）、残差四图、交互均值图。",
        "先看哪些项可估计，再看 F/P。",
        "不填补空格子。",
        ["anova"],
    ))

    ENTRIES.append(entry(
        "regression", "线性回归", "回归", "统计 > 回归",
        "regression", "regression", "regression_output_test",
        "用一个或多个预测变量拟合带截距的线性模型。",
        "QR 分解求最小二乘。error_df=N−p−1≤0 时只给点估计，不输出 t/F/P。异常观测按 R/X/I 打标。",
        "一个响应列，一个或多个预测列。",
        ["complete-case 对齐。", "含截距设计矩阵，QR 求解。", "SSE、R²、Adj R²、系数 t、VIF、Cook、残差。",
         "单预测变量画拟合线与 CI/PI；多预测变量画残差对每个 X。"],
        [("p", "预测变量个数（不含截距）"), ("h_ii", "杠杆"), ("SSE", "残差平方和"), ("VIF", "方差膨胀因子")],
        [fb("最小二乘", "y=Xβ+ε，MSE=SSE/(n−p−1)，R²=1−SSE/SST。",
            [t("R² = 1 − "), frac("SSE", "SST")]),
         fb("残差", "内部标准化 e_i/(s√(1−h_ii))；学生化用删除后 s_(i)。"),
         fb("异常观测", "R=残差大，X=杠杆高，I=影响大。无打标则不出现该表。")],
        ["VIF>5 只是共线性调查提示，不自动删列。", "R² 高不等于模型合格。",
         "Durbin–Watson 按输入行序；α=0.05 近似 dL/dU 判定区，不能写成已证明无自相关。"],
        "秩亏、有效行不足或无法对齐时诊断。",
        "系数表、ANOVA（Seq SS/Adj SS）、Durbin-Watson 表、拟合优度、异常观测、残差图/拟合线图。",
        "同时看系数区间、残差形态、DW 判定区和异常点原始行。",
        "不自动做变量选择。",
        ["reg"],
    ))

    ENTRIES.append(entry(
        "logistic_regression", "二元 Logistic 回归", "回归", "统计 > 回归",
        "logistic_regression", "logistic", "quality_statistics_test",
        "用对数几率模型预测二元事件概率。",
        "IRLS 拟合。Hosmer–Lemeshow 只在分组可行（通常 n≥20）时计算。输出拟合与残差表、最大杠杆与阈值 `min(3p/n,0.99)`，系数表附 VIF。",
        "二元响应列与一个或多个预测列。",
        ["编码事件/非事件。", "IRLS 估系数。", "若可行则做 HL。", "计算杠杆并用 `min(3p/n,0.99)` 标记高杠杆。", "输出影响点、残差与 VIF。"],
        [("π", "事件概率"), ("HL", "Hosmer–Lemeshow 卡方"), ("p", "参数个数（含截距）"), ("VIF", "方差膨胀因子")],
        [fb("对数几率", "logit(π)=ln(π/(1−π))=xᵀβ。"),
         fb("Hosmer–Lemeshow", "按预测概率分组比较观察与期望事件数。n<20 或分组不可行则为未计算。"),
         fb("高杠杆阈值", "高杠杆阈值 = min(3p/n, 0.99)。VIF 只作为共线性调查线索，不自动删变量。")],
        ["拒绝 HL 只说明拟合不足的证据，不写模型已充分。", "未知事件编码直接拒绝。"],
        "响应不是二元、完全分离不收敛或预测秩亏时诊断。",
        "系数表（含 VIF）、拟合优度表、拟合与残差/影响点（含杠杆阈值）。",
        "先看收敛与 HL 状态，再看系数方向。",
        "不做多项或有序 logistic。",
        ["reg"],
    ))

    ENTRIES.append(entry(
        "chi_square", "列联表卡方", "假设检验", "统计 > 假设检验",
        "chi_square", "chi_square", "quality_statistics_test",
        "检验两个分类变量是否独立。",
        "Pearson χ²、似然比 χ²、期望频数、残差和单元贡献；行%/列%/合计%；观察频数热图与调整残差热图。"
        "期望<1 时不显示近似 P。与交叉表命令分流：本命令做关联检验。",
        "两个分类列。",
        ["complete-case 交叉分类。", "期望=行合计×列合计/总计。", "Pearson 与似然比。",
         "标准化残差=r/√E；调整残差=r/√[E(1−n_i+/n)(1−n_+j/n)]。",
         "输出百分比表与调整残差热图。"],
        [("O", "观察频数"), ("E", "期望频数"), ("χ²", "Pearson 统计量"),
         ("Adj residual", "调整残差")],
        [fb("Pearson", "χ²=Σ (O−E)²/E。", [t("χ² = Σ "), frac("(O − E)²", "E")])],
        ["p 小不等于有因果关系。", "期望<1 时近似失效。", "最大 |调整残差| 只定位偏离，不证明因果。"],
        "任一类无有效水平或表退化时诊断。",
        "观察表、检验表、单元格统计、百分比表、观察热图、调整残差热图。",
        "先看期望是否过小，再看 p、残差热图与贡献最大单元格。",
        "不合并稀疏格子；不改 chi_square_gof。",
        ["crosstab"],
    ))

    ENTRIES.append(entry(
        "cross_tabulation", "交叉表", "描述统计", "统计 > 表格",
        "cross_tabulation", "cross_tab", "p2_eda4_crosstab_chi_resid_test",
        "独立交叉表：观察频数与行%/列%/合计%，不做卡方检验。",
        "complete-case 交叉分类；输出频数表、三类百分比与观察频数热图。"
        "独立性检验请用列联表卡方。不替代 chi_square / chi_square_gof。",
        "两个分类列。",
        ["complete-case 交叉分类。", "边际合计。", "行%=O/行合计；列%=O/列合计；合计%=O/N。",
         "信息诊断提示改用 chi_square 做检验。"],
        [("O", "观察频数"), ("row%", "行百分比"), ("col%", "列百分比"), ("total%", "合计百分比")],
        [fb("百分比", "描述性比例，不是检验统计量。",
            [t("row% = 100 · O / n_{i+}；col% = 100 · O / n_{+j}；total% = 100 · O / n")])],
        ["不得写成已证明存在或不存在关联。", "不做 Pearson/LR 检验。"],
        "无有效交叉观测时诊断。",
        "观察频数表、百分比表、热图。",
        "先看边际与百分比结构；若要检验独立性，改用列联表卡方。",
        "不破坏 chi_square 命令；本命令不做检验。",
        ["crosstab"],
    ))

    ENTRIES.append(entry(
        "chi_square_gof", "卡方拟合优度", "假设检验", "统计 > 假设检验",
        "chi_square_gof", "chi_square_gof", "capability_ci_gof_rare_event_power_test",
        "检验一个分类变量的观察频数是否符合指定或等比例。",
        "Pearson χ²。类别按首次出现顺序。默认等比例；可选逗号分隔期望比例。输出 `minimum_expected_count`、`validity_status` 与 recommendation，作为建议而不是硬判。与列联表卡方命令独立，不画热图。",
        "一个分类列；可选期望比例。",
        ["complete-case 计数；* 计入 N*。", "E_i=p_i N。", "χ²=Σ(O−E)²/E，DF=k−1。", "记录最小期望频数并给出 validity/recommendation。", "条图对比观察与期望。"],
        [("O", "观察频数"), ("E", "期望频数"), ("p_i", "检验比例"), ("minimum_expected_count", "最小期望频数")],
        [fb("Pearson 拟合优度", "χ²=Σ (O−E)²/E，E=pN。",
            [t("χ² = Σ "), frac("(O − E)²", "E")]),
         fb("有效性提示", "`validity_status` 依据期望频数大小给出 `ok / caution / weak` 一类提示；recommendation 只提醒近似是否偏弱，不把结果硬判 invalid。")],
        ["p 小不等于总体比例已被否定为唯一真相。", "比例个数与类别不符只诊断，不硬凑。"],
        "少于两个类别、计数非法或比例和不为 1 时诊断。",
        "观察与期望表、卡方检验表、观察/期望条图、有效性提示。",
        "先看 `minimum_expected_count` / `validity_status`，再看 χ² 与残差。",
        "不把两列按索引 zip。",
        ["gof"],
    ))

    ENTRIES.append(entry(
        "mann_whitney", "Mann-Whitney 检验", "假设检验", "统计 > 假设检验",
        "mann_whitney", "nonparametric", "quality_statistics_test",
        "不假设正态，比较两独立样本的位置。",
        "秩和。位置差 Hodges–Lehmann；区间 McKean–Ryan。公式参考非 golden。",
        "两个独立数值样本。",
        ["两组 complete-case。", "合并赋平均秩。", "W、近似 p、HL 与 CI。"],
        [("W", "秩和"), ("HL", "Hodges–Lehmann 位置差"), ("ties", "结的个数")],
        [fb("秩和与 HL", "合并赋秩，结用平均秩。HL 为两样本差的两两中位数；McKean–Ryan 为其序统计区间。")],
        ["有结时报告 ties 与两种 p。", "不得写成已证明分布相同或不同。"],
        "任一组有效观测过少时诊断。",
        "秩和表、位置差与 CI、箱线/个体值图。",
        "看位置差区间是否含 0。",
        "小样本近似变差。",
        ["t"],
    ))

    ENTRIES.append(entry(
        "wilcoxon_signed_rank", "Wilcoxon 符号秩检验", "假设检验", "统计 > 假设检验",
        "wilcoxon_signed_rank", "nonparametric", "quality_statistics_test",
        "对配对差或单样本中位数做符号秩检验。",
        "去掉差值为 0 的观测，对绝对值赋秩再带上符号。单样本相对 η0；配对两列差分。单样本与配对均报 Walsh 估计中位数与正态近似 CI（公式参考）。",
        "一列+η0（默认 0），或两列配对；可选置信水平（Walsh CI）。",
        ["complete-case 对齐。", "算差值并去掉 0。", "绝对值赋秩，加回符号。", "近似 p；Walsh 点估计与 CI。"],
        [("W⁺", "正秩和"), ("η0", "假设中位数"), ("Walsh", "两两平均的中位数")],
        [fb("符号秩", "对 |d_i|>0 赋秩，W 为带符号秩和；结修正方差。零差不进入秩。"),
         fb("Walsh 估计", "对非结观测构造 (Yi+Yj)/2（i≤j），取中位数为 η̂；CI 用正态近似秩序统计。",
            conditions="单样本与配对；formula_reference。")],
        ["零差不进秩。", "不得写已证明中位数等于假设值。", "不改秩和/结修正公式。"],
        "非零差个数过少时诊断。",
        "符号秩表；位置估计（Walsh）表；箱线/个体值；配对另有散点。",
        "结合图形看差的方向；先看 η̂ 与区间是否含 0（或 η0）。",
        "分布明显不对称时优先符号检验。",
        ["wilcoxon1", "nist_np"],
    ))

    ENTRIES.append(entry(
        "mood_median", "Mood 中位数检验", "假设检验", "统计 > 假设检验",
        "mood_median", "nonparametric", "quality_statistics_test",
        "不假设正态，比较 k 组中位数（基于总体中位数的 2×k 表）。",
        "全体求总体中位数 M；各组计 N≤ / N>（等于 M 计入 N≤）；对 2×k 表做 Pearson χ²。各组另报 Sign 中位数 CI（复用序统计 helper）。",
        "测量列+分组列；complete-case；N<2 的水平排除；可选置信水平。",
        ["complete-case。", "计算总体中位数 M。", "各组计 N≤、N> 与 Sign CI。", "Pearson χ² 与 p。"],
        [("M", "总体中位数"), ("N≤", "≤M 的个数"), ("N>", ">M 的个数"), ("χ²", "Pearson 统计量")],
        [fb("Mood", "χ²=Σ(O−E)²/E，DF=k−1；期望 E=行合计×列合计/N。"),
         fb("各组 Sign CI", "对组内有限观测做精确序统计中位数区间；达到水平最接近名义 γ。",
            conditions="formula_reference；与 Mood χ² 独立。")],
        ["不得写已证明各组中位数相同。", "不做 Mood 后比较。", "不改 Kruskal Dunn/Steel–Dwass。"],
        "有效组不足、N≤ 或 N> 一侧为 0 时诊断；期望频数 <5 警告；组 CI 不可算时诊断。",
        "各组 Above/Below（含 CI）、Mood 检验表、箱线/个体值。",
        "先看 χ²/p，再看各组 N≤/N>、CI 与箱线。",
        "需要秩检验时用 Kruskal-Wallis。",
        ["mood", "nist_np"],
    ))

    ENTRIES.append(entry(
        "cochran_q", "Cochran Q 检验", "假设检验", "统计 > 假设检验",
        "cochran_q", "cochran_q", "quality_statistics_test",
        "配对二元、k≥3 处理的边际阳性率检验。",
        "宽表 complete-case；二元编码与 McNemar 相同。Q=(k−1)(kΣC²−T²)/(kT−ΣR²)，DF=k−1。k=2 只诊断并引导 McNemar。",
        "≥3 列配对二元（0/1、pass/fail 等）。",
        ["多列 complete-case。", "二元编码。", "计算列和/行和。", "Q 与 χ² 近似 p。"],
        [("Q", "Cochran 统计量"), ("C_j", "处理 j 成功数"), ("R_i", "受试者 i 成功数")],
        [fb("Cochran Q", "Q=(k−1)(kΣ_j C_j²−T²)/(kT−Σ_i R_i²)，近似 χ²_{k−1}。")],
        ["不得写已证明各处理阳性率相同。", "不修改 chi_square / chi_square_gof。", "k=2 请用 McNemar。"],
        "列数<3、非二元、分母退化时诊断。",
        "处理成功计数表、Cochran Q 检验表、阳性率条图。",
        "先确认 k≥3 与二元编码，再看 Q/p。",
        "两列配对用 McNemar。",
        ["mcnemar", "nist_np"],
    ))

    ENTRIES.append(entry(
        "kruskal_wallis", "Kruskal-Wallis 检验", "假设检验", "统计 > 假设检验",
        "kruskal_wallis", "nonparametric", "quality_statistics_test",
        "不假设正态，比较 k 组位置。",
        "全体赋秩后看组平均秩。默认 posthoc=dunn：Dunn–Bonferroni 成对比较与 Grouping Information。可选 posthoc=steel_dwass：成对 Wilcoxon + 渐近 Tukey–Kramer 临界（近似），Grouping 标题标明 Steel-Dwass。",
        "测量列+分组列；可选 posthoc=dunn|steel_dwass。",
        ["全体 complete-case 赋平均秩。", "计算 H 与 p。", "报告组平均秩与 Z。",
         "按 posthoc 输出 Dunn 或 Steel–Dwass 成对表；按显著矩阵生成 Grouping 字母。"],
        [("H", "Kruskal–Wallis 统计量"), ("R̄_j", "第 j 组平均秩"),
         ("Dunn Z", "|R̄_i−R̄_j|/SE"), ("Steel–Dwass Z", "成对 Wilcoxon 标准化统计量"),
         ("Grouping", "多重比较字母")],
        [fb("KW", "H 基于各组平均秩相对总平均秩的加权平方和，近似 χ²_{k−1}。"),
         fb("Dunn", "SE=√[(N(N+1)/12−C_tie)·(1/n_i+1/n_j)]；p_adj=min(1,m·p_raw)。",
            conditions="posthoc=dunn（默认）。"),
         fb("Steel–Dwass（近似）", "每对做 Wilcoxon 秩和得 |Z|；显著当 |Z|≥q_{α,k,∞}/√2（本产品用渐近正态 Bonferroni/TK 临界）。",
            conditions="posthoc=steel_dwass；formula_reference，非 Minitab golden。")],
        ["显著不等于过程不合格。", "不得写已证明相同或不同。", "不做精确 studentized-range 表。"],
        "组数<2 或有效观测不足时诊断。",
        "KW 表、成对比较表、Grouping Information、组箱线/个体值。",
        "先看 H/p，再看哪对显著与字母分组；切换 posthoc 时默认仍为 Dunn。",
        "有结时使用结修正。",
        ["t"],
    ))

    ENTRIES.append(entry(
        "friedman", "Friedman 检验", "假设检验", "统计 > 假设检验",
        "friedman", "nonparametric", "quality_statistics_test",
        "区组设计下比较多个处理的位置（非参数重复测量）。",
        "每个区组内对处理赋秩，汇总处理秩和后计算 Friedman S（可结修正），近似 χ²_{k−1}。要求每区组×处理恰 1 个观测。可选 posthoc=nemenyi：平均秩差 Nemenyi（近似）成对比较与 Grouping。",
        "响应列、处理列、区组列；complete-case；可选 posthoc=nemenyi。",
        ["三列 complete-case 对齐并保留 source_row。", "检查平衡设计。", "区组内赋秩并汇总。",
         "计算 S / 调整 S 与 p。", "若 posthoc=nemenyi，输出成对表与 Grouping。"],
        [("S", "Friedman 统计量"), ("S′", "结修正后统计量"), ("R̄_j", "处理 j 平均秩"),
         ("Nemenyi Z", "|R̄_i−R̄_j|/SE"), ("Grouping", "多重比较字母")],
        [fb("Friedman", "S=12/(bk(k+1))Σ R_.j² − 3b(k+1)；结修正 S′=S/(1−C/(bk(k²−1)))。"),
         fb("Nemenyi（近似）", "SE=√(k(k+1)/(6b))；显著当 |Z|≥q_{α,k,∞}/√2（与 Steel–Dwass 同族渐近临界）。",
            conditions="posthoc=nemenyi；默认无后比较；formula_reference。")],
        ["不得写已证明相同或不同。", "不做独立 Nemenyi 命令。", "不做精确 studentized-range 表。"],
        "不平衡区组、重复单元格、处理/区组不足或输入错位时诊断。",
        "处理摘要、Friedman 检验表、可选 Nemenyi 成对/Grouping、按处理箱线/个体值。",
        "先确认区组完整，再看 S/p；需要成对比较时显式选 nemenyi。",
        "独立样本多组比较请用 Kruskal-Wallis。",
        ["t"],
    ))

    ENTRIES.append(entry(
        "sign_test", "符号检验", "假设检验", "统计 > 假设检验",
        "sign_test", "nonparametric", "quality_statistics_test",
        "对单样本中位数或配对差做符号检验（二项精确），并报告中位数置信区间。",
        "丢弃等于假设中位数的结后，对 n+/n− 做 Bin(n,1/2) 精确双侧（或单侧）p。中位数 CI 基于全部有限观测的精确序统计区间（达到水平最接近名义 γ）。",
        "一列+η0（默认 0），或两列配对差分对 0；可选置信水平。",
        ["complete-case 对齐。", "丢弃结并计数 n+/n−。", "计算二项精确 p。", "序统计中位数 CI。"],
        [("n+", "大于 η0 的个数"), ("n−", "小于 η0 的个数"), ("η0", "假设中位数")],
        [fb("Sign 主检验", "双侧 p=2·min{P(X≤n+),P(X≥n+)}，X~Bin(n,1/2)，截断到 [0,1]。"),
         fb("Sign CI", "对有序样本取最大 d 使 P(B<d)<α/2；在窄/宽精确区间中选达到水平最接近 γ 者。",
            conditions="formula_reference；不做 NLI 三区间。")],
        ["不得写已证明中位数等于假设值。", "不改 Wilcoxon 符号秩本体。"],
        "全结或无有效符号时诊断；n<2 时无 CI。",
        "符号摘要、符号检验表、中位数置信区间表、箱线/个体值；配对另有散点。",
        "先看有效符号数与精确 p，再看中位数区间。",
        "需要秩信息时用 Wilcoxon 符号秩。",
        ["t"],
    ))

    ENTRIES.append(entry(
        "mcnemar", "McNemar 检验", "假设检验", "统计 > 假设检验",
        "mcnemar", "mcnemar", "quality_statistics_test",
        "配对二元结果的边际比例检验（2×2 不一致对）。",
        "complete-case 两列二元标签；Edwards 连续性校正 χ²=(|b−c|−1)²/(b+c)。不改列联表卡方命令。",
        "两列配对二元（0/1、pass/fail、yes/no，或恰两水平）。",
        ["配对 complete-case。", "识别二元水平。", "统计 a,b,c,d。", "计算 Edwards χ² 与 p。"],
        [("b,c", "不一致对计数"), ("χ²", "Edwards 统计量")],
        [fb("McNemar–Edwards", "当 b+c>0：χ²=(|b−c|−1)²/(b+c)，DF=1；|b−c|<1 时分子置 0。")],
        ["不得写已证明前后比例相同或不同。", "不修改 chi_square / chi_square_gof。"],
        "非二元、水平不对齐或 b+c=0 时诊断。",
        "2×2 交叉表、McNemar 检验表。",
        "先看不一致对是否足够，再看 χ²/p。",
        "无配对结构时用列联表卡方。",
        ["t"],
    ))

    ENTRIES.append(entry(
        "runs_test", "游程检验", "假设检验", "统计 > 假设检验",
        "runs_test", "wilcoxon_signed_rank", "quality_statistics_test",
        "检验一列数值按行序相对比较准则 K 是否随机（Wald–Wolfowitz / Minitab Runs）。",
        "默认 K=均值；可选中位数或常数。A=#(X>K)，B=#(X≤K)；等号归 B。正态近似双侧 P，无连续性校正。中间缺失不出检验。",
        "一列数值序列；比较准则 mean/median/value（value 时填 K）。",
        ["按行序抽取有限值。", "中间缺失则诊断并中止。", "计算 K、A、B、游程数。", "正态近似 Z 与双侧 P。"],
        [("K", "比较准则"), ("A", "大于 K 的个数"), ("B", "小于等于 K 的个数"), ("R", "观察游程数")],
        [fb("Runs 正态近似",
            "Expected=2AB/N+1，Var=2AB(2AB−N)/(N²(N−1))，Z=(R−Expected)/√Var，p=2(1−Φ(|Z|))。",
            conditions="formula_reference；min(A,B)<10 时警告近似偏弱。")],
        ["不得写已证明过程受控/失控。", "不与运行图四模式检验合并。"],
        "N<2、全同侧、中间缺失、方差不可算时诊断。",
        "比较准则表、Runs检验表、带中心线 K 的序列控制图式图。",
        "先看两侧计数与正态近似警告，再看 P。",
        "需要关于中位数的四模式 P 时用运行图。",
        ["t"],
    ))

    ENTRIES.append(entry(
        "fisher_exact", "Fisher 精确检验", "假设检验", "统计 > 假设检验",
        "fisher_exact", "chi_square", "quality_statistics_test",
        "对恰好 2×2 的分类交叉表做 Fisher 双侧精确检验，并报告可选优势比。",
        "两列分类 complete-case 计数；复用与两比例相同的超几何双侧求和核。不改 two_proportions 行为。",
        "正好两列分类，且各恰有 2 个水平。",
        ["complete-case 交叉计数。", "校验 2×2。", "调用 fisher_exact_2x2。", "输出交叉表、P、可选 OR 与热图。"],
        [("a,b,c,d", "2×2 计数"), ("OR", "ad/bc（bc>0）"), ("P", "双侧精确概率和")],
        [fb("Fisher 双侧",
            "固定边际下对所有 P(a')≤P(a) 的可行格求和；与 two_proportions 的 fisher_two_sided 一致。",
            conditions="formula_reference；不做 r×c / mid-p / Blaker。")],
        ["不得写已证明关联存在或不存在。", "禁止因本命令改 two_proportions。"],
        "非 2×2、空表时诊断。",
        "交叉表、Fisher精确检验表、观察频数热图。",
        "先确认 2×2 水平，再看精确 P 与 OR。",
        "一般 r×c 关联用列联表卡方；配对二元用 McNemar。",
        ["t"],
    ))

    ENTRIES.append(entry(
        "run_chart", "运行图", "质量工具", "质量工具",
        "run_chart", "time_series", "quality_statistics_test",
        "按行序画个体运行图（中位数中心线），并给出聚类/混合/趋势/振荡四模式近似 P。",
        "子组大小=1；中间缺失不出四模式检验。不跑 SPC Test 1–8，不做控制限。独立于 Gage 内嵌 run chart。",
        "一列数值观测。",
        ["抽取连续有限值。", "中位数为中心。", "关于中位数游程与上升/下降游程。", "四模式单侧正态近似 P。"],
        [("M", "中位数"), ("R", "关于中位数游程数"), ("V", "上升/下降游程数")],
        [fb("关于中位数",
            "E=1+2mn/N，Z=(R−E)/√Var；clustering=Φ(Z)，mixtures=1−Φ(Z)。点落在中位数上归下侧。",
            conditions="formula_reference。"),
         fb("上升/下降",
            "E=(2N−1)/3，Var=(16N−29)/90；trends=Φ(Z)，oscillation=1−Φ(Z)。平坦差分归下行。",
            conditions="formula_reference。")],
        ["不得写已证明过程受控或失控。", "不与游程检验命令合并。"],
        "空序列、中间缺失、一侧为空时诊断。",
        "关于中位数的游程表、上升/下降游程表、中位数中心运行图。",
        "先看图上聚集/交替形态，再对照四个 P。",
        "只要相对常数 K 的随机性用游程检验。",
        ["cap"],
    ))

    ENTRIES.append(entry(
        "cause_and_effect", "因果图", "质量工具", "质量工具",
        "cause_and_effect", "pareto", "quality_statistics_test",
        "按类别汇总原因条目，输出结构摘要与类别计数图（鱼骨/因果头脑风暴）。",
        "无 P 值、无分布假设。效应标题可配置；跳过空类别/空原因。不与柏拉图合并。",
        "类别列 + 原因列；可选效应标题（默认“效应”）。",
        ["读取类别-原因对。", "按类别分组计数。", "结构摘要表。", "类别原因计数条/Pareto 式图。"],
        [("effect", "效应标题"), ("category", "分支类别"), ("cause", "原因文本")],
        [fb("结构摘要", "仅分组计数与展示；不做权重、排序检验或根因判定。",
            conditions="非统计检验；formula_reference 仅指产品合同。")],
        ["不得写已证明根因。", "禁止重做或拆坏 pareto。"],
        "无有效类别-原因对时诊断。",
        "结构摘要表、类别原因计数图。",
        "用于组织原因清单；频次优先级请转柏拉图并现场验证。",
        "需要统计排序时用柏拉图。",
        ["graph"],
    ))

    ENTRIES.append(entry(
        "variance_test", "等方差检验", "假设检验", "统计 > 假设检验",
        "variance_test", "variance", "quality_statistics_test",
        "检验两组或多组方差/标准差是否相等。",
        "可选 F、Levene（中位数 Brown–Forsythe，稳健默认）、Levene（均值）、Bonett（两样本标准差比）或 Bartlett（k≥2，正态敏感）。",
        "两列数值，或测量+分组；Bonett 仅两样本（两列或恰 2 组）；Bartlett 支持 k≥2。",
        ["选择方法。", "F：经典方差比。", "Levene：对 |y−中位数或均值| 做 ANOVA。",
         "Bonett：合并峰度 + ln(S1/S2) 正态近似。", "Bartlett：对数方差加权 χ² + 校正因子。"],
        [("z_ij", "到组中位数的绝对偏差"), ("W", "Levene 统计量"), ("ρ", "σ1/σ2"), ("χ²", "Bartlett 统计量")],
        [fb("Brown–Forsythe / Levene", "对 |y_ij−median_j| 做 ANOVA，即 Minitab 所称 Levene（中位数）。"),
         fb("Bonett", "对 ρ=σ1/σ2 用修正合并峰度构造 Z 与置信区间；P 检验 H0: ρ=1。"
            "与 Levene 不同：Bonett 通常更有功效，极偏/重尾小样本宜对照 Levene。不做 Bonett 功效。",
            conditions="method=bonett；k>2 组只诊断。"),
         fb("Bartlett", "χ² = q/c，其中 q=ν ln(s_p²)−Σ ν_i ln(s_i²)，"
            "c=1+(1/(3(k−1)))[Σ(1/ν_i)−1/ν]。对正态偏离敏感；稳健场景宜对照中位数 Levene。",
            conditions="method=bartlett。")],
        ["拒绝只说明散布可能不同，不能写成已证明等方差。", "单组无法做等方差。"],
        "组数<2、某组少于 2 个有效值、Bonett 用于 k>2、Bartlett 遇零方差时诊断。",
        "方法表（含 P 与可选 CI）与组散布信息。",
        "与箱线一起看；在 F / Levene / Bonett / Bartlett 之间按分布形状选择，不要混称同一种检验。",
        "不做多重比较字母分组（字母分组见单因素 ANOVA Tukey）。",
        ["anova"],
    ))

    ENTRIES.append(entry(
        "pca", "主成分分析", "多变量", "统计 > 多变量",
        "pca", "pca", "quality_statistics_test",
        "把相关数值列换成互不相关的主成分。",
        "特征分解。解释率用全部特征值。T²/Q 用经验分位，不是 Jackson–Mudholkar 解析限。",
        "至少两列数值。",
        ["complete-case 多列对齐。", "标准化后特征分解。", "特征值、系数 V、载荷、得分、T²/Q。"],
        [("λ_i", "特征值"), ("V", "特征向量/系数"), ("T²", "Hotelling"), ("Q", "SPE 残差平方")],
        [fb("特征分解", "S V = V Λ。解释率 = λ_i / Σλ。"),
         fb("T²/Q", "用得分与残差的经验分位做参考线，不是解析分布限。")],
        ["解释率高不等于过程合格。", "T²/Q 超分位只提示调查。"],
        "列数<2、有效行不足或矩阵不可分解时诊断。",
        "特征值、系数、载荷、得分（含原始行）、T²/Q。",
        "看累计解释率和得分图离群行。",
        "不做旋转因子模型。",
        ["pca"],
    ))

    ENTRIES.append(entry(
        "kmeans", "K-Means 聚类", "多变量", "统计 > 多变量",
        "kmeans", "kmeans", "p3_batch1_kmeans_cart_adf_test",
        "把多维数值观测分成 k 个簇，并报告质心与簇内平方和。",
        "欧氏距离 Lloyd 迭代；初始质心取前 k 个有效观测；可选标准化。",
        "至少两列数值；参数 k、最大迭代、是否标准化。",
        ["complete-case 多列对齐。", "可选标准化后取前 k 行作初始质心。", "Lloyd 迭代得到分配、质心、簇内 SS。"],
        [("k", "簇数"), ("d", "欧氏距离"), ("WSS", "簇内平方和")],
        [fb("欧氏距离", "d(x,c)=√Σ(x_j−c_j)²。"),
         fb("Lloyd", "分配到最近质心 → 按成员均值更新质心 → 重复。")],
        ["簇标签只描述相对邻近，不是工艺判定。", "未收敛时只报告迭代诊断。"],
        "列数<2、有效行<k、k<2。",
        "簇摘要、质心、分配表、前两列散点。",
        "看簇大小与 WSS；结合工艺变量解释邻近结构。",
        "不做层次聚类或自动选 k；非 Minitab golden。",
        ["pca"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "cluster_observations", "层次聚类（观测）", "多变量", "统计 > 多变量",
        "cluster_observations", "hierarchical_cluster", "p3_batch2_poisson_iforest_bootstrap_hclust_test",
        "对多维观测做 complete linkage 凝聚层次聚类，并按 k 切簇。",
        "欧氏距离；簇间最大两两距离；输出合并历程与分配。",
        "≥2 数值列；k；可选标准化。",
        ["complete-case。", "凝聚合并。", "切 k 分配。"],
        [("height", "合并时 complete 距离")],
        [fb("Complete linkage", "D(A,B)=max_{i∈A,j∈B} d(i,j)。")],
        ["簇标签只描述邻近结构。"],
        "列数<2 或 n<k。",
        "合并历程、分配表、前两列散点。",
        "结合 height 跳跃与散点阅读。",
        "本轮仅 complete；非 single/Ward；非 K-Means。",
        ["pca"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "cart_tree", "CART 单树", "预测 / 经典 ML", "统计 > 预测辅助",
        "cart_tree", "cart_tree", "p3_batch1_kmeans_cart_adf_test",
        "用自研二叉递归划分做分类或回归单树，输出结点表与变量重要性。",
        "分类用 Gini，回归用 SSE；深度/叶样本停。非 TreeNet/Random Forests 对齐。",
        "响应列 + ≥1 数值预测列；task；max_depth；min_leaf。",
        ["对齐响应与预测列。", "递归分裂直至停止条件。", "汇总树表、重要性、混淆矩阵或 RMSE。"],
        [("Gini", "1−Σp_c²"), ("SSE", "Σ(y−ȳ)²")],
        [fb("分类分裂", "增益 = 父 Gini − 加权子 Gini。"),
         fb("回归分裂", "增益 = 父 SSE − (左 SSE + 右 SSE)。")],
        ["训练集指标不能外推为工艺合格。", "不得声称等同 Minitab TreeNet/RF。"],
        "无响应、无预测列、分类类别不足。",
        "树结点、变量重要性、混淆矩阵或观测-拟合图。",
        "先看主导分裂变量与叶纯度。",
        "本轮无成本复杂度剪枝；无随机森林；无 Python/sklearn 运行时。",
        ["pca"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "isolation_forest", "Isolation Forest", "预测 / 经典 ML", "统计 > 预测辅助",
        "isolation_forest", "isolation_forest", "p3_batch2_poisson_iforest_bootstrap_hclust_test",
        "对多维数值观测计算孤立分数，标记相对孤立点。",
        "随机划分树平均路径长度；分数 s=2^(-E(h)/c(n))。与单变量 outlier_test 分流。",
        "≥2 数值列；tree/max_samples/分位阈值/seed。",
        ["complete-case。", "建树并估计路径。", "按分数分位标记。"],
        [("s", "异常分数"), ("c(n)", "平均路径修正")],
        [fb("分数", "s = 2^(-E(h(x))/c(n))。")],
        ["高分只提示相对孤立。", "不得声称等同 TreeNet/RF。"],
        "列数<2 或有效行不足。",
        "分数表、异常标记、分数图。",
        "结合工艺变量回查高分行。",
        "自研 C++；无 sklearn 运行时。",
        ["pca"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "poisson_regression", "Poisson 回归", "回归", "统计 > 回归",
        "poisson_regression", "poisson_regression", "p3_batch2_poisson_iforest_bootstrap_hclust_test",
        "对非负计数响应拟合 log 链 Poisson GLM，并报告系数与偏差。",
        "IRLS 最大似然；μ=exp(xβ)；权重=μ。",
        "计数响应 + ≥1 数值预测列。",
        ["对齐 complete-case。", "IRLS 估计。", "输出系数与 Pearson 残差。"],
        [("μ", "均值"), ("D", "偏差")],
        [fb("log 链", "log μ = xβ。"),
         fb("偏差", "D=2Σ[y log(y/μ)-(y-μ)]（y=0 时 y log 项为 0）。")],
        ["系数显著性只描述关联证据。", "未收敛时不外推解释。"],
        "响应负值、观测不足或奇异设计。",
        "模型摘要、系数、拟合残差、残差散点。",
        "先看收敛与偏差，再读系数方向。",
        "本轮无负二项/零膨胀/偏移列；非 Minitab golden。",
        ["reg"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "bootstrap_mean", "Bootstrap 均值 CI", "推断 / 仿真", "统计 > 基本统计",
        "bootstrap_mean", "bootstrap_mean", "p3_batch2_poisson_iforest_bootstrap_hclust_test",
        "对单列样本均值做百分位 bootstrap 置信区间。",
        "B 次有放回重抽样；取经验分位 α/2 与 1−α/2。非 BCa。",
        "一个数值列；B、置信水平、seed。",
        ["读有限值。", "重抽样均值。", "百分位区间。"],
        [("B", "重抽样次数"), ("x̄*", "bootstrap 均值")],
        [fb("百分位 CI", "取 {x̄*} 的经验分位 α/2 与 1−α/2。")],
        ["区间只描述重抽样不确定性。"],
        "n<2 或 B 过小。",
        "摘要表与 bootstrap 均值直方图。",
        "看区间宽度与样本均值位置。",
        "本轮百分位法；非 BCa；非两样本。",
        ["t"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "ordinal_logistic", "有序 Logistic 回归", "回归", "统计 > 回归",
        "ordinal_logistic", "ordinal_logistic", "p3_batch3_ordinal_lda_ccf_correlogram_test",
        "对有序多水平响应拟合比例优势 logit 模型。",
        "logit P(Y≤k)=θ_k+xβ；共享斜率。",
        "有序响应（≥3 水平）+ ≥1 数值预测。",
        ["编码有序水平。", "MLE 估计。", "输出系数与 AIC。"],
        [("θ_k", "累积阈值"), ("β", "共享斜率")],
        [fb("比例优势", "logit P(Y≤k)=θ_k+xβ。")],
        ["系数描述累积对数优势关联证据。"],
        "水平不足或奇异信息矩阵。",
        "模型摘要与系数表。",
        "先看收敛与 AIC，再读斜率方向。",
        "本轮仅 logit；非名义 Logistic。",
        ["reg"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "discriminant", "线性判别分析", "多变量", "统计 > 多变量",
        "discriminant", "discriminant", "p3_batch3_ordinal_lda_ccf_correlogram_test",
        "用等协方差线性判别对类别响应分类并报告混淆矩阵。",
        "类均值、合并协方差、线性得分与先验。",
        "类别响应 + ≥1 数值预测；≥2 类。",
        ["估计类均值与合并协方差。", "线性得分分类。", "输出混淆矩阵。"],
        [("Σ", "合并协方差"), ("π_c", "类先验")],
        [fb("线性得分", "δ_c(x)=x'Σ^{-1}μ_c−½μ_c'Σ^{-1}μ_c+log π_c。")],
        ["训练准确率不能外推为工艺判定。"],
        "类过小或协方差奇异。",
        "类均值、混淆矩阵、LD 投影散点。",
        "看类可分性与误分模式。",
        "不做 QDA。",
        ["pca"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "ccf", "互相关（CCF）", "时间序列", "统计 > 时间序列",
        "ccf", "ccf", "p3_batch3_ordinal_lda_ccf_correlogram_test",
        "计算两列对齐序列在正负滞后上的互相关，并画置信带。",
        "样本互相关；带宽 ±z/√n。",
        "两个数值序列；可选 max_lag。",
        ["对齐有效对。", "计算各滞后 CCF。", "输出表与图。"],
        [("c_k", "滞后 k 的互相关")],
        [fb("CCF", "c_k=Σ(x_t−x̄)(y_{t+k}−ȳ)/√[Σ(x−x̄)²Σ(y−ȳ)²]。")],
        ["越过带宽只提示相关证据。"],
        "有效对过少或零方差。",
        "CCF 表与带置信限的图。",
        "先看 lag0 与邻近滞后。",
        "非预白化；宜与 ACF/PACF 对照。",
        ["arima"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "correlogram", "Correlogram（相关热图）", "图形", "图形",
        "correlogram", "correlogram", "p3_batch3_ordinal_lda_ccf_correlogram_test",
        "把多列两两相关矩阵画成热图并输出系数表。",
        "复用 correlation_matrix；PlotKind::heatmap。",
        "≥2 数值列；Pearson/Spearman。",
        ["complete-case。", "相关矩阵。", "热图。"],
        [("r", "相关系数")],
        [fb("相关矩阵", "对 complete-case 列计算 Pearson 或 Spearman 相关。")],
        ["热图只展示相关结构。"],
        "列数<2。",
        "相关矩阵表与热图。",
        "看强相关块与符号。",
        "与 correlation_plot 分流；非 Graph Builder。",
        ["graph"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "stepwise_regression", "逐步回归", "回归", "统计 > 回归",
        "stepwise_regression", "stepwise_regression", "p3_track_h_stepwise_km_pb_test",
        "按 α_enter/α_remove 对线性回归候选预测做逐步选择。",
        "stepwise / forward / backward；每步用项 p 值进退。",
        "数值响应 + ≥2 候选预测。",
        ["拟合当前子集。", "按 p 值进/出。", "输出步骤与终模型。"],
        [("α_enter", "进入阈值"), ("α_remove", "剔除阈值")],
        [fb("逐步", "按项 p 值与 α_enter/α_remove 进退预测变量。")],
        ["选入项只描述相对拟合证据。"],
        "候选不足或观测过少。",
        "步骤表、选入项、终模型系数。",
        "先看步骤稳定性，再读终模型系数。",
        "非 Best subsets；非 AICc 前进。",
        ["reg"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "km_interval", "区间删失 Kaplan–Meier", "可靠性", "统计 > 可靠性",
        "km_interval", "km_interval", "p3_track_h_stepwise_km_pb_test",
        "对左/区间/右删失寿命数据用 Turnbull NPMLE 估计生存函数。",
        "把观测写成 (L,R]；自洽迭代质量点。",
        "左端列与右端列；右端空/Inf 表示右删失。",
        ["构造区间。", "Turnbull 迭代。", "累计质量得 S(t)。"],
        [("S(t)", "生存函数"), ("(L,R]", "删失区间")],
        [fb("Turnbull", "自洽更新质量点直至收敛，再累计得 S(t)。")],
        ["中位寿命未估出时只报告曲线。"],
        "有效区间过少或 R<L。",
        "摘要、生存表与曲线。",
        "对照删失类型计数与中位寿命。",
        "非右删失 product-limit。",
        ["rel"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "doe_plackett_burman", "Plackett–Burman 设计生成", "DOE", "质量工具 > DOE",
        "doe_plackett_burman", "plackett_burman", "p3_track_h_stepwise_km_pb_test",
        "生成 Plackett–Burman 两水平筛选设计矩阵。",
        "选择最小 N=4m≥k+1；循环 ±1 行。",
        "因子名列表；可选高低水平与中心点。",
        ["选 N。", "循环生成。", "输出运行表。"],
        [("N", "运行数"), ("k", "因子数")],
        [fb("PB", "用循环生成器构造 N×(N−1) 的 ±1 矩阵并截取前 k 列。")],
        ["分辨率 III，仅适合筛选。"],
        "因子数越界或名称重复。",
        "设计信息与编码运行表。",
        "按运行表安排试验。",
        "本轮支持 N∈{8,12,16,20,24}；非 CCD。",
        ["doe"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "multi_vari", "Multi-Vari 图", "质量工具", "质量工具",
        "multi_vari", "multi_vari", "multi_vari_test",
        "用 2～4 个因子展示测量值在各层的位置与散布。",
        "计算每个因子组合的单元均值并连线。覆盖率 <60% 只诊断不画图。",
        "一个测量列和 2～4 个因子列。",
        ["complete-case。", "按因子格子算均值与点数。", "覆盖率足够则画点+均值线。"],
        [("格子", "因子水平组合"), ("覆盖率", "非空格子比例")],
        [fb("单元均值", "每个可见格子的均值 = 该格子有效测量的算术平均。无检验 p 值。")],
        ["第 5 个及以上因子不支持。", "覆盖不足只诊断。"],
        "因子不是 2～4 个、测量非有限或覆盖<60% 时不画图。",
        "Multi-Vari 图与覆盖诊断。",
        "看哪一层均值移动最大；这是探索图。",
        "不拟合方差分量模型。",
        ["graph"],
    ))

    ENTRIES.append(entry(
        "variability_chart", "变异性图", "质量工具", "质量工具",
        "variability_chart", "variability", "quality_statistics_test",
        "按 1～2 个因子展示各单元均值（含极差）与标准差双面板。",
        "与 Multi-Vari 独立：输出均值+range 与 SD 两图，不做交互均值连线探索。单元 mean/SD 按因子水平组合聚合；SD 中心线为有 SD 的单元平均。",
        "一个测量列和 1～2 个因子列（每因子建议 ≥2 水平）。",
        ["complete-case。", "按因子格子算 N/Mean/StDev/Min/Max。", "画均值+极差面板与标准差面板。"],
        [("格子", "因子水平组合"), ("s̄", "各单元样本 SD 的平均")],
        [fb("单元均值与 SD",
            "ȳ_c=平均，s_c=√[Σ(y−ȳ_c)²/(n_c−1)]（n_c≥2）；极差条为 [min,max]。",
            conditions="formula_reference；本轮锁定 1～2 因子。")],
        ["不是 Multi-Vari redo。", "不是 ANOVA 显著性检验。", "不得写过程已受控。"],
        "因子不是 1～2 个、测量非有限或全单元 n=1（SD 图空）时诊断。",
        "单元统计表 + 均值/极差图 + 标准差图。",
        "先看哪一单元均值偏移，再看哪一单元离散度偏大。",
        "不做 3～8 因子；不并入 multi_vari 命令。",
        ["graph"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "acceptance_sampling", "属性一次抽样", "质量工具", "质量工具",
        "acceptance_sampling", "interval", "quality_statistics_test",
        "按样本量 n 与接收数 c 给出二项 OC 曲线与可选 AQL/RQL 风险点。",
        "Pa(p)=P(X≤c)，X~Bin(n,p)。批大小 N 可选且仅摘要；有限批超几何本轮不做，仍用二项 OC。",
        "不读工作表。输入 n、c；可选 AQL、RQL、批大小 N。",
        ["校验 n≥1、c≤n。", "在 p 网格上算 Pa(p)。", "可选标记 Pa(AQL)/Pa(RQL)。", "输出计划表、OC 表与 OC 曲线图。"],
        [("n", "样本量"), ("c", "接收数"), ("Pa(p)", "接收概率"), ("p", "不合格品率")],
        [fb("二项 OC",
            "Pa(p)=Σ_{k=0}^{c} C(n,k) p^k (1−p)^{n−k}。",
            conditions="formula_reference；p=0 时 Pa=1。")],
        ["不得写批次合格或必须接收/拒收。", "N 仅信息，不改变本轮二项 OC。", "不做 ANSI 全表 golden。"],
        "n=0、c>n 或 AQL/RQL 越界时诊断。",
        "抽样计划表、OC 曲线表、OC 曲线图。",
        "先看 OC 形状，再看 AQL/RQL 风险点是否可接受。",
        "不做超几何有限批 OC；不做多次抽样链。",
        ["cap"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "anom", "均值分析 (ANOM)", "ANOVA", "统计 > ANOVA",
        "anom", "anova", "quality_statistics_test",
        "在正态均值假定下，比较各组均值是否偏离总体均值（Analysis of Means）。",
        "总体均值与 pooled SD；决策限用 Nelson 正态/多重比较近似。本轮仅正态均值，不做二项/泊松 ANOM。",
        "一个数值响应列与一个分组列；α 默认 0.05。",
        ["按组 complete-case。", "算组均值、pooled SD 与 UDL/LDL。", "标记超出决策限的组。", "输出决策限表、组均值表与 ANOM 图。"],
        [("ȳ̄", "总体均值"), ("s_p", "组内 pooled SD"), ("UDL/LDL", "决策限"), ("α", "族误差率")],
        [fb("ANOM 决策限",
            "UDL/LDL=ȳ̄± z_{1−α/(2k)}·s_p·√((k−1)/N)。",
            conditions="formula_reference；不等 n 时仍用总 N 近似并警告。")],
        ["不得写已证明同均值或必须删除组。", "二项/泊松计数请用其他工具。", "近似限不是 Minitab exact h golden。"],
        "组数<2、某组 n<2、s_p=0 时诊断。",
        "决策限表、组均值表、带中心线与 UDL/LDL 的 ANOM 图。",
        "先看哪些组超出限，再结合工程背景调查。",
        "不做二项/泊松 ANOM 变体。",
        ["anova"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "poisson_gof", "泊松拟合优度", "假设检验", "统计 > 假设检验",
        "poisson_gof", "chi_square_gof", "quality_statistics_test",
        "检验一列非负整数计数是否服从泊松分布（估计 λ=样本均值）。",
        "Pearson χ² 合并小期望格；DF=合并后类别数−1−1。与列联表卡方 GOF 命令独立。",
        "一列非负整数计数。",
        ["complete-case 读取整数计数。", "λ̂=均值。", "按观察值合并期望<1 的格。", "输出 λ̂、χ²、DF、p 与有效性提示。"],
        [("λ̂", "泊松率估计"), ("χ²", "Pearson 统计量"), ("DF", "自由度")],
        [fb("泊松 GOF",
            "E_k≈n·P(X=k|λ̂)；χ²=Σ(O−E)²/E，DF=#bins−2。",
            conditions="formula_reference；全同计数时 P 应偏大。")],
        ["不得写已证明服从泊松。", "不修改 chi_square_gof 命令。", "非整数计数诊断。"],
        "n<2、非整数、合并后类别<2 或 DF<1 时诊断。",
        "泊松参数表、卡方检验表。",
        "先看期望<5 警告，再看 P。",
        "分类列比例 GOF 仍用 chi_square_gof。",
        ["gof"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "t_power", "t 功效与样本量", "功效与样本量", "统计 > 功效与样本量",
        "t_power", "t_power", "p2_doe_acf_power_test",
        "在给定效应、α 和功效目标下，估计样本量或可检测效应。"
        "mode 覆盖 t/ANOVA/比例/方差/泊松，以及等价 TOST、2 水平 DOE、正态容差样本量。",
        "不使用工作表。等价功效为已知 σ 正态规划近似；DOE 按主效应高低对比复用双样本非中心 t；"
        "容差按 Howe k(n)≤max_k 求最小 n。",
        "mode、效应、α、功效或样本量；DOE 用 groups=k、observation_length=p；"
        "等价半宽用 effect（σ 单位）；容差覆盖率用 effect、置信用 target、max k 用 null_proportion。",
        ["读取 mode、效应、α、功效或 n。", "按 mode 选择公式。", "输出 Actual Power / n 与功效曲线。"],
        [("α", "第一类错误"), ("功效", "1−β"), ("δ", "等价界（σ 单位）"),
         ("k,p,r", "DOE 因子数/部分析因/重复"), ("Howe k", "双侧正态容差因子")],
        [fb("功效", "功效 = P(拒绝 H0 | 真实效应=δ)。t 用非中心 t；等价用正态 TOST 规划近似。"),
         fb("DOE 功效", "n₊=n₋=r·2^(k-p-1)，效应=|ȳ₊−ȳ₋|/σ，复用双样本 t 功效。"),
         fb("容差样本量", "求最小 n 使 Howe k(n;P,γ) ≤ max_k。")],
        ["这是设计阶段参考，不是已收集数据的 p 值。", "不得写成样本量足够。"],
        "α 或功效越界、效应为 0、率≤0 或非有限时诊断。",
        "功效与样本量表和功效曲线。",
        "先核对 mode，再看 σ/等价界/DOE 参数是否来自工程要求。",
        "不做 crossover 等价功效、PB 功效、非参数容差样本量；不做泊松 Blaker。",
        ["t", "power"],
        missing="本命令不读取工作表，因此没有 N/N*。",
        status="formula_reference",
    ))

    ENTRIES.append(entry(
        "acf_pacf", "ACF/PACF", "时间序列", "统计 > 时间序列",
        "acf_pacf", "acf_pacf", "p2_doe_acf_power_test",
        "计算单列序列的自相关与偏自相关，并画带置信限的 ACF/PACF 图。",
        "ACF 为样本自相关；PACF 用 Durbin–Levinson。"
        "默认置信带为 NIST 白噪声固定带宽 ±z/√n（独立性检验），不是 Bartlett 变带宽。",
        "一个数值序列列；可选 max_lag 与置信水平。",
        ["按行序读取有限值。", "计算 ACF/PACF 与 Ljung–Box。", "输出表与双图。"],
        [("r_k", "滞后 k 的 ACF"), ("φ_kk", "PACF"), ("带宽", "±z_{1−α/2}/√n")],
        [fb("ACF", "r_k = Σ(x_t−x̄)(x_{t+k}−x̄) / Σ(x_t−x̄)²，含 lag0=1。"),
         fb("PACF", "Durbin–Levinson 递推得到 φ_kk。"),
         fb("置信带", "默认 white_noise_fixed：±z/√n；诊断中说明非 ARIMA 识别变带宽。")],
        ["越过带宽不是过程已失控。", "Ljung–Box 小 P 不是已证明模型错误。"],
        "n<3 或零方差时诊断。",
        "ACF/PACF 表、Ljung–Box、ACF 图、PACF 图。",
        "先看 lag1–几阶是否持续越带，再结合工艺时序。",
        "不做 CCF；ADF 见独立命令 adf_test；不自动改 ARIMA 阶。",
        ["arima"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "adf_test", "ADF 单位根检验", "时间序列", "统计 > 时间序列",
        "adf_test", "adf", "p3_batch1_kmeans_cart_adf_test",
        "对单列序列做 Augmented Dickey–Fuller 检验，报告 τ 与临界值。",
        "对 Δy 回归 y(t−1) 与滞后差分，可选漂移/趋势。τ=γ̂/se(γ̂)。临界值为大样本 MacKinnon 风格常数。",
        "一个数值序列；regression=none|drift|trend；lags 可空自动。",
        ["读有限值并差分。", "OLS 估计 ADF 回归。", "输出 τ、临界值、系数表与序列图。"],
        [("γ", "y(t−1) 系数"), ("τ", "γ̂ / se(γ̂)")],
        [fb("ADF（漂移）", "Δy_t = α + γ y_{t−1} + Σ δ_i Δy_{t−i} + ε_t。"),
         fb("临界值", "使用大样本 MacKinnon 风格 1%/5%/10% 常数表。")],
        ["τ 低于 5% 临界值只提示拒绝单位根的证据。", "宜与 ACF/PACF 一并阅读。"],
        "有效观测过少或设计矩阵奇异。",
        "检验表、系数表、序列图。",
        "先看回归规格与滞后，再解释 τ 相对临界值。",
        "不做 KPSS/PP/CCF；非 Minitab golden。",
        ["arima"], status="formula_reference",
    ))

    def add_ts(eid, title, overview, formulas, status="implemented"):
        ENTRIES.append(entry(
            eid, title, "时间序列", "统计 > 时间序列",
            eid, "forecast", "seasonal_forecasting_output_test",
            f"对单列时间顺序数据做{title}。",
            overview,
            "一个数值序列列，按当前行序视为时间顺序；可设季节周期和预测期数。",
            ["按行序读取有限值，缺失记入诊断。", "估计水平/趋势/季节或 ARIMA 项。", "给出拟合、预测、准确度。"],
            [("y_t", "时刻 t 的观测"), ("α,β,γ", "平滑参数"), ("h", "预测步数"), ("MAPE", "平均绝对百分比误差")],
            formulas,
            ["不把行序自动改成日期索引。", "MAPE 低不等于模型已验证。", "不要用内部 CSS/指定参数去对 Minitab TSERIES 数值。"],
            "序列过短、季节周期不整除、缺失过多或参数越界时诊断。",
            "拟合与预测明细（含原始行）、准确度、季节指数（若有）、预测区间图。",
            "看残差和预测区间宽度，而不是只看一条光滑曲线。",
            "Kalman/TSERIES 迭代最小二乘未实现。",
            ["arima"] if eid == "arima" else ["desc"],
            status=status,
        ))

    add_ts("time_series_smoothing", "指数平滑",
           "单指数：S_t=α y_t+(1−α)S_{t−1}。双指数（Holt）另加趋势。参数由用户指定。",
           [fb("单指数", "S_t=α y_t+(1−α)S_{t−1}，预报 ŷ_{t+h}=S_t。",
               [t("S_t = α y_t + (1−α) S_{t−1}")], conditions="method=single。"),
            fb("Holt", "S_t=α y_t+(1−α)(S_{t−1}+b_{t−1})；b_t=β(S_t−S_{t−1})+(1−β)b_{t−1}；ŷ_{t+h}=S_t+h b_t。")])
    add_ts("time_series_decomposition", "时间序列分解",
           "经典加法/乘法分解：中心化移动平均趋势 + 季节指数 + 不规则项。",
           [fb("加法", "y_t = T_t + S_t + E_t。一个周期内季节项之和为 0。"),
            fb("乘法", "y_t = T_t · S_t · E_t。一个周期内季节指数平均为 1。")])
    add_ts("seasonal_forecasting", "季节性预测（Winters）",
           "Holt–Winters。α/β/γ 用户指定，parameter_source=specified。非 TSERIES golden。",
           [fb("Winters", "水平、趋势、季节三式递推；季节项以周期 L 循环。参数指定而非自动寻优。")],
           status="formula_reference")
    add_ts("arima", "ARIMA / Best ARIMA",
           "差分后 ARMA。Best：p/q≤3、d≤2 的 CSS 网格。季节可混合 SARIMA CSS。非 TSERIES golden。",
           [fb("ARIMA(p,d,q)", "w_t=∇^d y_t = Σ φ_i w_{t−i} + e_t + Σ θ_j e_{t−j}。"),
            fb("候选", "网格 CSS 输出若干候选，不宣称全局最优。")],
           status="formula_reference")

    ENTRIES.append(entry(
        "reliability", "可靠性分析", "可靠性", "统计 > 可靠性",
        "reliability", "reliability", "reliability_msa_power_test",
        "用寿命/删失数据估计生存函数或参数寿命分布。",
        "Kaplan–Meier；参数 Weibull/指数/对数正态，以及 weibull3/exponential2/lognormal3（剖面似然）。无界似然只诊断。三参数无 Minitab golden。",
        "寿命列、可选删失指示、模型、百分位。",
        ["读取寿命与删失。", "KM 逐步乘积。", "若选参数模型则 MLE/剖面似然。", "百分位与概率图（可识别时）。"],
        [("t", "寿命"), ("Ŝ(t)", "生存函数"), ("β,η,γ", "形状、尺度、阈值")],
        [fb("Kaplan–Meier", "在死亡时刻 Ŝ(t)=Π (1−d_i/n_i)。"),
         fb("两参数 Weibull", "S(t)=exp[−(t/η)^β]，t>0。"),
         fb("三参数", "把 t 换成 t−γ。Weibull3 在 β≤1 时可能无界似然，只诊断。",
            note="formula_reference ≠ Minitab golden")],
        ["KM 不是合格线。", "拟合未拒绝 ≠ 寿命服从该分布。"],
        "无正寿命、无失效导致不可识别、或阈值把点推到边界时诊断。",
        "KM/参数表、百分位、比较表、生存曲线与概率图。",
        "先看删失比例和可否识别，再看百分位。",
        "比较表仍以二参数列为对照。Weighted Kappa 仍诊断。",
        ["rel"], status="formula_reference",
    ))

    def spc_test_name(eid: str) -> str:
        return {
            "imr": "special_cause_rule_test",
            "imr_rs": "imr_rs_test",
            "xbar_r": "xbar_output_test",
            "xbar_s": "xbar_output_test",
            "ewma": "ewma_cusum_output_test",
            "cusum": "ewma_cusum_output_test",
            "hotelling_t2": "p2_t2_mewma_nelson_emp_test",
            "mewma": "p2_t2_mewma_nelson_emp_test",
            "generalized_variance": "p2_gv_expanded_b4b5_test",
            "zone_chart": "zone_zmr_ma_output_test",
            "z_mr": "zone_zmr_ma_output_test",
            "moving_average": "zone_zmr_ma_output_test",
            "g_chart": "capability_ci_gof_rare_event_power_test",
            "t_chart": "capability_ci_gof_rare_event_power_test",
        }.get(eid, "quality_statistics_test")

    def add_spc(eid, title, service, overview, formulas, refs=None):
        ENTRIES.append(entry(
            eid, title, "控制图", "控制图",
            service, "spc", spc_test_name(eid),
            f"用控制图监视过程：{title}。",
            overview,
            "测量列或计数/分母列；可选子组、阶段、历史中心线/σ、特殊原因测试集合。",
            ["按输入规则筛行与子组。", "估计中心线与 σ（或使用历史参数）。", "计算每个点的 LCL/UCL。", "按启用的 Test 打标。"],
            [("CL", "中心线"), ("LCL/UCL", "控制下限/上限"), ("σ_within", "组内标准差估计")],
            formulas,
            SPC_TESTS,
            spc_invalid(),
            "控制图、参数表、逐点/逐子组表（含 source_row 与失败测试集合）。",
            "出限是统计信号，需要结合工艺调查；不是自动判不合格批。",
            "新分析默认启用该图适用的全部测试；旧项目 JSON 若只存 [1] 则仍只跑 Test 1。",
            refs or ["tests", "imr"],
        ))

    add_spc("imr", "I-MR 控制图", "individuals_moving_range",
            "单值图用 X̄ 作中心线；移动极差默认 w=2。"
            "σ 方法可选：平均 MR/d2、中位 MR、MSSD；可选 Nelson estimate（剔除 MR>D4·MR̄ 后重估）。",
            [
                fb("组内标准差",
                   "σ_within = MR̄ / d2(w)\n默认 w=2，d2(2)=1.128，MR_i=|x_i−x_{i−1}|。"
                   "Nelson：剔除过大 MR 后重算 MR̄。MSSD：√(Σd²/(2(N−1)))/c4'。",
                   [line("σ", sub("within"), " = ", frac([bar("MR")], [t("d"), sub("2"), t("(w)")]))],
                   explanation="移动极差长度默认 w=2；Nelson/MSSD 见参数页。"),
                fb("I 图（单值）",
                   "UCL = x̄ + 3 σ_within\nCL = x̄\nLCL = x̄ − 3 σ_within",
                   [stack(
                       heading("I（单值图）"),
                       cases(
                           [t("UCL = "), bar("x"), t(" + 3σ"), sub("within")],
                           [t("CL = "), bar("x")],
                           [t("LCL = "), bar("x"), t(" − 3σ"), sub("within")],
                       ),
                   )]),
                fb("MR 图（移动极差）",
                   "UCL = D4 · MR̄\nCL = MR̄\nLCL = D3 · MR̄",
                   [stack(
                       heading("MR（移动极差图）"),
                       cases(
                           [t("UCL"), sub("MR"), t(" = D"), sub("4"), bar("MR")],
                           [t("CL"), sub("MR"), t(" = "), bar("MR")],
                           [t("LCL"), sub("MR"), t(" = D"), sub("3"), bar("MR")],
                       ),
                   )]),
            ],
            ["imr", "tests"])
    ENTRIES.append(entry(
        "hotelling_t2", "Hotelling T²", "控制图", "控制图",
        "hotelling_t2", "multivariate_spc", "p2_t2_mewma_nelson_emp_test",
        "多元个体 Hotelling T² 控制图。",
        "Phase I 用 Tracy–Young–Mason Beta UCL；可选 Phase II F 限。"
        "不是 PCA 经验分位 T²。",
        "至少两个数值变量列；complete-case。",
        ["估计均值向量与协方差。", "计算逐点 T²。", "按 phase 计算 UCL。", "超限计数。"],
        [("T²", "马氏距离平方"), ("UCL", "上控制限"), ("m,p", "观测数与变量数")],
        [fb("T²", "Q=(x−x̄)'S⁻¹(x−x̄)。", [t("Q = (x − x̄)' S⁻¹ (x − x̄)")]),
         fb("Phase I UCL", "UCL=((m−1)²/m)·B_{1−α}(p/2,(m−p−1)/2)。")],
        ["超限不是过程失控证明。", "不要与 PCA 经验 T² 混淆。"],
        "m≤p+1 或协方差奇异时诊断。",
        "T² 图、摘要表、逐点表。",
        "先看 UCL 方法与超限点，再结合工艺。",
        "默认 α=0.05。",
        ["spc"],
    ))
    ENTRIES.append(entry(
        "mewma", "MEWMA", "控制图", "控制图",
        "mewma", "multivariate_spc", "p2_t2_mewma_nelson_emp_test",
        "多元 EWMA（MEWMA）控制图。",
        "Z_i=λX_i+(1−λ)Z_{i−1}；T²=Z'Σ_Z⁻¹Z。默认 UCL 为渐近 χ² 近似（非 ARL 仿真），可手工指定。",
        "至少两个数值变量；λ 默认 0.1。",
        ["估计协方差。", "递推 Z。", "每步精确 Σ_Z。", "画 T² 与 UCL。"],
        [("λ", "平滑常数"), ("T²", "MEWMA 统计量"), ("UCL", "上控制限")],
        [fb("MEWMA", "Z_i = λ X_i + (1−λ) Z_{i−1}。"),
         fb("T²", "T_i² = Z_i' Σ_{Z_i}⁻¹ Z_i。")],
        ["超限不是过程失控证明。", "默认 UCL 不是 ARL 校准常数。"],
        "观测过少或协方差奇异时诊断。",
        "MEWMA T² 图与摘要。",
        "先看诊断是否提示 UCL 近似，再解释信号。",
        "可手工输入 UCL。",
        ["spc"],
    ))
    ENTRIES.append(entry(
        "generalized_variance", "广义方差图", "控制图", "控制图",
        "generalized_variance", "multivariate_spc", "p2_gv_expanded_b4b5_test",
        "多元广义方差 |S| 子组控制图（Montgomery）。",
        "等量子组 n>p：点为 det(S_i)；b1/b2 常数；CL=平均|S|；UCL/LCL=|Σ̂|(b1±3√b2)，LCL≥0。"
        "个体观测不做假 |S|。NIST 指出多元变差图存在争议，本输出作探索信号。",
        "至少两个数值变量；子组大小 n>p；观测数可被 n 整除。",
        ["按顺序切等量子组。", "算各子组协方差行列式。", "估 |Σ| 与控制限。", "画 |S| 图。"],
        [("|S|", "子组协方差行列式"), ("b1,b2", "期望/方差常数"), ("CL/UCL/LCL", "中心与控制限")],
        [fb("b1", "b1=Π(n−i)/(n−1)^p，i=1…p。"),
         fb("限", "UCL=|Σ̂|(b1+3√b2)；LCL=max(0,|Σ̂|(b1−3√b2))。")],
        ["超限不是过程失控证明。", "不要把个体路径当成子组 |S|。"],
        "n≤p、不等子组或奇异协方差时诊断。",
        "|S| 图、摘要与逐子组表。",
        "与 Hotelling T² / MEWMA 联读：T² 看均值向量，|S| 看联合变差。",
        "本命令不提供个体标准化替代图。",
        ["spc"],
    ))
    add_spc("xbar_r", "Xbar-R 控制图", "xbar_range",
            "子组均值与极差。σ_within=R̄/d2(n)。适合 n≤8。A2=3/(d2√n)。",
            [
                fb("Xbar（均值图）",
                   "UCL = x̿ + A2 R̄\nCL = x̿\nLCL = x̿ − A2 R̄",
                   [stack(
                       heading("Xbar（均值图）"),
                       cases(
                           [t("UCL = "), dbar("x"), t(" + A"), sub("2"), bar("R")],
                           [t("CL = "), dbar("x")],
                           [t("LCL = "), dbar("x"), t(" − A"), sub("2"), bar("R")],
                       ),
                   )]),
                fb("R（极差图）",
                   "UCL_R = D4 R̄\nCL_R = R̄\nLCL_R = D3 R̄",
                   [stack(
                       heading("R（极差图）"),
                       cases(
                           [t("UCL"), sub("R"), t(" = D"), sub("4"), bar("R")],
                           [t("CL"), sub("R"), t(" = "), bar("R")],
                           [t("LCL"), sub("R"), t(" = D"), sub("3"), bar("R")],
                       ),
                   )]),
                fb("控制图常数",
                   "σ_within = R̄ / d2(n)\nA2 = 3 / (d2 √n)\nD3 = max(0, 1 − 3 d3/d2)\nD4 = 1 + 3 d3/d2",
                   [stack(
                       line("σ", sub("within"), " = ", frac([bar("R")], [t("d"), sub("2"), t("(n)")])),
                       line("A", sub("2"), " = ", frac("3", [t("d"), sub("2"), t(" √n")])),
                       line("D", sub("3"), " = max(0, 1 − 3 d", sub("3"), "/d", sub("2"), ")"),
                       line("D", sub("4"), " = 1 + 3 d", sub("3"), "/d", sub("2")),
                   )]),
            ],
            ["xbar", "tests"])
    add_spc("xbar_s", "Xbar-S 控制图", "xbar_s",
            "子组均值与标准差。σ_within=S̄/c4(n)。更大子组用 S 而不是 R。",
            [
                fb("无偏常数 c4",
                   "c4(n) = √[2/(n−1)] · Γ(n/2) / Γ((n−1)/2)",
                   [line("c", sub("4"), "(n) = ",
                         sqrt([frac("2", "n − 1")]),
                         " · ",
                         frac("Γ(n/2)", "Γ((n − 1)/2)"))]),
                fb("Xbar（均值图）",
                   "UCL = x̿ + A3 s̄\nCL = x̿\nLCL = x̿ − A3 s̄",
                   [stack(
                       heading("Xbar（均值图）"),
                       cases(
                           [t("UCL = "), dbar("x"), t(" + A"), sub("3"), bar("s")],
                           [t("CL = "), dbar("x")],
                           [t("LCL = "), dbar("x"), t(" − A"), sub("3"), bar("s")],
                       ),
                   )]),
                fb("S（标准差图）",
                   "UCL_S = B4 s̄\nCL_S = s̄\nLCL_S = B3 s̄",
                   [stack(
                       heading("S（标准差图）"),
                       cases(
                           [t("UCL"), sub("S"), t(" = B"), sub("4"), bar("s")],
                           [t("CL"), sub("S"), t(" = "), bar("s")],
                           [t("LCL"), sub("S"), t(" = B"), sub("3"), bar("s")],
                       ),
                   )]),
                fb("控制图常数",
                   "σ_within = s̄ / c4(n)\nA3 = 3 / (c4 √n)\nB3 = max(0, 1 − 3√(1−c4²)/c4)\nB4 = 1 + 3√(1−c4²)/c4",
                   [stack(
                       line("σ", sub("within"), " = ", frac([bar("s")], [t("c"), sub("4"), t("(n)")])),
                       line("A", sub("3"), " = ", frac("3", [t("c"), sub("4"), t(" √n")])),
                       line("B", sub("3"), " = max(0, 1 − 3", sqrt("1 − c₄²"), "/c", sub("4"), ")"),
                       line("B", sub("4"), " = 1 + 3", sqrt("1 − c₄²"), "/c", sub("4")),
                   )]),
            ],
            ["xbar", "tests"])
    add_spc("imr_rs", "I-MR-R/S 控制图", "imr_rs",
            "组间 I/MR 与组内 R 或 S。n≤8 用 R̄/d2；n≥9 用 S̄/c4。与组间/组内能力同口径。",
            [
                fb("组内 σ",
                   "n≤8：σ_w = R̄ / d2(n)\nn≥9：σ_w = s̄ / c4(n)",
                   [{"type": "piecewise", "content": [
                       {"type": "case",
                        "content": [t("σ"), sub("w"), t(" = "),
                                    frac([bar("R")], [t("d"), sub("2"), t("(n)")])],
                        "when": [t("n ≤ 8")]},
                       {"type": "case",
                        "content": [t("σ"), sub("w"), t(" = "),
                                    frac([bar("s")], [t("c"), sub("4"), t("(n)")])],
                        "when": [t("n ≥ 9")]},
                   ]}],
                   explanation="组间来自子组均值的移动极差。无子组只诊断。"),
            ],
            ["imr", "tests"])
    add_spc("p_chart", "P 图", "p_chart",
            "不合格品率。p̄=总不合格品/总检验。控制限随 n_i 变化并截断到 [0,1]。",
            [fb("P 图控制限",
                "p_i = d_i / n_i\nUCL = min(1, p̄ + 3√[p̄(1−p̄)/n_i])\nCL = p̄\nLCL = max(0, p̄ − 3√[p̄(1−p̄)/n_i])",
                [stack(
                    line("p", sub("i"), " = ", frac("dᵢ", "nᵢ"), " ，  ", bar("p"), " = ", frac("Σ dᵢ", "Σ nᵢ")),
                    heading("P 图"),
                    cases(
                        [t("UCL"), sub("i"), t(" = min(1, "), bar("p"), t(" + 3"),
                         sqrt([frac([bar("p"), t("(1 − "), bar("p"), t(")")], "nᵢ")]), t(")")],
                        [t("CL = "), bar("p")],
                        [t("LCL"), sub("i"), t(" = max(0, "), bar("p"), t(" − 3"),
                         sqrt([frac([bar("p"), t("(1 − "), bar("p"), t(")")], "nᵢ")]), t(")")],
                    ),
                )])],
            ["tests"])
    add_spc("np_chart", "NP 图", "np_chart",
            "不合格品数。中心线 n_i p̄，LCL 截到 0。",
            [fb("NP 图控制限",
                "CL = n_i p̄\nUCL = n_i p̄ + 3√[n_i p̄(1−p̄)]\nLCL = max(0, n_i p̄ − 3√[n_i p̄(1−p̄)])",
                [stack(
                    heading("NP 图"),
                    cases(
                        [t("UCL"), sub("i"), t(" = n"), sub("i"), bar("p"), t(" + 3"),
                         sqrt("nᵢ p̄ (1 − p̄)")],
                        [t("CL"), sub("i"), t(" = n"), sub("i"), bar("p")],
                        [t("LCL"), sub("i"), t(" = max(0, n"), sub("i"), bar("p"), t(" − 3"),
                         sqrt("nᵢ p̄ (1 − p̄)"), t(")")],
                    ),
                )])],
            ["tests"])
    add_spc("c_chart", "C 图", "c_chart",
            "固定单位数下的缺陷数。各子组单位数须相同。",
            [fb("C 图控制限",
                "c̄ = mean(c_i)\nUCL = c̄ + 3√c̄\nCL = c̄\nLCL = max(0, c̄ − 3√c̄)",
                [stack(
                    heading("C 图"),
                    cases(
                        [t("UCL = "), bar("c"), t(" + 3"), sqrt([bar("c")])],
                        [t("CL = "), bar("c")],
                        [t("LCL = max(0, "), bar("c"), t(" − 3"), sqrt([bar("c")]), t(")")],
                    ),
                )])],
            ["tests"])
    add_spc("u_chart", "U 图", "u_chart",
            "单位缺陷数。ū=Σc/Σn，控制限随 n_i 变化。",
            [fb("U 图控制限",
                "u_i = c_i / n_i\nUCL = ū + 3√(ū/n_i)\nCL = ū\nLCL = max(0, ū − 3√(ū/n_i))",
                [stack(
                    line("u", sub("i"), " = ", frac("cᵢ", "nᵢ"), " ，  ", bar("u"), " = ", frac("Σ cᵢ", "Σ nᵢ")),
                    heading("U 图"),
                    cases(
                        [t("UCL"), sub("i"), t(" = "), bar("u"), t(" + 3"),
                         sqrt([frac([bar("u")], "nᵢ")])],
                        [t("CL = "), bar("u")],
                        [t("LCL"), sub("i"), t(" = max(0, "), bar("u"), t(" − 3"),
                         sqrt([frac([bar("u")], "nᵢ")]), t(")")],
                    ),
                )])],
            ["tests"])
    add_spc("laney_p_chart", "Laney P' 图", "laney_p_chart",
            "在 P 图上用 Z 的移动极差估计额外离散 Sigma Z。",
            [fb("Laney P'",
                "Z_i = (p_i − p̄) / √[p̄(1−p̄)/n_i]\nSigmaZ = MR̄(Z) / 1.128\nUCL/LCL = p̄ ± 3 SigmaZ √[p̄(1−p̄)/n_i]，截到 [0,1]",
                [stack(
                    line("Z", sub("i"), " = ",
                         frac([t("p"), sub("i"), t(" − "), bar("p")],
                              [sqrt([frac([bar("p"), t("(1 − "), bar("p"), t(")")], "nᵢ")])])),
                    line("Sigma Z = ", frac([bar("MR"), t("(Z)")], "1.128")),
                    heading("Laney P' 控制限"),
                    cases(
                        [t("UCL"), sub("i"), t(" = min(1, "), bar("p"), t(" + 3·SigmaZ·"),
                         sqrt([frac([bar("p"), t("(1 − "), bar("p"), t(")")], "nᵢ")]), t(")")],
                        [t("CL = "), bar("p")],
                        [t("LCL"), sub("i"), t(" = max(0, "), bar("p"), t(" − 3·SigmaZ·"),
                         sqrt([frac([bar("p"), t("(1 − "), bar("p"), t(")")], "nᵢ")]), t(")")],
                    ),
                )])],
            ["laney", "tests"])
    add_spc("laney_u_chart", "Laney U' 图", "laney_u_chart",
            "在 U 图上用 Z 的 MR 估计 Sigma Z。",
            [fb("Laney U'",
                "Z_i = (u_i − ū) / √(ū/n_i)\nSigmaZ = MR̄(Z) / 1.128\n限 = ū ± 3 SigmaZ √(ū/n_i)，LCL≥0",
                [stack(
                    line("Z", sub("i"), " = ",
                         frac([t("u"), sub("i"), t(" − "), bar("u")],
                              [sqrt([frac([bar("u")], "nᵢ")])])),
                    line("Sigma Z = ", frac([bar("MR"), t("(Z)")], "1.128")),
                    heading("Laney U' 控制限"),
                    cases(
                        [t("UCL"), sub("i"), t(" = "), bar("u"), t(" + 3·SigmaZ·"),
                         sqrt([frac([bar("u")], "nᵢ")])],
                        [t("CL = "), bar("u")],
                        [t("LCL"), sub("i"), t(" = max(0, "), bar("u"), t(" − 3·SigmaZ·"),
                         sqrt([frac([bar("u")], "nᵢ")]), t(")")],
                    ),
                )])],
            ["laney", "tests"])
    add_spc("ewma", "EWMA 控制图", "ewma",
            "指数加权移动平均。仅 Test 1。可选 historical_sigma；不运行 Tests 2–8。",
            [fb("EWMA",
                "z_t = λ x_t + (1−λ) z_{t−1}\n渐近限：μ ± L σ √[λ/(2−λ)]",
                [stack(
                    line("z", sub("t"), " = λ x", sub("t"), " + (1 − λ) z", sub("t−1")),
                    heading("渐近控制限"),
                    cases(
                        [t("UCL = μ + L σ "), sqrt([frac("λ", "2 − λ")])],
                        [t("CL = μ")],
                        [t("LCL = μ − L σ "), sqrt([frac("λ", "2 − λ")])],
                    ),
                )])],
            ["tests"])
    add_spc("cusum", "CUSUM 控制图", "cusum",
            "累积和。上/下侧分别累积，越过判定距 h 为信号。CUSUM 使用专用信号逻辑，不运行 Tests 1–8。",
            [fb("CUSUM",
                "C⁺_t = max(0, C⁺_{t−1} + (x_t−μ₀)/σ − k)\nC⁻ 对称。信号：C > h",
                [stack(
                    line("C", sup("+"), sub("t"), " = max(0, C", sup("+"), sub("t−1"),
                         " + (x", sub("t"), " − μ", sub("0"), ")/σ − k)"),
                    line("C", sup("−"), sub("t"), " = max(0, C", sup("−"), sub("t−1"),
                         " − (x", sub("t"), " − μ", sub("0"), ")/σ − k)"),
                    line("信号：C > h"),
                )])],
            ["tests"])

    add_spc("zone_chart", "区域图", "zone_chart",
            "Jaehn 区域计分：同侧连续进入 1σ/2σ/3σ 区分别记 1/2/4 分，累计 ≥8 报警。"
            "个体值图 CL=均值，σ=MR̄/d2。不是完整 Tests 1–8。",
            [fb("Jaehn 区域计分",
                "Z=(x−CL)/σ\n1σ→1, 2σ→2, >3σ→4；换侧或中心带内重置；累计≥8 信号",
                [stack(
                    line("Z = (x − CL) / σ"),
                    heading("区域权重（formula_reference）"),
                    cases(
                        [t("1σ ≤ |Z| < 2σ → 权重 1")],
                        [t("2σ ≤ |Z| < 3σ → 权重 2")],
                        [t("|Z| ≥ 3σ → 权重 4")],
                        [t("累计得分 ≥ 8 → 信号")],
                    ),
                )])],
            ["imr"])
    add_spc("z_mr", "Z-MR 控制图", "z_mr",
            "短流程/多产品：Z=(x−μ_i)/σ_i；Z 图 CL=0、±3；MR(Z) 标准 MR 限。"
            "无完整历史参数表时用样本估计并诊断。",
            [fb("Z-MR",
                "Z_i=(x_i−μ_g)/σ_g\nZ 图：CL=0, UCL/LCL=±3\nMR(Z)：标准 MR 控制限",
                [stack(
                    line("Z", sub("i"), " = (x", sub("i"), " − μ", sub("g"), ")/σ", sub("g")),
                    heading("Z 图"),
                    cases(
                        [t("CL = 0")],
                        [t("UCL = +3")],
                        [t("LCL = −3")],
                    ),
                    heading("MR(Z) 图"),
                    cases(
                        [t("UCL"), sub("MR"), t(" = D"), sub("4"), bar("MR"), t("(Z)")],
                        [t("CL = "), bar("MR"), t("(Z)")],
                    ),
                )])],
            ["imr", "tests"])
    add_spc("moving_average", "移动平均控制图", "moving_average",
            "窗宽 w 的简单移动平均；从第 w 点起画。CL=均值；"
            "UCL/LCL=CL±L·σ/√w；σ=MR̄/d2。与 EWMA 独立。",
            [fb("移动平均图",
                "MA_t=(x_{t−w+1}+…+x_t)/w\nUCL/LCL=CL±L σ/√w",
                [stack(
                    line("MA", sub("t"), " = (x", sub("t−w+1"), " + … + x", sub("t"), ") / w"),
                    heading("控制限（固定 w，仅完整窗）"),
                    cases(
                        [t("UCL = CL + L σ / "), sqrt("w")],
                        [t("CL = "), bar("x")],
                        [t("LCL = CL − L σ / "), sqrt("w")],
                    ),
                )])],
            ["imr", "tests"])

    add_spc("g_chart", "G 图", "g_chart",
            "稀有事件间隔的几何控制图。输入为已算好的非负数值间隔，不解析事件日期。默认仅 Test 1。",
            [fb("G 图控制限",
                "p̂=1/(x̄+1)。CL/LCL/UCL 为几何分布 0.5 / 0.00135 / 0.99865 分位再减 1。LCL<0 记为 0。",
                [stack(
                    line("p̂ = 1 / (x̄ + 1)"),
                    heading("几何分位控制限"),
                    cases(
                        [t("CL = INVCDF(0.5) − 1")],
                        [t("LCL = max(0, INVCDF(0.00135) − 1)")],
                        [t("UCL = INVCDF(0.99865) − 1")],
                    ),
                )])],
            ["gchart", "tests"])
    add_spc("t_chart", "T 图", "t_chart",
            "稀有事件间隔的 Weibull 控制图。全部间隔>0 时用 Weibull MLE；含 0 间隔则排除后 log-log 回归并诊断。默认仅 Test 1。",
            [fb("T 图控制限",
                "拟合 Weibull 后，CL/LCL/UCL 为 0.5 / 0.00135 / 0.99865 分位。",
                [stack(
                    heading("Weibull 分位控制限"),
                    cases(
                        [t("CL = t"), sub("0.5")],
                        [t("LCL = t"), sub("0.00135")],
                        [t("UCL = t"), sub("0.99865")],
                    ),
                )])],
            ["tchart", "tests"])

    ENTRIES.append(entry(
        "capability", "正态过程能力", "质量工具", "质量工具",
        "capability", "capability", "quality_statistics_test",
        "在正态与稳定假设未验证的前提下，用规格限计算 Cp/Cpk（组内 σ）和 Pp/Ppk（总体 s）。",
        "LSL/USL/Target 由工程输入。双侧要求 LSL<USL。子组=1 时 σ_within=MR̄/d2，与 I-MR 一致；子组>1 用 R̄/d2。观测恰好等于规格限不计超规。",
        "测量列；LSL/USL/Target；可选子组。",
        ["筛选有限测量。", "估计均值、σ_within、σ_overall。", "按存在的规格侧计算 CPL/CPU 或 PPL/PPU。", "PPM：期望用 Φ，观测用严格超限比例。"],
        [("σ_within", "组内标准差"), ("σ_overall", "样本标准差 s"), ("Cpk", "min(CPL,CPU)"), ("PPM", "百万机会超规")],
        [fb("Cp / Cpk（组内 σ）",
            "Cp = (USL − LSL) / (6 σ_within)\nCPL = (μ − LSL) / (3 σ_within)\nCPU = (USL − μ) / (3 σ_within)\nCpk = min(CPL, CPU)",
            [stack(
                cases(
                    [t("Cp = "), frac("USL − LSL", "6 σ_within")],
                    [t("CPL = "), frac("μ − LSL", "3 σ_within")],
                    [t("CPU = "), frac("USL − μ", "3 σ_within")],
                    [t("Cpk = min(CPL, CPU)")],
                ),
            )],
            "缺一侧规格则对应指数为空，不填 0。", "σ_within>0 且规格有限。"),
         fb("Pp / Ppk（总体 s）",
            "把 σ_within 换成 σ_overall 得到 Pp、PPL、PPU、Ppk。",
            [stack(
                heading("Pp / Ppk"),
                cases(
                    [t("Pp = "), frac("USL − LSL", "6 σ_overall")],
                    [t("Ppk = min(PPL, PPU)")],
                ),
            )],
            "σ_overall 为样本标准差 s。"),
         fb("期望 PPM", "低于 LSL：1e6·Φ((LSL−μ)/σ)；高于 USL：1e6·(1−Φ((USL−μ)/σ))。等于规格限不计观测 PPM。"),
         fb("指数置信区间",
            "Cp/Pp 用 χ² 尺度：估计×√(χ²_{α/2,ν}/ν) 到估计×√(χ²_{1-α/2,ν}/ν)。Cpk/Ppk 用 Bissell 近似：C±z√(1/(9N)+C²/(2ν))。缺规格侧仍为 *。不是 Kushler–Hurwitz 全套。",
            note="公式参考，非 Minitab golden"),
         fb("Johnson 变换", "Chou 分位匹配，选 AD p 最大且 p>0.10 的 SB/SL/SU。成功后只报 overall Pp/Ppk，不报 Cp/Cpk。找不到变换则诊断。",
            note="公式参考，非 Minitab golden")],
        ["LSL=USL → invalid_specification。", "σ=0 不输出无限指数。", "Cpk/Ppk=1.33 只是调查提示阈值，不是合格判定。", "未拒绝 AD ≠ 已正态。"],
        "非法规格、非法 Target、σ 非正、测量不足时诊断。",
        "Process Data、能力表（估计/下限/上限）、Performance PPM、直方图（LSL/USL/Target）、可选 Johnson 表。",
        "同时看 within 与 overall；单侧时另一侧为 *。",
        "领域层 assumption_status=not_verified。",
        ["cap"],
    ))

    ENTRIES.append(entry(
        "nonnormal_capability", "非正态过程能力", "质量工具", "质量工具",
        "nonnormal_capability", "capability", "quality_statistics_test",
        "在 Weibull 或对数正态假设下用 Z 分数计算 overall Pp/Ppk。",
        "Z.LSL=Φ⁻¹(F(LSL))。不报告 Cp/Cpk。不是 Minitab golden。不做 Gamma/三参数。",
        "测量列、规格限、分布族。",
        ["拟合所选分布。", "把规格限映射为 Z。", "Pp=(Z.USL−Z.LSL)/6，Ppk=min(−Z.LSL/3, Z.USL/3)。"],
        [("F", "拟合分布的 CDF"), ("Z.LSL", "Φ⁻¹(F(LSL))")],
        [fb("Z-score 能力", "Pp=(Z.USL−Z.LSL)/6；PPL=−Z.LSL/3；PPU=Z.USL/3；Ppk=min(PPL,PPU)。期望 PPM 由 F(LSL) 与 1−F(USL) 得到。")],
        ["不报告 within Cp/Cpk。", "拟合未拒绝 ≠ 过程服从该分布。"],
        "分布无法拟合、非正值对 Weibull/对数正态、规格越出支撑时诊断。",
        "分布参数表、Overall 指数、PPM（无 Within 期望列）。",
        "只把结果当 overall 参考。",
        "formula_reference。",
        ["cap"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "between_within_capability", "组间/组内过程能力", "质量工具", "质量工具",
        "between_within_capability", "capability", "quality_statistics_test",
        "同时估计组内与组间变异，并用 σ_BW 计算 Cp/Cpk。",
        "σ_BW=√(σ_B²+σ_w²)。无子组只诊断。直方图 Between/Within 曲线对应该口径。",
        "测量列、子组列、规格限。",
        ["等量子组。", "σ_w 用 R̄/d2 或 S̄/c4（与 I-MR-R/S 相同）。", "σ_B 来自子组均值。", "Cp 用 σ_BW，Pp 用 overall s。"],
        [("σ_w", "组内"), ("σ_B", "组间"), ("σ_BW", "√(σ_B²+σ_w²)")],
        [fb("σ_BW", "σ_BW = sqrt(σ_B² + σ_w²)；Cp=(USL−LSL)/(6σ_BW)。",
            [t("σ_BW = "), sqrt("σ_B² + σ_w²")])],
        ["无子组或不 balanc 一致时诊断。", "不写过程合格。"],
        "子组大小不一致或缺失导致无法估计时中止。",
        "Process Data（Within/Between/BW/Overall σ）、能力表、直方图。",
        "比较 σ_w 与 σ_B 谁主导。",
        "n=5 用 R̄/d2，n≥9 用 S̄/c4。",
        ["cap"],
    ))

    ENTRIES.append(entry(
        "binomial_capability", "二项过程能力", "质量工具", "质量工具",
        "binomial_capability", "capability", "attribute_capability_test",
        "用不合格品率和检验数评估属性过程（二项）。",
        "p̂=Σd/Σn。输出 %Defective、PPM、Process Z 与 CI。累计图 + P 图。Sixpack 仍只用于正态。",
        "不合格品列和检验列。",
        ["求和 d、n。", "p̂=d/n。", "二项区间与 Process Z。", "画累计图和 P 图。"],
        [("p̂", "不合格品率"), ("Process Z", "对应正态分位数的过程 Z")],
        [fb("二项能力", "p̂=Σd_i/Σn_i；PPM=1e6 p̂。Process Z 由标准正态分位对应 p̂ 得到。")],
        ["不是计量 Cp/Cpk。", "解释无合格。"],
        "计数非法、分母 0 或 d>n 时诊断。",
        "过程数据、%Defective/PPM/Z+CI、累计图、P 图。",
        "同时看 P 图是否出限。",
        "method=binomial。",
        ["cap"],
    ))

    ENTRIES.append(entry(
        "poisson_capability", "泊松过程能力", "质量工具", "质量工具",
        "poisson_capability", "capability", "attribute_capability_test",
        "用单位缺陷数评估泊松过程。",
        "ū=Σc/Σn。Mean DPU 与 CI；累计 DPU + U 图。",
        "缺陷列和单位列。",
        ["求和 c、n。", "ū=c/n。", "泊松区间。", "累计 DPU 与 U 图。"],
        [("ū", "平均 DPU"), ("DPU", "单位缺陷数")],
        [fb("泊松能力", "ū=Σc_i/Σn_i。区间按泊松/Garwood 口径给出。")],
        ["不是计量能力指数。", "解释无合格。"],
        "负计数或单位非正时诊断。",
        "Mean DPU/CI、累计 DPU、U 图。",
        "看 U 图是否出限。",
        "method=poisson。",
        ["cap"],
    ))

    ENTRIES.append(entry(
        "capability_sixpack", "过程能力 Sixpack", "质量工具", "质量工具",
        "capability_sixpack", "capability", "quality_statistics_test",
        "在一页里同时看稳定性、正态性和能力。",
        "六图顺序：I 或 Xbar → 直方图 → MR 或 R → 正态概率 → 最后 25 点 → 能力图。σ_within 必须与能力 Within 相同。",
        "与正态能力相同的测量/规格/子组。",
        ["按子组大小选择 I-MR 或 Xbar-R。", "计算与正态能力相同的指数。", "按固定顺序排六图。"],
        [("Blom p_i", "(i+0.625)/(n+0.25)"), ("corr(z,x)", "概率图辅助相关，不能替代 AD")],
        [fb("Sixpack 概率图", "p_i=(i+0.625)/(n+0.25)，z_i=Φ⁻¹(p_i)。图中相关是辅助，不是正式正态性检验。"),
         fb("顺序", "I/Xbar，直方图，MR/R，正态概率，最后 25 点，能力图。")],
        ["结论卡 1.33 只是提示。", "Sixpack 不做二项/泊松。"],
        "与正态能力相同的非法输入。",
        "六图 + 能力表。",
        "先看控制图有没有特殊原因，再看能力。",
        "直方图与正态能力一致。",
        ["cap"],
    ))

    ENTRIES.append(entry(
        "box_cox", "Box-Cox 变换", "质量工具", "质量工具",
        "box_cox", "box_cox", "quality_statistics_test",
        "寻找使正值数据更接近常数方差/近似正态的幂变换。",
        "在 [-5,5] 网格最小化变换后样本标准差，并可圆整到常用 λ。零或负值不自动修正。",
        "严格正的测量列；可选规格限（变换后能力仍按变换值）。",
        ["拒绝非正值。", "对网格 λ 计算标准化 W 的 s。", "选最小 s 的 λ，可选圆整。", "输出 λ–SD 图与变换前后概率图。"],
        [("λ", "幂参数"), ("G", "几何均值"), ("W", "标准化变换")],
        [fb("Box-Cox", "λ=0 时 W=G ln(Y)；λ≠0 时 W=(Y^λ−1)/(λ G^{λ−1})。",
            nodes=[{"type": "piecewise", "content": [
                {"type": "case", "content": [t("G ln(Y)")], "when": [t("λ = 0")]},
                {"type": "case", "content": [t("(Y^λ − 1) / (λ G^{λ−1})")], "when": [t("λ ≠ 0")]},
            ]}],
            explanation="G 使不同 λ 下 W 的尺度可比较。")],
        ["最优 λ 不等于数据已正态。", "变换后能力不是原单位合格判定。"],
        "存在 0 或负值、全相同正值或 n 不足时诊断。",
        "λ 搜索、λ–SD 图、变换前后概率图、可选变换后能力。",
        "看 λ–SD 曲线是否有明确谷底。",
        "常用圆整：−2,−1,−0.5,0,0.5,1,2。",
        ["cap"],
    ))

    ENTRIES.append(entry(
        "distribution_identification", "个体分布识别", "质量工具", "质量工具",
        "distribution_identification", "distribution_identification", "quality_statistics_test",
        "比较正态、Weibull、对数正态、指数二参数的 Anderson–Darling，辅助选分布。",
        "四族二参数 AD 排序 + 概率图。不自动改写后续能力分析的 capability_method。非正值时 Weibull/指数/对数正态为未计算。",
        "一个测量列。",
        ["对每族尝试拟合。", "计算 AD 并排序。", "画各族概率图。"],
        [("AD", "Anderson–Darling"), ("四族", "Normal / Weibull / Lognormal / Exponential")],
        [fb("排序", "对各可计算分布给出 AD 与 p，从小到大排序。p 最大也不等于已证明该分布。")],
        ["不改能力默认分布。", "非正值三族 not_computed。"],
        "有效观测过少时诊断。",
        "AD 排序表 + 概率图。",
        "把它当筛选工具，再做对应的能力/可靠性分析。",
        "仅四族二参数。",
        ["ad"],
    ))

    ENTRIES.append(entry(
        "tolerance_intervals", "容差区间", "质量工具", "质量工具",
        "tolerance_intervals", "tolerance", "tolerance_interval_test",
        "给出以指定置信覆盖总体至少 P 比例的区间。",
        "显式 method=normal|nonparametric（兼容旧 variance_method=nonparametric）。双侧 normal 用 Howe；单侧 normal 用 Natrella；非参数序统计并报告 achieved_confidence。公式参考，不是 Minitab golden。",
        "测量列、方法 normal/nonparametric、覆盖率、置信水平、双侧或单侧。",
        ["取有限值算 x̄、s。", "按 method / method_family 选择 normal 或 nonparametric。", "normal 双侧/单侧分别用 Howe 或 Natrella。", "nonparametric 输出 achieved_confidence 与样本量提示。"],
        [("P", "要覆盖的总体比例"), ("γ", "目标置信水平"), ("k", "容差因子"), ("achieved_confidence", "样本在非参数法下实际达到的置信度")],
        [fb("Howe 双侧", "区间 x̄ ± k s，k 为 Howe 近似因子，使 P(覆盖≥P)≈γ。"),
         fb("Natrella 单侧", "单侧界限 x̄ ± k s，k 为 Natrella 近似。"),
         fb("非参数顺序统计", "当样本量不足以达到目标 γ 时，输出 achieved_confidence，提醒当前样本真正达到的置信度。")],
        ["不是规格限，也不是过程合格。", "nonparametric 的 achieved_confidence 低于目标时，只说明样本量不足，不是计算错误。"],
        "n 不足、s=0 或覆盖/置信越界时诊断。",
        "过程数据 N/N*、按 method 主表、method_family 与 achieved_confidence。",
        "核对 P 与 γ 是否来自标准/客户要求，再看 method 是否适合当前样本。",
        "formula_reference；normal 与 nonparametric 输出口径保持一致。",
        ["tol"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "gage_rr", "Crossed Gage R&R", "MSA", "质量工具",
        "gage_rr", "msa", "gage_rr_output_test",
        "交叉设计下把测量变异分解为重复性、再现性与零件。",
        "ANOVA 方差分量。ndc=floor(1.41×Part/Gage)。图序：%Contribution → %Study Var → Run Chart → 按零件 Xbar/R → 按零件散点 → 交互。不改 OLS/ANOVA/ndc 公式。",
        "测量、零件、操作者；通常每零件每操作者多次重复。",
        ["平衡交叉结构检查。", "ANOVA 得方差分量。", "%Contribution 与 %Study Var。", "ndc 与图。"],
        [("Repeatability", "同一零件同一人的重复误差"), ("Reproducibility", "操作者效应"),
         ("ndc", "可区分类别数 floor(1.41 σ_part/σ_gage)")],
        [fb("ndc", "ndc = floor(1.41 × σ_part / σ_gage)。",
            [t("ndc = floor(1.41 × "), frac("σ_part", "σ_gage"), t(")")]),
         fb("%Study Var", "各分量标准差相对总研究变异（或公差，若提供）的百分比。")],
        ["ndc 或 %Gage 不写成量具通过。", "负方差分量按实现规则截断，但保存截断前值。"],
        "设计不平衡无法估计、公差非法或测量不足时诊断。",
        "ANOVA/分量表、ndc、上述图序。",
        "同时看分量百分比和 Run Chart 是否有异常点。",
        "invalid_tolerance 时不拿公差当研究变异。",
        ["gage"],
    ))

    ENTRIES.append(entry(
        "emp_crossed", "EMP Crossed", "MSA", "质量工具",
        "emp_crossed", "msa", "p2_t2_mewma_nelson_emp_test",
        "Wheeler EMP Crossed：用交叉 Gage 方差分量做 ICC 分级。",
        "复用交叉 ANOVA 分量。ICC(no bias / with bias / with interaction)；"
        "PE=0.67449√Repeatability；First–Fourth 按 ICC(with interaction)。"
        "不是 AIAG 合格判定；不是全量 Expanded Gage GLM。",
        "测量、零件、操作者（平衡交叉）。",
        ["交叉 ANOVA 方差分量。", "计算三种 ICC。", "Probable Error。", "按 ICC 分级。"],
        [("ICC", "零件方差 / 相关总方差"), ("PE", "Probable Error"),
         ("First–Fourth", "Wheeler 监控能力分级")],
        [fb("ICC (with interaction)",
            "Part / (Part + Repeat + Operator + Part×Operator)。",
            [t("ICC = "), frac("σ²_part", "σ²_part+σ²_e+σ²_op+σ²_int")])],
        ["不得写量具合格/不合格。", "与 AIAG %Study Var 阈值不同。"],
        "设计不平衡或分量不可估时诊断。",
        "分量表 + EMP 统计表。",
        "先看分级与衰减%，再决定是否需要改进测量过程。",
        "本命令不替代 Crossed Gage R&R 的完整图序。",
        ["gage"],
    ))

    ENTRIES.append(entry(
        "expanded_gage_rr", "Expanded Gage R&R", "MSA", "质量工具",
        "expanded_gage_rr", "msa", "p2_gv_expanded_b4b5_test",
        "Expanded Gage：平衡 Part×Operator×附加因子三因子随机 ANOVA。",
        "主效应 + 全部二阶交互；重复≥2 时有纯误差，否则三阶交互作重复性。"
        "Reproducibility=Operator+附加因子+相关交互（不含 Part）。"
        "不平衡/固定效应/嵌套混合 GLM 仍延后。",
        "测量、零件、操作员、附加因子（各≥2 水平，完整平衡交叉）。",
        ["检查平衡。", "三因子 ANOVA。", "EMS 方差分量。", "汇总 Total Gage R&R / Part-To-Part。"],
        [("Additional", "第 3 随机因子"), ("Reproducibility", "操作员+附加+交互"),
         ("Repeatability", "残差或三阶交互")],
        [fb("范围", "仅平衡三因子随机；不是 Minitab 全量 Expanded GLM。")],
        ["不得写量具合格/不合格。", "不平衡设计请用交叉 Gage 或等待后续 GLM。"],
        "缺失格子、不等重复、水平不足时诊断。",
        "ANOVA 表 + 分量表。",
        "先看附加因子与交互是否主导再现性。",
        "与 EMP Crossed / 交叉 Gage 互补，不互相替代。",
        ["gage"],
    ))

    ENTRIES.append(entry(
        "nested_gage_rr", "Nested Gage R&R", "MSA", "质量工具",
        "nested_gage_rr", "msa", "gage_rr_output_test",
        "零件嵌套在操作者下的 Gage 研究。",
        "嵌套 ANOVA。图为分量条 + 按操作者 Xbar-R + By Part。没有 Total Gage R&R 三条中的交叉交互项。",
        "测量、零件、操作者；零件 nested in 操作者。",
        ["检查嵌套结构。", "嵌套 ANOVA 分量。", "画分量条、按操作者 Xbar-R、By Part。"],
        [("Part(Operator)", "嵌套零件效应"), ("Repeatability", "重复性")],
        [fb("嵌套 ANOVA", "零件平方和在操作者内计算，不估计 Operator×Part 交互。")],
        ["解释无量具通过。", "缺失零件行跳过。"],
        "非嵌套结构或无法估计时诊断。",
        "ANOVA/分量/ndc 与嵌套图。",
        "看操作者间是否主导。",
        "与交叉 Gage 公式不同，不要混读交互图。",
        ["gage"],
    ))

    ENTRIES.append(entry(
        "msa_type1", "MSA Type 1 / Bias / Stability", "MSA", "质量工具",
        "msa_type1", "msa", "reliability_msa_power_test",
        "对标准件评估偏倚、线性与 Type 1 Cg/Cgk；Stability 看重复测量是否漂移。",
        "bias_i=y_i−r_i。Linearity 对参考值做 OLS：Linearity=|slope|×PV。Gage Bias 表含各级 t/P 与 Average。零重复性不输出 p=0。",
        "测量列、参考值列（或单一参考）、公差/PV。",
        ["配对测量与参考。", "Type 1：s 与 Cg=Tol/(6s)、Cgk。", "Bias/Linearity OLS。", "Stability 按时间顺序看。"],
        [("bias_i", "y_i−r_i"), ("Cg", "Tol/(6s)"), ("PV", "过程变差，用于线性度")],
        [fb("Type 1", "Cg=Tol/(6s)；Cgk 还扣偏倚。s=0 时不输出假 p=0。",
            [t("Cg = "), frac("Tol", "6s")]),
         fb("线性度", "bias 对参考值回归；Linearity=|b1|×PV。输出截距/斜率 SE、t、P 与残差 S。"),
         fb("Gage Bias", "每个参考水平的平均偏倚 t/P，以及 Average Bias 行。")],
        ["Cg/Cgk 高不等于量具合格。", "线性显著只说明斜率证据，要看实际偏倚大小。"],
        "无参考值、公差非正、有效重复不足时诊断。",
        "Cg/Cgk、S and R-Sq、Gage Linearity、Gage Bias、图形。",
        "同时看偏倚方向和重复性 s。",
        "OLS 公式本轮不改。",
        ["lin"],
    ))

    ENTRIES.append(entry(
        "attribute_agreement", "属性一致性分析", "MSA", "质量工具",
        "attribute_agreement", "msa", "reliability_msa_power_test",
        "评估多个评价人对属性等级的一致性。",
        "两两 Cohen Kappa（可选 linear/quadratic 加权）；≥3 人 Fleiss overall 保持未加权。"
        "Weighted Kappa 是 DataLab 扩展，不是 Minitab AAA 默认（有序用 Kendall）。"
        "无 Minitab golden 时不填假数值。Kendall 需 ordinal=true。",
        "每个评价人一列等级；可选标准列；可选 kappa_weight=none/linear/quadratic。",
        ["对齐评价。", "两两 Cohen（可加权）。", "≥3 人 Fleiss（未加权）。", "若 ordinal=true 且等级≥3 计算 Kendall。"],
        [("κ", "Kappa"), ("P_o", "观察一致率"), ("P_e", "期望一致率"), ("w_ij", "线性/二次权重")],
        [fb("Cohen", "κ=(P_o−P_e)/(1−P_e)。P_e=1 时不可识别，不输出 κ。"),
         fb("Weighted Kappa", "linear: w=1−|i−j|/(k−1)；quadratic: w=1−[(i−j)/(k−1)]²。评级须可数值排序。"),
         fb("Fleiss", "多个评价人 overall κ 保持未加权。")],
        ["κ 高不得写成已证明一致或量具通过。", "未知等级编码拒绝。", "不要把加权 κ 当成 Minitab AAA 输出。"],
        "评价人数不足、等级无法对齐时诊断。",
        "一致率表、Cohen/Fleiss、可选加权 κ、可选 Kendall。",
        "先看对角一致，再看 κ。",
        "formula_reference。",
        ["kappa"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "doe_factorial", "2 水平析因设计生成", "DOE", "统计 > DOE",
        "doe_factorial", "doe", "p2_doe_acf_power_test",
        "生成 2^k 全因子或 2^(k-p) 部分析因设计矩阵，也可对已有设计表做响应分析。",
        "编码 ±1。p=0 为全因子；p>0 用默认最高分辨度生成器或手写 D=ABC;E=ABD。"
        "输出设计信息、生成器、定义关系、别名结构与设计矩阵。响应分析 Pareto 用 |t|；df=0 时用 Lenth PSE。",
        "因子名与低/高水平，或已有设计表的响应与因子列；fraction_p、generators、中心点、区组、随机种子可选。",
        ["创建设计或读取已有表。", "编码后（响应分析时）回归/ANOVA。",
         "设计生成：矩阵+别名；响应分析：Pareto、立方、主效应、交互、等值线/曲面、残差 4 图。"],
        [("效应", "高−低的编码效应"), ("p", "部分析因生成器个数"), ("Resolution", "定义关系最短非 I 字长")],
        [fb("全因子", "2^k 运行；每因子独立 ±1。"),
         fb("部分析因", "基设计 2^(k-p)，附加因子由生成器乘积定义；默认表覆盖常见 (k,p)。"),
         fb("别名", "用定义关系把效应乘到各词上得到混淆链；不是显著性检验。")],
        ["最大效应不是过程合格。", "别名链不是已证实混淆因果。", "≥4 因子响应分析无立方图。"],
        "因子水平无法编码、p≥k、无默认生成器且未手写、响应缺失过多时诊断。",
        "设计信息/生成器/定义关系/别名/设计矩阵；或响应分析表+图。",
        "先生成矩阵写入工作表，再选响应列做 doe_response。",
        "不做 PB/DSD/RSM 设计生成；不做可旋转 3D。",
        ["doe"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "doe_response", "DOE 响应分析", "DOE", "统计 > DOE",
        "doe_factorial", "doe", "doe_factorial_output_test",
        "对已有 2 水平设计表拟合响应。",
        "与 doe_factorial 共用配置与执行。需要响应列和因子列。",
        "响应列 + 因子列（已有数据）。",
        ["读取响应与因子。", "与析因分析相同的模型和图。"],
        [("响应", "要分析的输出"), ("因子列", "已编码或可映射的因子")],
        [fb("同析因模型", "编码 ±1 后估计主效应与交互；图序与 2 水平全因子响应页相同。")],
        ["没有响应列时不能当分析用。"],
        "因子列不足或响应非有限时诊断。",
        "与 doe_factorial 响应页相同。",
        "把它当作“已有表上的析因分析”。",
        "共享 doe_factorial 服务。",
        ["doe"],
    ))

    ENTRIES.append(entry(
        "rsm_response", "响应曲面分析", "DOE", "统计 > DOE",
        "rsm_response", "rsm", "p2_rsm_special_cause_test",
        "对已有连续因子设计表拟合二次响应曲面（线性+交互+纯二次）。",
        "因子按列内 min/max 编码到 [-1,1]（已在区间内则视为已编码）。系数、ANOVA、残差四图；"
        "前两因子等值线与静态曲面，其余因子编码 hold=0。",
        "响应列 + ≥2 连续因子列（complete-case）。",
        ["complete-case 对齐。", "编码因子。", "构造二次设计矩阵并 OLS。",
         "输出系数/ANOVA/残差图与等值线曲面。"],
        [("Coef", "编码单位系数"), ("R²", "决定系数"), ("残差", "观测−拟合")],
        [fb("二次模型", "y=β0+Σβi xi+Σβij xi xj+Σβii xi²+ε（编码单位）。"),
         fb("编码", "xi' = 2(xi−min)/(max−min)−1；已在 [-1,1] 则不改。"),
         fb("等值线", "在编码网格上评估拟合曲面；非轴因子 hold=0。")],
        ["R² 高不是工艺已验证。", "显著项不是工程最优设定。", "等值线是探索图，不是可旋转 3D。"],
        "因子不足两个、无变异、观测少于参数时诊断。",
        "模型摘要、系数表、ANOVA、残差四图、等值线与曲面。",
        "先看残差是否随机，再解读系数与等值线形状。",
        "不做 CCD/BBD 设计生成、混合物、Box–Cox 自动。",
        ["doe", "rsm"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "special_cause_rules", "特殊原因规则 Catalog", "控制图", "帮助 > 算法",
        "imr", "spc", "special_cause_rule_test",
        "Minitab Tests 1–8 与 DataLab 图种适用表、默认策略说明。",
        "Test 1：1 点超 ±3σ。Test 2：连续 9 点同侧。Test 3：连续 6 点升降。"
        "Test 4：连续 14 点交替上下。Test 5：连续 3 点中 2 点超 ±2σ 同侧。"
        "Test 6：连续 5 点中 4 点超 ±1σ 同侧。Test 7：连续 15 点在 ±1σ 内。"
        "Test 8：连续 8 点在 ±1σ 外。"
        "适用：I/Xbar/属性/Laney=1–8；R/S/MR/Z-MR=1–4；EWMA/MA/G/T=仅 1；CUSUM=无 Tests；"
        "Zone 图用 Jaehn 分区，不是 Tests 1–8。"
        "默认策略 all_applicable=启用该图种全部适用 Tests；minitab_like=仅 Test 1。"
        "DataLab 默认 all_applicable，与 Minitab 常见仅 Test 1 不同；多规则提高误报风险。"
        "WECO 四规则与 Tests 1/5/6/2 部分重叠，不可一一等同。"
        "交叉链接：Run Chart（游程/聚类/混合）不是控制图 Tests；"
        "ANOM 决策限用于组均值比较，不是 Shewhart Tests；"
        "Zone 图用 Jaehn 分区计分，明确不是 Tests 1–8。",
        "控制图对话框的规则默认策略与特殊原因测试勾选。",
        ["选择策略或显式勾选 Tests。", "按图种过滤不适用规则。", "触发点写入图与表。"],
        [("Test k", "第 k 条特殊原因规则"), ("rule_policy", "all_applicable / minitab_like / explicit")],
        [fb("策略", "空 tests 时：all_applicable→全部适用；minitab_like→仅 Test 1（若适用）。"),
         fb("显式", "勾选或文本列出 Tests 时 policy=explicit，覆盖策略默认。")],
        ["规则触发是调查信号，不是过程已失控、合格或已证明稳定。",
         "Zone≠Tests 1–8。", "CUSUM 用专用信号逻辑。",
         "Run Chart / ANOM / Zone 见各自命令帮助，勿与 Tests 混读。"],
        "CUSUM 与 Zone 不套用 Tests 1–8。",
        "本条目为规则百科；实际输出见各控制图命令；Run Chart/ANOM/Zone 交叉说明见上文。",
        "先确认策略，再解读触发点。",
        "正文不得引用外部公式底稿路径。",
        ["spc", "rules"], status="formula_reference",
    ))

    ENTRIES.append(entry(
        "response_optimization", "DOE 响应优化", "DOE", "统计 > DOE",
        "response_optimization", "doe", "doe_response_test",
        "在因子编码空间里找使一个或多个响应最接近目标的设置。",
        "每个响应独立 goal/权重。多响应总体 D 为各 d 的几何平均。缺协方差时区间显示 *。",
        "一个或多个响应列、因子列；目标 maximize/minimize/target 及界限。",
        ["拟合各响应模型。", "在网格/候选点上算单个 d 与总体 D。", "报告最佳组合与预测。"],
        [("d", "单个 desirability，0～1"), ("D", "几何平均"), ("goal", "maximize / minimize / target")],
        [fb("Desirability", "maximize：低于下限 d=0，高于上限 d=1，中间升幂；minimize 相反；target 在目标处为 1。D=(d1·d2·…)^{1/m}。")],
        ["最大 D 不是工艺已验证。", "区间 * 表示协方差不可用，不是预测为 0。"],
        "目标字段矛盾、响应无法拟合时诊断。",
        "候选表、各响应 d、总体 D、最佳组合。",
        "核对每个响应的 goal 是否与工程方向一致。",
        "单响应无 JSON 时旧字段写入 [0]。",
        ["doe"],
    ))

    graphs = [
        ("histogram", "直方图", "histogram",
         "把数值分成若干区间，用矩形高度表示频数或密度。",
         "默认自动分箱。可叠加正态参考曲线，曲线不是检验。"),
        ("boxplot", "箱线图", "boxplot",
         "用五数概括展示位置与散布：Q1、中位数、Q3，须线到最后未超出围栏的点，围栏外画为离群点。",
         "围栏通常为 Q1−1.5 IQR 与 Q3+1.5 IQR。离群点仍是数据点，不是自动删除规则。"),
        ("pareto", "柏拉图", "pareto",
         "按类别频数从大到小排序，并画累积百分比。",
         "累积百分比 = 到该类为止的频数之和 / 总频数 ×100%。"),
        ("scatter_plot", "散点图", "scatter",
         "每个 complete-case 点画 (x,y)。",
         "可加回归线时，线来自当前图的拟合设置，不是假设检验结果。"),
        ("interval_plot", "区间图", "interval",
         "按组显示均值和置信区间。",
         "区间计算与所选置信水平一致；区间含比较值不得写成显著差异。"),
        ("correlation_plot", "相关图", "correlation",
         "多变量两两散点矩阵，辅助看线性或非线性形态。",
         "图本身不算 Pearson 表；相关分析命令才给 r 与 p。"),
        ("bubble_plot", "气泡图", "bubble",
         "(x,y) 位置，气泡面积映射第三列。",
         "面积比例按实现规则缩放，避免零或负尺寸。"),
        ("probability_plot", "正态概率图", "probability",
         "排序观测对 Blom 正态分位。",
         "p_i=(i+0.625)/(n+0.25)，y=Φ⁻¹(p_i)。直线只是参考，不能替代 AD 检验。"),
        ("ecdf_plot", "经验累积分布图", "ecdf",
         "F̂(x)=#{y≤x}/n，右端为 1。",
         "阶梯函数；缺失不进入 n。"),
        ("matrix_plot", "矩阵图", "matrix",
         "所选数值列的两两散点。",
         "对角线通常为变量名或单变量图。"),
        ("marginal_plot", "边际图", "marginal",
         "散点加上 x/y 边际直方图或箱线。",
         "边际图与中心散点使用同一 complete-case 规则。"),
        ("parallel_plot", "平行坐标图", "parallel",
         "每个观测一条折线，轴为各变量（常做列内缩放）。",
         "用于发现聚类与离群折线，无 p 值。"),
        ("heatmap_plot", "热图", "heatmap",
         "用颜色表示表格或分箱密度。",
         "色标范围可固定；缺失格子不填假颜色。"),
        ("time_series_plot", "时间序列图", "time_series",
         "按行序或时间列连接观测。",
         "不自动差分或季节调整。"),
        ("area_plot", "面积图", "area",
         "折线下方填色，强调累积或堆叠。",
         "堆叠时各组应为可加的同类量。"),
        ("contour_plot", "等值线图", "contour",
         "在规则网格上对 z(x,y) 画等值线。",
         "不规则网格给出诊断，不擅自插值成假规则网格。"),
        ("pie_plot", "饼图", "pie",
         "类别频数占合计的比例为扇区角。",
         "角度 = 360° × n_k / Σ n。类别很多时可读性下降。"),
        ("density_plot", "密度图", "density",
         "高斯核密度估计曲线（Silverman 带宽）。",
         "h=0.9·min(s,IQR/1.34)·n^(-1/5)；曲线是平滑估计，不是分布检验。"),
        ("hexbin_plot", "Hexbin", "hexbin",
         "二维矩形分箱计数着色（Binned Scatter）。",
         "complete-case (x,y) 落入矩形格；产品名 Hexbin，非正六边形镶嵌。"),
        ("violin_plot", "小提琴图", "violin",
         "分组镜像 KDE + 箱线五数。",
         "每组独立 Silverman 带宽；形状与箱线同页。"),
        ("bar_chart", "条形图", "bar",
         "分类计数条形；保持出现顺序。",
         "无按计数排序、无累积百分比；与柏拉图分流。"),
    ]
    for gid, gtitle, gicon, purpose, overview in graphs:
        ENTRIES.append(entry(
            gid, gtitle, "探索性图形", "图形",
            "GraphService::run", "—", "graph_service_test",
            purpose,
            overview + " 图形命令不写质量 Facts，也不做合格判定。",
            "按对话框选择 x/y/z 或类别列。",
            ["按角色读取列。", "complete-case 过滤。", "按该图几何规则计算坐标/频数/分箱。", "生成 ChartModel，可编辑属性并复制 PNG。"],
            [("source_row", "点对应的原始工作表行"), ("complete-case", "该图用到的列在该行都有效")],
            [fb("绘图规则", overview, explanation="本图是探索性展示。若需要推断（p 值、控制限、能力指数），请使用对应分析命令。")],
            ["悬停应能回到原始行。", "编辑颜色/线型不改变底层数据。", "复制图形走渲染器，而不是截取窗口像素。"],
            "缺必要列、非数值被当作数值轴、或网格不规则（等值线）时诊断或空图。",
            "PlotSpec / ChartModel 图形，可在属性页改系列、轴、主题。",
            "把它当数据浏览工具。统计结论以分析输出页为准。",
            "不附加推断表。",
            ["graph"],
            aliases=[gid, gicon, gtitle],
        ))

    ENTRIES.append(entry(
        "eda_4plot", "EDA 四图", "探索性图形", "图形",
        "eda_4plot", "eda", "p2_eda4_crosstab_chi_resid_test",
        "NIST 单变量四图打包：run sequence、lag-1、histogram、normal probability。",
        "同页四个 PlotSpec；用于检查位置/散布/随机性/分布形态假设。"
        "不能写成过程受控或分布已正态。与单独直方图/正态概率图命令并存。",
        "一个连续变量列；可选直方图组数。",
        ["按观测顺序画 run sequence。", "lag-1：Y(i-1) vs Y(i)。",
         "直方图（Sturges 或手工组数）。", "正态概率图（理论分位数 vs 有序值）。"],
        [("i", "观测顺序"), ("Y(i)", "第 i 个观测"), ("lag-1", "相邻对")],
        [fb("NIST 4-Plot", "四图并列探索四类假设。",
            [t("run sequence / lag-1 / histogram / normal probability")])],
        ["不得写过程已失控、已证明稳定、分布已正态。", "不是假设检验替代。"],
        "有效观测 < 2 时诊断。",
        "四图 + 说明表；EdaPlotFacts.kind=eda_4plot。",
        "先扫四图形态，再决定是否做正态性/控制图等正式分析。",
        "不做合格判定；不冒充 mosaic。",
        ["graph"],
        aliases=["eda_4plot", "4-plot", "EDA 四图"],
    ))
