# -*- coding: utf-8 -*-
"""Merge analysis command menu/title/group labels into ui_menu_strings.json."""
from __future__ import annotations

import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]

# Curated zh_CN -> en_US for analysis menus. Unlisted Chinese falls back to zh (honest).
# English-looking sources keep themselves.
TRANSLATIONS: dict[str, str] = {
    "图形": "Graph",
    "统计": "Stat",
    "控制图": "Control Charts",
    "质量工具": "Quality Tools",
    "基础统计": "Basic Statistics",
    "ANOVA": "ANOVA",
    "回归": "Regression",
    "时间序列": "Time Series",
    "多变量": "Multivariate",
    "可靠性": "Reliability",
    "功效与样本量": "Power and Sample Size",
    "假设检验": "Hypothesis Tests",
    "表格": "Tables",
    "DOE": "DOE",
    "探索性图形": "Exploratory Graphs",
    "散点图": "Scatterplot",
    "气泡图": "Bubble Plot",
    "矩阵图": "Matrix Plot",
    "边际图": "Marginal Plot",
    "概率图": "Probability Plot",
    "经验累积分布图": "ECDF Plot",
    "直方图": "Histogram",
    "箱线图": "Boxplot",
    "区间散点图": "Interval Plot",
    "相关图": "Correlation Plot",
    "时间序列图": "Time Series Plot",
    "等值线图": "Contour Plot",
    "饼图": "Pie Chart",
    "密度图": "Density Plot",
    "Hexbin": "Hexbin",
    "Hexbin / 二维分箱": "Hexbin / 2D Binning",
    "小提琴图": "Violin Plot",
    "条形图": "Bar Chart",
    "面积图": "Area Chart",
    "平行坐标图": "Parallel Coordinates",
    "热图": "Heatmap",
    "Pareto 图": "Pareto Chart",
    "I-MR 控制图": "I-MR Chart",
    "Xbar-R 控制图": "Xbar-R Chart",
    "Xbar-S 控制图": "Xbar-S Chart",
    "C 图": "C Chart",
    "U 图": "U Chart",
    "P 图": "P Chart",
    "NP 图": "NP Chart",
    "EWMA 控制图": "EWMA Chart",
    "CUSUM 控制图": "CUSUM Chart",
    "G 图": "G Chart",
    "G 图（稀有事件计数）": "G Chart (Rare Event Counts)",
    "过程能力": "Capability Analysis",
    "非正态过程能力": "Nonnormal Capability",
    "正态性检验": "Normality Test",
    "描述性统计": "Descriptive Statistics",
    "单样本 t 检验": "1-Sample t-Test",
    "双样本 t 检验": "2-Sample t-Test",
    "配对 t 检验": "Paired t-Test",
    "单比例检验": "1-Proportion Test",
    "双比例检验": "2-Proportion Test",
    "单方差检验": "1-Variance Test",
    "双方差检验": "2-Variances Test",
    "单因素 ANOVA": "One-Way ANOVA",
    "双因素 ANOVA": "Two-Way ANOVA",
    "一般线性模型": "General Linear Model",
    "回归分析": "Regression",
    "逐步回归": "Stepwise Regression",
    "二元逻辑回归": "Binary Logistic Regression",
    "正交回归": "Orthogonal Regression",
    "非线性回归": "Nonlinear Regression",
    "拟合线图": "Fitted Line Plot",
    "残差图": "Residual Plots",
    "相关分析": "Correlation",
    "协方差": "Covariance",
    "卡方检验": "Chi-Square Test",
    "交叉表": "Cross Tabulation",
    "Fisher 精确检验": "Fisher Exact Test",
    "Cochran Q 检验": "Cochran Q Test",
    "Friedman 检验": "Friedman Test",
    "Mann-Whitney": "Mann-Whitney",
    "Kruskal-Wallis": "Kruskal-Wallis",
    "Mood 中位数检验": "Mood Median Test",
    "符号检验": "Sign Test",
    "Wilcoxon": "Wilcoxon",
    "运行图": "Run Chart",
    "时间序列分解": "Time Series Decomposition",
    "移动平均": "Moving Average",
    "单指数平滑": "Single Exponential Smoothing",
    "双指数平滑": "Double Exponential Smoothing",
    "Winters 方法": "Winters Method",
    "ARIMA 建模预测": "ARIMA Modeling and Forecast",
    "ADF 单位根检验": "ADF Unit Root Test",
    "Augmented Dickey-Fuller": "Augmented Dickey-Fuller",
    "ACF/PACF": "ACF/PACF",
    "Correlogram": "Correlogram",
    "Correlogram（相关图）": "Correlogram",
    "Cross Correlation": "Cross Correlation",
    "谱分析": "Spectral Analysis",
    "主成分分析": "Principal Components",
    "因子分析": "Factor Analysis",
    "判别分析": "Discriminant Analysis",
    "Discriminant Analysis": "Discriminant Analysis",
    "Cluster Observations": "Cluster Observations",
    "Cluster K-Means": "Cluster K-Means",
    "多元方差分析": "MANOVA",
    "可靠性分析": "Reliability Analysis",
    "分布 ID 图": "Distribution ID Plot",
    "寿命数据回归": "Life Data Regression",
    "保修分析": "Warranty Analysis",
    "参数增长曲线": "Parametric Growth Curve",
    "非参数增长曲线": "Nonparametric Growth Curve",
    "加速寿命试验": "Accelerated Life Test",
    "样本容量：单比例": "Sample Size: 1 Proportion",
    "样本容量：双比例": "Sample Size: 2 Proportions",
    "样本容量：单均值": "Sample Size: 1 Mean",
    "样本容量：双均值": "Sample Size: 2 Means",
    "样本容量：单方差": "Sample Size: 1 Variance",
    "样本容量：双方差": "Sample Size: 2 Variances",
    "功效曲线": "Power Curve",
    "量具 R&R（交叉）": "Gage R&R (Crossed)",
    "Crossed Gage R&R": "Crossed Gage R&R",
    "量具 R&R（嵌套）": "Gage R&R (Nested)",
    "Expanded Gage R&R": "Expanded Gage R&R",
    "Expanded Gage R&R（扩大平均）": "Expanded Gage R&R",
    "EMP Crossed": "EMP Crossed",
    "EMP Crossed（Wheeler）": "EMP Crossed (Wheeler)",
    "属性一致性分析": "Attribute Agreement Analysis",
    "量具线性与偏倚": "Gage Linearity and Bias",
    "量具研究（类型 1）": "Type 1 Gage Study",
    "创建分析": "Tolerance Analysis",
    "多变量图": "Multi-Vari Chart",
    "因果图": "Cause-and-Effect Diagram",
    "箱线图（质量）": "Boxplot (Quality)",
    "正态概率图": "Normal Probability Plot",
    "个体值图": "Individual Value Plot",
    "点图": "Dotplot",
    "茎叶图": "Stem-and-Leaf",
    "全因子设计": "Full Factorial Design",
    "部分因子设计": "Fractional Factorial Design",
    "Plackett-Burman 设计": "Plackett-Burman Design",
    "中心复合设计": "Central Composite Design",
    "Central Composite Design": "Central Composite Design",
    "Box-Behnken Design": "Box-Behnken Design",
    "Box–Behnken 设计": "Box-Behnken Design",
    "Box-Behnken 设计": "Box-Behnken Design",
    "响应曲面分析": "Response Surface Analysis",
    "DOE 响应曲面": "DOE Response Surface",
    "DOE 响应优化": "DOE Response Optimization",
    "混料设计": "Mixture Design",
    "田口设计": "Taguchi Design",
    "2 水平筛选设计": "2-Level Screening Design",
    "2 水平全因子 / 部分因子设计": "2-Level Full / Fractional Factorial",
    "2 水平因子响应分析": "2-Level Factorial Response Analysis",
    "定义自定义因子设计": "Define Custom Factorial Design",
    "创建分析（统计）": "Tolerance Analysis (Stat)",
    "过程能力（非正态）": "Capability Analysis (Nonnormal)",
    "过程能力六包": "Capability Sixpack",
    "正态能力六包": "Normal Capability Sixpack",
    "非正态能力六包": "Nonnormal Capability Sixpack",
    "Box-Cox 变换": "Box-Cox Transformation",
    "Johnson 变换": "Johnson Transformation",
    "Johnson 变换（研究预览）": "Johnson Transformation (Research Preview)",
    "Bootstrap Mean CI": "Bootstrap Mean CI",
    "Bootstrap 均值 CI": "Bootstrap Mean CI",
    "CART Tree": "CART Tree",
    "CART 树": "CART Tree",
    "随机森林": "Random Forest",
    "EDA 散点": "EDA Scatter",
    "EDA 直方图": "EDA Histogram",
    "EDA 直方图（NIST）": "EDA Histogram (NIST)",
    "稀有事件控制图": "Rare Event Control Chart",
    "稀有事件": "Rare Events",
    "测量系统分析": "Measurement Systems Analysis",
    "过程能力分析": "Process Capability",
    "验收抽样": "Acceptance Sampling",
    "抽样计划": "Sampling Plan",
    "简单随机抽样": "Simple Random Sampling",
    "分层抽样": "Stratified Sampling",
    "2 水平全因子 / 部分析因设计": "2-Level Full / Fractional Factorial Design",
    "2 水平析因响应分析": "2-Level Factorial Response Analysis",
    "2 水平析因设计生成": "2-Level Factorial Design Generation",
    "ARIMA 基础预测": "ARIMA Basic Forecast",
    "CART 单树": "CART Single Tree",
    "Correlogram（相关热图）": "Correlogram (Correlation Heatmap)",
    "DOE 响应分析": "DOE Response Analysis",
    "EDA 四图": "EDA Four-in-One",
    "EDA 四图（NIST）": "EDA Four-in-One (NIST)",
    "Expanded Gage R&R（三因子平衡）": "Expanded Gage R&R (3-Factor Balanced)",
    "G 图（稀有事件间隔）": "G Chart (Rare Event Interval)",
    "Hotelling T²": "Hotelling T²",
    "Hotelling T² 多元控制图": "Hotelling T² Multivariate Chart",
    "I-MR-R/S 控制图": "I-MR-R/S Chart",
    "K-Means 聚类": "K-Means Clustering",
    "Kruskal-Wallis 检验": "Kruskal-Wallis Test",
    "Laney P' 图": "Laney P' Chart",
    "Laney U' 图": "Laney U' Chart",
    "Mann-Whitney 检验": "Mann-Whitney Test",
    "McNemar 检验": "McNemar Test",
    "Multi-Vari 图": "Multi-Vari Chart",
    "Nested Gage R&R": "Nested Gage R&R",
    "Plackett–Burman 设计生成": "Plackett-Burman Design Generation",
    "Poisson 回归": "Poisson Regression",
    "T 图": "T Chart",
    "T 图（稀有事件间隔）": "T Chart (Rare Event Interval)",
    "Wilcoxon 符号秩检验": "Wilcoxon Signed-Rank Test",
    "Z-MR 控制图": "Z-MR Chart",
    "t 功效与样本量": "t Power and Sample Size",
    "两比例检验": "2-Proportion Test",
    "两比例等价性检验": "2-Proportion Equivalence Test",
    "个体分布识别": "Individual Distribution Identification",
    "中心复合设计 CCD": "Central Composite Design (CCD)",
    "二元 Logistic 回归": "Binary Logistic Regression",
    "二项过程能力": "Binomial Capability",
    "二项过程能力分析": "Binomial Capability Analysis",
    "互相关（CCF）": "Cross Correlation (CCF)",
    "交叉表 / Tally": "Cross Tabulation / Tally",
    "保修摘要": "Warranty Summary",
    "列联表卡方": "Contingency Table Chi-Square",
    "区域图": "Area Chart",
    "区间删失 Kaplan–Meier": "Interval-Censored Kaplan-Meier",
    "单样本 Z 检验": "1-Sample Z-Test",
    "单样本泊松率": "1-Sample Poisson Rate",
    "单样本泊松率检验": "1-Sample Poisson Rate Test",
    "单样本等价性检验": "1-Sample Equivalence Test",
    "单比例等价性检验": "1-Proportion Equivalence Test",
    "卡方拟合优度": "Chi-Square Goodness of Fit",
    "双样本均值比等价性检验": "2-Sample Mean Ratio Equivalence Test",
    "双样本泊松率": "2-Sample Poisson Rate",
    "双样本泊松率检验": "2-Sample Poisson Rate Test",
    "双样本等价性检验": "2-Sample Equivalence Test",
    "变异性图": "Variability Chart",
    "可靠性分析（Kaplan-Meier / Weibull）": "Reliability Analysis (Kaplan-Meier / Weibull)",
    "响应曲面分析（RSM）": "Response Surface Analysis (RSM)",
    "因果图（鱼骨）": "Cause-and-Effect Diagram (Fishbone)",
    "均值分析 (ANOM)": "Analysis of Means (ANOM)",
    "多元 EWMA": "Multivariate EWMA",
    "季节性预测": "Seasonal Forecast",
    "容差区间": "Tolerance Interval",
    "层次聚类（观测）": "Hierarchical Clustering (Observations)",
    "属性一次抽样": "Attribute Single Sampling",
    "广义方差 |S| 多元控制图": "Generalized Variance |S| Multivariate Chart",
    "广义方差图": "Generalized Variance Chart",
    "异常值检验": "Outlier Test",
    "方差检验": "Variance Test",
    "时间序列平滑": "Time Series Smoothing",
    "显示描述性统计": "Display Descriptive Statistics",
    "有序 Logistic 回归": "Ordinal Logistic Regression",
    "柏拉图": "Pareto Chart",
    "正态过程能力": "Normal Capability",
    "正态过程能力分析": "Normal Capability Analysis",
    "泊松拟合优度": "Poisson Goodness of Fit",
    "泊松过程能力": "Poisson Capability",
    "泊松过程能力分析": "Poisson Capability Analysis",
    "游程检验": "Runs Test",
    "移动平均控制图": "Moving Average Chart",
    "线性判别分析": "Linear Discriminant Analysis",
    "线性回归": "Linear Regression",
    "组间/组内过程能力": "Between/Within Capability",
    "组间/组内过程能力分析": "Between/Within Capability Analysis",
    "自相关与偏自相关": "ACF and PACF",
    "过程能力 Sixpack": "Capability Sixpack",
    "配对等价性检验": "Paired Equivalence Test",
    "非正态过程能力分析": "Nonnormal Capability Analysis",
}

text = (root / "src/ui/analysis_commands.cpp").read_text(encoding="utf-8")
pat = re.compile(
    r'QStringLiteral\("([^"]+)"\),\s*\n\s*'
    r'QStringLiteral\("([^"]+)"\),\s*\n\s*'
    r'QStringLiteral\("([^"]+)"\),\s*\n\s*'
    r'QStringLiteral\("([^"]+)"\)',
    re.M,
)
labels: set[str] = set()
for _cid, menu, title, group in pat.findall(text):
    labels.update([menu, title, group])

path = root / "translations/ui_menu_strings.json"
data = json.loads(path.read_text(encoding="utf-8"))
by_zh = {e["zh_cn"]: e for e in data["entries"]}

added = 0
untranslated: list[str] = []
for zh in sorted(labels):
    if zh in by_zh:
        continue
    en = TRANSLATIONS.get(zh)
    if en is None:
        # ASCII-heavy labels: keep as-is
        if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9 /_\-\(\)\.·–—+%]*", zh):
            en = zh
        else:
            untranslated.append(zh)
            continue
    entry_id = "cmd." + re.sub(r"[^A-Za-z0-9]+", "_", en.lower()).strip("_")[:48]
    # ensure unique id
    base = entry_id
    n = 2
    existing_ids = {e["id"] for e in data["entries"]}
    while entry_id in existing_ids:
        entry_id = f"{base}_{n}"
        n += 1
    data["entries"].append({"id": entry_id, "zh_cn": zh, "en_us": en})
    by_zh[zh] = data["entries"][-1]
    added += 1

data["catalog_version"] = "2026-08-21.phase3-analysis-commands"
path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

out = root / "tools/_ui_menu_untranslated.txt"
out.write_text("\n".join(untranslated) + ("\n" if untranslated else ""), encoding="utf-8")
print(f"added={added} still_untranslated={len(untranslated)} total_entries={len(data['entries'])}")
